# Model 8 - Transfer Learning + Augmentation (MobileNetV2)

Same frozen-MobileNetV2 model as model 7, but trained on the **augmented**
pipeline (`augment=True`: flip/rotate/shift/zoom on the train set only). Tests
whether augmentation pushes the 0.94 transfer model any higher - the frozen
ImageNet features are robust, so augmentation may help here where it hurt the
small from-scratch GAP model.

## 1. Setup & imports

In [1]:
import os
import sys

sys.path.append(os.path.join(os.getcwd(), "preprocessing", "label_mapping"))
sys.path.append(os.path.join(os.getcwd(), "preprocessing", "data_loader"))
sys.path.append(os.path.join(os.getcwd(), "model"))
sys.path.append(os.path.join(os.getcwd(), "evaluation", "model_metrics"))
sys.path.append(os.path.join(os.getcwd(), "evaluation", "plots"))

import pandas as pd
from tensorflow.keras.callbacks import EarlyStopping

from label_mapping import build_labeled_dataset
from data_loader import build_train_val_test_generators
from transfer_mobilenet import build_transfer_mobilenet
from model_metrics import debug_model, evaluate_model, record_result
from plots import plot_misclassified

## 2. Load & label the dataset

In [2]:
df = build_labeled_dataset()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26179 entries, 0 to 26178
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   image_path  26179 non-null  str
 1   label_it    26179 non-null  str
 2   label_en    26179 non-null  str
dtypes: str(3)
memory usage: 613.7 KB

## 3. Preprocess: split, resize, normalize, **augment**

Identical split/size to every model, but `augment=True` adds random
flip/rotate/shift/zoom to the **train** generator only (val/test stay clean).

In [3]:
train_generator, val_generator, test_generator = build_train_val_test_generators(
    df, project_root=os.getcwd(), image_size=(128, 128), augment=True
)
train_generator.class_indices

Found 18325 validated image filenames belonging to 10 classes.

Found 3927 validated image filenames belonging to 10 classes.

Found 3927 validated image filenames belonging to 10 classes.

{'butterfly': 0,
 'cat': 1,
 'chicken': 2,
 'cow': 3,
 'dog': 4,
 'elephant': 5,
 'horse': 6,
 'sheep': 7,
 'spider': 8,
 'squirrel': 9}

## 4. Build the model

Same `build_transfer_mobilenet` as model 7 (frozen MobileNetV2 + GAP head).

In [4]:
model = build_transfer_mobilenet(
    input_shape=train_generator.image_shape,
    num_classes=len(train_generator.class_indices),
)
model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ rescaling (Rescaling)           │ (None, 128, 128, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ mobilenetv2_1.00_128            │ (None, 4, 4, 1280)     │     2,257,984 │
│ (Functional)                    │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 1280)           │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 1280)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 10)             │        12,810 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,270,794 (8.66 MB)

 Trainable params: 12,810 (50.04 KB)

 Non-trainable params: 2,257,984 (8.61 MB)

## 5. Train - or load a saved model

Saves to a **separate** file so model 7's winner stays intact. Set
`RETRAIN = True` to force a fresh run.

In [5]:
import time
from tensorflow import keras

MODEL_PATH = "models_saved/transfer_mobilenet_aug.keras"
RETRAIN = False

if not RETRAIN and os.path.exists(MODEL_PATH):
    model = keras.models.load_model(MODEL_PATH)
    history, train_time_min = None, None
    print(f"Loaded {MODEL_PATH} (skipped training).")
else:
    early_stopping = EarlyStopping(
        monitor="val_loss", patience=3, restore_best_weights=True
    )
    start_time = time.time()
    history = model.fit(
        train_generator,
        validation_data=val_generator,
        epochs=20,
        callbacks=[early_stopping],
    )
    train_time_min = round((time.time() - start_time) / 60, 1)
    print(f"Trained in {train_time_min} min.")

Epoch 1/20

  1/573 ━━━━━━━━━━━━━━━━━━━━ 18:28 2s/step - accuracy: 0.1250 - loss: 3.3101

  3/573 ━━━━━━━━━━━━━━━━━━━━ 38s 67ms/step - accuracy: 0.1354 - loss: 3.2702

  4/573 ━━━━━━━━━━━━━━━━━━━━ 38s 68ms/step - accuracy: 0.1406 - loss: 3.1785

  5/573 ━━━━━━━━━━━━━━━━━━━━ 41s 73ms/step - accuracy: 0.1562 - loss: 3.0876

  6/573 ━━━━━━━━━━━━━━━━━━━━ 41s 73ms/step - accuracy: 0.1615 - loss: 3.0235

  7/573 ━━━━━━━━━━━━━━━━━━━━ 43s 76ms/step - accuracy: 0.1786 - loss: 2.9717

  8/573 ━━━━━━━━━━━━━━━━━━━━ 42s 76ms/step - accuracy: 0.1875 - loss: 2.9301

  9/573 ━━━━━━━━━━━━━━━━━━━━ 43s 77ms/step - accuracy: 0.1910 - loss: 2.8974

 10/573 ━━━━━━━━━━━━━━━━━━━━ 43s 77ms/step - accuracy: 0.1906 - loss: 2.9259

 11/573 ━━━━━━━━━━━━━━━━━━━━ 43s 77ms/step - accuracy: 0.1960 - loss: 2.9247

 12/573 ━━━━━━━━━━━━━━━━━━━━ 43s 77ms/step - accuracy: 0.2083 - loss: 2.8660

 13/573 ━━━━━━━━━━━━━━━━━━━━ 43s 78ms/step - accuracy: 0.2139 - loss: 2.8247

 14/573 ━━━━━━━━━━━━━━━━━━━━ 43s 78ms/step - accuracy: 0.2277 - loss: 2.7386

 15/573 ━━━━━━━━━━━━━━━━━━━━ 43s 78ms/step - accuracy: 0.2354 - loss: 2.6997

 16/573 ━━━━━━━━━━━━━━━━━━━━ 43s 78ms/step - accuracy: 0.2461 - loss: 2.6685

 17/573 ━━━━━━━━━━━━━━━━━━━━ 43s 78ms/step - accuracy: 0.2537 - loss: 2.6203

 18/573 ━━━━━━━━━━━━━━━━━━━━ 43s 79ms/step - accuracy: 0.2552 - loss: 2.6097

 19/573 ━━━━━━━━━━━━━━━━━━━━ 43s 78ms/step - accuracy: 0.2615 - loss: 2.5886

 20/573 ━━━━━━━━━━━━━━━━━━━━ 43s 78ms/step - accuracy: 0.2688 - loss: 2.5609

 21/573 ━━━━━━━━━━━━━━━━━━━━ 43s 79ms/step - accuracy: 0.2753 - loss: 2.5375

 22/573 ━━━━━━━━━━━━━━━━━━━━ 43s 78ms/step - accuracy: 0.2855 - loss: 2.4908

 23/573 ━━━━━━━━━━━━━━━━━━━━ 43s 79ms/step - accuracy: 0.2948 - loss: 2.4511

 24/573 ━━━━━━━━━━━━━━━━━━━━ 43s 79ms/step - accuracy: 0.3034 - loss: 2.4191

 25/573 ━━━━━━━━━━━━━━━━━━━━ 42s 78ms/step - accuracy: 0.3137 - loss: 2.3894

 26/573 ━━━━━━━━━━━━━━━━━━━━ 43s 79ms/step - accuracy: 0.3233 - loss: 2.3517

 27/573 ━━━━━━━━━━━━━━━━━━━━ 42s 79ms/step - accuracy: 0.3299 - loss: 2.3243

 28/573 ━━━━━━━━━━━━━━━━━━━━ 42s 79ms/step - accuracy: 0.3393 - loss: 2.2914

 29/573 ━━━━━━━━━━━━━━━━━━━━ 42s 79ms/step - accuracy: 0.3438 - loss: 2.2724

 30/573 ━━━━━━━━━━━━━━━━━━━━ 42s 79ms/step - accuracy: 0.3500 - loss: 2.2458

 31/573 ━━━━━━━━━━━━━━━━━━━━ 42s 79ms/step - accuracy: 0.3538 - loss: 2.2344

 32/573 ━━━━━━━━━━━━━━━━━━━━ 42s 79ms/step - accuracy: 0.3594 - loss: 2.2076

 33/573 ━━━━━━━━━━━━━━━━━━━━ 42s 79ms/step - accuracy: 0.3665 - loss: 2.1756

 34/573 ━━━━━━━━━━━━━━━━━━━━ 42s 79ms/step - accuracy: 0.3722 - loss: 2.1445

 35/573 ━━━━━━━━━━━━━━━━━━━━ 42s 79ms/step - accuracy: 0.3750 - loss: 2.1340

 36/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.3793 - loss: 2.1085

 37/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.3868 - loss: 2.0836

 38/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.3906 - loss: 2.0667

 39/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.3974 - loss: 2.0492

 40/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.4055 - loss: 2.0203

 41/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.4085 - loss: 2.0019

 42/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.4152 - loss: 1.9769

 43/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.4193 - loss: 1.9615

 44/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.4240 - loss: 1.9411

 45/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.4285 - loss: 1.9248

 46/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.4348 - loss: 1.9072

 47/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.4422 - loss: 1.8849

 48/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.4492 - loss: 1.8644

 49/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.4541 - loss: 1.8473

 50/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.4569 - loss: 1.8350

 51/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.4626 - loss: 1.8119

 52/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.4663 - loss: 1.7975

 53/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.4699 - loss: 1.7819

 54/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.4740 - loss: 1.7644

 55/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.4790 - loss: 1.7481

 56/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.4827 - loss: 1.7338

 57/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.4857 - loss: 1.7238

 58/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.4871 - loss: 1.7167

 59/573 ━━━━━━━━━━━━━━━━━━━━ 40s 80ms/step - accuracy: 0.4883 - loss: 1.7113

 60/573 ━━━━━━━━━━━━━━━━━━━━ 40s 80ms/step - accuracy: 0.4901 - loss: 1.7009

 61/573 ━━━━━━━━━━━━━━━━━━━━ 40s 80ms/step - accuracy: 0.4933 - loss: 1.6915

 62/573 ━━━━━━━━━━━━━━━━━━━━ 40s 80ms/step - accuracy: 0.4970 - loss: 1.6762

 63/573 ━━━━━━━━━━━━━━━━━━━━ 40s 80ms/step - accuracy: 0.5010 - loss: 1.6615

 64/573 ━━━━━━━━━━━━━━━━━━━━ 40s 80ms/step - accuracy: 0.5039 - loss: 1.6470

 65/573 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.5082 - loss: 1.6322

 66/573 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.5104 - loss: 1.6202

 67/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.5145 - loss: 1.6098

 68/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.5175 - loss: 1.5984

 69/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.5213 - loss: 1.5898

 70/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.5246 - loss: 1.5776

 71/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.5286 - loss: 1.5658

 72/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.5304 - loss: 1.5571

 73/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.5347 - loss: 1.5447

 74/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.5363 - loss: 1.5374

 75/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.5392 - loss: 1.5248

 76/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.5419 - loss: 1.5178

 77/573 ━━━━━━━━━━━━━━━━━━━━ 39s 80ms/step - accuracy: 0.5459 - loss: 1.5065

 78/573 ━━━━━━━━━━━━━━━━━━━━ 39s 80ms/step - accuracy: 0.5469 - loss: 1.5010

 79/573 ━━━━━━━━━━━━━━━━━━━━ 39s 80ms/step - accuracy: 0.5491 - loss: 1.4905

 80/573 ━━━━━━━━━━━━━━━━━━━━ 39s 80ms/step - accuracy: 0.5492 - loss: 1.4877

 81/573 ━━━━━━━━━━━━━━━━━━━━ 39s 80ms/step - accuracy: 0.5517 - loss: 1.4777

 82/573 ━━━━━━━━━━━━━━━━━━━━ 39s 80ms/step - accuracy: 0.5541 - loss: 1.4706

 83/573 ━━━━━━━━━━━━━━━━━━━━ 39s 80ms/step - accuracy: 0.5569 - loss: 1.4647

 84/573 ━━━━━━━━━━━━━━━━━━━━ 39s 80ms/step - accuracy: 0.5603 - loss: 1.4541

 85/573 ━━━━━━━━━━━━━━━━━━━━ 39s 80ms/step - accuracy: 0.5629 - loss: 1.4481

 86/573 ━━━━━━━━━━━━━━━━━━━━ 39s 80ms/step - accuracy: 0.5647 - loss: 1.4405

 87/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.5672 - loss: 1.4321

 88/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.5700 - loss: 1.4219

 89/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.5734 - loss: 1.4103

 90/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.5757 - loss: 1.4028

 91/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.5776 - loss: 1.3956

 92/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.5798 - loss: 1.3881

 93/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.5820 - loss: 1.3798

 94/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.5831 - loss: 1.3737

 95/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.5852 - loss: 1.3685

 96/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.5879 - loss: 1.3589

 97/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.5896 - loss: 1.3546

 98/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.5915 - loss: 1.3473

 99/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.5931 - loss: 1.3444

100/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.5950 - loss: 1.3390

101/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.5978 - loss: 1.3300

102/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.6002 - loss: 1.3225

103/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.6016 - loss: 1.3183

104/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.6031 - loss: 1.3104

105/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.6045 - loss: 1.3068

106/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.6067 - loss: 1.3006

107/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.6084 - loss: 1.2952

108/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.6100 - loss: 1.2894

109/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.6112 - loss: 1.2839

110/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.6134 - loss: 1.2763

111/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.6154 - loss: 1.2690

112/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.6172 - loss: 1.2632

113/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.6192 - loss: 1.2569

114/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.6209 - loss: 1.2511

115/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.6223 - loss: 1.2448

116/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.6239 - loss: 1.2394

117/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.6255 - loss: 1.2347

118/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.6279 - loss: 1.2271

119/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.6287 - loss: 1.2234

120/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.6307 - loss: 1.2157

121/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.6309 - loss: 1.2143

122/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.6324 - loss: 1.2104

123/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.6341 - loss: 1.2035

124/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.6353 - loss: 1.1989

125/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.6370 - loss: 1.1938

126/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.6391 - loss: 1.1879

127/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.6407 - loss: 1.1830

128/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.6418 - loss: 1.1792

129/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.6427 - loss: 1.1764

130/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.6442 - loss: 1.1713

131/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.6443 - loss: 1.1694

132/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.6451 - loss: 1.1650

133/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.6461 - loss: 1.1618

134/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.6479 - loss: 1.1559

135/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.6484 - loss: 1.1521

136/573 ━━━━━━━━━━━━━━━━━━━━ 35s 81ms/step - accuracy: 0.6494 - loss: 1.1490

137/573 ━━━━━━━━━━━━━━━━━━━━ 35s 81ms/step - accuracy: 0.6510 - loss: 1.1447

138/573 ━━━━━━━━━━━━━━━━━━━━ 35s 81ms/step - accuracy: 0.6526 - loss: 1.1387

139/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.6538 - loss: 1.1359

140/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.6554 - loss: 1.1305

141/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.6562 - loss: 1.1275

142/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.6569 - loss: 1.1238

143/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.6582 - loss: 1.1194

144/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.6597 - loss: 1.1165

145/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.6606 - loss: 1.1135

146/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.6618 - loss: 1.1095

147/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.6628 - loss: 1.1069

148/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.6639 - loss: 1.1030

149/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.6644 - loss: 1.0996

150/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.6660 - loss: 1.0945

151/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.6666 - loss: 1.0911

152/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.6682 - loss: 1.0863

153/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.6687 - loss: 1.0838

154/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.6694 - loss: 1.0800

155/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.6704 - loss: 1.0770

156/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.6713 - loss: 1.0731

157/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.6726 - loss: 1.0692

158/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.6735 - loss: 1.0651

159/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.6741 - loss: 1.0608

160/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.6752 - loss: 1.0572

161/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.6766 - loss: 1.0524

162/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.6780 - loss: 1.0475

163/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.6793 - loss: 1.0445

164/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.6799 - loss: 1.0410

165/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.6816 - loss: 1.0367

166/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.6828 - loss: 1.0332

167/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.6838 - loss: 1.0306

168/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.6849 - loss: 1.0264

169/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.6853 - loss: 1.0234

170/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.6864 - loss: 1.0207

171/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.6875 - loss: 1.0171

172/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.6882 - loss: 1.0173

173/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.6893 - loss: 1.0138

174/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.6904 - loss: 1.0101

175/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.6911 - loss: 1.0073

176/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.6916 - loss: 1.0053

177/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.6921 - loss: 1.0034

178/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.6929 - loss: 0.9997

179/573 ━━━━━━━━━━━━━━━━━━━━ 31s 81ms/step - accuracy: 0.6936 - loss: 0.9966

180/573 ━━━━━━━━━━━━━━━━━━━━ 31s 81ms/step - accuracy: 0.6938 - loss: 0.9947

181/573 ━━━━━━━━━━━━━━━━━━━━ 31s 81ms/step - accuracy: 0.6942 - loss: 0.9919

182/573 ━━━━━━━━━━━━━━━━━━━━ 31s 81ms/step - accuracy: 0.6947 - loss: 0.9910

183/573 ━━━━━━━━━━━━━━━━━━━━ 31s 81ms/step - accuracy: 0.6955 - loss: 0.9885

184/573 ━━━━━━━━━━━━━━━━━━━━ 31s 81ms/step - accuracy: 0.6968 - loss: 0.9850

185/573 ━━━━━━━━━━━━━━━━━━━━ 31s 81ms/step - accuracy: 0.6980 - loss: 0.9814

186/573 ━━━━━━━━━━━━━━━━━━━━ 31s 81ms/step - accuracy: 0.6984 - loss: 0.9798

187/573 ━━━━━━━━━━━━━━━━━━━━ 31s 81ms/step - accuracy: 0.6992 - loss: 0.9775

188/573 ━━━━━━━━━━━━━━━━━━━━ 31s 81ms/step - accuracy: 0.6998 - loss: 0.9756

189/573 ━━━━━━━━━━━━━━━━━━━━ 31s 81ms/step - accuracy: 0.7004 - loss: 0.9731

190/573 ━━━━━━━━━━━━━━━━━━━━ 30s 81ms/step - accuracy: 0.7012 - loss: 0.9710

191/573 ━━━━━━━━━━━━━━━━━━━━ 30s 81ms/step - accuracy: 0.7021 - loss: 0.9682

192/573 ━━━━━━━━━━━━━━━━━━━━ 30s 81ms/step - accuracy: 0.7026 - loss: 0.9669

193/573 ━━━━━━━━━━━━━━━━━━━━ 30s 81ms/step - accuracy: 0.7034 - loss: 0.9651

194/573 ━━━━━━━━━━━━━━━━━━━━ 30s 81ms/step - accuracy: 0.7038 - loss: 0.9634

195/573 ━━━━━━━━━━━━━━━━━━━━ 30s 81ms/step - accuracy: 0.7043 - loss: 0.9618

196/573 ━━━━━━━━━━━━━━━━━━━━ 30s 81ms/step - accuracy: 0.7049 - loss: 0.9585

197/573 ━━━━━━━━━━━━━━━━━━━━ 30s 81ms/step - accuracy: 0.7057 - loss: 0.9552

198/573 ━━━━━━━━━━━━━━━━━━━━ 30s 81ms/step - accuracy: 0.7068 - loss: 0.9522

199/573 ━━━━━━━━━━━━━━━━━━━━ 30s 81ms/step - accuracy: 0.7076 - loss: 0.9494

200/573 ━━━━━━━━━━━━━━━━━━━━ 30s 81ms/step - accuracy: 0.7086 - loss: 0.9463

201/573 ━━━━━━━━━━━━━━━━━━━━ 30s 81ms/step - accuracy: 0.7096 - loss: 0.9434

202/573 ━━━━━━━━━━━━━━━━━━━━ 29s 81ms/step - accuracy: 0.7106 - loss: 0.9402

203/573 ━━━━━━━━━━━━━━━━━━━━ 29s 81ms/step - accuracy: 0.7111 - loss: 0.9386

204/573 ━━━━━━━━━━━━━━━━━━━━ 29s 81ms/step - accuracy: 0.7119 - loss: 0.9360

205/573 ━━━━━━━━━━━━━━━━━━━━ 29s 81ms/step - accuracy: 0.7122 - loss: 0.9338

206/573 ━━━━━━━━━━━━━━━━━━━━ 29s 81ms/step - accuracy: 0.7125 - loss: 0.9325

207/573 ━━━━━━━━━━━━━━━━━━━━ 29s 81ms/step - accuracy: 0.7130 - loss: 0.9302

208/573 ━━━━━━━━━━━━━━━━━━━━ 29s 81ms/step - accuracy: 0.7127 - loss: 0.9288

209/573 ━━━━━━━━━━━━━━━━━━━━ 29s 81ms/step - accuracy: 0.7135 - loss: 0.9273

210/573 ━━━━━━━━━━━━━━━━━━━━ 29s 81ms/step - accuracy: 0.7141 - loss: 0.9253

211/573 ━━━━━━━━━━━━━━━━━━━━ 29s 81ms/step - accuracy: 0.7148 - loss: 0.9237

212/573 ━━━━━━━━━━━━━━━━━━━━ 29s 81ms/step - accuracy: 0.7158 - loss: 0.9213

213/573 ━━━━━━━━━━━━━━━━━━━━ 29s 81ms/step - accuracy: 0.7168 - loss: 0.9178

214/573 ━━━━━━━━━━━━━━━━━━━━ 29s 81ms/step - accuracy: 0.7176 - loss: 0.9145

215/573 ━━━━━━━━━━━━━━━━━━━━ 28s 81ms/step - accuracy: 0.7173 - loss: 0.9137

216/573 ━━━━━━━━━━━━━━━━━━━━ 28s 81ms/step - accuracy: 0.7174 - loss: 0.9121

217/573 ━━━━━━━━━━━━━━━━━━━━ 28s 81ms/step - accuracy: 0.7180 - loss: 0.9094

218/573 ━━━━━━━━━━━━━━━━━━━━ 28s 81ms/step - accuracy: 0.7189 - loss: 0.9069

219/573 ━━━━━━━━━━━━━━━━━━━━ 28s 81ms/step - accuracy: 0.7195 - loss: 0.9043

220/573 ━━━━━━━━━━━━━━━━━━━━ 28s 81ms/step - accuracy: 0.7196 - loss: 0.9027

221/573 ━━━━━━━━━━━━━━━━━━━━ 28s 81ms/step - accuracy: 0.7203 - loss: 0.9005

222/573 ━━━━━━━━━━━━━━━━━━━━ 28s 81ms/step - accuracy: 0.7210 - loss: 0.8983

223/573 ━━━━━━━━━━━━━━━━━━━━ 28s 81ms/step - accuracy: 0.7210 - loss: 0.8994

224/573 ━━━━━━━━━━━━━━━━━━━━ 28s 81ms/step - accuracy: 0.7214 - loss: 0.8979

225/573 ━━━━━━━━━━━━━━━━━━━━ 28s 81ms/step - accuracy: 0.7224 - loss: 0.8949

226/573 ━━━━━━━━━━━━━━━━━━━━ 28s 81ms/step - accuracy: 0.7229 - loss: 0.8936

227/573 ━━━━━━━━━━━━━━━━━━━━ 28s 81ms/step - accuracy: 0.7238 - loss: 0.8910

228/573 ━━━━━━━━━━━━━━━━━━━━ 28s 81ms/step - accuracy: 0.7249 - loss: 0.8878

229/573 ━━━━━━━━━━━━━━━━━━━━ 27s 81ms/step - accuracy: 0.7258 - loss: 0.8849

230/573 ━━━━━━━━━━━━━━━━━━━━ 27s 81ms/step - accuracy: 0.7266 - loss: 0.8823

231/573 ━━━━━━━━━━━━━━━━━━━━ 27s 81ms/step - accuracy: 0.7273 - loss: 0.8798

232/573 ━━━━━━━━━━━━━━━━━━━━ 27s 81ms/step - accuracy: 0.7279 - loss: 0.8774

233/573 ━━━━━━━━━━━━━━━━━━━━ 27s 81ms/step - accuracy: 0.7284 - loss: 0.8757

234/573 ━━━━━━━━━━━━━━━━━━━━ 27s 81ms/step - accuracy: 0.7286 - loss: 0.8746

235/573 ━━━━━━━━━━━━━━━━━━━━ 27s 81ms/step - accuracy: 0.7287 - loss: 0.8739

236/573 ━━━━━━━━━━━━━━━━━━━━ 27s 81ms/step - accuracy: 0.7295 - loss: 0.8722

237/573 ━━━━━━━━━━━━━━━━━━━━ 27s 81ms/step - accuracy: 0.7298 - loss: 0.8710

238/573 ━━━━━━━━━━━━━━━━━━━━ 27s 82ms/step - accuracy: 0.7303 - loss: 0.8690

239/573 ━━━━━━━━━━━━━━━━━━━━ 27s 82ms/step - accuracy: 0.7308 - loss: 0.8674

240/573 ━━━━━━━━━━━━━━━━━━━━ 27s 82ms/step - accuracy: 0.7314 - loss: 0.8657

241/573 ━━━━━━━━━━━━━━━━━━━━ 27s 82ms/step - accuracy: 0.7318 - loss: 0.8655

242/573 ━━━━━━━━━━━━━━━━━━━━ 27s 82ms/step - accuracy: 0.7321 - loss: 0.8640

243/573 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - accuracy: 0.7325 - loss: 0.8623

244/573 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - accuracy: 0.7328 - loss: 0.8611

245/573 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - accuracy: 0.7335 - loss: 0.8587

246/573 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - accuracy: 0.7336 - loss: 0.8592

247/573 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - accuracy: 0.7341 - loss: 0.8583

248/573 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - accuracy: 0.7348 - loss: 0.8561

249/573 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - accuracy: 0.7352 - loss: 0.8547

250/573 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - accuracy: 0.7351 - loss: 0.8554

251/573 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - accuracy: 0.7357 - loss: 0.8536

252/573 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - accuracy: 0.7364 - loss: 0.8515

253/573 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - accuracy: 0.7364 - loss: 0.8511

254/573 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - accuracy: 0.7368 - loss: 0.8496

255/573 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - accuracy: 0.7373 - loss: 0.8481

256/573 ━━━━━━━━━━━━━━━━━━━━ 26s 82ms/step - accuracy: 0.7375 - loss: 0.8469

257/573 ━━━━━━━━━━━━━━━━━━━━ 25s 82ms/step - accuracy: 0.7377 - loss: 0.8455

258/573 ━━━━━━━━━━━━━━━━━━━━ 25s 82ms/step - accuracy: 0.7383 - loss: 0.8434

259/573 ━━━━━━━━━━━━━━━━━━━━ 25s 82ms/step - accuracy: 0.7388 - loss: 0.8422

260/573 ━━━━━━━━━━━━━━━━━━━━ 25s 82ms/step - accuracy: 0.7393 - loss: 0.8404

261/573 ━━━━━━━━━━━━━━━━━━━━ 25s 82ms/step - accuracy: 0.7401 - loss: 0.8380

262/573 ━━━━━━━━━━━━━━━━━━━━ 25s 82ms/step - accuracy: 0.7408 - loss: 0.8363

263/573 ━━━━━━━━━━━━━━━━━━━━ 25s 82ms/step - accuracy: 0.7413 - loss: 0.8349

264/573 ━━━━━━━━━━━━━━━━━━━━ 25s 82ms/step - accuracy: 0.7418 - loss: 0.8335

265/573 ━━━━━━━━━━━━━━━━━━━━ 25s 82ms/step - accuracy: 0.7422 - loss: 0.8330

266/573 ━━━━━━━━━━━━━━━━━━━━ 25s 82ms/step - accuracy: 0.7426 - loss: 0.8313

267/573 ━━━━━━━━━━━━━━━━━━━━ 25s 82ms/step - accuracy: 0.7429 - loss: 0.8303

268/573 ━━━━━━━━━━━━━━━━━━━━ 25s 82ms/step - accuracy: 0.7432 - loss: 0.8285

269/573 ━━━━━━━━━━━━━━━━━━━━ 24s 82ms/step - accuracy: 0.7438 - loss: 0.8264

270/573 ━━━━━━━━━━━━━━━━━━━━ 24s 82ms/step - accuracy: 0.7443 - loss: 0.8244

271/573 ━━━━━━━━━━━━━━━━━━━━ 24s 82ms/step - accuracy: 0.7446 - loss: 0.8234

272/573 ━━━━━━━━━━━━━━━━━━━━ 24s 82ms/step - accuracy: 0.7449 - loss: 0.8224

273/573 ━━━━━━━━━━━━━━━━━━━━ 24s 82ms/step - accuracy: 0.7452 - loss: 0.8212

274/573 ━━━━━━━━━━━━━━━━━━━━ 24s 82ms/step - accuracy: 0.7458 - loss: 0.8194

275/573 ━━━━━━━━━━━━━━━━━━━━ 24s 82ms/step - accuracy: 0.7458 - loss: 0.8192

276/573 ━━━━━━━━━━━━━━━━━━━━ 24s 82ms/step - accuracy: 0.7464 - loss: 0.8173

277/573 ━━━━━━━━━━━━━━━━━━━━ 24s 82ms/step - accuracy: 0.7467 - loss: 0.8160

278/573 ━━━━━━━━━━━━━━━━━━━━ 24s 82ms/step - accuracy: 0.7469 - loss: 0.8149

279/573 ━━━━━━━━━━━━━━━━━━━━ 24s 82ms/step - accuracy: 0.7474 - loss: 0.8134

280/573 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - accuracy: 0.7480 - loss: 0.8115

281/573 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - accuracy: 0.7488 - loss: 0.8096

282/573 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - accuracy: 0.7491 - loss: 0.8084

283/573 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - accuracy: 0.7494 - loss: 0.8074

284/573 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - accuracy: 0.7498 - loss: 0.8073

285/573 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - accuracy: 0.7504 - loss: 0.8057

286/573 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - accuracy: 0.7508 - loss: 0.8040

287/573 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - accuracy: 0.7512 - loss: 0.8034

288/573 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - accuracy: 0.7515 - loss: 0.8019

289/573 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - accuracy: 0.7519 - loss: 0.8005

290/573 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - accuracy: 0.7522 - loss: 0.7995

291/573 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - accuracy: 0.7520 - loss: 0.8002

292/573 ━━━━━━━━━━━━━━━━━━━━ 23s 82ms/step - accuracy: 0.7524 - loss: 0.7987

293/573 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - accuracy: 0.7529 - loss: 0.7969

294/573 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - accuracy: 0.7533 - loss: 0.7958

295/573 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - accuracy: 0.7539 - loss: 0.7939

296/573 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - accuracy: 0.7544 - loss: 0.7919

297/573 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - accuracy: 0.7552 - loss: 0.7898

298/573 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - accuracy: 0.7553 - loss: 0.7900

299/573 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - accuracy: 0.7553 - loss: 0.7889

300/573 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - accuracy: 0.7556 - loss: 0.7882

301/573 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - accuracy: 0.7560 - loss: 0.7870

302/573 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - accuracy: 0.7561 - loss: 0.7860

303/573 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - accuracy: 0.7565 - loss: 0.7848

304/573 ━━━━━━━━━━━━━━━━━━━━ 22s 82ms/step - accuracy: 0.7568 - loss: 0.7840

305/573 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - accuracy: 0.7572 - loss: 0.7832

306/573 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - accuracy: 0.7576 - loss: 0.7822

307/573 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - accuracy: 0.7581 - loss: 0.7810

308/573 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - accuracy: 0.7587 - loss: 0.7794

309/573 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - accuracy: 0.7588 - loss: 0.7787

310/573 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - accuracy: 0.7591 - loss: 0.7778

311/573 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - accuracy: 0.7593 - loss: 0.7768

312/573 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - accuracy: 0.7596 - loss: 0.7758

313/573 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - accuracy: 0.7599 - loss: 0.7751

314/573 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - accuracy: 0.7602 - loss: 0.7740

315/573 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - accuracy: 0.7606 - loss: 0.7725

316/573 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - accuracy: 0.7606 - loss: 0.7721

317/573 ━━━━━━━━━━━━━━━━━━━━ 20s 82ms/step - accuracy: 0.7610 - loss: 0.7709

318/573 ━━━━━━━━━━━━━━━━━━━━ 20s 82ms/step - accuracy: 0.7613 - loss: 0.7699

319/573 ━━━━━━━━━━━━━━━━━━━━ 20s 82ms/step - accuracy: 0.7617 - loss: 0.7684

320/573 ━━━━━━━━━━━━━━━━━━━━ 20s 82ms/step - accuracy: 0.7621 - loss: 0.7670

321/573 ━━━━━━━━━━━━━━━━━━━━ 20s 82ms/step - accuracy: 0.7620 - loss: 0.7673

322/573 ━━━━━━━━━━━━━━━━━━━━ 20s 82ms/step - accuracy: 0.7623 - loss: 0.7662

323/573 ━━━━━━━━━━━━━━━━━━━━ 20s 82ms/step - accuracy: 0.7628 - loss: 0.7645

324/573 ━━━━━━━━━━━━━━━━━━━━ 20s 82ms/step - accuracy: 0.7629 - loss: 0.7647

325/573 ━━━━━━━━━━━━━━━━━━━━ 20s 82ms/step - accuracy: 0.7628 - loss: 0.7640

326/573 ━━━━━━━━━━━━━━━━━━━━ 20s 82ms/step - accuracy: 0.7633 - loss: 0.7632

327/573 ━━━━━━━━━━━━━━━━━━━━ 20s 82ms/step - accuracy: 0.7634 - loss: 0.7619

328/573 ━━━━━━━━━━━━━━━━━━━━ 20s 82ms/step - accuracy: 0.7638 - loss: 0.7613

329/573 ━━━━━━━━━━━━━━━━━━━━ 19s 82ms/step - accuracy: 0.7640 - loss: 0.7601

330/573 ━━━━━━━━━━━━━━━━━━━━ 19s 82ms/step - accuracy: 0.7641 - loss: 0.7602

331/573 ━━━━━━━━━━━━━━━━━━━━ 19s 82ms/step - accuracy: 0.7643 - loss: 0.7593

332/573 ━━━━━━━━━━━━━━━━━━━━ 19s 82ms/step - accuracy: 0.7643 - loss: 0.7589

333/573 ━━━━━━━━━━━━━━━━━━━━ 19s 82ms/step - accuracy: 0.7646 - loss: 0.7576

334/573 ━━━━━━━━━━━━━━━━━━━━ 19s 82ms/step - accuracy: 0.7650 - loss: 0.7562

335/573 ━━━━━━━━━━━━━━━━━━━━ 19s 82ms/step - accuracy: 0.7654 - loss: 0.7547

336/573 ━━━━━━━━━━━━━━━━━━━━ 19s 82ms/step - accuracy: 0.7655 - loss: 0.7543

337/573 ━━━━━━━━━━━━━━━━━━━━ 19s 82ms/step - accuracy: 0.7658 - loss: 0.7532

338/573 ━━━━━━━━━━━━━━━━━━━━ 19s 82ms/step - accuracy: 0.7656 - loss: 0.7533

339/573 ━━━━━━━━━━━━━━━━━━━━ 19s 82ms/step - accuracy: 0.7660 - loss: 0.7523

340/573 ━━━━━━━━━━━━━━━━━━━━ 19s 82ms/step - accuracy: 0.7661 - loss: 0.7514

341/573 ━━━━━━━━━━━━━━━━━━━━ 19s 82ms/step - accuracy: 0.7663 - loss: 0.7513

342/573 ━━━━━━━━━━━━━━━━━━━━ 18s 82ms/step - accuracy: 0.7667 - loss: 0.7503

343/573 ━━━━━━━━━━━━━━━━━━━━ 18s 82ms/step - accuracy: 0.7672 - loss: 0.7489

344/573 ━━━━━━━━━━━━━━━━━━━━ 18s 82ms/step - accuracy: 0.7676 - loss: 0.7477

345/573 ━━━━━━━━━━━━━━━━━━━━ 18s 82ms/step - accuracy: 0.7678 - loss: 0.7471

346/573 ━━━━━━━━━━━━━━━━━━━━ 18s 82ms/step - accuracy: 0.7679 - loss: 0.7468

347/573 ━━━━━━━━━━━━━━━━━━━━ 18s 82ms/step - accuracy: 0.7681 - loss: 0.7460

348/573 ━━━━━━━━━━━━━━━━━━━━ 18s 82ms/step - accuracy: 0.7684 - loss: 0.7455

349/573 ━━━━━━━━━━━━━━━━━━━━ 18s 82ms/step - accuracy: 0.7685 - loss: 0.7446

350/573 ━━━━━━━━━━━━━━━━━━━━ 18s 82ms/step - accuracy: 0.7688 - loss: 0.7434

351/573 ━━━━━━━━━━━━━━━━━━━━ 18s 82ms/step - accuracy: 0.7691 - loss: 0.7429

352/573 ━━━━━━━━━━━━━━━━━━━━ 18s 82ms/step - accuracy: 0.7693 - loss: 0.7420

353/573 ━━━━━━━━━━━━━━━━━━━━ 18s 82ms/step - accuracy: 0.7696 - loss: 0.7405

354/573 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - accuracy: 0.7702 - loss: 0.7387

355/573 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - accuracy: 0.7706 - loss: 0.7374

356/573 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - accuracy: 0.7709 - loss: 0.7360

357/573 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - accuracy: 0.7711 - loss: 0.7356

358/573 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - accuracy: 0.7713 - loss: 0.7346

359/573 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - accuracy: 0.7714 - loss: 0.7343

360/573 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - accuracy: 0.7717 - loss: 0.7332

361/573 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - accuracy: 0.7720 - loss: 0.7323

362/573 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - accuracy: 0.7723 - loss: 0.7316

363/573 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - accuracy: 0.7723 - loss: 0.7314

364/573 ━━━━━━━━━━━━━━━━━━━━ 17s 82ms/step - accuracy: 0.7726 - loss: 0.7311

365/573 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.7728 - loss: 0.7304

366/573 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.7729 - loss: 0.7299

367/573 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.7730 - loss: 0.7293

368/573 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.7735 - loss: 0.7281

369/573 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.7735 - loss: 0.7278

370/573 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.7739 - loss: 0.7265

371/573 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.7742 - loss: 0.7256

372/573 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.7742 - loss: 0.7249

373/573 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.7744 - loss: 0.7237

374/573 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.7746 - loss: 0.7229

375/573 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.7750 - loss: 0.7216

376/573 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.7754 - loss: 0.7207

377/573 ━━━━━━━━━━━━━━━━━━━━ 16s 82ms/step - accuracy: 0.7756 - loss: 0.7202

378/573 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - accuracy: 0.7758 - loss: 0.7191

379/573 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - accuracy: 0.7759 - loss: 0.7189

380/573 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - accuracy: 0.7760 - loss: 0.7191

381/573 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - accuracy: 0.7763 - loss: 0.7183

382/573 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - accuracy: 0.7765 - loss: 0.7173

383/573 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - accuracy: 0.7767 - loss: 0.7167

384/573 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - accuracy: 0.7769 - loss: 0.7165

385/573 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - accuracy: 0.7773 - loss: 0.7158

386/573 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - accuracy: 0.7777 - loss: 0.7144

387/573 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - accuracy: 0.7778 - loss: 0.7140

388/573 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - accuracy: 0.7781 - loss: 0.7133

389/573 ━━━━━━━━━━━━━━━━━━━━ 15s 82ms/step - accuracy: 0.7781 - loss: 0.7133

390/573 ━━━━━━━━━━━━━━━━━━━━ 14s 82ms/step - accuracy: 0.7785 - loss: 0.7118

391/573 ━━━━━━━━━━━━━━━━━━━━ 14s 82ms/step - accuracy: 0.7789 - loss: 0.7106

392/573 ━━━━━━━━━━━━━━━━━━━━ 14s 82ms/step - accuracy: 0.7790 - loss: 0.7109

393/573 ━━━━━━━━━━━━━━━━━━━━ 14s 82ms/step - accuracy: 0.7795 - loss: 0.7094

394/573 ━━━━━━━━━━━━━━━━━━━━ 14s 82ms/step - accuracy: 0.7797 - loss: 0.7082

395/573 ━━━━━━━━━━━━━━━━━━━━ 14s 82ms/step - accuracy: 0.7800 - loss: 0.7073

396/573 ━━━━━━━━━━━━━━━━━━━━ 14s 82ms/step - accuracy: 0.7803 - loss: 0.7063

397/573 ━━━━━━━━━━━━━━━━━━━━ 14s 82ms/step - accuracy: 0.7807 - loss: 0.7057

398/573 ━━━━━━━━━━━━━━━━━━━━ 14s 82ms/step - accuracy: 0.7808 - loss: 0.7053

399/573 ━━━━━━━━━━━━━━━━━━━━ 14s 82ms/step - accuracy: 0.7811 - loss: 0.7049

400/573 ━━━━━━━━━━━━━━━━━━━━ 14s 82ms/step - accuracy: 0.7811 - loss: 0.7048

401/573 ━━━━━━━━━━━━━━━━━━━━ 14s 82ms/step - accuracy: 0.7815 - loss: 0.7035

402/573 ━━━━━━━━━━━━━━━━━━━━ 13s 82ms/step - accuracy: 0.7818 - loss: 0.7026

403/573 ━━━━━━━━━━━━━━━━━━━━ 13s 82ms/step - accuracy: 0.7817 - loss: 0.7025

404/573 ━━━━━━━━━━━━━━━━━━━━ 13s 82ms/step - accuracy: 0.7817 - loss: 0.7021

405/573 ━━━━━━━━━━━━━━━━━━━━ 13s 82ms/step - accuracy: 0.7820 - loss: 0.7011

406/573 ━━━━━━━━━━━━━━━━━━━━ 13s 82ms/step - accuracy: 0.7821 - loss: 0.7008

407/573 ━━━━━━━━━━━━━━━━━━━━ 13s 82ms/step - accuracy: 0.7824 - loss: 0.7004

408/573 ━━━━━━━━━━━━━━━━━━━━ 13s 82ms/step - accuracy: 0.7828 - loss: 0.6995

409/573 ━━━━━━━━━━━━━━━━━━━━ 13s 82ms/step - accuracy: 0.7829 - loss: 0.6991

410/573 ━━━━━━━━━━━━━━━━━━━━ 13s 82ms/step - accuracy: 0.7830 - loss: 0.6985

411/573 ━━━━━━━━━━━━━━━━━━━━ 13s 82ms/step - accuracy: 0.7830 - loss: 0.6985

412/573 ━━━━━━━━━━━━━━━━━━━━ 13s 82ms/step - accuracy: 0.7832 - loss: 0.6980

413/573 ━━━━━━━━━━━━━━━━━━━━ 13s 82ms/step - accuracy: 0.7830 - loss: 0.6976

414/573 ━━━━━━━━━━━━━━━━━━━━ 13s 82ms/step - accuracy: 0.7833 - loss: 0.6973

415/573 ━━━━━━━━━━━━━━━━━━━━ 12s 82ms/step - accuracy: 0.7835 - loss: 0.6967

416/573 ━━━━━━━━━━━━━━━━━━━━ 12s 82ms/step - accuracy: 0.7836 - loss: 0.6963

417/573 ━━━━━━━━━━━━━━━━━━━━ 12s 82ms/step - accuracy: 0.7836 - loss: 0.6956

418/573 ━━━━━━━━━━━━━━━━━━━━ 12s 82ms/step - accuracy: 0.7838 - loss: 0.6953

419/573 ━━━━━━━━━━━━━━━━━━━━ 12s 82ms/step - accuracy: 0.7840 - loss: 0.6954

420/573 ━━━━━━━━━━━━━━━━━━━━ 12s 82ms/step - accuracy: 0.7840 - loss: 0.6949

421/573 ━━━━━━━━━━━━━━━━━━━━ 12s 82ms/step - accuracy: 0.7846 - loss: 0.6935

422/573 ━━━━━━━━━━━━━━━━━━━━ 12s 82ms/step - accuracy: 0.7847 - loss: 0.6931

423/573 ━━━━━━━━━━━━━━━━━━━━ 12s 82ms/step - accuracy: 0.7848 - loss: 0.6928

424/573 ━━━━━━━━━━━━━━━━━━━━ 12s 82ms/step - accuracy: 0.7849 - loss: 0.6927

425/573 ━━━━━━━━━━━━━━━━━━━━ 12s 82ms/step - accuracy: 0.7853 - loss: 0.6916

426/573 ━━━━━━━━━━━━━━━━━━━━ 12s 82ms/step - accuracy: 0.7856 - loss: 0.6911

427/573 ━━━━━━━━━━━━━━━━━━━━ 11s 82ms/step - accuracy: 0.7856 - loss: 0.6905

428/573 ━━━━━━━━━━━━━━━━━━━━ 11s 82ms/step - accuracy: 0.7860 - loss: 0.6894

429/573 ━━━━━━━━━━━━━━━━━━━━ 11s 82ms/step - accuracy: 0.7862 - loss: 0.6885

430/573 ━━━━━━━━━━━━━━━━━━━━ 11s 82ms/step - accuracy: 0.7865 - loss: 0.6875

431/573 ━━━━━━━━━━━━━━━━━━━━ 11s 82ms/step - accuracy: 0.7866 - loss: 0.6869

432/573 ━━━━━━━━━━━━━━━━━━━━ 11s 82ms/step - accuracy: 0.7868 - loss: 0.6858

433/573 ━━━━━━━━━━━━━━━━━━━━ 11s 82ms/step - accuracy: 0.7871 - loss: 0.6851

434/573 ━━━━━━━━━━━━━━━━━━━━ 11s 82ms/step - accuracy: 0.7873 - loss: 0.6844

435/573 ━━━━━━━━━━━━━━━━━━━━ 11s 82ms/step - accuracy: 0.7877 - loss: 0.6836

436/573 ━━━━━━━━━━━━━━━━━━━━ 11s 82ms/step - accuracy: 0.7880 - loss: 0.6827

437/573 ━━━━━━━━━━━━━━━━━━━━ 11s 82ms/step - accuracy: 0.7882 - loss: 0.6819

438/573 ━━━━━━━━━━━━━━━━━━━━ 11s 82ms/step - accuracy: 0.7883 - loss: 0.6819

439/573 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - accuracy: 0.7886 - loss: 0.6811

440/573 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - accuracy: 0.7890 - loss: 0.6800

441/573 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - accuracy: 0.7892 - loss: 0.6792

442/573 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - accuracy: 0.7895 - loss: 0.6782

443/573 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - accuracy: 0.7896 - loss: 0.6780

444/573 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - accuracy: 0.7896 - loss: 0.6780

445/573 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - accuracy: 0.7897 - loss: 0.6772

446/573 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - accuracy: 0.7899 - loss: 0.6767

447/573 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - accuracy: 0.7900 - loss: 0.6763

448/573 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - accuracy: 0.7903 - loss: 0.6751

449/573 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - accuracy: 0.7904 - loss: 0.6744

450/573 ━━━━━━━━━━━━━━━━━━━━ 10s 82ms/step - accuracy: 0.7907 - loss: 0.6734

451/573 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - accuracy: 0.7910 - loss: 0.6728

452/573 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - accuracy: 0.7912 - loss: 0.6724

453/573 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - accuracy: 0.7915 - loss: 0.6713

454/573 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - accuracy: 0.7918 - loss: 0.6704

455/573 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - accuracy: 0.7919 - loss: 0.6697

456/573 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - accuracy: 0.7919 - loss: 0.6692

457/573 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - accuracy: 0.7921 - loss: 0.6685

458/573 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - accuracy: 0.7925 - loss: 0.6673

459/573 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - accuracy: 0.7927 - loss: 0.6664

460/573 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - accuracy: 0.7928 - loss: 0.6659

461/573 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - accuracy: 0.7930 - loss: 0.6653

462/573 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - accuracy: 0.7931 - loss: 0.6646

463/573 ━━━━━━━━━━━━━━━━━━━━ 9s 82ms/step - accuracy: 0.7933 - loss: 0.6638

464/573 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - accuracy: 0.7934 - loss: 0.6634

465/573 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - accuracy: 0.7932 - loss: 0.6640

466/573 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - accuracy: 0.7931 - loss: 0.6648

467/573 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - accuracy: 0.7934 - loss: 0.6639

468/573 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - accuracy: 0.7938 - loss: 0.6628

469/573 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - accuracy: 0.7940 - loss: 0.6624

470/573 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - accuracy: 0.7941 - loss: 0.6621

471/573 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - accuracy: 0.7944 - loss: 0.6614

472/573 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - accuracy: 0.7945 - loss: 0.6614

473/573 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - accuracy: 0.7948 - loss: 0.6608

474/573 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - accuracy: 0.7950 - loss: 0.6598

475/573 ━━━━━━━━━━━━━━━━━━━━ 8s 82ms/step - accuracy: 0.7952 - loss: 0.6597

476/573 ━━━━━━━━━━━━━━━━━━━━ 7s 82ms/step - accuracy: 0.7951 - loss: 0.6595

477/573 ━━━━━━━━━━━━━━━━━━━━ 7s 82ms/step - accuracy: 0.7953 - loss: 0.6592

478/573 ━━━━━━━━━━━━━━━━━━━━ 7s 82ms/step - accuracy: 0.7955 - loss: 0.6584

479/573 ━━━━━━━━━━━━━━━━━━━━ 7s 82ms/step - accuracy: 0.7958 - loss: 0.6572

480/573 ━━━━━━━━━━━━━━━━━━━━ 7s 82ms/step - accuracy: 0.7961 - loss: 0.6572

481/573 ━━━━━━━━━━━━━━━━━━━━ 7s 82ms/step - accuracy: 0.7960 - loss: 0.6571

482/573 ━━━━━━━━━━━━━━━━━━━━ 7s 82ms/step - accuracy: 0.7960 - loss: 0.6567

483/573 ━━━━━━━━━━━━━━━━━━━━ 7s 82ms/step - accuracy: 0.7962 - loss: 0.6561

484/573 ━━━━━━━━━━━━━━━━━━━━ 7s 82ms/step - accuracy: 0.7963 - loss: 0.6558

485/573 ━━━━━━━━━━━━━━━━━━━━ 7s 82ms/step - accuracy: 0.7964 - loss: 0.6557

486/573 ━━━━━━━━━━━━━━━━━━━━ 7s 82ms/step - accuracy: 0.7964 - loss: 0.6551

487/573 ━━━━━━━━━━━━━━━━━━━━ 7s 82ms/step - accuracy: 0.7966 - loss: 0.6545

488/573 ━━━━━━━━━━━━━━━━━━━━ 6s 82ms/step - accuracy: 0.7969 - loss: 0.6536

489/573 ━━━━━━━━━━━━━━━━━━━━ 6s 82ms/step - accuracy: 0.7970 - loss: 0.6538

490/573 ━━━━━━━━━━━━━━━━━━━━ 6s 82ms/step - accuracy: 0.7972 - loss: 0.6529

491/573 ━━━━━━━━━━━━━━━━━━━━ 6s 82ms/step - accuracy: 0.7972 - loss: 0.6526

492/573 ━━━━━━━━━━━━━━━━━━━━ 6s 82ms/step - accuracy: 0.7974 - loss: 0.6520

493/573 ━━━━━━━━━━━━━━━━━━━━ 6s 82ms/step - accuracy: 0.7975 - loss: 0.6517

494/573 ━━━━━━━━━━━━━━━━━━━━ 6s 82ms/step - accuracy: 0.7976 - loss: 0.6513

495/573 ━━━━━━━━━━━━━━━━━━━━ 6s 82ms/step - accuracy: 0.7978 - loss: 0.6505

496/573 ━━━━━━━━━━━━━━━━━━━━ 6s 82ms/step - accuracy: 0.7981 - loss: 0.6496

497/573 ━━━━━━━━━━━━━━━━━━━━ 6s 82ms/step - accuracy: 0.7983 - loss: 0.6486

498/573 ━━━━━━━━━━━━━━━━━━━━ 6s 82ms/step - accuracy: 0.7985 - loss: 0.6478

499/573 ━━━━━━━━━━━━━━━━━━━━ 6s 82ms/step - accuracy: 0.7988 - loss: 0.6470

500/573 ━━━━━━━━━━━━━━━━━━━━ 5s 82ms/step - accuracy: 0.7989 - loss: 0.6464

501/573 ━━━━━━━━━━━━━━━━━━━━ 5s 82ms/step - accuracy: 0.7991 - loss: 0.6460

502/573 ━━━━━━━━━━━━━━━━━━━━ 5s 82ms/step - accuracy: 0.7994 - loss: 0.6452

503/573 ━━━━━━━━━━━━━━━━━━━━ 5s 82ms/step - accuracy: 0.7995 - loss: 0.6448

504/573 ━━━━━━━━━━━━━━━━━━━━ 5s 82ms/step - accuracy: 0.7993 - loss: 0.6447

505/573 ━━━━━━━━━━━━━━━━━━━━ 5s 82ms/step - accuracy: 0.7996 - loss: 0.6440

506/573 ━━━━━━━━━━━━━━━━━━━━ 5s 82ms/step - accuracy: 0.7998 - loss: 0.6433

507/573 ━━━━━━━━━━━━━━━━━━━━ 5s 82ms/step - accuracy: 0.8001 - loss: 0.6434

508/573 ━━━━━━━━━━━━━━━━━━━━ 5s 82ms/step - accuracy: 0.8003 - loss: 0.6428

509/573 ━━━━━━━━━━━━━━━━━━━━ 5s 82ms/step - accuracy: 0.8004 - loss: 0.6427

510/573 ━━━━━━━━━━━━━━━━━━━━ 5s 82ms/step - accuracy: 0.8006 - loss: 0.6419

511/573 ━━━━━━━━━━━━━━━━━━━━ 5s 82ms/step - accuracy: 0.8009 - loss: 0.6411

512/573 ━━━━━━━━━━━━━━━━━━━━ 4s 82ms/step - accuracy: 0.8011 - loss: 0.6402

513/573 ━━━━━━━━━━━━━━━━━━━━ 4s 82ms/step - accuracy: 0.8013 - loss: 0.6397

514/573 ━━━━━━━━━━━━━━━━━━━━ 4s 82ms/step - accuracy: 0.8015 - loss: 0.6391

515/573 ━━━━━━━━━━━━━━━━━━━━ 4s 82ms/step - accuracy: 0.8017 - loss: 0.6386

516/573 ━━━━━━━━━━━━━━━━━━━━ 4s 82ms/step - accuracy: 0.8019 - loss: 0.6378

517/573 ━━━━━━━━━━━━━━━━━━━━ 4s 82ms/step - accuracy: 0.8019 - loss: 0.6383

518/573 ━━━━━━━━━━━━━━━━━━━━ 4s 82ms/step - accuracy: 0.8021 - loss: 0.6380

519/573 ━━━━━━━━━━━━━━━━━━━━ 4s 82ms/step - accuracy: 0.8024 - loss: 0.6372

520/573 ━━━━━━━━━━━━━━━━━━━━ 4s 82ms/step - accuracy: 0.8026 - loss: 0.6363

521/573 ━━━━━━━━━━━━━━━━━━━━ 4s 82ms/step - accuracy: 0.8028 - loss: 0.6360

522/573 ━━━━━━━━━━━━━━━━━━━━ 4s 82ms/step - accuracy: 0.8025 - loss: 0.6371

523/573 ━━━━━━━━━━━━━━━━━━━━ 4s 82ms/step - accuracy: 0.8027 - loss: 0.6366

524/573 ━━━━━━━━━━━━━━━━━━━━ 4s 82ms/step - accuracy: 0.8029 - loss: 0.6361

525/573 ━━━━━━━━━━━━━━━━━━━━ 3s 82ms/step - accuracy: 0.8031 - loss: 0.6354

526/573 ━━━━━━━━━━━━━━━━━━━━ 3s 82ms/step - accuracy: 0.8031 - loss: 0.6352

527/573 ━━━━━━━━━━━━━━━━━━━━ 3s 82ms/step - accuracy: 0.8033 - loss: 0.6344

528/573 ━━━━━━━━━━━━━━━━━━━━ 3s 82ms/step - accuracy: 0.8034 - loss: 0.6340

529/573 ━━━━━━━━━━━━━━━━━━━━ 3s 82ms/step - accuracy: 0.8036 - loss: 0.6330

530/573 ━━━━━━━━━━━━━━━━━━━━ 3s 82ms/step - accuracy: 0.8038 - loss: 0.6321

531/573 ━━━━━━━━━━━━━━━━━━━━ 3s 82ms/step - accuracy: 0.8040 - loss: 0.6317

532/573 ━━━━━━━━━━━━━━━━━━━━ 3s 82ms/step - accuracy: 0.8041 - loss: 0.6308

533/573 ━━━━━━━━━━━━━━━━━━━━ 3s 82ms/step - accuracy: 0.8044 - loss: 0.6301

534/573 ━━━━━━━━━━━━━━━━━━━━ 3s 82ms/step - accuracy: 0.8044 - loss: 0.6299

535/573 ━━━━━━━━━━━━━━━━━━━━ 3s 82ms/step - accuracy: 0.8046 - loss: 0.6293

536/573 ━━━━━━━━━━━━━━━━━━━━ 3s 82ms/step - accuracy: 0.8047 - loss: 0.6290

537/573 ━━━━━━━━━━━━━━━━━━━━ 2s 82ms/step - accuracy: 0.8050 - loss: 0.6282

538/573 ━━━━━━━━━━━━━━━━━━━━ 2s 82ms/step - accuracy: 0.8053 - loss: 0.6278

539/573 ━━━━━━━━━━━━━━━━━━━━ 2s 82ms/step - accuracy: 0.8055 - loss: 0.6272

540/573 ━━━━━━━━━━━━━━━━━━━━ 2s 82ms/step - accuracy: 0.8057 - loss: 0.6267

541/573 ━━━━━━━━━━━━━━━━━━━━ 2s 82ms/step - accuracy: 0.8058 - loss: 0.6263

542/573 ━━━━━━━━━━━━━━━━━━━━ 2s 82ms/step - accuracy: 0.8059 - loss: 0.6263

543/573 ━━━━━━━━━━━━━━━━━━━━ 2s 82ms/step - accuracy: 0.8060 - loss: 0.6257

544/573 ━━━━━━━━━━━━━━━━━━━━ 2s 82ms/step - accuracy: 0.8063 - loss: 0.6247

545/573 ━━━━━━━━━━━━━━━━━━━━ 2s 82ms/step - accuracy: 0.8065 - loss: 0.6243

546/573 ━━━━━━━━━━━━━━━━━━━━ 2s 82ms/step - accuracy: 0.8065 - loss: 0.6240

547/573 ━━━━━━━━━━━━━━━━━━━━ 2s 82ms/step - accuracy: 0.8067 - loss: 0.6233

548/573 ━━━━━━━━━━━━━━━━━━━━ 2s 82ms/step - accuracy: 0.8067 - loss: 0.6233

549/573 ━━━━━━━━━━━━━━━━━━━━ 1s 82ms/step - accuracy: 0.8067 - loss: 0.6236

550/573 ━━━━━━━━━━━━━━━━━━━━ 1s 82ms/step - accuracy: 0.8069 - loss: 0.6231

551/573 ━━━━━━━━━━━━━━━━━━━━ 1s 82ms/step - accuracy: 0.8070 - loss: 0.6229

552/573 ━━━━━━━━━━━━━━━━━━━━ 1s 82ms/step - accuracy: 0.8073 - loss: 0.6222

553/573 ━━━━━━━━━━━━━━━━━━━━ 1s 82ms/step - accuracy: 0.8074 - loss: 0.6219

554/573 ━━━━━━━━━━━━━━━━━━━━ 1s 82ms/step - accuracy: 0.8074 - loss: 0.6217

555/573 ━━━━━━━━━━━━━━━━━━━━ 1s 82ms/step - accuracy: 0.8074 - loss: 0.6214

556/573 ━━━━━━━━━━━━━━━━━━━━ 1s 82ms/step - accuracy: 0.8077 - loss: 0.6205

557/573 ━━━━━━━━━━━━━━━━━━━━ 1s 82ms/step - accuracy: 0.8078 - loss: 0.6201

558/573 ━━━━━━━━━━━━━━━━━━━━ 1s 82ms/step - accuracy: 0.8080 - loss: 0.6198

559/573 ━━━━━━━━━━━━━━━━━━━━ 1s 82ms/step - accuracy: 0.8082 - loss: 0.6190

560/573 ━━━━━━━━━━━━━━━━━━━━ 1s 82ms/step - accuracy: 0.8085 - loss: 0.6182

561/573 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.8087 - loss: 0.6175

562/573 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.8089 - loss: 0.6169

563/573 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.8091 - loss: 0.6165

564/573 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.8092 - loss: 0.6160

565/573 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.8095 - loss: 0.6152

566/573 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.8095 - loss: 0.6153

567/573 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.8096 - loss: 0.6148

568/573 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.8097 - loss: 0.6143

569/573 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.8099 - loss: 0.6140

570/573 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.8101 - loss: 0.6132

571/573 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.8104 - loss: 0.6123

572/573 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.8106 - loss: 0.6115

573/573 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.8105 - loss: 0.6116

573/573 ━━━━━━━━━━━━━━━━━━━━ 55s 93ms/step - accuracy: 0.8105 - loss: 0.6116 - val_accuracy: 0.9206 - val_loss: 0.2485

Epoch 2/20

  1/573 ━━━━━━━━━━━━━━━━━━━━ 1:06 116ms/step - accuracy: 0.9062 - loss: 0.1828

  2/573 ━━━━━━━━━━━━━━━━━━━━ 45s 79ms/step - accuracy: 0.9062 - loss: 0.2072

  3/573 ━━━━━━━━━━━━━━━━━━━━ 57s 100ms/step - accuracy: 0.8854 - loss: 0.3039

  4/573 ━━━━━━━━━━━━━━━━━━━━ 53s 93ms/step - accuracy: 0.8828 - loss: 0.3413

  5/573 ━━━━━━━━━━━━━━━━━━━━ 52s 92ms/step - accuracy: 0.8938 - loss: 0.3180

  6/573 ━━━━━━━━━━━━━━━━━━━━ 50s 89ms/step - accuracy: 0.8802 - loss: 0.3344

  7/573 ━━━━━━━━━━━━━━━━━━━━ 49s 87ms/step - accuracy: 0.8929 - loss: 0.3027

  8/573 ━━━━━━━━━━━━━━━━━━━━ 48s 86ms/step - accuracy: 0.8945 - loss: 0.2928

  9/573 ━━━━━━━━━━━━━━━━━━━━ 47s 85ms/step - accuracy: 0.8993 - loss: 0.2766

 10/573 ━━━━━━━━━━━━━━━━━━━━ 47s 84ms/step - accuracy: 0.9031 - loss: 0.2752

 11/573 ━━━━━━━━━━━━━━━━━━━━ 47s 85ms/step - accuracy: 0.9006 - loss: 0.2999

 12/573 ━━━━━━━━━━━━━━━━━━━━ 46s 84ms/step - accuracy: 0.9010 - loss: 0.2936

 13/573 ━━━━━━━━━━━━━━━━━━━━ 46s 84ms/step - accuracy: 0.8966 - loss: 0.3200

 14/573 ━━━━━━━━━━━━━━━━━━━━ 46s 83ms/step - accuracy: 0.8929 - loss: 0.3242

 15/573 ━━━━━━━━━━━━━━━━━━━━ 46s 83ms/step - accuracy: 0.8896 - loss: 0.3287

 16/573 ━━━━━━━━━━━━━━━━━━━━ 45s 82ms/step - accuracy: 0.8867 - loss: 0.3342

 17/573 ━━━━━━━━━━━━━━━━━━━━ 45s 82ms/step - accuracy: 0.8915 - loss: 0.3212

 18/573 ━━━━━━━━━━━━━━━━━━━━ 45s 82ms/step - accuracy: 0.8958 - loss: 0.3126

 19/573 ━━━━━━━━━━━━━━━━━━━━ 45s 82ms/step - accuracy: 0.8964 - loss: 0.3165

 20/573 ━━━━━━━━━━━━━━━━━━━━ 44s 81ms/step - accuracy: 0.8938 - loss: 0.3349

 21/573 ━━━━━━━━━━━━━━━━━━━━ 45s 83ms/step - accuracy: 0.8929 - loss: 0.3539

 22/573 ━━━━━━━━━━━━━━━━━━━━ 45s 82ms/step - accuracy: 0.8963 - loss: 0.3498

 23/573 ━━━━━━━━━━━━━━━━━━━━ 45s 82ms/step - accuracy: 0.9008 - loss: 0.3382

 24/573 ━━━━━━━━━━━━━━━━━━━━ 44s 82ms/step - accuracy: 0.9023 - loss: 0.3321

 25/573 ━━━━━━━━━━━━━━━━━━━━ 44s 82ms/step - accuracy: 0.9025 - loss: 0.3292

 26/573 ━━━━━━━━━━━━━━━━━━━━ 44s 82ms/step - accuracy: 0.9050 - loss: 0.3246

 27/573 ━━━━━━━━━━━━━━━━━━━━ 44s 82ms/step - accuracy: 0.9039 - loss: 0.3304

 28/573 ━━━━━━━━━━━━━━━━━━━━ 44s 81ms/step - accuracy: 0.9040 - loss: 0.3421

 29/573 ━━━━━━━━━━━━━━━━━━━━ 44s 82ms/step - accuracy: 0.9041 - loss: 0.3397

 30/573 ━━━━━━━━━━━━━━━━━━━━ 44s 81ms/step - accuracy: 0.9042 - loss: 0.3356

 31/573 ━━━━━━━━━━━━━━━━━━━━ 43s 81ms/step - accuracy: 0.9042 - loss: 0.3302

 32/573 ━━━━━━━━━━━━━━━━━━━━ 43s 81ms/step - accuracy: 0.9023 - loss: 0.3310

 33/573 ━━━━━━━━━━━━━━━━━━━━ 43s 81ms/step - accuracy: 0.8977 - loss: 0.3378

 34/573 ━━━━━━━━━━━━━━━━━━━━ 43s 81ms/step - accuracy: 0.8971 - loss: 0.3403

 35/573 ━━━━━━━━━━━━━━━━━━━━ 43s 81ms/step - accuracy: 0.8973 - loss: 0.3396

 36/573 ━━━━━━━━━━━━━━━━━━━━ 43s 81ms/step - accuracy: 0.8984 - loss: 0.3358

 37/573 ━━━━━━━━━━━━━━━━━━━━ 43s 81ms/step - accuracy: 0.8961 - loss: 0.3376

 38/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.8923 - loss: 0.3430

 39/573 ━━━━━━━━━━━━━━━━━━━━ 42s 81ms/step - accuracy: 0.8942 - loss: 0.3380

 40/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.8953 - loss: 0.3353

 41/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.8963 - loss: 0.3308

 42/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.8943 - loss: 0.3365

 43/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.8961 - loss: 0.3342

 44/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.8949 - loss: 0.3395

 45/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.8931 - loss: 0.3429

 46/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.8913 - loss: 0.3449

 47/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.8916 - loss: 0.3453

 48/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.8919 - loss: 0.3439

 49/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.8890 - loss: 0.3519

 50/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.8888 - loss: 0.3523

 51/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.8897 - loss: 0.3520

 52/573 ━━━━━━━━━━━━━━━━━━━━ 42s 81ms/step - accuracy: 0.8918 - loss: 0.3470

 53/573 ━━━━━━━━━━━━━━━━━━━━ 42s 81ms/step - accuracy: 0.8921 - loss: 0.3442

 54/573 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.8924 - loss: 0.3437

 55/573 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.8938 - loss: 0.3400

 56/573 ━━━━━━━━━━━━━━━━━━━━ 42s 82ms/step - accuracy: 0.8934 - loss: 0.3450

 57/573 ━━━━━━━━━━━━━━━━━━━━ 42s 81ms/step - accuracy: 0.8942 - loss: 0.3424

 58/573 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.8922 - loss: 0.3432

 59/573 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.8919 - loss: 0.3472

 60/573 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.8938 - loss: 0.3428

 61/573 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.8934 - loss: 0.3442

 62/573 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.8947 - loss: 0.3421

 63/573 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.8934 - loss: 0.3489

 64/573 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.8940 - loss: 0.3481

 65/573 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.8938 - loss: 0.3467

 66/573 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.8939 - loss: 0.3476

 67/573 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.8937 - loss: 0.3458

 68/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.8938 - loss: 0.3461

 69/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.8945 - loss: 0.3452

 70/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.8946 - loss: 0.3453

 71/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.8944 - loss: 0.3467

 72/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.8941 - loss: 0.3471

 73/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.8934 - loss: 0.3492

 74/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.8936 - loss: 0.3475

 75/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.8929 - loss: 0.3500

 76/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.8935 - loss: 0.3502

 77/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.8933 - loss: 0.3499

 78/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.8930 - loss: 0.3504

 79/573 ━━━━━━━━━━━━━━━━━━━━ 39s 81ms/step - accuracy: 0.8924 - loss: 0.3507

 80/573 ━━━━━━━━━━━━━━━━━━━━ 39s 81ms/step - accuracy: 0.8934 - loss: 0.3490

 81/573 ━━━━━━━━━━━━━━━━━━━━ 39s 81ms/step - accuracy: 0.8924 - loss: 0.3494

 82/573 ━━━━━━━━━━━━━━━━━━━━ 39s 81ms/step - accuracy: 0.8929 - loss: 0.3492

 83/573 ━━━━━━━━━━━━━━━━━━━━ 39s 81ms/step - accuracy: 0.8934 - loss: 0.3475

 84/573 ━━━━━━━━━━━━━━━━━━━━ 39s 81ms/step - accuracy: 0.8943 - loss: 0.3443

 85/573 ━━━━━━━━━━━━━━━━━━━━ 39s 81ms/step - accuracy: 0.8949 - loss: 0.3432

 86/573 ━━━━━━━━━━━━━━━━━━━━ 39s 81ms/step - accuracy: 0.8935 - loss: 0.3493

 87/573 ━━━━━━━━━━━━━━━━━━━━ 39s 81ms/step - accuracy: 0.8940 - loss: 0.3470

 88/573 ━━━━━━━━━━━━━━━━━━━━ 39s 81ms/step - accuracy: 0.8938 - loss: 0.3484

 89/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.8943 - loss: 0.3470

 90/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.8944 - loss: 0.3469

 91/573 ━━━━━━━━━━━━━━━━━━━━ 38s 81ms/step - accuracy: 0.8939 - loss: 0.3482

 92/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.8933 - loss: 0.3501

 93/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.8935 - loss: 0.3487

 94/573 ━━━━━━━━━━━━━━━━━━━━ 38s 81ms/step - accuracy: 0.8939 - loss: 0.3479

 95/573 ━━━━━━━━━━━━━━━━━━━━ 38s 81ms/step - accuracy: 0.8934 - loss: 0.3498

 96/573 ━━━━━━━━━━━━━━━━━━━━ 38s 81ms/step - accuracy: 0.8942 - loss: 0.3475

 97/573 ━━━━━━━━━━━━━━━━━━━━ 38s 81ms/step - accuracy: 0.8940 - loss: 0.3492

 98/573 ━━━━━━━━━━━━━━━━━━━━ 38s 81ms/step - accuracy: 0.8941 - loss: 0.3484

 99/573 ━━━━━━━━━━━━━━━━━━━━ 38s 81ms/step - accuracy: 0.8946 - loss: 0.3480

100/573 ━━━━━━━━━━━━━━━━━━━━ 38s 81ms/step - accuracy: 0.8938 - loss: 0.3546

101/573 ━━━━━━━━━━━━━━━━━━━━ 38s 81ms/step - accuracy: 0.8936 - loss: 0.3536

102/573 ━━━━━━━━━━━━━━━━━━━━ 37s 81ms/step - accuracy: 0.8946 - loss: 0.3511

103/573 ━━━━━━━━━━━━━━━━━━━━ 37s 81ms/step - accuracy: 0.8944 - loss: 0.3499

104/573 ━━━━━━━━━━━━━━━━━━━━ 37s 81ms/step - accuracy: 0.8942 - loss: 0.3496

105/573 ━━━━━━━━━━━━━━━━━━━━ 37s 81ms/step - accuracy: 0.8929 - loss: 0.3514

106/573 ━━━━━━━━━━━━━━━━━━━━ 37s 81ms/step - accuracy: 0.8918 - loss: 0.3531

107/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.8914 - loss: 0.3527

108/573 ━━━━━━━━━━━━━━━━━━━━ 37s 81ms/step - accuracy: 0.8912 - loss: 0.3521

109/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.8911 - loss: 0.3519

110/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.8906 - loss: 0.3519

111/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.8908 - loss: 0.3514

112/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.8909 - loss: 0.3515

113/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8913 - loss: 0.3507

114/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8914 - loss: 0.3500

115/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8913 - loss: 0.3520

116/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8912 - loss: 0.3521

117/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8902 - loss: 0.3531

118/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8906 - loss: 0.3517

119/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8902 - loss: 0.3532

120/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8906 - loss: 0.3535

121/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8897 - loss: 0.3571

122/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8901 - loss: 0.3563

123/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8897 - loss: 0.3572

124/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8899 - loss: 0.3576

125/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8905 - loss: 0.3554

126/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8904 - loss: 0.3561

127/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8903 - loss: 0.3553

128/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8896 - loss: 0.3588

129/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8898 - loss: 0.3595

130/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8901 - loss: 0.3583

131/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8896 - loss: 0.3591

132/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8897 - loss: 0.3614

133/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8898 - loss: 0.3611

134/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8904 - loss: 0.3603

135/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8903 - loss: 0.3621

136/573 ━━━━━━━━━━━━━━━━━━━━ 34s 80ms/step - accuracy: 0.8909 - loss: 0.3606

137/573 ━━━━━━━━━━━━━━━━━━━━ 34s 80ms/step - accuracy: 0.8905 - loss: 0.3617

138/573 ━━━━━━━━━━━━━━━━━━━━ 34s 80ms/step - accuracy: 0.8904 - loss: 0.3623

139/573 ━━━━━━━━━━━━━━━━━━━━ 35s 81ms/step - accuracy: 0.8903 - loss: 0.3621

140/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.8895 - loss: 0.3629

141/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.8896 - loss: 0.3617

142/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.8900 - loss: 0.3615

143/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.8903 - loss: 0.3608

144/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.8900 - loss: 0.3614

145/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.8892 - loss: 0.3631

146/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.8887 - loss: 0.3635

147/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.8888 - loss: 0.3641

148/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.8883 - loss: 0.3642

149/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.8884 - loss: 0.3649

150/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.8890 - loss: 0.3634

151/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.8887 - loss: 0.3627

152/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.8890 - loss: 0.3623

153/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.8889 - loss: 0.3643

154/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.8892 - loss: 0.3632

155/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.8893 - loss: 0.3625

156/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.8890 - loss: 0.3625

157/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.8891 - loss: 0.3619

158/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.8894 - loss: 0.3616

159/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.8890 - loss: 0.3644

160/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.8889 - loss: 0.3638

161/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.8894 - loss: 0.3624

162/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.8899 - loss: 0.3610

163/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.8900 - loss: 0.3614

164/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.8901 - loss: 0.3605

165/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.8902 - loss: 0.3603

166/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.8902 - loss: 0.3601

167/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.8903 - loss: 0.3608

168/573 ━━━━━━━━━━━━━━━━━━━━ 32s 80ms/step - accuracy: 0.8906 - loss: 0.3597

169/573 ━━━━━━━━━━━━━━━━━━━━ 32s 80ms/step - accuracy: 0.8903 - loss: 0.3597

170/573 ━━━━━━━━━━━━━━━━━━━━ 32s 80ms/step - accuracy: 0.8899 - loss: 0.3615

171/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.8900 - loss: 0.3619

172/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.8895 - loss: 0.3633

173/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.8900 - loss: 0.3619

174/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.8901 - loss: 0.3623

175/573 ━━━━━━━━━━━━━━━━━━━━ 32s 81ms/step - accuracy: 0.8898 - loss: 0.3618

176/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8897 - loss: 0.3621

177/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8897 - loss: 0.3616

178/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8903 - loss: 0.3598

179/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8902 - loss: 0.3606

180/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8903 - loss: 0.3601

181/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8907 - loss: 0.3594

182/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8910 - loss: 0.3587

183/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8911 - loss: 0.3580

184/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8906 - loss: 0.3581

185/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8905 - loss: 0.3583

186/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8906 - loss: 0.3574

187/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8907 - loss: 0.3569

188/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8908 - loss: 0.3566

189/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8910 - loss: 0.3567

190/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8916 - loss: 0.3552

191/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8917 - loss: 0.3546

192/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8911 - loss: 0.3564

193/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8910 - loss: 0.3574

194/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8906 - loss: 0.3582

195/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8901 - loss: 0.3592

196/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8898 - loss: 0.3613

197/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8896 - loss: 0.3610

198/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8898 - loss: 0.3609

199/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8902 - loss: 0.3603

200/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8905 - loss: 0.3603

201/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8907 - loss: 0.3595

202/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8905 - loss: 0.3593

203/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8907 - loss: 0.3584

204/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8908 - loss: 0.3587

205/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8905 - loss: 0.3596

206/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8905 - loss: 0.3596

207/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8909 - loss: 0.3583

208/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8911 - loss: 0.3575

210/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8915 - loss: 0.3563

211/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8919 - loss: 0.3557

212/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8918 - loss: 0.3557

213/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8916 - loss: 0.3578

214/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8918 - loss: 0.3567

215/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8918 - loss: 0.3560

216/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8918 - loss: 0.3567

217/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8917 - loss: 0.3568

218/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8919 - loss: 0.3561

219/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8921 - loss: 0.3552

220/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8923 - loss: 0.3546

221/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8922 - loss: 0.3542

222/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8923 - loss: 0.3540

223/573 ━━━━━━━━━━━━━━━━━━━━ 27s 80ms/step - accuracy: 0.8924 - loss: 0.3536

224/573 ━━━━━━━━━━━━━━━━━━━━ 27s 80ms/step - accuracy: 0.8926 - loss: 0.3531

225/573 ━━━━━━━━━━━━━━━━━━━━ 27s 80ms/step - accuracy: 0.8926 - loss: 0.3526

226/573 ━━━━━━━━━━━━━━━━━━━━ 27s 80ms/step - accuracy: 0.8924 - loss: 0.3538

227/573 ━━━━━━━━━━━━━━━━━━━━ 27s 80ms/step - accuracy: 0.8926 - loss: 0.3535

228/573 ━━━━━━━━━━━━━━━━━━━━ 27s 80ms/step - accuracy: 0.8931 - loss: 0.3522

229/573 ━━━━━━━━━━━━━━━━━━━━ 27s 80ms/step - accuracy: 0.8930 - loss: 0.3524

230/573 ━━━━━━━━━━━━━━━━━━━━ 27s 80ms/step - accuracy: 0.8928 - loss: 0.3526

231/573 ━━━━━━━━━━━━━━━━━━━━ 27s 80ms/step - accuracy: 0.8931 - loss: 0.3518

232/573 ━━━━━━━━━━━━━━━━━━━━ 27s 80ms/step - accuracy: 0.8934 - loss: 0.3509

233/573 ━━━━━━━━━━━━━━━━━━━━ 27s 80ms/step - accuracy: 0.8939 - loss: 0.3497

234/573 ━━━━━━━━━━━━━━━━━━━━ 27s 80ms/step - accuracy: 0.8938 - loss: 0.3499

235/573 ━━━━━━━━━━━━━━━━━━━━ 27s 80ms/step - accuracy: 0.8937 - loss: 0.3500

236/573 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - accuracy: 0.8939 - loss: 0.3491

237/573 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - accuracy: 0.8937 - loss: 0.3496

238/573 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - accuracy: 0.8939 - loss: 0.3489

239/573 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - accuracy: 0.8934 - loss: 0.3503

240/573 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - accuracy: 0.8937 - loss: 0.3496

241/573 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - accuracy: 0.8938 - loss: 0.3493

242/573 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - accuracy: 0.8940 - loss: 0.3490

243/573 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - accuracy: 0.8938 - loss: 0.3487

244/573 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - accuracy: 0.8939 - loss: 0.3487

245/573 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - accuracy: 0.8937 - loss: 0.3490

246/573 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - accuracy: 0.8939 - loss: 0.3487

247/573 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - accuracy: 0.8938 - loss: 0.3485

248/573 ━━━━━━━━━━━━━━━━━━━━ 25s 80ms/step - accuracy: 0.8940 - loss: 0.3478

249/573 ━━━━━━━━━━━━━━━━━━━━ 25s 80ms/step - accuracy: 0.8942 - loss: 0.3470

250/573 ━━━━━━━━━━━━━━━━━━━━ 25s 80ms/step - accuracy: 0.8944 - loss: 0.3469

251/573 ━━━━━━━━━━━━━━━━━━━━ 25s 80ms/step - accuracy: 0.8942 - loss: 0.3469

252/573 ━━━━━━━━━━━━━━━━━━━━ 25s 80ms/step - accuracy: 0.8942 - loss: 0.3474

253/573 ━━━━━━━━━━━━━━━━━━━━ 25s 80ms/step - accuracy: 0.8944 - loss: 0.3474

254/573 ━━━━━━━━━━━━━━━━━━━━ 25s 80ms/step - accuracy: 0.8944 - loss: 0.3472

255/573 ━━━━━━━━━━━━━━━━━━━━ 25s 80ms/step - accuracy: 0.8945 - loss: 0.3469

256/573 ━━━━━━━━━━━━━━━━━━━━ 25s 80ms/step - accuracy: 0.8943 - loss: 0.3474

257/573 ━━━━━━━━━━━━━━━━━━━━ 25s 80ms/step - accuracy: 0.8941 - loss: 0.3479

258/573 ━━━━━━━━━━━━━━━━━━━━ 25s 80ms/step - accuracy: 0.8944 - loss: 0.3472

259/573 ━━━━━━━━━━━━━━━━━━━━ 25s 80ms/step - accuracy: 0.8944 - loss: 0.3474

260/573 ━━━━━━━━━━━━━━━━━━━━ 24s 80ms/step - accuracy: 0.8946 - loss: 0.3467

261/573 ━━━━━━━━━━━━━━━━━━━━ 24s 80ms/step - accuracy: 0.8941 - loss: 0.3488

262/573 ━━━━━━━━━━━━━━━━━━━━ 24s 80ms/step - accuracy: 0.8944 - loss: 0.3479

263/573 ━━━━━━━━━━━━━━━━━━━━ 24s 80ms/step - accuracy: 0.8943 - loss: 0.3481

264/573 ━━━━━━━━━━━━━━━━━━━━ 24s 80ms/step - accuracy: 0.8940 - loss: 0.3492

265/573 ━━━━━━━━━━━━━━━━━━━━ 24s 80ms/step - accuracy: 0.8940 - loss: 0.3504

266/573 ━━━━━━━━━━━━━━━━━━━━ 24s 80ms/step - accuracy: 0.8941 - loss: 0.3504

267/573 ━━━━━━━━━━━━━━━━━━━━ 24s 80ms/step - accuracy: 0.8941 - loss: 0.3500

268/573 ━━━━━━━━━━━━━━━━━━━━ 24s 80ms/step - accuracy: 0.8941 - loss: 0.3501

269/573 ━━━━━━━━━━━━━━━━━━━━ 24s 80ms/step - accuracy: 0.8937 - loss: 0.3502

270/573 ━━━━━━━━━━━━━━━━━━━━ 24s 80ms/step - accuracy: 0.8934 - loss: 0.3514

271/573 ━━━━━━━━━━━━━━━━━━━━ 24s 80ms/step - accuracy: 0.8934 - loss: 0.3513

272/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8936 - loss: 0.3506

273/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8936 - loss: 0.3506

274/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8937 - loss: 0.3498

275/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8932 - loss: 0.3514

276/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8934 - loss: 0.3505

277/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8933 - loss: 0.3508

278/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8932 - loss: 0.3515

279/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8931 - loss: 0.3514

280/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8929 - loss: 0.3522

281/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8930 - loss: 0.3517

282/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8930 - loss: 0.3511

283/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8931 - loss: 0.3515

284/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8929 - loss: 0.3523

285/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8930 - loss: 0.3526

286/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8929 - loss: 0.3525

287/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8928 - loss: 0.3519

288/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8928 - loss: 0.3520

289/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8927 - loss: 0.3517

290/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8928 - loss: 0.3513

291/573 ━━━━━━━━━━━━━━━━━━━━ 22s 79ms/step - accuracy: 0.8929 - loss: 0.3517

292/573 ━━━━━━━━━━━━━━━━━━━━ 22s 79ms/step - accuracy: 0.8925 - loss: 0.3525

293/573 ━━━━━━━━━━━━━━━━━━━━ 22s 79ms/step - accuracy: 0.8923 - loss: 0.3529

294/573 ━━━━━━━━━━━━━━━━━━━━ 22s 79ms/step - accuracy: 0.8922 - loss: 0.3529

295/573 ━━━━━━━━━━━━━━━━━━━━ 22s 79ms/step - accuracy: 0.8924 - loss: 0.3530

296/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8924 - loss: 0.3529

297/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8923 - loss: 0.3526

298/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8924 - loss: 0.3525

299/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8923 - loss: 0.3524

300/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8927 - loss: 0.3515

301/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8927 - loss: 0.3511

302/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8926 - loss: 0.3519

303/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8924 - loss: 0.3527

304/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8925 - loss: 0.3530

305/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8924 - loss: 0.3528

306/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8922 - loss: 0.3528

307/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8923 - loss: 0.3526

308/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8923 - loss: 0.3526

309/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8925 - loss: 0.3522

310/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8923 - loss: 0.3526

311/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8923 - loss: 0.3522

312/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8921 - loss: 0.3523

313/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8919 - loss: 0.3530

314/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8920 - loss: 0.3528

315/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8917 - loss: 0.3533

316/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8917 - loss: 0.3546

317/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8914 - loss: 0.3544

318/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8915 - loss: 0.3541

319/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8916 - loss: 0.3537

320/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8917 - loss: 0.3543

321/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8917 - loss: 0.3540

322/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8920 - loss: 0.3532

323/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8920 - loss: 0.3533

324/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8920 - loss: 0.3532

325/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8918 - loss: 0.3541

326/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8919 - loss: 0.3536

327/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8922 - loss: 0.3530

328/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8924 - loss: 0.3522

329/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8922 - loss: 0.3530

330/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8923 - loss: 0.3524

331/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8924 - loss: 0.3520

332/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8918 - loss: 0.3536

333/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8919 - loss: 0.3535

334/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8915 - loss: 0.3535

335/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8914 - loss: 0.3536

336/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8915 - loss: 0.3533

337/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8914 - loss: 0.3535

338/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8915 - loss: 0.3532

339/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8915 - loss: 0.3532

340/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8916 - loss: 0.3534

341/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8915 - loss: 0.3535

342/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8913 - loss: 0.3538

343/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8910 - loss: 0.3546

344/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8911 - loss: 0.3542

345/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8911 - loss: 0.3539

346/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8909 - loss: 0.3544

347/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8909 - loss: 0.3544

348/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8910 - loss: 0.3546

349/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8909 - loss: 0.3545

350/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8911 - loss: 0.3539

351/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8912 - loss: 0.3536

352/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8911 - loss: 0.3543

353/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8910 - loss: 0.3542

354/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8910 - loss: 0.3540

355/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8907 - loss: 0.3548

356/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8907 - loss: 0.3549

357/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8906 - loss: 0.3550

358/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8905 - loss: 0.3553

359/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8906 - loss: 0.3551

360/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8903 - loss: 0.3552

361/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8901 - loss: 0.3566

362/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8902 - loss: 0.3568

363/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8903 - loss: 0.3565

364/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8902 - loss: 0.3566

365/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8901 - loss: 0.3569

366/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8902 - loss: 0.3564

367/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8898 - loss: 0.3571

368/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8899 - loss: 0.3569

369/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8900 - loss: 0.3570

370/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8902 - loss: 0.3562

371/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8901 - loss: 0.3565

372/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8900 - loss: 0.3562

373/573 ━━━━━━━━━━━━━━━━━━━━ 15s 80ms/step - accuracy: 0.8901 - loss: 0.3561

374/573 ━━━━━━━━━━━━━━━━━━━━ 15s 80ms/step - accuracy: 0.8904 - loss: 0.3553

375/573 ━━━━━━━━━━━━━━━━━━━━ 15s 80ms/step - accuracy: 0.8904 - loss: 0.3550

376/573 ━━━━━━━━━━━━━━━━━━━━ 15s 80ms/step - accuracy: 0.8902 - loss: 0.3551

377/573 ━━━━━━━━━━━━━━━━━━━━ 15s 80ms/step - accuracy: 0.8902 - loss: 0.3549

378/573 ━━━━━━━━━━━━━━━━━━━━ 15s 80ms/step - accuracy: 0.8902 - loss: 0.3548

379/573 ━━━━━━━━━━━━━━━━━━━━ 15s 80ms/step - accuracy: 0.8902 - loss: 0.3554

380/573 ━━━━━━━━━━━━━━━━━━━━ 15s 80ms/step - accuracy: 0.8902 - loss: 0.3562

381/573 ━━━━━━━━━━━━━━━━━━━━ 15s 80ms/step - accuracy: 0.8902 - loss: 0.3561

382/573 ━━━━━━━━━━━━━━━━━━━━ 15s 80ms/step - accuracy: 0.8902 - loss: 0.3563

383/573 ━━━━━━━━━━━━━━━━━━━━ 15s 80ms/step - accuracy: 0.8902 - loss: 0.3561

384/573 ━━━━━━━━━━━━━━━━━━━━ 15s 80ms/step - accuracy: 0.8904 - loss: 0.3556

385/573 ━━━━━━━━━━━━━━━━━━━━ 14s 80ms/step - accuracy: 0.8904 - loss: 0.3561

386/573 ━━━━━━━━━━━━━━━━━━━━ 14s 80ms/step - accuracy: 0.8906 - loss: 0.3554

387/573 ━━━━━━━━━━━━━━━━━━━━ 14s 80ms/step - accuracy: 0.8902 - loss: 0.3563

388/573 ━━━━━━━━━━━━━━━━━━━━ 14s 80ms/step - accuracy: 0.8904 - loss: 0.3557

389/573 ━━━━━━━━━━━━━━━━━━━━ 14s 80ms/step - accuracy: 0.8906 - loss: 0.3554

390/573 ━━━━━━━━━━━━━━━━━━━━ 14s 80ms/step - accuracy: 0.8907 - loss: 0.3551

391/573 ━━━━━━━━━━━━━━━━━━━━ 14s 80ms/step - accuracy: 0.8906 - loss: 0.3552

392/573 ━━━━━━━━━━━━━━━━━━━━ 14s 80ms/step - accuracy: 0.8907 - loss: 0.3548

393/573 ━━━━━━━━━━━━━━━━━━━━ 14s 80ms/step - accuracy: 0.8906 - loss: 0.3546

394/573 ━━━━━━━━━━━━━━━━━━━━ 14s 80ms/step - accuracy: 0.8908 - loss: 0.3546

395/573 ━━━━━━━━━━━━━━━━━━━━ 14s 80ms/step - accuracy: 0.8907 - loss: 0.3548

396/573 ━━━━━━━━━━━━━━━━━━━━ 14s 80ms/step - accuracy: 0.8908 - loss: 0.3546

397/573 ━━━━━━━━━━━━━━━━━━━━ 14s 80ms/step - accuracy: 0.8908 - loss: 0.3545

398/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8909 - loss: 0.3542

399/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8910 - loss: 0.3536

400/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8908 - loss: 0.3542

401/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8907 - loss: 0.3541

402/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8907 - loss: 0.3544

403/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8905 - loss: 0.3552

404/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8905 - loss: 0.3560

405/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8905 - loss: 0.3563

406/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8902 - loss: 0.3575

407/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8900 - loss: 0.3578

408/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8900 - loss: 0.3578

409/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8899 - loss: 0.3590

410/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8900 - loss: 0.3590

411/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8898 - loss: 0.3594

412/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8899 - loss: 0.3594

413/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8900 - loss: 0.3588

414/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8901 - loss: 0.3591

415/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8902 - loss: 0.3598

416/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8902 - loss: 0.3596

417/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8903 - loss: 0.3592

418/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8902 - loss: 0.3596

419/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8904 - loss: 0.3589

420/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8904 - loss: 0.3589

421/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8902 - loss: 0.3592

422/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8902 - loss: 0.3596

423/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8902 - loss: 0.3597

424/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8902 - loss: 0.3599

425/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8904 - loss: 0.3594

426/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8905 - loss: 0.3590

427/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8904 - loss: 0.3597

428/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8903 - loss: 0.3599

429/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8906 - loss: 0.3592

430/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8904 - loss: 0.3603

431/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8904 - loss: 0.3600

432/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8905 - loss: 0.3596

433/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8904 - loss: 0.3597

434/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8905 - loss: 0.3593

435/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8906 - loss: 0.3593

436/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8903 - loss: 0.3599

437/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8903 - loss: 0.3596

438/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8903 - loss: 0.3594

439/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8902 - loss: 0.3596

440/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8899 - loss: 0.3602

441/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8898 - loss: 0.3607

442/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8898 - loss: 0.3604

443/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8899 - loss: 0.3603

444/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8898 - loss: 0.3606

445/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8897 - loss: 0.3612

446/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8898 - loss: 0.3607

447/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8896 - loss: 0.3620

448/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8894 - loss: 0.3626

449/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8893 - loss: 0.3628

450/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8893 - loss: 0.3632

451/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8895 - loss: 0.3628

452/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8892 - loss: 0.3639

453/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8893 - loss: 0.3633

454/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8894 - loss: 0.3631

455/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8894 - loss: 0.3634

456/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8892 - loss: 0.3646

457/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8893 - loss: 0.3645

458/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8891 - loss: 0.3649

459/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8893 - loss: 0.3644

460/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8895 - loss: 0.3641

461/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8894 - loss: 0.3641

462/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8894 - loss: 0.3638

463/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8895 - loss: 0.3633

464/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8894 - loss: 0.3648

465/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8894 - loss: 0.3646

466/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8895 - loss: 0.3641

467/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8895 - loss: 0.3644

468/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8895 - loss: 0.3641

469/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8894 - loss: 0.3648

470/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8895 - loss: 0.3647

471/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8894 - loss: 0.3646

472/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8894 - loss: 0.3645

473/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8895 - loss: 0.3643

474/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8895 - loss: 0.3640

475/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8897 - loss: 0.3635

476/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8898 - loss: 0.3630

477/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8896 - loss: 0.3634

478/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8895 - loss: 0.3634

479/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8895 - loss: 0.3637

480/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8894 - loss: 0.3646

481/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8895 - loss: 0.3643

482/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8896 - loss: 0.3641

483/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8895 - loss: 0.3646

484/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8896 - loss: 0.3643

485/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8897 - loss: 0.3639

486/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8897 - loss: 0.3641

487/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8897 - loss: 0.3640

488/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8897 - loss: 0.3641

489/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8896 - loss: 0.3648

490/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8896 - loss: 0.3646

491/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8897 - loss: 0.3643

492/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8895 - loss: 0.3646

493/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8896 - loss: 0.3643

494/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8895 - loss: 0.3644

495/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8894 - loss: 0.3645

496/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8893 - loss: 0.3648

497/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8891 - loss: 0.3650

498/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8893 - loss: 0.3646

499/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8894 - loss: 0.3642

500/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8894 - loss: 0.3642

501/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8893 - loss: 0.3642

502/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8894 - loss: 0.3640

503/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8893 - loss: 0.3643

504/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8895 - loss: 0.3637

505/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8893 - loss: 0.3641

506/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8894 - loss: 0.3641

507/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8893 - loss: 0.3643

508/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8893 - loss: 0.3645

509/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8894 - loss: 0.3643

510/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8895 - loss: 0.3640

511/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8895 - loss: 0.3638

512/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8896 - loss: 0.3640

513/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8897 - loss: 0.3636

514/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8897 - loss: 0.3637

515/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8898 - loss: 0.3635

516/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8898 - loss: 0.3636

517/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8899 - loss: 0.3637

518/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8900 - loss: 0.3632

519/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8900 - loss: 0.3632

520/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8901 - loss: 0.3627

521/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8902 - loss: 0.3629

522/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8902 - loss: 0.3632

523/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8903 - loss: 0.3630

524/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8902 - loss: 0.3636

525/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8902 - loss: 0.3635

526/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8903 - loss: 0.3631

527/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8905 - loss: 0.3627

528/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8905 - loss: 0.3624

529/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8906 - loss: 0.3623

530/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8904 - loss: 0.3627

531/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8904 - loss: 0.3627

532/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8906 - loss: 0.3623

533/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8906 - loss: 0.3619

534/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8906 - loss: 0.3620

535/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8908 - loss: 0.3614

536/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8908 - loss: 0.3610

537/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8908 - loss: 0.3609

538/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8908 - loss: 0.3612

539/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8907 - loss: 0.3619

540/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8907 - loss: 0.3616

541/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8906 - loss: 0.3622

542/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8906 - loss: 0.3622

543/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8906 - loss: 0.3619

544/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8906 - loss: 0.3619

545/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8907 - loss: 0.3616

546/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8908 - loss: 0.3612

547/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8907 - loss: 0.3613

548/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8907 - loss: 0.3615

549/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8909 - loss: 0.3609

550/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8907 - loss: 0.3616

551/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8907 - loss: 0.3614

552/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8907 - loss: 0.3615

553/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8909 - loss: 0.3612

554/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8908 - loss: 0.3616

555/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8909 - loss: 0.3613

556/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8909 - loss: 0.3612

557/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8909 - loss: 0.3614

558/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8909 - loss: 0.3614

559/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8905 - loss: 0.3620

560/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8906 - loss: 0.3617

561/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8905 - loss: 0.3621

562/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8906 - loss: 0.3617

563/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8906 - loss: 0.3616

564/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8906 - loss: 0.3615

565/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8905 - loss: 0.3619

566/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8904 - loss: 0.3623

567/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8904 - loss: 0.3623

568/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8906 - loss: 0.3618

569/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8906 - loss: 0.3615

570/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8905 - loss: 0.3623

571/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8904 - loss: 0.3626

572/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8904 - loss: 0.3625

573/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8903 - loss: 0.3629

573/573 ━━━━━━━━━━━━━━━━━━━━ 52s 91ms/step - accuracy: 0.8903 - loss: 0.3629 - val_accuracy: 0.9256 - val_loss: 0.2338

Epoch 3/20

  1/573 ━━━━━━━━━━━━━━━━━━━━ 1:07 119ms/step - accuracy: 0.9375 - loss: 0.1947

  2/573 ━━━━━━━━━━━━━━━━━━━━ 42s 75ms/step - accuracy: 0.9062 - loss: 0.3850

  3/573 ━━━━━━━━━━━━━━━━━━━━ 43s 76ms/step - accuracy: 0.9167 - loss: 0.3288

  4/573 ━━━━━━━━━━━━━━━━━━━━ 43s 76ms/step - accuracy: 0.9297 - loss: 0.2973

  5/573 ━━━━━━━━━━━━━━━━━━━━ 43s 76ms/step - accuracy: 0.9312 - loss: 0.2744

  6/573 ━━━━━━━━━━━━━━━━━━━━ 43s 76ms/step - accuracy: 0.9323 - loss: 0.2670

  7/573 ━━━━━━━━━━━━━━━━━━━━ 43s 77ms/step - accuracy: 0.9152 - loss: 0.3056

  8/573 ━━━━━━━━━━━━━━━━━━━━ 43s 77ms/step - accuracy: 0.8945 - loss: 0.3495

  9/573 ━━━━━━━━━━━━━━━━━━━━ 43s 77ms/step - accuracy: 0.8924 - loss: 0.3756

 10/573 ━━━━━━━━━━━━━━━━━━━━ 43s 77ms/step - accuracy: 0.8938 - loss: 0.3696

 11/573 ━━━━━━━━━━━━━━━━━━━━ 43s 77ms/step - accuracy: 0.8949 - loss: 0.3551

 12/573 ━━━━━━━━━━━━━━━━━━━━ 43s 77ms/step - accuracy: 0.8906 - loss: 0.3701

 13/573 ━━━━━━━━━━━━━━━━━━━━ 44s 80ms/step - accuracy: 0.8966 - loss: 0.3499

 14/573 ━━━━━━━━━━━━━━━━━━━━ 44s 80ms/step - accuracy: 0.9018 - loss: 0.3320

 15/573 ━━━━━━━━━━━━━━━━━━━━ 44s 80ms/step - accuracy: 0.8979 - loss: 0.3262

 16/573 ━━━━━━━━━━━━━━━━━━━━ 46s 83ms/step - accuracy: 0.9023 - loss: 0.3138

 17/573 ━━━━━━━━━━━━━━━━━━━━ 45s 83ms/step - accuracy: 0.9026 - loss: 0.3097

 18/573 ━━━━━━━━━━━━━━━━━━━━ 45s 82ms/step - accuracy: 0.9028 - loss: 0.3047

 19/573 ━━━━━━━━━━━━━━━━━━━━ 45s 82ms/step - accuracy: 0.9079 - loss: 0.2925

 20/573 ━━━━━━━━━━━━━━━━━━━━ 45s 82ms/step - accuracy: 0.9062 - loss: 0.2953

 21/573 ━━━━━━━━━━━━━━━━━━━━ 45s 82ms/step - accuracy: 0.9033 - loss: 0.2972

 22/573 ━━━━━━━━━━━━━━━━━━━━ 44s 82ms/step - accuracy: 0.9006 - loss: 0.2981

 23/573 ━━━━━━━━━━━━━━━━━━━━ 44s 82ms/step - accuracy: 0.8995 - loss: 0.3052

 24/573 ━━━━━━━━━━━━━━━━━━━━ 44s 81ms/step - accuracy: 0.8984 - loss: 0.3115

 25/573 ━━━━━━━━━━━━━━━━━━━━ 44s 81ms/step - accuracy: 0.8988 - loss: 0.3073

 26/573 ━━━━━━━━━━━━━━━━━━━━ 44s 81ms/step - accuracy: 0.8966 - loss: 0.3111

 27/573 ━━━━━━━━━━━━━━━━━━━━ 44s 81ms/step - accuracy: 0.8947 - loss: 0.3302

 28/573 ━━━━━━━━━━━━━━━━━━━━ 44s 81ms/step - accuracy: 0.8940 - loss: 0.3270

 29/573 ━━━━━━━━━━━━━━━━━━━━ 43s 81ms/step - accuracy: 0.8966 - loss: 0.3206

 30/573 ━━━━━━━━━━━━━━━━━━━━ 43s 81ms/step - accuracy: 0.8979 - loss: 0.3195

 31/573 ━━━━━━━━━━━━━━━━━━━━ 43s 81ms/step - accuracy: 0.8972 - loss: 0.3255

 32/573 ━━━━━━━━━━━━━━━━━━━━ 43s 81ms/step - accuracy: 0.8984 - loss: 0.3245

 33/573 ━━━━━━━━━━━━━━━━━━━━ 43s 81ms/step - accuracy: 0.8987 - loss: 0.3258

 34/573 ━━━━━━━━━━━━━━━━━━━━ 43s 80ms/step - accuracy: 0.8961 - loss: 0.3331

 35/573 ━━━━━━━━━━━━━━━━━━━━ 43s 80ms/step - accuracy: 0.8964 - loss: 0.3323

 36/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.8950 - loss: 0.3347

 37/573 ━━━━━━━━━━━━━━━━━━━━ 43s 81ms/step - accuracy: 0.8927 - loss: 0.3387

 38/573 ━━━━━━━━━━━━━━━━━━━━ 43s 81ms/step - accuracy: 0.8923 - loss: 0.3362

 39/573 ━━━━━━━━━━━━━━━━━━━━ 42s 81ms/step - accuracy: 0.8918 - loss: 0.3399

 40/573 ━━━━━━━━━━━━━━━━━━━━ 42s 81ms/step - accuracy: 0.8938 - loss: 0.3336

 41/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.8910 - loss: 0.3391

 42/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.8899 - loss: 0.3428

 43/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.8881 - loss: 0.3426

 44/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.8864 - loss: 0.3446

 45/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.8868 - loss: 0.3470

 46/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.8865 - loss: 0.3441

 47/573 ━━━━━━━━━━━━━━━━━━━━ 42s 80ms/step - accuracy: 0.8870 - loss: 0.3445

 48/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.8867 - loss: 0.3480

 49/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.8871 - loss: 0.3450

 50/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.8844 - loss: 0.3572

 51/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.8860 - loss: 0.3518

 52/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.8882 - loss: 0.3461

 53/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.8880 - loss: 0.3494

 54/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.8854 - loss: 0.3546

 55/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.8864 - loss: 0.3513

 56/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.8862 - loss: 0.3556

 57/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.8865 - loss: 0.3531

 58/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.8852 - loss: 0.3618

 59/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.8851 - loss: 0.3620

 60/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.8849 - loss: 0.3602

 61/573 ━━━━━━━━━━━━━━━━━━━━ 41s 80ms/step - accuracy: 0.8842 - loss: 0.3630

 62/573 ━━━━━━━━━━━━━━━━━━━━ 40s 80ms/step - accuracy: 0.8846 - loss: 0.3644

 63/573 ━━━━━━━━━━━━━━━━━━━━ 40s 80ms/step - accuracy: 0.8834 - loss: 0.3662

 64/573 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.8823 - loss: 0.3674

 65/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.8827 - loss: 0.3650

 66/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.8826 - loss: 0.3652

 67/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.8829 - loss: 0.3624

 68/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.8837 - loss: 0.3592

 69/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.8836 - loss: 0.3590

 70/573 ━━━━━━━━━━━━━━━━━━━━ 40s 80ms/step - accuracy: 0.8839 - loss: 0.3599

 71/573 ━━━━━━━━━━━━━━━━━━━━ 40s 80ms/step - accuracy: 0.8829 - loss: 0.3639

 72/573 ━━━━━━━━━━━━━━━━━━━━ 40s 80ms/step - accuracy: 0.8824 - loss: 0.3669

 73/573 ━━━━━━━━━━━━━━━━━━━━ 40s 80ms/step - accuracy: 0.8823 - loss: 0.3661

 74/573 ━━━━━━━━━━━━━━━━━━━━ 40s 80ms/step - accuracy: 0.8830 - loss: 0.3648

 75/573 ━━━━━━━━━━━━━━━━━━━━ 39s 80ms/step - accuracy: 0.8833 - loss: 0.3647

 76/573 ━━━━━━━━━━━━━━━━━━━━ 39s 80ms/step - accuracy: 0.8845 - loss: 0.3623

 77/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.8847 - loss: 0.3611

 78/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.8854 - loss: 0.3588

 79/573 ━━━━━━━━━━━━━━━━━━━━ 39s 81ms/step - accuracy: 0.8853 - loss: 0.3587

 80/573 ━━━━━━━━━━━━━━━━━━━━ 39s 81ms/step - accuracy: 0.8855 - loss: 0.3580

 81/573 ━━━━━━━━━━━━━━━━━━━━ 39s 81ms/step - accuracy: 0.8866 - loss: 0.3552

 82/573 ━━━━━━━━━━━━━━━━━━━━ 39s 81ms/step - accuracy: 0.8868 - loss: 0.3551

 83/573 ━━━━━━━━━━━━━━━━━━━━ 39s 81ms/step - accuracy: 0.8878 - loss: 0.3524

 84/573 ━━━━━━━━━━━━━━━━━━━━ 39s 81ms/step - accuracy: 0.8880 - loss: 0.3503

 85/573 ━━━━━━━━━━━━━━━━━━━━ 39s 81ms/step - accuracy: 0.8886 - loss: 0.3479

 86/573 ━━━━━━━━━━━━━━━━━━━━ 39s 81ms/step - accuracy: 0.8892 - loss: 0.3455

 87/573 ━━━━━━━━━━━━━━━━━━━━ 39s 80ms/step - accuracy: 0.8897 - loss: 0.3452

 88/573 ━━━━━━━━━━━━━━━━━━━━ 39s 80ms/step - accuracy: 0.8892 - loss: 0.3450

 89/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.8894 - loss: 0.3449

 90/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.8906 - loss: 0.3416

 91/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.8915 - loss: 0.3390

 92/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.8923 - loss: 0.3364

 93/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.8925 - loss: 0.3359

 94/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.8930 - loss: 0.3345

 95/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.8931 - loss: 0.3349

 96/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.8919 - loss: 0.3362

 97/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.8905 - loss: 0.3427

 98/573 ━━━━━━━━━━━━━━━━━━━━ 38s 80ms/step - accuracy: 0.8916 - loss: 0.3396

 99/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.8920 - loss: 0.3381

100/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.8925 - loss: 0.3364

101/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.8926 - loss: 0.3362

102/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.8922 - loss: 0.3400

103/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.8920 - loss: 0.3420

104/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.8918 - loss: 0.3431

105/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.8917 - loss: 0.3433

106/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.8915 - loss: 0.3446

107/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.8925 - loss: 0.3420

108/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.8929 - loss: 0.3410

109/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.8933 - loss: 0.3394

110/573 ━━━━━━━━━━━━━━━━━━━━ 37s 80ms/step - accuracy: 0.8938 - loss: 0.3386

111/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8933 - loss: 0.3385

112/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8931 - loss: 0.3388

113/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8930 - loss: 0.3389

114/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8931 - loss: 0.3395

115/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8938 - loss: 0.3377

116/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8941 - loss: 0.3374

117/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8942 - loss: 0.3382

118/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8941 - loss: 0.3392

119/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8934 - loss: 0.3393

120/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8935 - loss: 0.3392

121/573 ━━━━━━━━━━━━━━━━━━━━ 36s 80ms/step - accuracy: 0.8939 - loss: 0.3385

122/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8937 - loss: 0.3404

123/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8933 - loss: 0.3416

124/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8926 - loss: 0.3436

125/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8925 - loss: 0.3433

126/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8924 - loss: 0.3449

127/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8922 - loss: 0.3459

128/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8926 - loss: 0.3448

129/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8922 - loss: 0.3453

130/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8913 - loss: 0.3494

131/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8917 - loss: 0.3478

132/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8918 - loss: 0.3471

133/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8924 - loss: 0.3454

134/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8920 - loss: 0.3463

135/573 ━━━━━━━━━━━━━━━━━━━━ 35s 80ms/step - accuracy: 0.8924 - loss: 0.3451

136/573 ━━━━━━━━━━━━━━━━━━━━ 34s 80ms/step - accuracy: 0.8925 - loss: 0.3445

137/573 ━━━━━━━━━━━━━━━━━━━━ 34s 80ms/step - accuracy: 0.8926 - loss: 0.3447

138/573 ━━━━━━━━━━━━━━━━━━━━ 34s 80ms/step - accuracy: 0.8924 - loss: 0.3454

139/573 ━━━━━━━━━━━━━━━━━━━━ 34s 80ms/step - accuracy: 0.8930 - loss: 0.3437

140/573 ━━━━━━━━━━━━━━━━━━━━ 34s 80ms/step - accuracy: 0.8931 - loss: 0.3437

141/573 ━━━━━━━━━━━━━━━━━━━━ 34s 80ms/step - accuracy: 0.8934 - loss: 0.3435

142/573 ━━━━━━━━━━━━━━━━━━━━ 34s 80ms/step - accuracy: 0.8926 - loss: 0.3474

143/573 ━━━━━━━━━━━━━━━━━━━━ 34s 80ms/step - accuracy: 0.8931 - loss: 0.3455

144/573 ━━━━━━━━━━━━━━━━━━━━ 34s 80ms/step - accuracy: 0.8934 - loss: 0.3445

145/573 ━━━━━━━━━━━━━━━━━━━━ 34s 80ms/step - accuracy: 0.8935 - loss: 0.3443

146/573 ━━━━━━━━━━━━━━━━━━━━ 34s 80ms/step - accuracy: 0.8940 - loss: 0.3424

147/573 ━━━━━━━━━━━━━━━━━━━━ 34s 80ms/step - accuracy: 0.8939 - loss: 0.3437

148/573 ━━━━━━━━━━━━━━━━━━━━ 33s 80ms/step - accuracy: 0.8940 - loss: 0.3435

149/573 ━━━━━━━━━━━━━━━━━━━━ 33s 80ms/step - accuracy: 0.8945 - loss: 0.3424

150/573 ━━━━━━━━━━━━━━━━━━━━ 33s 80ms/step - accuracy: 0.8948 - loss: 0.3412

151/573 ━━━━━━━━━━━━━━━━━━━━ 33s 80ms/step - accuracy: 0.8945 - loss: 0.3412

152/573 ━━━━━━━━━━━━━━━━━━━━ 33s 80ms/step - accuracy: 0.8939 - loss: 0.3411

153/573 ━━━━━━━━━━━━━━━━━━━━ 33s 80ms/step - accuracy: 0.8942 - loss: 0.3403

154/573 ━━━━━━━━━━━━━━━━━━━━ 33s 80ms/step - accuracy: 0.8943 - loss: 0.3398

155/573 ━━━━━━━━━━━━━━━━━━━━ 33s 80ms/step - accuracy: 0.8935 - loss: 0.3416

156/573 ━━━━━━━━━━━━━━━━━━━━ 33s 80ms/step - accuracy: 0.8934 - loss: 0.3420

157/573 ━━━━━━━━━━━━━━━━━━━━ 33s 80ms/step - accuracy: 0.8929 - loss: 0.3428

158/573 ━━━━━━━━━━━━━━━━━━━━ 33s 80ms/step - accuracy: 0.8930 - loss: 0.3422

159/573 ━━━━━━━━━━━━━━━━━━━━ 33s 80ms/step - accuracy: 0.8929 - loss: 0.3442

160/573 ━━━━━━━━━━━━━━━━━━━━ 32s 80ms/step - accuracy: 0.8932 - loss: 0.3434

161/573 ━━━━━━━━━━━━━━━━━━━━ 32s 80ms/step - accuracy: 0.8934 - loss: 0.3422

162/573 ━━━━━━━━━━━━━━━━━━━━ 32s 80ms/step - accuracy: 0.8935 - loss: 0.3417

163/573 ━━━━━━━━━━━━━━━━━━━━ 32s 80ms/step - accuracy: 0.8940 - loss: 0.3401

164/573 ━━━━━━━━━━━━━━━━━━━━ 32s 80ms/step - accuracy: 0.8935 - loss: 0.3413

165/573 ━━━━━━━━━━━━━━━━━━━━ 32s 80ms/step - accuracy: 0.8939 - loss: 0.3401

166/573 ━━━━━━━━━━━━━━━━━━━━ 32s 80ms/step - accuracy: 0.8940 - loss: 0.3393

167/573 ━━━━━━━━━━━━━━━━━━━━ 32s 80ms/step - accuracy: 0.8941 - loss: 0.3387

168/573 ━━━━━━━━━━━━━━━━━━━━ 32s 80ms/step - accuracy: 0.8938 - loss: 0.3391

169/573 ━━━━━━━━━━━━━━━━━━━━ 32s 80ms/step - accuracy: 0.8937 - loss: 0.3383

170/573 ━━━━━━━━━━━━━━━━━━━━ 32s 80ms/step - accuracy: 0.8938 - loss: 0.3402

171/573 ━━━━━━━━━━━━━━━━━━━━ 32s 80ms/step - accuracy: 0.8938 - loss: 0.3391

172/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8937 - loss: 0.3390

173/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8938 - loss: 0.3382

174/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8940 - loss: 0.3390

175/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8941 - loss: 0.3384

176/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8935 - loss: 0.3392

177/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8941 - loss: 0.3377

178/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8945 - loss: 0.3363

179/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8940 - loss: 0.3386

180/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8936 - loss: 0.3392

181/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8935 - loss: 0.3394

182/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8934 - loss: 0.3398

183/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8934 - loss: 0.3411

184/573 ━━━━━━━━━━━━━━━━━━━━ 31s 80ms/step - accuracy: 0.8940 - loss: 0.3396

185/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8941 - loss: 0.3392

186/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8938 - loss: 0.3393

187/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8939 - loss: 0.3390

188/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8938 - loss: 0.3387

189/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8935 - loss: 0.3394

190/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8933 - loss: 0.3403

191/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8935 - loss: 0.3397

192/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8936 - loss: 0.3391

193/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8936 - loss: 0.3382

194/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8934 - loss: 0.3402

195/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8936 - loss: 0.3393

196/573 ━━━━━━━━━━━━━━━━━━━━ 30s 80ms/step - accuracy: 0.8933 - loss: 0.3395

197/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8937 - loss: 0.3381

198/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8936 - loss: 0.3401

199/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8938 - loss: 0.3397

200/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8942 - loss: 0.3388

201/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8935 - loss: 0.3410

202/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8937 - loss: 0.3406

203/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8938 - loss: 0.3406

204/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8940 - loss: 0.3397

205/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8938 - loss: 0.3399

206/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8940 - loss: 0.3398

207/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8937 - loss: 0.3413

208/573 ━━━━━━━━━━━━━━━━━━━━ 29s 80ms/step - accuracy: 0.8938 - loss: 0.3408

209/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8941 - loss: 0.3396

210/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8940 - loss: 0.3394

211/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8938 - loss: 0.3407

212/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8937 - loss: 0.3414

213/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8936 - loss: 0.3414

214/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8938 - loss: 0.3404

215/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8936 - loss: 0.3401

216/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8935 - loss: 0.3402

217/573 ━━━━━━━━━━━━━━━━━━━━ 28s 80ms/step - accuracy: 0.8934 - loss: 0.3408

218/573 ━━━━━━━━━━━━━━━━━━━━ 28s 79ms/step - accuracy: 0.8938 - loss: 0.3397

219/573 ━━━━━━━━━━━━━━━━━━━━ 28s 79ms/step - accuracy: 0.8941 - loss: 0.3391

220/573 ━━━━━━━━━━━━━━━━━━━━ 28s 79ms/step - accuracy: 0.8940 - loss: 0.3391

221/573 ━━━━━━━━━━━━━━━━━━━━ 27s 80ms/step - accuracy: 0.8942 - loss: 0.3385

222/573 ━━━━━━━━━━━━━━━━━━━━ 27s 79ms/step - accuracy: 0.8947 - loss: 0.3374

223/573 ━━━━━━━━━━━━━━━━━━━━ 27s 80ms/step - accuracy: 0.8946 - loss: 0.3369

224/573 ━━━━━━━━━━━━━━━━━━━━ 27s 79ms/step - accuracy: 0.8944 - loss: 0.3369

225/573 ━━━━━━━━━━━━━━━━━━━━ 27s 79ms/step - accuracy: 0.8947 - loss: 0.3361

226/573 ━━━━━━━━━━━━━━━━━━━━ 27s 79ms/step - accuracy: 0.8946 - loss: 0.3356

227/573 ━━━━━━━━━━━━━━━━━━━━ 27s 79ms/step - accuracy: 0.8947 - loss: 0.3349

228/573 ━━━━━━━━━━━━━━━━━━━━ 27s 79ms/step - accuracy: 0.8945 - loss: 0.3356

229/573 ━━━━━━━━━━━━━━━━━━━━ 27s 79ms/step - accuracy: 0.8941 - loss: 0.3357

230/573 ━━━━━━━━━━━━━━━━━━━━ 27s 79ms/step - accuracy: 0.8939 - loss: 0.3360

231/573 ━━━━━━━━━━━━━━━━━━━━ 27s 79ms/step - accuracy: 0.8938 - loss: 0.3358

232/573 ━━━━━━━━━━━━━━━━━━━━ 27s 79ms/step - accuracy: 0.8941 - loss: 0.3348

233/573 ━━━━━━━━━━━━━━━━━━━━ 27s 79ms/step - accuracy: 0.8942 - loss: 0.3355

234/573 ━━━━━━━━━━━━━━━━━━━━ 26s 79ms/step - accuracy: 0.8940 - loss: 0.3361

235/573 ━━━━━━━━━━━━━━━━━━━━ 26s 79ms/step - accuracy: 0.8938 - loss: 0.3362

236/573 ━━━━━━━━━━━━━━━━━━━━ 26s 79ms/step - accuracy: 0.8938 - loss: 0.3358

237/573 ━━━━━━━━━━━━━━━━━━━━ 26s 79ms/step - accuracy: 0.8937 - loss: 0.3361

238/573 ━━━━━━━━━━━━━━━━━━━━ 26s 79ms/step - accuracy: 0.8940 - loss: 0.3353

239/573 ━━━━━━━━━━━━━━━━━━━━ 26s 79ms/step - accuracy: 0.8944 - loss: 0.3344

240/573 ━━━━━━━━━━━━━━━━━━━━ 26s 79ms/step - accuracy: 0.8939 - loss: 0.3360

241/573 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - accuracy: 0.8941 - loss: 0.3355

242/573 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - accuracy: 0.8937 - loss: 0.3368

243/573 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - accuracy: 0.8936 - loss: 0.3380

244/573 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - accuracy: 0.8937 - loss: 0.3382

245/573 ━━━━━━━━━━━━━━━━━━━━ 26s 80ms/step - accuracy: 0.8939 - loss: 0.3382

246/573 ━━━━━━━━━━━━━━━━━━━━ 25s 80ms/step - accuracy: 0.8941 - loss: 0.3374

247/573 ━━━━━━━━━━━━━━━━━━━━ 25s 80ms/step - accuracy: 0.8939 - loss: 0.3380

248/573 ━━━━━━━━━━━━━━━━━━━━ 25s 80ms/step - accuracy: 0.8935 - loss: 0.3379

249/573 ━━━━━━━━━━━━━━━━━━━━ 25s 79ms/step - accuracy: 0.8937 - loss: 0.3375

250/573 ━━━━━━━━━━━━━━━━━━━━ 25s 79ms/step - accuracy: 0.8936 - loss: 0.3380

251/573 ━━━━━━━━━━━━━━━━━━━━ 25s 79ms/step - accuracy: 0.8936 - loss: 0.3379

252/573 ━━━━━━━━━━━━━━━━━━━━ 25s 79ms/step - accuracy: 0.8936 - loss: 0.3375

253/573 ━━━━━━━━━━━━━━━━━━━━ 25s 79ms/step - accuracy: 0.8939 - loss: 0.3371

254/573 ━━━━━━━━━━━━━━━━━━━━ 25s 79ms/step - accuracy: 0.8938 - loss: 0.3368

255/573 ━━━━━━━━━━━━━━━━━━━━ 25s 79ms/step - accuracy: 0.8935 - loss: 0.3373

256/573 ━━━━━━━━━━━━━━━━━━━━ 25s 79ms/step - accuracy: 0.8939 - loss: 0.3361

257/573 ━━━━━━━━━━━━━━━━━━━━ 25s 79ms/step - accuracy: 0.8935 - loss: 0.3373

258/573 ━━━━━━━━━━━━━━━━━━━━ 25s 79ms/step - accuracy: 0.8934 - loss: 0.3380

259/573 ━━━━━━━━━━━━━━━━━━━━ 24s 79ms/step - accuracy: 0.8936 - loss: 0.3376

260/573 ━━━━━━━━━━━━━━━━━━━━ 24s 79ms/step - accuracy: 0.8934 - loss: 0.3383

261/573 ━━━━━━━━━━━━━━━━━━━━ 24s 79ms/step - accuracy: 0.8934 - loss: 0.3385

262/573 ━━━━━━━━━━━━━━━━━━━━ 24s 79ms/step - accuracy: 0.8934 - loss: 0.3392

263/573 ━━━━━━━━━━━━━━━━━━━━ 24s 79ms/step - accuracy: 0.8935 - loss: 0.3386

264/573 ━━━━━━━━━━━━━━━━━━━━ 24s 79ms/step - accuracy: 0.8936 - loss: 0.3391

265/573 ━━━━━━━━━━━━━━━━━━━━ 24s 79ms/step - accuracy: 0.8935 - loss: 0.3389

266/573 ━━━━━━━━━━━━━━━━━━━━ 24s 79ms/step - accuracy: 0.8937 - loss: 0.3391

267/573 ━━━━━━━━━━━━━━━━━━━━ 24s 79ms/step - accuracy: 0.8941 - loss: 0.3380

268/573 ━━━━━━━━━━━━━━━━━━━━ 24s 79ms/step - accuracy: 0.8944 - loss: 0.3373

269/573 ━━━━━━━━━━━━━━━━━━━━ 24s 79ms/step - accuracy: 0.8943 - loss: 0.3380

270/573 ━━━━━━━━━━━━━━━━━━━━ 24s 79ms/step - accuracy: 0.8941 - loss: 0.3380

271/573 ━━━━━━━━━━━━━━━━━━━━ 23s 79ms/step - accuracy: 0.8940 - loss: 0.3376

272/573 ━━━━━━━━━━━━━━━━━━━━ 23s 79ms/step - accuracy: 0.8940 - loss: 0.3376

273/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8940 - loss: 0.3372

274/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8942 - loss: 0.3364

275/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8941 - loss: 0.3362

276/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8939 - loss: 0.3363

277/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8938 - loss: 0.3369

278/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8940 - loss: 0.3362

279/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8938 - loss: 0.3367

280/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8936 - loss: 0.3370

281/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8937 - loss: 0.3375

282/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8934 - loss: 0.3376

283/573 ━━━━━━━━━━━━━━━━━━━━ 23s 80ms/step - accuracy: 0.8936 - loss: 0.3368

284/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8935 - loss: 0.3372

285/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8936 - loss: 0.3365

286/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8934 - loss: 0.3364

287/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8934 - loss: 0.3360

288/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8930 - loss: 0.3376

289/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8927 - loss: 0.3382

290/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8927 - loss: 0.3394

291/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8927 - loss: 0.3395

292/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8924 - loss: 0.3401

293/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8925 - loss: 0.3394

294/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8924 - loss: 0.3398

295/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8927 - loss: 0.3392

296/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8926 - loss: 0.3399

297/573 ━━━━━━━━━━━━━━━━━━━━ 22s 80ms/step - accuracy: 0.8923 - loss: 0.3402

298/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8920 - loss: 0.3414

299/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8919 - loss: 0.3416

300/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8920 - loss: 0.3412

301/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8918 - loss: 0.3414

302/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8920 - loss: 0.3407

303/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8919 - loss: 0.3412

304/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8919 - loss: 0.3417

305/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8918 - loss: 0.3422

306/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8920 - loss: 0.3414

307/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8918 - loss: 0.3418

308/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8919 - loss: 0.3411

309/573 ━━━━━━━━━━━━━━━━━━━━ 21s 80ms/step - accuracy: 0.8919 - loss: 0.3412

310/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8919 - loss: 0.3413

311/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8919 - loss: 0.3429

312/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8922 - loss: 0.3420

313/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8921 - loss: 0.3421

314/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8923 - loss: 0.3414

315/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8921 - loss: 0.3421

316/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8923 - loss: 0.3415

317/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8924 - loss: 0.3412

318/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8923 - loss: 0.3411

319/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8926 - loss: 0.3402

320/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8927 - loss: 0.3398

321/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8927 - loss: 0.3395

322/573 ━━━━━━━━━━━━━━━━━━━━ 20s 80ms/step - accuracy: 0.8926 - loss: 0.3398

323/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8927 - loss: 0.3393

324/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8926 - loss: 0.3397

325/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8926 - loss: 0.3400

326/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8924 - loss: 0.3405

327/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8927 - loss: 0.3397

328/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8925 - loss: 0.3395

329/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8925 - loss: 0.3391

330/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8925 - loss: 0.3389

331/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8925 - loss: 0.3394

332/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8924 - loss: 0.3395

333/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8924 - loss: 0.3391

334/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8923 - loss: 0.3403

335/573 ━━━━━━━━━━━━━━━━━━━━ 19s 80ms/step - accuracy: 0.8921 - loss: 0.3423

336/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8922 - loss: 0.3417

337/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8922 - loss: 0.3415

338/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8920 - loss: 0.3420

339/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8920 - loss: 0.3422

340/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8921 - loss: 0.3422

341/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8921 - loss: 0.3421

342/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8923 - loss: 0.3418

343/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8920 - loss: 0.3422

344/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8920 - loss: 0.3421

345/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8920 - loss: 0.3430

346/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8920 - loss: 0.3430

347/573 ━━━━━━━━━━━━━━━━━━━━ 18s 80ms/step - accuracy: 0.8919 - loss: 0.3435

348/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8921 - loss: 0.3433

349/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8920 - loss: 0.3432

350/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8921 - loss: 0.3428

351/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8924 - loss: 0.3420

352/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8923 - loss: 0.3425

353/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8922 - loss: 0.3426

354/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8921 - loss: 0.3432

355/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8922 - loss: 0.3432

356/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8923 - loss: 0.3431

357/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8919 - loss: 0.3447

358/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8920 - loss: 0.3442

359/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8918 - loss: 0.3451

360/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8918 - loss: 0.3450

361/573 ━━━━━━━━━━━━━━━━━━━━ 17s 80ms/step - accuracy: 0.8918 - loss: 0.3454

362/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8917 - loss: 0.3457

363/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8919 - loss: 0.3458

364/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8919 - loss: 0.3455

365/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8921 - loss: 0.3448

366/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8921 - loss: 0.3447

367/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8922 - loss: 0.3445

368/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8922 - loss: 0.3439

369/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8923 - loss: 0.3439

370/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8923 - loss: 0.3439

371/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8924 - loss: 0.3435

372/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8921 - loss: 0.3438

373/573 ━━━━━━━━━━━━━━━━━━━━ 16s 80ms/step - accuracy: 0.8923 - loss: 0.3433

374/573 ━━━━━━━━━━━━━━━━━━━━ 15s 80ms/step - accuracy: 0.8924 - loss: 0.3434

375/573 ━━━━━━━━━━━━━━━━━━━━ 15s 80ms/step - accuracy: 0.8923 - loss: 0.3436

376/573 ━━━━━━━━━━━━━━━━━━━━ 15s 80ms/step - accuracy: 0.8925 - loss: 0.3431

377/573 ━━━━━━━━━━━━━━━━━━━━ 15s 81ms/step - accuracy: 0.8923 - loss: 0.3440

378/573 ━━━━━━━━━━━━━━━━━━━━ 15s 81ms/step - accuracy: 0.8923 - loss: 0.3438

379/573 ━━━━━━━━━━━━━━━━━━━━ 15s 81ms/step - accuracy: 0.8924 - loss: 0.3437

380/573 ━━━━━━━━━━━━━━━━━━━━ 15s 81ms/step - accuracy: 0.8923 - loss: 0.3441

381/573 ━━━━━━━━━━━━━━━━━━━━ 15s 81ms/step - accuracy: 0.8924 - loss: 0.3435

382/573 ━━━━━━━━━━━━━━━━━━━━ 15s 81ms/step - accuracy: 0.8924 - loss: 0.3434

383/573 ━━━━━━━━━━━━━━━━━━━━ 15s 81ms/step - accuracy: 0.8925 - loss: 0.3430

384/573 ━━━━━━━━━━━━━━━━━━━━ 15s 81ms/step - accuracy: 0.8927 - loss: 0.3429

385/573 ━━━━━━━━━━━━━━━━━━━━ 15s 81ms/step - accuracy: 0.8924 - loss: 0.3432

386/573 ━━━━━━━━━━━━━━━━━━━━ 15s 81ms/step - accuracy: 0.8923 - loss: 0.3435

387/573 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - accuracy: 0.8924 - loss: 0.3431

388/573 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - accuracy: 0.8926 - loss: 0.3425

389/573 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - accuracy: 0.8927 - loss: 0.3420

390/573 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - accuracy: 0.8925 - loss: 0.3420

391/573 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - accuracy: 0.8925 - loss: 0.3420

392/573 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - accuracy: 0.8927 - loss: 0.3418

393/573 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - accuracy: 0.8927 - loss: 0.3417

394/573 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - accuracy: 0.8926 - loss: 0.3414

395/573 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - accuracy: 0.8926 - loss: 0.3409

396/573 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - accuracy: 0.8926 - loss: 0.3410

397/573 ━━━━━━━━━━━━━━━━━━━━ 14s 81ms/step - accuracy: 0.8925 - loss: 0.3415

398/573 ━━━━━━━━━━━━━━━━━━━━ 14s 80ms/step - accuracy: 0.8927 - loss: 0.3410

399/573 ━━━━━━━━━━━━━━━━━━━━ 14s 80ms/step - accuracy: 0.8926 - loss: 0.3411

400/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8926 - loss: 0.3414

401/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8926 - loss: 0.3417

402/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8927 - loss: 0.3416

403/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8924 - loss: 0.3430

404/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8926 - loss: 0.3424

405/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8927 - loss: 0.3421

406/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8926 - loss: 0.3424

407/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8926 - loss: 0.3428

408/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8926 - loss: 0.3429

409/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8924 - loss: 0.3434

410/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8925 - loss: 0.3430

411/573 ━━━━━━━━━━━━━━━━━━━━ 13s 80ms/step - accuracy: 0.8926 - loss: 0.3427

412/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8925 - loss: 0.3429

413/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8926 - loss: 0.3425

414/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8926 - loss: 0.3423

415/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8926 - loss: 0.3421

416/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8923 - loss: 0.3428

417/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8922 - loss: 0.3433

418/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8922 - loss: 0.3434

419/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8920 - loss: 0.3439

420/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8922 - loss: 0.3434

421/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8922 - loss: 0.3431

422/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8923 - loss: 0.3432

423/573 ━━━━━━━━━━━━━━━━━━━━ 12s 80ms/step - accuracy: 0.8922 - loss: 0.3439

424/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8923 - loss: 0.3437

425/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8924 - loss: 0.3435

426/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8925 - loss: 0.3436

427/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8923 - loss: 0.3437

428/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8924 - loss: 0.3438

429/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8926 - loss: 0.3431

430/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8926 - loss: 0.3432

431/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8927 - loss: 0.3429

432/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8927 - loss: 0.3434

433/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8928 - loss: 0.3429

434/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8928 - loss: 0.3432

435/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8928 - loss: 0.3429

436/573 ━━━━━━━━━━━━━━━━━━━━ 11s 80ms/step - accuracy: 0.8931 - loss: 0.3422

437/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8932 - loss: 0.3421

438/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8931 - loss: 0.3425

439/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8931 - loss: 0.3422

440/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8932 - loss: 0.3420

441/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8933 - loss: 0.3417

442/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8934 - loss: 0.3419

443/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8935 - loss: 0.3416

444/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8936 - loss: 0.3415

445/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8937 - loss: 0.3411

446/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8937 - loss: 0.3408

447/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8939 - loss: 0.3406

448/573 ━━━━━━━━━━━━━━━━━━━━ 10s 80ms/step - accuracy: 0.8938 - loss: 0.3412

449/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8937 - loss: 0.3412

450/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8937 - loss: 0.3413

451/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8938 - loss: 0.3410

452/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8935 - loss: 0.3410

453/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8937 - loss: 0.3408

454/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8937 - loss: 0.3405

455/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8938 - loss: 0.3403

456/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8937 - loss: 0.3413

457/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8937 - loss: 0.3411

458/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8937 - loss: 0.3411

459/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8937 - loss: 0.3412

460/573 ━━━━━━━━━━━━━━━━━━━━ 9s 80ms/step - accuracy: 0.8938 - loss: 0.3409

461/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8936 - loss: 0.3412

462/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8937 - loss: 0.3410

463/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8938 - loss: 0.3405

464/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8937 - loss: 0.3411

465/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8937 - loss: 0.3410

466/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8937 - loss: 0.3409

467/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8937 - loss: 0.3411

468/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8938 - loss: 0.3407

469/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8939 - loss: 0.3406

470/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8941 - loss: 0.3404

471/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8939 - loss: 0.3414

472/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8940 - loss: 0.3414

473/573 ━━━━━━━━━━━━━━━━━━━━ 8s 80ms/step - accuracy: 0.8940 - loss: 0.3417

474/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8940 - loss: 0.3416

475/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8941 - loss: 0.3411

476/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8938 - loss: 0.3416

477/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8939 - loss: 0.3416

478/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8939 - loss: 0.3414

479/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8940 - loss: 0.3414

480/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8941 - loss: 0.3414

481/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8941 - loss: 0.3412

482/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8940 - loss: 0.3416

483/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8940 - loss: 0.3419

484/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8939 - loss: 0.3425

485/573 ━━━━━━━━━━━━━━━━━━━━ 7s 80ms/step - accuracy: 0.8938 - loss: 0.3429

486/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8938 - loss: 0.3429

487/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8939 - loss: 0.3425

488/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8940 - loss: 0.3423

489/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8941 - loss: 0.3420

490/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8939 - loss: 0.3422

491/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8938 - loss: 0.3425

492/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8938 - loss: 0.3422

493/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8939 - loss: 0.3419

494/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8939 - loss: 0.3421

495/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8937 - loss: 0.3424

496/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8936 - loss: 0.3426

497/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8935 - loss: 0.3429

498/573 ━━━━━━━━━━━━━━━━━━━━ 6s 80ms/step - accuracy: 0.8936 - loss: 0.3426

499/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8936 - loss: 0.3424

500/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8936 - loss: 0.3424

501/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8937 - loss: 0.3421

502/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8937 - loss: 0.3421

503/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8937 - loss: 0.3419

504/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8936 - loss: 0.3423

505/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8938 - loss: 0.3417

506/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8938 - loss: 0.3416

507/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8939 - loss: 0.3412

508/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8941 - loss: 0.3413

509/573 ━━━━━━━━━━━━━━━━━━━━ 5s 80ms/step - accuracy: 0.8942 - loss: 0.3416

511/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8941 - loss: 0.3416

512/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8942 - loss: 0.3414

513/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8942 - loss: 0.3414

514/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8941 - loss: 0.3413

515/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8939 - loss: 0.3414

516/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8938 - loss: 0.3417

517/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8938 - loss: 0.3414

518/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8938 - loss: 0.3425

519/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8937 - loss: 0.3430

520/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8937 - loss: 0.3430

521/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8938 - loss: 0.3429

522/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8938 - loss: 0.3428

523/573 ━━━━━━━━━━━━━━━━━━━━ 4s 80ms/step - accuracy: 0.8938 - loss: 0.3429

524/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8936 - loss: 0.3432

525/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8937 - loss: 0.3431

526/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8938 - loss: 0.3433

527/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8938 - loss: 0.3432

528/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8939 - loss: 0.3430

529/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8938 - loss: 0.3436

530/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8937 - loss: 0.3441

531/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8935 - loss: 0.3445

532/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8935 - loss: 0.3446

533/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8936 - loss: 0.3443

534/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8935 - loss: 0.3442

535/573 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - accuracy: 0.8936 - loss: 0.3439

536/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8936 - loss: 0.3441

537/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8935 - loss: 0.3440

538/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8935 - loss: 0.3440

539/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8935 - loss: 0.3438

540/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8933 - loss: 0.3442

541/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8932 - loss: 0.3446

542/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8931 - loss: 0.3447

543/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8931 - loss: 0.3445

544/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8933 - loss: 0.3445

545/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8933 - loss: 0.3441

546/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8934 - loss: 0.3439

547/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8934 - loss: 0.3442

548/573 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.8935 - loss: 0.3439

549/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8934 - loss: 0.3441

550/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8936 - loss: 0.3437

551/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8935 - loss: 0.3438

552/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8936 - loss: 0.3435

553/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8935 - loss: 0.3436

554/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8934 - loss: 0.3441

555/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8933 - loss: 0.3440

556/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8933 - loss: 0.3439

557/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8933 - loss: 0.3440

558/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8933 - loss: 0.3440

559/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8934 - loss: 0.3438

560/573 ━━━━━━━━━━━━━━━━━━━━ 1s 80ms/step - accuracy: 0.8934 - loss: 0.3435

561/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8931 - loss: 0.3445

562/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8931 - loss: 0.3445

563/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8930 - loss: 0.3449

564/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8929 - loss: 0.3449

565/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8930 - loss: 0.3451

566/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8929 - loss: 0.3454

567/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8930 - loss: 0.3454

568/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8930 - loss: 0.3454

569/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8929 - loss: 0.3456

570/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8930 - loss: 0.3457

571/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8930 - loss: 0.3462

572/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8931 - loss: 0.3458

573/573 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.8930 - loss: 0.3466

573/573 ━━━━━━━━━━━━━━━━━━━━ 52s 91ms/step - accuracy: 0.8930 - loss: 0.3466 - val_accuracy: 0.9287 - val_loss: 0.2390

Epoch 4/20

  1/573 ━━━━━━━━━━━━━━━━━━━━ 1:10 123ms/step - accuracy: 0.8750 - loss: 0.4555

  2/573 ━━━━━━━━━━━━━━━━━━━━ 46s 82ms/step - accuracy: 0.8906 - loss: 0.4110

  3/573 ━━━━━━━━━━━━━━━━━━━━ 44s 78ms/step - accuracy: 0.9167 - loss: 0.3024

  4/573 ━━━━━━━━━━━━━━━━━━━━ 45s 81ms/step - accuracy: 0.9219 - loss: 0.3185

  5/573 ━━━━━━━━━━━━━━━━━━━━ 45s 80ms/step - accuracy: 0.9187 - loss: 0.3141

  6/573 ━━━━━━━━━━━━━━━━━━━━ 44s 79ms/step - accuracy: 0.9219 - loss: 0.3043

  7/573 ━━━━━━━━━━━━━━━━━━━━ 45s 80ms/step - accuracy: 0.9286 - loss: 0.2770

  8/573 ━━━━━━━━━━━━━━━━━━━━ 44s 80ms/step - accuracy: 0.9219 - loss: 0.3266

  9/573 ━━━━━━━━━━━━━━━━━━━━ 45s 80ms/step - accuracy: 0.9201 - loss: 0.3198

 10/573 ━━━━━━━━━━━━━━━━━━━━ 44s 79ms/step - accuracy: 0.9219 - loss: 0.3075

 11/573 ━━━━━━━━━━━━━━━━━━━━ 44s 80ms/step - accuracy: 0.9176 - loss: 0.3126

 12/573 ━━━━━━━━━━━━━━━━━━━━ 44s 79ms/step - accuracy: 0.9141 - loss: 0.3171

 13/573 ━━━━━━━━━━━━━━━━━━━━ 44s 79ms/step - accuracy: 0.9183 - loss: 0.2995

 14/573 ━━━━━━━━━━━━━━━━━━━━ 44s 80ms/step - accuracy: 0.9152 - loss: 0.3210

 15/573 ━━━━━━━━━━━━━━━━━━━━ 43s 79ms/step - accuracy: 0.9104 - loss: 0.3318

 16/573 ━━━━━━━━━━━━━━━━━━━━ 44s 79ms/step - accuracy: 0.9062 - loss: 0.3560

 17/573 ━━━━━━━━━━━━━━━━━━━━ 43s 79ms/step - accuracy: 0.9062 - loss: 0.3466

 18/573 ━━━━━━━━━━━━━━━━━━━━ 44s 79ms/step - accuracy: 0.9028 - loss: 0.3466

 19/573 ━━━━━━━━━━━━━━━━━━━━ 43s 79ms/step - accuracy: 0.8997 - loss: 0.3418

 20/573 ━━━━━━━━━━━━━━━━━━━━ 44s 80ms/step - accuracy: 0.9031 - loss: 0.3344

 21/573 ━━━━━━━━━━━━━━━━━━━━ 43s 80ms/step - accuracy: 0.9033 - loss: 0.3353

 22/573 ━━━━━━━━━━━━━━━━━━━━ 43s 80ms/step - accuracy: 0.9062 - loss: 0.3238

 23/573 ━━━━━━━━━━━━━━━━━━━━ 43s 79ms/step - accuracy: 0.9103 - loss: 0.3139

 24/573 ━━━━━━━━━━━━━━━━━━━━ 43s 80ms/step - accuracy: 0.9128 - loss: 0.3116

 25/573 ━━━━━━━━━━━━━━━━━━━━ 43s 80ms/step - accuracy: 0.9112 - loss: 0.3199

 26/573 ━━━━━━━━━━━━━━━━━━━━ 43s 79ms/step - accuracy: 0.9147 - loss: 0.3099

 27/573 ━━━━━━━━━━━━━━━━━━━━ 45s 84ms/step - accuracy: 0.9120 - loss: 0.3114

 28/573 ━━━━━━━━━━━━━━━━━━━━ 45s 84ms/step - accuracy: 0.9152 - loss: 0.3038

 29/573 ━━━━━━━━━━━━━━━━━━━━ 45s 84ms/step - accuracy: 0.9159 - loss: 0.3019

 30/573 ━━━━━━━━━━━━━━━━━━━━ 45s 84ms/step - accuracy: 0.9156 - loss: 0.3004

 31/573 ━━━━━━━━━━━━━━━━━━━━ 45s 83ms/step - accuracy: 0.9163 - loss: 0.3003

 32/573 ━━━━━━━━━━━━━━━━━━━━ 44s 83ms/step - accuracy: 0.9170 - loss: 0.3007

 33/573 ━━━━━━━━━━━━━━━━━━━━ 44s 83ms/step - accuracy: 0.9167 - loss: 0.2971

 34/573 ━━━━━━━━━━━━━━━━━━━━ 44s 83ms/step - accuracy: 0.9154 - loss: 0.3018

 35/573 ━━━━━━━━━━━━━━━━━━━━ 44s 83ms/step - accuracy: 0.9143 - loss: 0.3039

 36/573 ━━━━━━━━━━━━━━━━━━━━ 44s 83ms/step - accuracy: 0.9141 - loss: 0.3071

 37/573 ━━━━━━━━━━━━━━━━━━━━ 44s 83ms/step - accuracy: 0.9147 - loss: 0.3060

 38/573 ━━━━━━━━━━━━━━━━━━━━ 44s 83ms/step - accuracy: 0.9137 - loss: 0.3045

 39/573 ━━━━━━━━━━━━━━━━━━━━ 44s 82ms/step - accuracy: 0.9143 - loss: 0.3016

 40/573 ━━━━━━━━━━━━━━━━━━━━ 43s 82ms/step - accuracy: 0.9156 - loss: 0.2965

 41/573 ━━━━━━━━━━━━━━━━━━━━ 43s 82ms/step - accuracy: 0.9169 - loss: 0.2919

 42/573 ━━━━━━━━━━━━━━━━━━━━ 43s 82ms/step - accuracy: 0.9174 - loss: 0.2895

 43/573 ━━━━━━━━━━━━━━━━━━━━ 43s 82ms/step - accuracy: 0.9157 - loss: 0.2928

 44/573 ━━━━━━━━━━━━━━━━━━━━ 43s 82ms/step - accuracy: 0.9148 - loss: 0.2932

 45/573 ━━━━━━━━━━━━━━━━━━━━ 43s 82ms/step - accuracy: 0.9125 - loss: 0.3013

 46/573 ━━━━━━━━━━━━━━━━━━━━ 43s 82ms/step - accuracy: 0.9124 - loss: 0.3014

 47/573 ━━━━━━━━━━━━━━━━━━━━ 43s 82ms/step - accuracy: 0.9136 - loss: 0.2972

 48/573 ━━━━━━━━━━━━━━━━━━━━ 43s 82ms/step - accuracy: 0.9128 - loss: 0.2981

 49/573 ━━━━━━━━━━━━━━━━━━━━ 42s 82ms/step - accuracy: 0.9139 - loss: 0.2956

 50/573 ━━━━━━━━━━━━━━━━━━━━ 42s 82ms/step - accuracy: 0.9156 - loss: 0.2913

 51/573 ━━━━━━━━━━━━━━━━━━━━ 42s 82ms/step - accuracy: 0.9154 - loss: 0.2919

 52/573 ━━━━━━━━━━━━━━━━━━━━ 42s 82ms/step - accuracy: 0.9153 - loss: 0.2910

 53/573 ━━━━━━━━━━━━━━━━━━━━ 42s 82ms/step - accuracy: 0.9145 - loss: 0.2939

 54/573 ━━━━━━━━━━━━━━━━━━━━ 42s 82ms/step - accuracy: 0.9149 - loss: 0.2910

 55/573 ━━━━━━━━━━━━━━━━━━━━ 42s 81ms/step - accuracy: 0.9148 - loss: 0.2891

 56/573 ━━━━━━━━━━━━━━━━━━━━ 42s 81ms/step - accuracy: 0.9146 - loss: 0.2887

 57/573 ━━━━━━━━━━━━━━━━━━━━ 42s 81ms/step - accuracy: 0.9139 - loss: 0.2915

 58/573 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.9143 - loss: 0.2886

 59/573 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.9153 - loss: 0.2884

 60/573 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.9151 - loss: 0.2895

 61/573 ━━━━━━━━━━━━━━━━━━━━ 41s 81ms/step - accuracy: 0.9144 - loss: 0.2905

 62/573 ━━━━━━━━━━━━━━━━━━━━ 41s 82ms/step - accuracy: 0.9158 - loss: 0.2863

 63/573 ━━━━━━━━━━━━━━━━━━━━ 41s 82ms/step - accuracy: 0.9162 - loss: 0.2870

 64/573 ━━━━━━━━━━━━━━━━━━━━ 41s 82ms/step - accuracy: 0.9160 - loss: 0.2864

 65/573 ━━━━━━━━━━━━━━━━━━━━ 41s 82ms/step - accuracy: 0.9154 - loss: 0.2884

 66/573 ━━━━━━━━━━━━━━━━━━━━ 41s 82ms/step - accuracy: 0.9124 - loss: 0.2928

 67/573 ━━━━━━━━━━━━━━━━━━━━ 41s 82ms/step - accuracy: 0.9123 - loss: 0.2918

 68/573 ━━━━━━━━━━━━━━━━━━━━ 41s 82ms/step - accuracy: 0.9104 - loss: 0.2974

 69/573 ━━━━━━━━━━━━━━━━━━━━ 41s 82ms/step - accuracy: 0.9108 - loss: 0.2951

 70/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.9116 - loss: 0.2925

 71/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.9098 - loss: 0.2969

 72/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.9093 - loss: 0.2993

 73/573 ━━━━━━━━━━━━━━━━━━━━ 40s 81ms/step - accuracy: 0.9092 - loss: 0.3016

 74/573 ━━━━━━━━━━━━━━━━━━━━ 40s 82ms/step - accuracy: 0.9088 - loss: 0.3022

 75/573 ━━━━━━━━━━━━━━━━━━━━ 40s 82ms/step - accuracy: 0.9087 - loss: 0.3031

 76/573 ━━━━━━━━━━━━━━━━━━━━ 40s 82ms/step - accuracy: 0.9091 - loss: 0.3003

 77/573 ━━━━━━━━━━━━━━━━━━━━ 40s 82ms/step - accuracy: 0.9075 - loss: 0.3014

 78/573 ━━━━━━━━━━━━━━━━━━━━ 40s 82ms/step - accuracy: 0.9087 - loss: 0.2990

 79/573 ━━━━━━━━━━━━━━━━━━━━ 40s 82ms/step - accuracy: 0.9086 - loss: 0.3022

 80/573 ━━━━━━━━━━━━━━━━━━━━ 40s 82ms/step - accuracy: 0.9082 - loss: 0.3010

 81/573 ━━━━━━━━━━━━━━━━━━━━ 40s 82ms/step - accuracy: 0.9074 - loss: 0.3028

 82/573 ━━━━━━━━━━━━━━━━━━━━ 39s 81ms/step - accuracy: 0.9074 - loss: 0.3023

 83/573 ━━━━━━━━━━━━━━━━━━━━ 39s 81ms/step - accuracy: 0.9081 - loss: 0.2994

 84/573 ━━━━━━━━━━━━━━━━━━━━ 40s 82ms/step - accuracy: 0.9077 - loss: 0.2999

 85/573 ━━━━━━━━━━━━━━━━━━━━ 40s 82ms/step - accuracy: 0.9081 - loss: 0.3021

 86/573 ━━━━━━━━━━━━━━━━━━━━ 40s 82ms/step - accuracy: 0.9084 - loss: 0.3008

 87/573 ━━━━━━━━━━━━━━━━━━━━ 39s 82ms/step - accuracy: 0.9084 - loss: 0.3009

 88/573 ━━━━━━━━━━━━━━━━━━━━ 39s 82ms/step - accuracy: 0.9087 - loss: 0.2995

 89/573 ━━━━━━━━━━━━━━━━━━━━ 39s 82ms/step - accuracy: 0.9087 - loss: 0.2994

 90/573 ━━━━━━━━━━━━━━━━━━━━ 39s 82ms/step - accuracy: 0.9090 - loss: 0.2999

 91/573 ━━━━━━━━━━━━━━━━━━━━ 39s 82ms/step - accuracy: 0.9083 - loss: 0.3031

 92/573 ━━━━━━━━━━━━━━━━━━━━ 39s 82ms/step - accuracy: 0.9086 - loss: 0.3025

 93/573 ━━━━━━━━━━━━━━━━━━━━ 39s 82ms/step - accuracy: 0.9079 - loss: 0.3049

 94/573 ━━━━━━━━━━━━━━━━━━━━ 39s 82ms/step - accuracy: 0.9072 - loss: 0.3064

 95/573 ━━━━━━━━━━━━━━━━━━━━ 39s 82ms/step - accuracy: 0.9069 - loss: 0.3060

 96/573 ━━━━━━━━━━━━━━━━━━━━ 39s 82ms/step - accuracy: 0.9069 - loss: 0.3073

 97/573 ━━━━━━━━━━━━━━━━━━━━ 38s 82ms/step - accuracy: 0.9069 - loss: 0.3066

 98/573 ━━━━━━━━━━━━━━━━━━━━ 38s 82ms/step - accuracy: 0.9062 - loss: 0.3106

 99/573 ━━━━━━━━━━━━━━━━━━━━ 38s 82ms/step - accuracy: 0.9059 - loss: 0.3117

100/573 ━━━━━━━━━━━━━━━━━━━━ 38s 82ms/step - accuracy: 0.9056 - loss: 0.3156

101/573 ━━━━━━━━━━━━━━━━━━━━ 38s 82ms/step - accuracy: 0.9059 - loss: 0.3145

102/573 ━━━━━━━━━━━━━━━━━━━━ 38s 82ms/step - accuracy: 0.9059 - loss: 0.3134

103/573 ━━━━━━━━━━━━━━━━━━━━ 38s 82ms/step - accuracy: 0.9059 - loss: 0.3124

104/573 ━━━━━━━━━━━━━━━━━━━━ 38s 82ms/step - accuracy: 0.9059 - loss: 0.3121

105/573 ━━━━━━━━━━━━━━━━━━━━ 38s 82ms/step - accuracy: 0.9060 - loss: 0.3118

106/573 ━━━━━━━━━━━━━━━━━━━━ 38s 82ms/step - accuracy: 0.9060 - loss: 0.3131

107/573 ━━━━━━━━━━━━━━━━━━━━ 38s 82ms/step - accuracy: 0.9057 - loss: 0.3127

108/573 ━━━━━━━━━━━━━━━━━━━━ 37s 82ms/step - accuracy: 0.9065 - loss: 0.3104

109/573 ━━━━━━━━━━━━━━━━━━━━ 37s 82ms/step - accuracy: 0.9068 - loss: 0.3105

110/573 ━━━━━━━━━━━━━━━━━━━━ 37s 82ms/step - accuracy: 0.9065 - loss: 0.3111

111/573 ━━━━━━━━━━━━━━━━━━━━ 37s 82ms/step - accuracy: 0.9068 - loss: 0.3111

112/573 ━━━━━━━━━━━━━━━━━━━━ 37s 82ms/step - accuracy: 0.9065 - loss: 0.3125

113/573 ━━━━━━━━━━━━━━━━━━━━ 37s 82ms/step - accuracy: 0.9062 - loss: 0.3139

114/573 ━━━━━━━━━━━━━━━━━━━━ 37s 82ms/step - accuracy: 0.9057 - loss: 0.3206

115/573 ━━━━━━━━━━━━━━━━━━━━ 37s 82ms/step - accuracy: 0.9057 - loss: 0.3209

116/573 ━━━━━━━━━━━━━━━━━━━━ 37s 82ms/step - accuracy: 0.9057 - loss: 0.3204

117/573 ━━━━━━━━━━━━━━━━━━━━ 37s 82ms/step - accuracy: 0.9060 - loss: 0.3207

118/573 ━━━━━━━━━━━━━━━━━━━━ 37s 82ms/step - accuracy: 0.9057 - loss: 0.3198

119/573 ━━━━━━━━━━━━━━━━━━━━ 37s 82ms/step - accuracy: 0.9055 - loss: 0.3205

120/573 ━━━━━━━━━━━━━━━━━━━━ 36s 82ms/step - accuracy: 0.9052 - loss: 0.3208

121/573 ━━━━━━━━━━━━━━━━━━━━ 36s 82ms/step - accuracy: 0.9044 - loss: 0.3222

122/573 ━━━━━━━━━━━━━━━━━━━━ 36s 82ms/step - accuracy: 0.9045 - loss: 0.3233

123/573 ━━━━━━━━━━━━━━━━━━━━ 36s 82ms/step - accuracy: 0.9040 - loss: 0.3255

124/573 ━━━━━━━━━━━━━━━━━━━━ 36s 82ms/step - accuracy: 0.9037 - loss: 0.3266

125/573 ━━━━━━━━━━━━━━━━━━━━ 36s 81ms/step - accuracy: 0.9035 - loss: 0.3263

126/573 ━━━━━━━━━━━━━━━━━━━━ 36s 81ms/step - accuracy: 0.9025 - loss: 0.3285

127/573 ━━━━━━━━━━━━━━━━━━━━ 36s 81ms/step - accuracy: 0.9021 - loss: 0.3335

128/573 ━━━━━━━━━━━━━━━━━━━━ 36s 81ms/step - accuracy: 0.9023 - loss: 0.3339

129/573 ━━━━━━━━━━━━━━━━━━━━ 36s 81ms/step - accuracy: 0.9029 - loss: 0.3336

130/573 ━━━━━━━━━━━━━━━━━━━━ 36s 81ms/step - accuracy: 0.9017 - loss: 0.3377

131/573 ━━━━━━━━━━━━━━━━━━━━ 35s 81ms/step - accuracy: 0.9015 - loss: 0.3376

132/573 ━━━━━━━━━━━━━━━━━━━━ 35s 81ms/step - accuracy: 0.9015 - loss: 0.3375

133/573 ━━━━━━━━━━━━━━━━━━━━ 35s 81ms/step - accuracy: 0.9018 - loss: 0.3378

134/573 ━━━━━━━━━━━━━━━━━━━━ 35s 81ms/step - accuracy: 0.9018 - loss: 0.3366

135/573 ━━━━━━━━━━━━━━━━━━━━ 35s 81ms/step - accuracy: 0.9014 - loss: 0.3384

136/573 ━━━━━━━━━━━━━━━━━━━━ 35s 81ms/step - accuracy: 0.9014 - loss: 0.3388

137/573 ━━━━━━━━━━━━━━━━━━━━ 35s 81ms/step - accuracy: 0.9017 - loss: 0.3379

138/573 ━━━━━━━━━━━━━━━━━━━━ 35s 81ms/step - accuracy: 0.9013 - loss: 0.3382

139/573 ━━━━━━━━━━━━━━━━━━━━ 35s 81ms/step - accuracy: 0.9011 - loss: 0.3396

140/573 ━━━━━━━━━━━━━━━━━━━━ 35s 81ms/step - accuracy: 0.9011 - loss: 0.3390

141/573 ━━━━━━━━━━━━━━━━━━━━ 35s 81ms/step - accuracy: 0.9003 - loss: 0.3418

142/573 ━━━━━━━━━━━━━━━━━━━━ 35s 81ms/step - accuracy: 0.9010 - loss: 0.3397

143/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.9010 - loss: 0.3386

144/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.9010 - loss: 0.3379

145/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.9002 - loss: 0.3389

146/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.9005 - loss: 0.3378

147/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.9007 - loss: 0.3371

148/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.9010 - loss: 0.3375

149/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.9008 - loss: 0.3386

150/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.9006 - loss: 0.3407

151/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.9013 - loss: 0.3389

152/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.9009 - loss: 0.3396

153/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.9005 - loss: 0.3390

154/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.9010 - loss: 0.3373

155/573 ━━━━━━━━━━━━━━━━━━━━ 34s 81ms/step - accuracy: 0.9008 - loss: 0.3393

156/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.9004 - loss: 0.3413

157/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.8999 - loss: 0.3417

158/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.8995 - loss: 0.3416

159/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.8992 - loss: 0.3439

160/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.8986 - loss: 0.3456

161/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.8985 - loss: 0.3452

162/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.8980 - loss: 0.3473

163/573 ━━━━━━━━━━━━━━━━━━━━ 33s 81ms/step - accuracy: 0.8984 - loss: 0.3463

164/573 ━━━━━━━━━━━━━━━━━━━━ 33s 82ms/step - accuracy: 0.8977 - loss: 0.3487

165/573 ━━━━━━━━━━━━━━━━━━━━ 33s 82ms/step - accuracy: 0.8975 - loss: 0.3484

166/573 ━━━━━━━━━━━━━━━━━━━━ 33s 82ms/step - accuracy: 0.8968 - loss: 0.3505

167/573 ━━━━━━━━━━━━━━━━━━━━ 33s 82ms/step - accuracy: 0.8967 - loss: 0.3499

168/573 ━━━━━━━━━━━━━━━━━━━━ 33s 82ms/step - accuracy: 0.8968 - loss: 0.3494

169/573 ━━━━━━━━━━━━━━━━━━━━ 33s 82ms/step - accuracy: 0.8968 - loss: 0.3495

170/573 ━━━━━━━━━━━━━━━━━━━━ 33s 82ms/step - accuracy: 0.8971 - loss: 0.3484

171/573 ━━━━━━━━━━━━━━━━━━━━ 33s 82ms/step - accuracy: 0.8971 - loss: 0.3499

172/573 ━━━━━━━━━━━━━━━━━━━━ 33s 82ms/step - accuracy: 0.8972 - loss: 0.3508

173/573 ━━━━━━━━━━━━━━━━━━━━ 32s 82ms/step - accuracy: 0.8972 - loss: 0.3511

174/573 ━━━━━━━━━━━━━━━━━━━━ 33s 83ms/step - accuracy: 0.8974 - loss: 0.3498

175/573 ━━━━━━━━━━━━━━━━━━━━ 32s 83ms/step - accuracy: 0.8973 - loss: 0.3495

176/573 ━━━━━━━━━━━━━━━━━━━━ 32s 83ms/step - accuracy: 0.8972 - loss: 0.3498

177/573 ━━━━━━━━━━━━━━━━━━━━ 32s 83ms/step - accuracy: 0.8974 - loss: 0.3492

178/573 ━━━━━━━━━━━━━━━━━━━━ 32s 83ms/step - accuracy: 0.8976 - loss: 0.3490

179/573 ━━━━━━━━━━━━━━━━━━━━ 32s 83ms/step - accuracy: 0.8972 - loss: 0.3497

180/573 ━━━━━━━━━━━━━━━━━━━━ 32s 83ms/step - accuracy: 0.8970 - loss: 0.3500

181/573 ━━━━━━━━━━━━━━━━━━━━ 32s 83ms/step - accuracy: 0.8971 - loss: 0.3492

182/573 ━━━━━━━━━━━━━━━━━━━━ 32s 83ms/step - accuracy: 0.8970 - loss: 0.3499

183/573 ━━━━━━━━━━━━━━━━━━━━ 32s 83ms/step - accuracy: 0.8969 - loss: 0.3499

184/573 ━━━━━━━━━━━━━━━━━━━━ 32s 83ms/step - accuracy: 0.8969 - loss: 0.3487

185/573 ━━━━━━━━━━━━━━━━━━━━ 32s 83ms/step - accuracy: 0.8965 - loss: 0.3517

186/573 ━━━━━━━━━━━━━━━━━━━━ 32s 83ms/step - accuracy: 0.8968 - loss: 0.3507

187/573 ━━━━━━━━━━━━━━━━━━━━ 32s 83ms/step - accuracy: 0.8974 - loss: 0.3491

188/573 ━━━━━━━━━━━━━━━━━━━━ 32s 83ms/step - accuracy: 0.8978 - loss: 0.3478

189/573 ━━━━━━━━━━━━━━━━━━━━ 31s 83ms/step - accuracy: 0.8978 - loss: 0.3475

190/573 ━━━━━━━━━━━━━━━━━━━━ 31s 83ms/step - accuracy: 0.8979 - loss: 0.3480

191/573 ━━━━━━━━━━━━━━━━━━━━ 31s 83ms/step - accuracy: 0.8982 - loss: 0.3466

192/573 ━━━━━━━━━━━━━━━━━━━━ 31s 83ms/step - accuracy: 0.8981 - loss: 0.3476

193/573 ━━━━━━━━━━━━━━━━━━━━ 31s 83ms/step - accuracy: 0.8983 - loss: 0.3466

194/573 ━━━━━━━━━━━━━━━━━━━━ 31s 83ms/step - accuracy: 0.8982 - loss: 0.3465

195/573 ━━━━━━━━━━━━━━━━━━━━ 31s 83ms/step - accuracy: 0.8984 - loss: 0.3452

196/573 ━━━━━━━━━━━━━━━━━━━━ 31s 83ms/step - accuracy: 0.8981 - loss: 0.3449

197/573 ━━━━━━━━━━━━━━━━━━━━ 31s 83ms/step - accuracy: 0.8978 - loss: 0.3459

198/573 ━━━━━━━━━━━━━━━━━━━━ 31s 83ms/step - accuracy: 0.8976 - loss: 0.3461

199/573 ━━━━━━━━━━━━━━━━━━━━ 31s 84ms/step - accuracy: 0.8976 - loss: 0.3462

200/573 ━━━━━━━━━━━━━━━━━━━━ 31s 84ms/step - accuracy: 0.8980 - loss: 0.3448

201/573 ━━━━━━━━━━━━━━━━━━━━ 31s 84ms/step - accuracy: 0.8975 - loss: 0.3468

202/573 ━━━━━━━━━━━━━━━━━━━━ 31s 84ms/step - accuracy: 0.8973 - loss: 0.3472

203/573 ━━━━━━━━━━━━━━━━━━━━ 31s 84ms/step - accuracy: 0.8973 - loss: 0.3465

204/573 ━━━━━━━━━━━━━━━━━━━━ 30s 84ms/step - accuracy: 0.8974 - loss: 0.3463

205/573 ━━━━━━━━━━━━━━━━━━━━ 30s 84ms/step - accuracy: 0.8970 - loss: 0.3475

206/573 ━━━━━━━━━━━━━━━━━━━━ 30s 84ms/step - accuracy: 0.8967 - loss: 0.3476

207/573 ━━━━━━━━━━━━━━━━━━━━ 30s 84ms/step - accuracy: 0.8964 - loss: 0.3485

208/573 ━━━━━━━━━━━━━━━━━━━━ 30s 84ms/step - accuracy: 0.8966 - loss: 0.3492

209/573 ━━━━━━━━━━━━━━━━━━━━ 30s 84ms/step - accuracy: 0.8965 - loss: 0.3500

210/573 ━━━━━━━━━━━━━━━━━━━━ 30s 84ms/step - accuracy: 0.8967 - loss: 0.3491

211/573 ━━━━━━━━━━━━━━━━━━━━ 30s 84ms/step - accuracy: 0.8968 - loss: 0.3483

212/573 ━━━━━━━━━━━━━━━━━━━━ 30s 84ms/step - accuracy: 0.8970 - loss: 0.3476

213/573 ━━━━━━━━━━━━━━━━━━━━ 30s 84ms/step - accuracy: 0.8970 - loss: 0.3472

214/573 ━━━━━━━━━━━━━━━━━━━━ 30s 84ms/step - accuracy: 0.8973 - loss: 0.3461

215/573 ━━━━━━━━━━━━━━━━━━━━ 30s 84ms/step - accuracy: 0.8969 - loss: 0.3467

216/573 ━━━━━━━━━━━━━━━━━━━━ 29s 84ms/step - accuracy: 0.8967 - loss: 0.3475

217/573 ━━━━━━━━━━━━━━━━━━━━ 29s 84ms/step - accuracy: 0.8970 - loss: 0.3463

218/573 ━━━━━━━━━━━━━━━━━━━━ 29s 84ms/step - accuracy: 0.8972 - loss: 0.3455

219/573 ━━━━━━━━━━━━━━━━━━━━ 29s 84ms/step - accuracy: 0.8965 - loss: 0.3488

220/573 ━━━━━━━━━━━━━━━━━━━━ 29s 84ms/step - accuracy: 0.8969 - loss: 0.3482

221/573 ━━━━━━━━━━━━━━━━━━━━ 29s 84ms/step - accuracy: 0.8971 - loss: 0.3478

222/573 ━━━━━━━━━━━━━━━━━━━━ 29s 84ms/step - accuracy: 0.8974 - loss: 0.3469

223/573 ━━━━━━━━━━━━━━━━━━━━ 29s 84ms/step - accuracy: 0.8974 - loss: 0.3467

224/573 ━━━━━━━━━━━━━━━━━━━━ 29s 84ms/step - accuracy: 0.8976 - loss: 0.3470

225/573 ━━━━━━━━━━━━━━━━━━━━ 29s 84ms/step - accuracy: 0.8978 - loss: 0.3466

226/573 ━━━━━━━━━━━━━━━━━━━━ 29s 84ms/step - accuracy: 0.8978 - loss: 0.3465

227/573 ━━━━━━━━━━━━━━━━━━━━ 29s 85ms/step - accuracy: 0.8977 - loss: 0.3472

228/573 ━━━━━━━━━━━━━━━━━━━━ 29s 85ms/step - accuracy: 0.8982 - loss: 0.3462

229/573 ━━━━━━━━━━━━━━━━━━━━ 29s 85ms/step - accuracy: 0.8983 - loss: 0.3458

230/573 ━━━━━━━━━━━━━━━━━━━━ 29s 85ms/step - accuracy: 0.8985 - loss: 0.3457

231/573 ━━━━━━━━━━━━━━━━━━━━ 28s 85ms/step - accuracy: 0.8980 - loss: 0.3466

232/573 ━━━━━━━━━━━━━━━━━━━━ 28s 85ms/step - accuracy: 0.8979 - loss: 0.3471

233/573 ━━━━━━━━━━━━━━━━━━━━ 28s 85ms/step - accuracy: 0.8981 - loss: 0.3461

234/573 ━━━━━━━━━━━━━━━━━━━━ 28s 85ms/step - accuracy: 0.8980 - loss: 0.3459

235/573 ━━━━━━━━━━━━━━━━━━━━ 28s 85ms/step - accuracy: 0.8976 - loss: 0.3471

236/573 ━━━━━━━━━━━━━━━━━━━━ 28s 85ms/step - accuracy: 0.8978 - loss: 0.3466

237/573 ━━━━━━━━━━━━━━━━━━━━ 28s 85ms/step - accuracy: 0.8975 - loss: 0.3474

238/573 ━━━━━━━━━━━━━━━━━━━━ 28s 85ms/step - accuracy: 0.8978 - loss: 0.3463

239/573 ━━━━━━━━━━━━━━━━━━━━ 28s 85ms/step - accuracy: 0.8976 - loss: 0.3470

240/573 ━━━━━━━━━━━━━━━━━━━━ 28s 85ms/step - accuracy: 0.8979 - loss: 0.3465

241/573 ━━━━━━━━━━━━━━━━━━━━ 28s 85ms/step - accuracy: 0.8981 - loss: 0.3462

242/573 ━━━━━━━━━━━━━━━━━━━━ 28s 85ms/step - accuracy: 0.8981 - loss: 0.3462

243/573 ━━━━━━━━━━━━━━━━━━━━ 27s 85ms/step - accuracy: 0.8983 - loss: 0.3454

244/573 ━━━━━━━━━━━━━━━━━━━━ 27s 85ms/step - accuracy: 0.8982 - loss: 0.3452

245/573 ━━━━━━━━━━━━━━━━━━━━ 27s 85ms/step - accuracy: 0.8985 - loss: 0.3444

246/573 ━━━━━━━━━━━━━━━━━━━━ 27s 85ms/step - accuracy: 0.8984 - loss: 0.3445

247/573 ━━━━━━━━━━━━━━━━━━━━ 27s 85ms/step - accuracy: 0.8984 - loss: 0.3443

248/573 ━━━━━━━━━━━━━━━━━━━━ 27s 85ms/step - accuracy: 0.8984 - loss: 0.3437

249/573 ━━━━━━━━━━━━━━━━━━━━ 27s 85ms/step - accuracy: 0.8985 - loss: 0.3439

250/573 ━━━━━━━━━━━━━━━━━━━━ 27s 85ms/step - accuracy: 0.8982 - loss: 0.3441

251/573 ━━━━━━━━━━━━━━━━━━━━ 27s 85ms/step - accuracy: 0.8984 - loss: 0.3434

252/573 ━━━━━━━━━━━━━━━━━━━━ 27s 85ms/step - accuracy: 0.8988 - loss: 0.3424

253/573 ━━━━━━━━━━━━━━━━━━━━ 27s 85ms/step - accuracy: 0.8990 - loss: 0.3427

254/573 ━━━━━━━━━━━━━━━━━━━━ 27s 85ms/step - accuracy: 0.8991 - loss: 0.3418

255/573 ━━━━━━━━━━━━━━━━━━━━ 27s 85ms/step - accuracy: 0.8993 - loss: 0.3414

256/573 ━━━━━━━━━━━━━━━━━━━━ 27s 85ms/step - accuracy: 0.8992 - loss: 0.3422

257/573 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - accuracy: 0.8988 - loss: 0.3422

258/573 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - accuracy: 0.8989 - loss: 0.3419

259/573 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - accuracy: 0.8988 - loss: 0.3422

260/573 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - accuracy: 0.8986 - loss: 0.3421

261/573 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - accuracy: 0.8987 - loss: 0.3420

262/573 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - accuracy: 0.8985 - loss: 0.3416

263/573 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - accuracy: 0.8983 - loss: 0.3421

264/573 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - accuracy: 0.8982 - loss: 0.3421

265/573 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - accuracy: 0.8983 - loss: 0.3413

266/573 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - accuracy: 0.8984 - loss: 0.3411

267/573 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - accuracy: 0.8984 - loss: 0.3406

268/573 ━━━━━━━━━━━━━━━━━━━━ 26s 85ms/step - accuracy: 0.8983 - loss: 0.3411

269/573 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - accuracy: 0.8984 - loss: 0.3408

270/573 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - accuracy: 0.8986 - loss: 0.3401

271/573 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - accuracy: 0.8985 - loss: 0.3413

272/573 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - accuracy: 0.8987 - loss: 0.3404

273/573 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - accuracy: 0.8979 - loss: 0.3430

274/573 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - accuracy: 0.8980 - loss: 0.3423

275/573 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - accuracy: 0.8982 - loss: 0.3419

276/573 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - accuracy: 0.8984 - loss: 0.3411

277/573 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - accuracy: 0.8980 - loss: 0.3413

278/573 ━━━━━━━━━━━━━━━━━━━━ 25s 85ms/step - accuracy: 0.8982 - loss: 0.3412

279/573 ━━━━━━━━━━━━━━━━━━━━ 25s 86ms/step - accuracy: 0.8983 - loss: 0.3404

280/573 ━━━━━━━━━━━━━━━━━━━━ 25s 86ms/step - accuracy: 0.8983 - loss: 0.3405

281/573 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - accuracy: 0.8981 - loss: 0.3411

282/573 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - accuracy: 0.8978 - loss: 0.3415

283/573 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - accuracy: 0.8979 - loss: 0.3414

284/573 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - accuracy: 0.8978 - loss: 0.3414

285/573 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - accuracy: 0.8981 - loss: 0.3404

286/573 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - accuracy: 0.8982 - loss: 0.3404

287/573 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - accuracy: 0.8985 - loss: 0.3395

288/573 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - accuracy: 0.8985 - loss: 0.3393

289/573 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - accuracy: 0.8986 - loss: 0.3389

290/573 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - accuracy: 0.8989 - loss: 0.3381

291/573 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - accuracy: 0.8991 - loss: 0.3373

292/573 ━━━━━━━━━━━━━━━━━━━━ 24s 86ms/step - accuracy: 0.8992 - loss: 0.3368

293/573 ━━━━━━━━━━━━━━━━━━━━ 23s 86ms/step - accuracy: 0.8990 - loss: 0.3374

294/573 ━━━━━━━━━━━━━━━━━━━━ 23s 86ms/step - accuracy: 0.8991 - loss: 0.3367

295/573 ━━━━━━━━━━━━━━━━━━━━ 23s 86ms/step - accuracy: 0.8990 - loss: 0.3374

296/573 ━━━━━━━━━━━━━━━━━━━━ 23s 86ms/step - accuracy: 0.8990 - loss: 0.3377

297/573 ━━━━━━━━━━━━━━━━━━━━ 23s 86ms/step - accuracy: 0.8989 - loss: 0.3376

298/573 ━━━━━━━━━━━━━━━━━━━━ 23s 86ms/step - accuracy: 0.8986 - loss: 0.3394

299/573 ━━━━━━━━━━━━━━━━━━━━ 23s 86ms/step - accuracy: 0.8987 - loss: 0.3389

300/573 ━━━━━━━━━━━━━━━━━━━━ 23s 86ms/step - accuracy: 0.8986 - loss: 0.3390

301/573 ━━━━━━━━━━━━━━━━━━━━ 23s 86ms/step - accuracy: 0.8987 - loss: 0.3386

302/573 ━━━━━━━━━━━━━━━━━━━━ 23s 86ms/step - accuracy: 0.8987 - loss: 0.3387

303/573 ━━━━━━━━━━━━━━━━━━━━ 23s 86ms/step - accuracy: 0.8988 - loss: 0.3380

304/573 ━━━━━━━━━━━━━━━━━━━━ 23s 86ms/step - accuracy: 0.8985 - loss: 0.3389

305/573 ━━━━━━━━━━━━━━━━━━━━ 22s 86ms/step - accuracy: 0.8986 - loss: 0.3390

306/573 ━━━━━━━━━━━━━━━━━━━━ 22s 86ms/step - accuracy: 0.8986 - loss: 0.3385

307/573 ━━━━━━━━━━━━━━━━━━━━ 22s 86ms/step - accuracy: 0.8988 - loss: 0.3379

308/573 ━━━━━━━━━━━━━━━━━━━━ 22s 86ms/step - accuracy: 0.8986 - loss: 0.3387

309/573 ━━━━━━━━━━━━━━━━━━━━ 22s 86ms/step - accuracy: 0.8988 - loss: 0.3381

310/573 ━━━━━━━━━━━━━━━━━━━━ 22s 86ms/step - accuracy: 0.8991 - loss: 0.3372

311/573 ━━━━━━━━━━━━━━━━━━━━ 22s 86ms/step - accuracy: 0.8991 - loss: 0.3377

312/573 ━━━━━━━━━━━━━━━━━━━━ 22s 86ms/step - accuracy: 0.8991 - loss: 0.3371

313/573 ━━━━━━━━━━━━━━━━━━━━ 22s 86ms/step - accuracy: 0.8992 - loss: 0.3371

314/573 ━━━━━━━━━━━━━━━━━━━━ 22s 86ms/step - accuracy: 0.8992 - loss: 0.3368

315/573 ━━━━━━━━━━━━━━━━━━━━ 22s 86ms/step - accuracy: 0.8990 - loss: 0.3368

316/573 ━━━━━━━━━━━━━━━━━━━━ 21s 86ms/step - accuracy: 0.8992 - loss: 0.3360

317/573 ━━━━━━━━━━━━━━━━━━━━ 21s 86ms/step - accuracy: 0.8993 - loss: 0.3360

318/573 ━━━━━━━━━━━━━━━━━━━━ 21s 86ms/step - accuracy: 0.8993 - loss: 0.3360

319/573 ━━━━━━━━━━━━━━━━━━━━ 21s 86ms/step - accuracy: 0.8996 - loss: 0.3351

320/573 ━━━━━━━━━━━━━━━━━━━━ 21s 86ms/step - accuracy: 0.8997 - loss: 0.3348

321/573 ━━━━━━━━━━━━━━━━━━━━ 21s 86ms/step - accuracy: 0.8996 - loss: 0.3355

322/573 ━━━━━━━━━━━━━━━━━━━━ 21s 86ms/step - accuracy: 0.8998 - loss: 0.3348

323/573 ━━━━━━━━━━━━━━━━━━━━ 21s 86ms/step - accuracy: 0.8999 - loss: 0.3344

324/573 ━━━━━━━━━━━━━━━━━━━━ 21s 86ms/step - accuracy: 0.8998 - loss: 0.3342

325/573 ━━━━━━━━━━━━━━━━━━━━ 21s 86ms/step - accuracy: 0.8998 - loss: 0.3341

326/573 ━━━━━━━━━━━━━━━━━━━━ 21s 86ms/step - accuracy: 0.8997 - loss: 0.3342

327/573 ━━━━━━━━━━━━━━━━━━━━ 21s 86ms/step - accuracy: 0.8998 - loss: 0.3345

328/573 ━━━━━━━━━━━━━━━━━━━━ 20s 86ms/step - accuracy: 0.8999 - loss: 0.3343

329/573 ━━━━━━━━━━━━━━━━━━━━ 20s 86ms/step - accuracy: 0.8998 - loss: 0.3351

330/573 ━━━━━━━━━━━━━━━━━━━━ 20s 86ms/step - accuracy: 0.8999 - loss: 0.3348

331/573 ━━━━━━━━━━━━━━━━━━━━ 20s 86ms/step - accuracy: 0.8999 - loss: 0.3351

332/573 ━━━━━━━━━━━━━━━━━━━━ 20s 86ms/step - accuracy: 0.8998 - loss: 0.3348

333/573 ━━━━━━━━━━━━━━━━━━━━ 20s 86ms/step - accuracy: 0.8996 - loss: 0.3356

334/573 ━━━━━━━━━━━━━━━━━━━━ 20s 86ms/step - accuracy: 0.8994 - loss: 0.3361

335/573 ━━━━━━━━━━━━━━━━━━━━ 20s 86ms/step - accuracy: 0.8993 - loss: 0.3364

336/573 ━━━━━━━━━━━━━━━━━━━━ 20s 86ms/step - accuracy: 0.8992 - loss: 0.3368

337/573 ━━━━━━━━━━━━━━━━━━━━ 20s 86ms/step - accuracy: 0.8992 - loss: 0.3367

338/573 ━━━━━━━━━━━━━━━━━━━━ 20s 86ms/step - accuracy: 0.8994 - loss: 0.3360

339/573 ━━━━━━━━━━━━━━━━━━━━ 20s 86ms/step - accuracy: 0.8992 - loss: 0.3359

340/573 ━━━━━━━━━━━━━━━━━━━━ 19s 86ms/step - accuracy: 0.8994 - loss: 0.3359

341/573 ━━━━━━━━━━━━━━━━━━━━ 19s 86ms/step - accuracy: 0.8995 - loss: 0.3359

342/573 ━━━━━━━━━━━━━━━━━━━━ 19s 86ms/step - accuracy: 0.8998 - loss: 0.3350

343/573 ━━━━━━━━━━━━━━━━━━━━ 19s 86ms/step - accuracy: 0.8996 - loss: 0.3350

344/573 ━━━━━━━━━━━━━━━━━━━━ 19s 86ms/step - accuracy: 0.8995 - loss: 0.3349

345/573 ━━━━━━━━━━━━━━━━━━━━ 19s 86ms/step - accuracy: 0.8995 - loss: 0.3350

346/573 ━━━━━━━━━━━━━━━━━━━━ 19s 86ms/step - accuracy: 0.8995 - loss: 0.3350

347/573 ━━━━━━━━━━━━━━━━━━━━ 19s 86ms/step - accuracy: 0.8994 - loss: 0.3353

348/573 ━━━━━━━━━━━━━━━━━━━━ 19s 86ms/step - accuracy: 0.8994 - loss: 0.3351

349/573 ━━━━━━━━━━━━━━━━━━━━ 19s 86ms/step - accuracy: 0.8993 - loss: 0.3355

350/573 ━━━━━━━━━━━━━━━━━━━━ 19s 86ms/step - accuracy: 0.8995 - loss: 0.3350

351/573 ━━━━━━━━━━━━━━━━━━━━ 19s 86ms/step - accuracy: 0.8993 - loss: 0.3352

352/573 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - accuracy: 0.8993 - loss: 0.3351

353/573 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - accuracy: 0.8994 - loss: 0.3350

354/573 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - accuracy: 0.8995 - loss: 0.3348

355/573 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - accuracy: 0.8994 - loss: 0.3346

356/573 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - accuracy: 0.8993 - loss: 0.3351

357/573 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - accuracy: 0.8994 - loss: 0.3346

358/573 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - accuracy: 0.8994 - loss: 0.3343

359/573 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - accuracy: 0.8996 - loss: 0.3340

360/573 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - accuracy: 0.8997 - loss: 0.3334

361/573 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - accuracy: 0.8999 - loss: 0.3330

362/573 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - accuracy: 0.8999 - loss: 0.3332

363/573 ━━━━━━━━━━━━━━━━━━━━ 18s 86ms/step - accuracy: 0.9001 - loss: 0.3325

364/573 ━━━━━━━━━━━━━━━━━━━━ 17s 86ms/step - accuracy: 0.9002 - loss: 0.3320

365/573 ━━━━━━━━━━━━━━━━━━━━ 17s 86ms/step - accuracy: 0.9001 - loss: 0.3315

366/573 ━━━━━━━━━━━━━━━━━━━━ 17s 86ms/step - accuracy: 0.9000 - loss: 0.3325

367/573 ━━━━━━━━━━━━━━━━━━━━ 17s 86ms/step - accuracy: 0.9002 - loss: 0.3318

368/573 ━━━━━━━━━━━━━━━━━━━━ 17s 86ms/step - accuracy: 0.9002 - loss: 0.3317

369/573 ━━━━━━━━━━━━━━━━━━━━ 17s 86ms/step - accuracy: 0.9001 - loss: 0.3316

370/573 ━━━━━━━━━━━━━━━━━━━━ 17s 86ms/step - accuracy: 0.8999 - loss: 0.3316

371/573 ━━━━━━━━━━━━━━━━━━━━ 17s 86ms/step - accuracy: 0.8999 - loss: 0.3315

372/573 ━━━━━━━━━━━━━━━━━━━━ 17s 86ms/step - accuracy: 0.8997 - loss: 0.3330

373/573 ━━━━━━━━━━━━━━━━━━━━ 17s 86ms/step - accuracy: 0.8995 - loss: 0.3331

374/573 ━━━━━━━━━━━━━━━━━━━━ 17s 86ms/step - accuracy: 0.8996 - loss: 0.3328

375/573 ━━━━━━━━━━━━━━━━━━━━ 16s 86ms/step - accuracy: 0.8998 - loss: 0.3321

376/573 ━━━━━━━━━━━━━━━━━━━━ 16s 86ms/step - accuracy: 0.8999 - loss: 0.3317

377/573 ━━━━━━━━━━━━━━━━━━━━ 16s 86ms/step - accuracy: 0.9000 - loss: 0.3320

378/573 ━━━━━━━━━━━━━━━━━━━━ 16s 86ms/step - accuracy: 0.9001 - loss: 0.3322

380/573 ━━━━━━━━━━━━━━━━━━━━ 16s 86ms/step - accuracy: 0.9002 - loss: 0.3318

381/573 ━━━━━━━━━━━━━━━━━━━━ 16s 86ms/step - accuracy: 0.9003 - loss: 0.3323

382/573 ━━━━━━━━━━━━━━━━━━━━ 16s 86ms/step - accuracy: 0.9002 - loss: 0.3327

383/573 ━━━━━━━━━━━━━━━━━━━━ 16s 86ms/step - accuracy: 0.9003 - loss: 0.3322

384/573 ━━━━━━━━━━━━━━━━━━━━ 16s 86ms/step - accuracy: 0.9003 - loss: 0.3320

385/573 ━━━━━━━━━━━━━━━━━━━━ 16s 86ms/step - accuracy: 0.9003 - loss: 0.3318

386/573 ━━━━━━━━━━━━━━━━━━━━ 16s 86ms/step - accuracy: 0.9003 - loss: 0.3318

387/573 ━━━━━━━━━━━━━━━━━━━━ 15s 86ms/step - accuracy: 0.9001 - loss: 0.3320

388/573 ━━━━━━━━━━━━━━━━━━━━ 15s 86ms/step - accuracy: 0.9002 - loss: 0.3315

389/573 ━━━━━━━━━━━━━━━━━━━━ 15s 86ms/step - accuracy: 0.9002 - loss: 0.3319

390/573 ━━━━━━━━━━━━━━━━━━━━ 15s 86ms/step - accuracy: 0.9001 - loss: 0.3328

391/573 ━━━━━━━━━━━━━━━━━━━━ 15s 86ms/step - accuracy: 0.9002 - loss: 0.3322

392/573 ━━━━━━━━━━━━━━━━━━━━ 15s 86ms/step - accuracy: 0.9004 - loss: 0.3316

393/573 ━━━━━━━━━━━━━━━━━━━━ 15s 86ms/step - accuracy: 0.9004 - loss: 0.3316

394/573 ━━━━━━━━━━━━━━━━━━━━ 15s 86ms/step - accuracy: 0.9005 - loss: 0.3316

395/573 ━━━━━━━━━━━━━━━━━━━━ 15s 86ms/step - accuracy: 0.9005 - loss: 0.3319

396/573 ━━━━━━━━━━━━━━━━━━━━ 15s 86ms/step - accuracy: 0.9005 - loss: 0.3315

397/573 ━━━━━━━━━━━━━━━━━━━━ 15s 86ms/step - accuracy: 0.9007 - loss: 0.3307

398/573 ━━━━━━━━━━━━━━━━━━━━ 14s 86ms/step - accuracy: 0.9008 - loss: 0.3305

399/573 ━━━━━━━━━━━━━━━━━━━━ 14s 86ms/step - accuracy: 0.9008 - loss: 0.3308

400/573 ━━━━━━━━━━━━━━━━━━━━ 14s 86ms/step - accuracy: 0.9007 - loss: 0.3309

401/573 ━━━━━━━━━━━━━━━━━━━━ 14s 86ms/step - accuracy: 0.9006 - loss: 0.3312

402/573 ━━━━━━━━━━━━━━━━━━━━ 14s 86ms/step - accuracy: 0.9004 - loss: 0.3319

403/573 ━━━━━━━━━━━━━━━━━━━━ 14s 86ms/step - accuracy: 0.9002 - loss: 0.3322

404/573 ━━━━━━━━━━━━━━━━━━━━ 14s 86ms/step - accuracy: 0.9000 - loss: 0.3330

405/573 ━━━━━━━━━━━━━━━━━━━━ 14s 86ms/step - accuracy: 0.9001 - loss: 0.3324

406/573 ━━━━━━━━━━━━━━━━━━━━ 14s 86ms/step - accuracy: 0.9000 - loss: 0.3326

407/573 ━━━━━━━━━━━━━━━━━━━━ 14s 86ms/step - accuracy: 0.8999 - loss: 0.3331

408/573 ━━━━━━━━━━━━━━━━━━━━ 14s 86ms/step - accuracy: 0.8998 - loss: 0.3336

409/573 ━━━━━━━━━━━━━━━━━━━━ 14s 86ms/step - accuracy: 0.8996 - loss: 0.3339

410/573 ━━━━━━━━━━━━━━━━━━━━ 13s 86ms/step - accuracy: 0.8995 - loss: 0.3341

411/573 ━━━━━━━━━━━━━━━━━━━━ 13s 86ms/step - accuracy: 0.8996 - loss: 0.3340

412/573 ━━━━━━━━━━━━━━━━━━━━ 13s 86ms/step - accuracy: 0.8998 - loss: 0.3336

413/573 ━━━━━━━━━━━━━━━━━━━━ 13s 86ms/step - accuracy: 0.8997 - loss: 0.3338

414/573 ━━━━━━━━━━━━━━━━━━━━ 13s 86ms/step - accuracy: 0.8998 - loss: 0.3336

415/573 ━━━━━━━━━━━━━━━━━━━━ 13s 86ms/step - accuracy: 0.8998 - loss: 0.3332

416/573 ━━━━━━━━━━━━━━━━━━━━ 13s 86ms/step - accuracy: 0.8999 - loss: 0.3328

417/573 ━━━━━━━━━━━━━━━━━━━━ 13s 86ms/step - accuracy: 0.8998 - loss: 0.3327

418/573 ━━━━━━━━━━━━━━━━━━━━ 13s 86ms/step - accuracy: 0.8999 - loss: 0.3324

419/573 ━━━━━━━━━━━━━━━━━━━━ 13s 86ms/step - accuracy: 0.8999 - loss: 0.3322

420/573 ━━━━━━━━━━━━━━━━━━━━ 13s 86ms/step - accuracy: 0.8999 - loss: 0.3323

421/573 ━━━━━━━━━━━━━━━━━━━━ 13s 86ms/step - accuracy: 0.8999 - loss: 0.3329

422/573 ━━━━━━━━━━━━━━━━━━━━ 12s 86ms/step - accuracy: 0.8999 - loss: 0.3328

423/573 ━━━━━━━━━━━━━━━━━━━━ 12s 86ms/step - accuracy: 0.9000 - loss: 0.3322

424/573 ━━━━━━━━━━━━━━━━━━━━ 12s 86ms/step - accuracy: 0.9001 - loss: 0.3324

425/573 ━━━━━━━━━━━━━━━━━━━━ 12s 86ms/step - accuracy: 0.9002 - loss: 0.3321

426/573 ━━━━━━━━━━━━━━━━━━━━ 12s 86ms/step - accuracy: 0.9001 - loss: 0.3322

427/573 ━━━━━━━━━━━━━━━━━━━━ 12s 86ms/step - accuracy: 0.9000 - loss: 0.3323

428/573 ━━━━━━━━━━━━━━━━━━━━ 12s 86ms/step - accuracy: 0.8999 - loss: 0.3333

429/573 ━━━━━━━━━━━━━━━━━━━━ 12s 86ms/step - accuracy: 0.8997 - loss: 0.3333

430/573 ━━━━━━━━━━━━━━━━━━━━ 12s 86ms/step - accuracy: 0.8996 - loss: 0.3336

431/573 ━━━━━━━━━━━━━━━━━━━━ 12s 86ms/step - accuracy: 0.8995 - loss: 0.3336

432/573 ━━━━━━━━━━━━━━━━━━━━ 12s 86ms/step - accuracy: 0.8993 - loss: 0.3344

433/573 ━━━━━━━━━━━━━━━━━━━━ 12s 86ms/step - accuracy: 0.8993 - loss: 0.3351

434/573 ━━━━━━━━━━━━━━━━━━━━ 11s 86ms/step - accuracy: 0.8994 - loss: 0.3350

435/573 ━━━━━━━━━━━━━━━━━━━━ 11s 86ms/step - accuracy: 0.8994 - loss: 0.3348

436/573 ━━━━━━━━━━━━━━━━━━━━ 11s 86ms/step - accuracy: 0.8993 - loss: 0.3350

437/573 ━━━━━━━━━━━━━━━━━━━━ 11s 86ms/step - accuracy: 0.8994 - loss: 0.3346

438/573 ━━━━━━━━━━━━━━━━━━━━ 11s 86ms/step - accuracy: 0.8995 - loss: 0.3343

439/573 ━━━━━━━━━━━━━━━━━━━━ 11s 86ms/step - accuracy: 0.8993 - loss: 0.3349

440/573 ━━━━━━━━━━━━━━━━━━━━ 11s 86ms/step - accuracy: 0.8993 - loss: 0.3346

441/573 ━━━━━━━━━━━━━━━━━━━━ 11s 86ms/step - accuracy: 0.8992 - loss: 0.3354

442/573 ━━━━━━━━━━━━━━━━━━━━ 11s 86ms/step - accuracy: 0.8992 - loss: 0.3354

443/573 ━━━━━━━━━━━━━━━━━━━━ 11s 86ms/step - accuracy: 0.8993 - loss: 0.3356

444/573 ━━━━━━━━━━━━━━━━━━━━ 11s 86ms/step - accuracy: 0.8993 - loss: 0.3351

445/573 ━━━━━━━━━━━━━━━━━━━━ 10s 86ms/step - accuracy: 0.8994 - loss: 0.3353

446/573 ━━━━━━━━━━━━━━━━━━━━ 10s 86ms/step - accuracy: 0.8994 - loss: 0.3354

447/573 ━━━━━━━━━━━━━━━━━━━━ 10s 86ms/step - accuracy: 0.8993 - loss: 0.3354

448/573 ━━━━━━━━━━━━━━━━━━━━ 10s 86ms/step - accuracy: 0.8993 - loss: 0.3353

449/573 ━━━━━━━━━━━━━━━━━━━━ 10s 86ms/step - accuracy: 0.8993 - loss: 0.3362

450/573 ━━━━━━━━━━━━━━━━━━━━ 10s 86ms/step - accuracy: 0.8993 - loss: 0.3365

451/573 ━━━━━━━━━━━━━━━━━━━━ 10s 86ms/step - accuracy: 0.8993 - loss: 0.3367

452/573 ━━━━━━━━━━━━━━━━━━━━ 10s 86ms/step - accuracy: 0.8992 - loss: 0.3368

453/573 ━━━━━━━━━━━━━━━━━━━━ 10s 86ms/step - accuracy: 0.8991 - loss: 0.3372

454/573 ━━━━━━━━━━━━━━━━━━━━ 10s 86ms/step - accuracy: 0.8991 - loss: 0.3370

455/573 ━━━━━━━━━━━━━━━━━━━━ 10s 86ms/step - accuracy: 0.8991 - loss: 0.3371

456/573 ━━━━━━━━━━━━━━━━━━━━ 10s 86ms/step - accuracy: 0.8990 - loss: 0.3370

457/573 ━━━━━━━━━━━━━━━━━━━━ 9s 86ms/step - accuracy: 0.8989 - loss: 0.3374

458/573 ━━━━━━━━━━━━━━━━━━━━ 9s 86ms/step - accuracy: 0.8991 - loss: 0.3369

459/573 ━━━━━━━━━━━━━━━━━━━━ 9s 86ms/step - accuracy: 0.8994 - loss: 0.3363

460/573 ━━━━━━━━━━━━━━━━━━━━ 9s 86ms/step - accuracy: 0.8995 - loss: 0.3360

461/573 ━━━━━━━━━━━━━━━━━━━━ 9s 86ms/step - accuracy: 0.8994 - loss: 0.3362

462/573 ━━━━━━━━━━━━━━━━━━━━ 9s 86ms/step - accuracy: 0.8993 - loss: 0.3359

463/573 ━━━━━━━━━━━━━━━━━━━━ 9s 86ms/step - accuracy: 0.8994 - loss: 0.3356

464/573 ━━━━━━━━━━━━━━━━━━━━ 9s 86ms/step - accuracy: 0.8993 - loss: 0.3359

465/573 ━━━━━━━━━━━━━━━━━━━━ 9s 86ms/step - accuracy: 0.8989 - loss: 0.3369

466/573 ━━━━━━━━━━━━━━━━━━━━ 9s 86ms/step - accuracy: 0.8989 - loss: 0.3368

467/573 ━━━━━━━━━━━━━━━━━━━━ 9s 86ms/step - accuracy: 0.8987 - loss: 0.3369

468/573 ━━━━━━━━━━━━━━━━━━━━ 9s 86ms/step - accuracy: 0.8988 - loss: 0.3372

469/573 ━━━━━━━━━━━━━━━━━━━━ 8s 86ms/step - accuracy: 0.8990 - loss: 0.3367

470/573 ━━━━━━━━━━━━━━━━━━━━ 8s 86ms/step - accuracy: 0.8991 - loss: 0.3364

471/573 ━━━━━━━━━━━━━━━━━━━━ 8s 86ms/step - accuracy: 0.8992 - loss: 0.3358

472/573 ━━━━━━━━━━━━━━━━━━━━ 8s 86ms/step - accuracy: 0.8992 - loss: 0.3357

473/573 ━━━━━━━━━━━━━━━━━━━━ 8s 86ms/step - accuracy: 0.8992 - loss: 0.3354

474/573 ━━━━━━━━━━━━━━━━━━━━ 8s 86ms/step - accuracy: 0.8993 - loss: 0.3352

475/573 ━━━━━━━━━━━━━━━━━━━━ 8s 86ms/step - accuracy: 0.8993 - loss: 0.3349

476/573 ━━━━━━━━━━━━━━━━━━━━ 8s 86ms/step - accuracy: 0.8992 - loss: 0.3352

477/573 ━━━━━━━━━━━━━━━━━━━━ 8s 86ms/step - accuracy: 0.8994 - loss: 0.3346

478/573 ━━━━━━━━━━━━━━━━━━━━ 8s 86ms/step - accuracy: 0.8995 - loss: 0.3341

479/573 ━━━━━━━━━━━━━━━━━━━━ 8s 86ms/step - accuracy: 0.8995 - loss: 0.3343

480/573 ━━━━━━━━━━━━━━━━━━━━ 7s 86ms/step - accuracy: 0.8995 - loss: 0.3344

481/573 ━━━━━━━━━━━━━━━━━━━━ 7s 86ms/step - accuracy: 0.8996 - loss: 0.3343

482/573 ━━━━━━━━━━━━━━━━━━━━ 7s 86ms/step - accuracy: 0.8998 - loss: 0.3338

483/573 ━━━━━━━━━━━━━━━━━━━━ 7s 86ms/step - accuracy: 0.8998 - loss: 0.3336

484/573 ━━━━━━━━━━━━━━━━━━━━ 7s 86ms/step - accuracy: 0.8999 - loss: 0.3336

485/573 ━━━━━━━━━━━━━━━━━━━━ 7s 86ms/step - accuracy: 0.8998 - loss: 0.3336

486/573 ━━━━━━━━━━━━━━━━━━━━ 7s 86ms/step - accuracy: 0.8998 - loss: 0.3338

487/573 ━━━━━━━━━━━━━━━━━━━━ 7s 86ms/step - accuracy: 0.8998 - loss: 0.3339

488/573 ━━━━━━━━━━━━━━━━━━━━ 7s 86ms/step - accuracy: 0.8998 - loss: 0.3337

489/573 ━━━━━━━━━━━━━━━━━━━━ 7s 86ms/step - accuracy: 0.8999 - loss: 0.3331

490/573 ━━━━━━━━━━━━━━━━━━━━ 7s 86ms/step - accuracy: 0.8997 - loss: 0.3337

491/573 ━━━━━━━━━━━━━━━━━━━━ 7s 86ms/step - accuracy: 0.8996 - loss: 0.3338

492/573 ━━━━━━━━━━━━━━━━━━━━ 6s 86ms/step - accuracy: 0.8996 - loss: 0.3339

493/573 ━━━━━━━━━━━━━━━━━━━━ 6s 86ms/step - accuracy: 0.8998 - loss: 0.3335

494/573 ━━━━━━━━━━━━━━━━━━━━ 6s 86ms/step - accuracy: 0.8997 - loss: 0.3334

495/573 ━━━━━━━━━━━━━━━━━━━━ 6s 86ms/step - accuracy: 0.8997 - loss: 0.3332

496/573 ━━━━━━━━━━━━━━━━━━━━ 6s 86ms/step - accuracy: 0.8996 - loss: 0.3334

497/573 ━━━━━━━━━━━━━━━━━━━━ 6s 86ms/step - accuracy: 0.8996 - loss: 0.3332

498/573 ━━━━━━━━━━━━━━━━━━━━ 6s 86ms/step - accuracy: 0.8998 - loss: 0.3328

499/573 ━━━━━━━━━━━━━━━━━━━━ 6s 86ms/step - accuracy: 0.8999 - loss: 0.3324

500/573 ━━━━━━━━━━━━━━━━━━━━ 6s 86ms/step - accuracy: 0.8997 - loss: 0.3327

501/573 ━━━━━━━━━━━━━━━━━━━━ 6s 86ms/step - accuracy: 0.8995 - loss: 0.3330

502/573 ━━━━━━━━━━━━━━━━━━━━ 6s 86ms/step - accuracy: 0.8997 - loss: 0.3324

503/573 ━━━━━━━━━━━━━━━━━━━━ 6s 86ms/step - accuracy: 0.8997 - loss: 0.3322

504/573 ━━━━━━━━━━━━━━━━━━━━ 5s 86ms/step - accuracy: 0.8997 - loss: 0.3322

505/573 ━━━━━━━━━━━━━━━━━━━━ 5s 86ms/step - accuracy: 0.8996 - loss: 0.3327

506/573 ━━━━━━━━━━━━━━━━━━━━ 5s 86ms/step - accuracy: 0.8996 - loss: 0.3327

507/573 ━━━━━━━━━━━━━━━━━━━━ 5s 86ms/step - accuracy: 0.8996 - loss: 0.3326

508/573 ━━━━━━━━━━━━━━━━━━━━ 5s 86ms/step - accuracy: 0.8997 - loss: 0.3321

509/573 ━━━━━━━━━━━━━━━━━━━━ 5s 86ms/step - accuracy: 0.8997 - loss: 0.3321

510/573 ━━━━━━━━━━━━━━━━━━━━ 5s 86ms/step - accuracy: 0.8996 - loss: 0.3324

511/573 ━━━━━━━━━━━━━━━━━━━━ 5s 86ms/step - accuracy: 0.8995 - loss: 0.3332

512/573 ━━━━━━━━━━━━━━━━━━━━ 5s 86ms/step - accuracy: 0.8993 - loss: 0.3332

513/573 ━━━━━━━━━━━━━━━━━━━━ 5s 86ms/step - accuracy: 0.8993 - loss: 0.3333

514/573 ━━━━━━━━━━━━━━━━━━━━ 5s 86ms/step - accuracy: 0.8994 - loss: 0.3329

515/573 ━━━━━━━━━━━━━━━━━━━━ 4s 86ms/step - accuracy: 0.8994 - loss: 0.3326

516/573 ━━━━━━━━━━━━━━━━━━━━ 4s 86ms/step - accuracy: 0.8993 - loss: 0.3328

517/573 ━━━━━━━━━━━━━━━━━━━━ 4s 86ms/step - accuracy: 0.8991 - loss: 0.3338

518/573 ━━━━━━━━━━━━━━━━━━━━ 4s 86ms/step - accuracy: 0.8991 - loss: 0.3338

519/573 ━━━━━━━━━━━━━━━━━━━━ 4s 86ms/step - accuracy: 0.8991 - loss: 0.3336

520/573 ━━━━━━━━━━━━━━━━━━━━ 4s 86ms/step - accuracy: 0.8989 - loss: 0.3347

521/573 ━━━━━━━━━━━━━━━━━━━━ 4s 86ms/step - accuracy: 0.8990 - loss: 0.3345

522/573 ━━━━━━━━━━━━━━━━━━━━ 4s 86ms/step - accuracy: 0.8989 - loss: 0.3347

523/573 ━━━━━━━━━━━━━━━━━━━━ 4s 86ms/step - accuracy: 0.8990 - loss: 0.3344

524/573 ━━━━━━━━━━━━━━━━━━━━ 4s 86ms/step - accuracy: 0.8990 - loss: 0.3345

525/573 ━━━━━━━━━━━━━━━━━━━━ 4s 86ms/step - accuracy: 0.8989 - loss: 0.3349

526/573 ━━━━━━━━━━━━━━━━━━━━ 4s 86ms/step - accuracy: 0.8991 - loss: 0.3344

527/573 ━━━━━━━━━━━━━━━━━━━━ 3s 86ms/step - accuracy: 0.8990 - loss: 0.3343

528/573 ━━━━━━━━━━━━━━━━━━━━ 3s 86ms/step - accuracy: 0.8990 - loss: 0.3348

529/573 ━━━━━━━━━━━━━━━━━━━━ 3s 86ms/step - accuracy: 0.8990 - loss: 0.3349

530/573 ━━━━━━━━━━━━━━━━━━━━ 3s 86ms/step - accuracy: 0.8991 - loss: 0.3348

531/573 ━━━━━━━━━━━━━━━━━━━━ 3s 86ms/step - accuracy: 0.8990 - loss: 0.3348

532/573 ━━━━━━━━━━━━━━━━━━━━ 3s 86ms/step - accuracy: 0.8991 - loss: 0.3345

533/573 ━━━━━━━━━━━━━━━━━━━━ 3s 86ms/step - accuracy: 0.8991 - loss: 0.3344

534/573 ━━━━━━━━━━━━━━━━━━━━ 3s 86ms/step - accuracy: 0.8992 - loss: 0.3342

535/573 ━━━━━━━━━━━━━━━━━━━━ 3s 86ms/step - accuracy: 0.8992 - loss: 0.3346

536/573 ━━━━━━━━━━━━━━━━━━━━ 3s 86ms/step - accuracy: 0.8991 - loss: 0.3348

537/573 ━━━━━━━━━━━━━━━━━━━━ 3s 86ms/step - accuracy: 0.8992 - loss: 0.3349

538/573 ━━━━━━━━━━━━━━━━━━━━ 3s 86ms/step - accuracy: 0.8992 - loss: 0.3350

539/573 ━━━━━━━━━━━━━━━━━━━━ 2s 86ms/step - accuracy: 0.8991 - loss: 0.3351

540/573 ━━━━━━━━━━━━━━━━━━━━ 2s 86ms/step - accuracy: 0.8991 - loss: 0.3358

541/573 ━━━━━━━━━━━━━━━━━━━━ 2s 86ms/step - accuracy: 0.8991 - loss: 0.3358

542/573 ━━━━━━━━━━━━━━━━━━━━ 2s 86ms/step - accuracy: 0.8991 - loss: 0.3357

543/573 ━━━━━━━━━━━━━━━━━━━━ 2s 86ms/step - accuracy: 0.8990 - loss: 0.3358

544/573 ━━━━━━━━━━━━━━━━━━━━ 2s 86ms/step - accuracy: 0.8991 - loss: 0.3359

545/573 ━━━━━━━━━━━━━━━━━━━━ 2s 86ms/step - accuracy: 0.8991 - loss: 0.3357

546/573 ━━━━━━━━━━━━━━━━━━━━ 2s 86ms/step - accuracy: 0.8990 - loss: 0.3359

547/573 ━━━━━━━━━━━━━━━━━━━━ 2s 86ms/step - accuracy: 0.8990 - loss: 0.3357

548/573 ━━━━━━━━━━━━━━━━━━━━ 2s 86ms/step - accuracy: 0.8991 - loss: 0.3355

549/573 ━━━━━━━━━━━━━━━━━━━━ 2s 86ms/step - accuracy: 0.8992 - loss: 0.3350

550/573 ━━━━━━━━━━━━━━━━━━━━ 1s 86ms/step - accuracy: 0.8991 - loss: 0.3353

551/573 ━━━━━━━━━━━━━━━━━━━━ 1s 86ms/step - accuracy: 0.8990 - loss: 0.3360

552/573 ━━━━━━━━━━━━━━━━━━━━ 1s 86ms/step - accuracy: 0.8992 - loss: 0.3357

553/573 ━━━━━━━━━━━━━━━━━━━━ 1s 86ms/step - accuracy: 0.8991 - loss: 0.3357

554/573 ━━━━━━━━━━━━━━━━━━━━ 1s 86ms/step - accuracy: 0.8990 - loss: 0.3356

555/573 ━━━━━━━━━━━━━━━━━━━━ 1s 86ms/step - accuracy: 0.8990 - loss: 0.3355

556/573 ━━━━━━━━━━━━━━━━━━━━ 1s 86ms/step - accuracy: 0.8989 - loss: 0.3358

557/573 ━━━━━━━━━━━━━━━━━━━━ 1s 86ms/step - accuracy: 0.8990 - loss: 0.3356

558/573 ━━━━━━━━━━━━━━━━━━━━ 1s 86ms/step - accuracy: 0.8991 - loss: 0.3353

559/573 ━━━━━━━━━━━━━━━━━━━━ 1s 86ms/step - accuracy: 0.8992 - loss: 0.3348

560/573 ━━━━━━━━━━━━━━━━━━━━ 1s 86ms/step - accuracy: 0.8992 - loss: 0.3347

561/573 ━━━━━━━━━━━━━━━━━━━━ 1s 86ms/step - accuracy: 0.8993 - loss: 0.3343

562/573 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.8993 - loss: 0.3343

563/573 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.8994 - loss: 0.3343

564/573 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.8993 - loss: 0.3346

565/573 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.8994 - loss: 0.3343

566/573 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.8996 - loss: 0.3340

567/573 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.8996 - loss: 0.3337

568/573 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.8995 - loss: 0.3339

569/573 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.8994 - loss: 0.3338

570/573 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.8994 - loss: 0.3340

571/573 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.8995 - loss: 0.3337

572/573 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.8996 - loss: 0.3337

573/573 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.8995 - loss: 0.3337

573/573 ━━━━━━━━━━━━━━━━━━━━ 55s 96ms/step - accuracy: 0.8995 - loss: 0.3337 - val_accuracy: 0.9282 - val_loss: 0.2362

Epoch 5/20

  1/573 ━━━━━━━━━━━━━━━━━━━━ 1:08 120ms/step - accuracy: 1.0000 - loss: 0.0520

  2/573 ━━━━━━━━━━━━━━━━━━━━ 47s 83ms/step - accuracy: 0.9688 - loss: 0.1170

  3/573 ━━━━━━━━━━━━━━━━━━━━ 47s 84ms/step - accuracy: 0.9479 - loss: 0.1642

  4/573 ━━━━━━━━━━━━━━━━━━━━ 47s 84ms/step - accuracy: 0.9219 - loss: 0.1955

  5/573 ━━━━━━━━━━━━━━━━━━━━ 48s 85ms/step - accuracy: 0.9187 - loss: 0.2217

  6/573 ━━━━━━━━━━━━━━━━━━━━ 48s 85ms/step - accuracy: 0.9167 - loss: 0.2396

  7/573 ━━━━━━━━━━━━━━━━━━━━ 48s 85ms/step - accuracy: 0.9152 - loss: 0.2491

  8/573 ━━━━━━━━━━━━━━━━━━━━ 47s 85ms/step - accuracy: 0.9180 - loss: 0.2440

  9/573 ━━━━━━━━━━━━━━━━━━━━ 47s 84ms/step - accuracy: 0.9201 - loss: 0.2329

 10/573 ━━━━━━━━━━━━━━━━━━━━ 47s 85ms/step - accuracy: 0.9156 - loss: 0.2516

 11/573 ━━━━━━━━━━━━━━━━━━━━ 47s 84ms/step - accuracy: 0.9062 - loss: 0.2887

 12/573 ━━━━━━━━━━━━━━━━━━━━ 47s 85ms/step - accuracy: 0.8984 - loss: 0.3126

 13/573 ━━━━━━━━━━━━━━━━━━━━ 47s 85ms/step - accuracy: 0.8966 - loss: 0.3104

 14/573 ━━━━━━━━━━━━━━━━━━━━ 47s 85ms/step - accuracy: 0.8996 - loss: 0.3027

 15/573 ━━━━━━━━━━━━━━━━━━━━ 47s 85ms/step - accuracy: 0.9021 - loss: 0.3021

 16/573 ━━━━━━━━━━━━━━━━━━━━ 47s 85ms/step - accuracy: 0.9023 - loss: 0.3010

 17/573 ━━━━━━━━━━━━━━━━━━━━ 47s 85ms/step - accuracy: 0.9007 - loss: 0.3093

 18/573 ━━━━━━━━━━━━━━━━━━━━ 47s 85ms/step - accuracy: 0.8958 - loss: 0.3242

 19/573 ━━━━━━━━━━━━━━━━━━━━ 46s 85ms/step - accuracy: 0.8980 - loss: 0.3218

 20/573 ━━━━━━━━━━━━━━━━━━━━ 46s 85ms/step - accuracy: 0.8984 - loss: 0.3194

 21/573 ━━━━━━━━━━━━━━━━━━━━ 46s 85ms/step - accuracy: 0.8988 - loss: 0.3251

 22/573 ━━━━━━━━━━━━━━━━━━━━ 46s 85ms/step - accuracy: 0.8977 - loss: 0.3297

 23/573 ━━━━━━━━━━━━━━━━━━━━ 46s 85ms/step - accuracy: 0.8995 - loss: 0.3259

 24/573 ━━━━━━━━━━━━━━━━━━━━ 46s 85ms/step - accuracy: 0.8984 - loss: 0.3247

 25/573 ━━━━━━━━━━━━━━━━━━━━ 46s 85ms/step - accuracy: 0.8963 - loss: 0.3348

 26/573 ━━━━━━━━━━━━━━━━━━━━ 46s 85ms/step - accuracy: 0.8990 - loss: 0.3259

 27/573 ━━━━━━━━━━━━━━━━━━━━ 46s 85ms/step - accuracy: 0.8958 - loss: 0.3303

 28/573 ━━━━━━━━━━━━━━━━━━━━ 46s 85ms/step - accuracy: 0.8962 - loss: 0.3282

 29/573 ━━━━━━━━━━━━━━━━━━━━ 46s 85ms/step - accuracy: 0.8976 - loss: 0.3227

 30/573 ━━━━━━━━━━━━━━━━━━━━ 46s 85ms/step - accuracy: 0.8948 - loss: 0.3291

 31/573 ━━━━━━━━━━━━━━━━━━━━ 46s 85ms/step - accuracy: 0.8931 - loss: 0.3338

 32/573 ━━━━━━━━━━━━━━━━━━━━ 45s 85ms/step - accuracy: 0.8936 - loss: 0.3283

 33/573 ━━━━━━━━━━━━━━━━━━━━ 45s 85ms/step - accuracy: 0.8939 - loss: 0.3235

 34/573 ━━━━━━━━━━━━━━━━━━━━ 45s 85ms/step - accuracy: 0.8961 - loss: 0.3198

 35/573 ━━━━━━━━━━━━━━━━━━━━ 45s 85ms/step - accuracy: 0.8973 - loss: 0.3151

 36/573 ━━━━━━━━━━━━━━━━━━━━ 45s 85ms/step - accuracy: 0.8976 - loss: 0.3161

 37/573 ━━━━━━━━━━━━━━━━━━━━ 45s 85ms/step - accuracy: 0.8944 - loss: 0.3161

 38/573 ━━━━━━━━━━━━━━━━━━━━ 45s 85ms/step - accuracy: 0.8956 - loss: 0.3104

 39/573 ━━━━━━━━━━━━━━━━━━━━ 45s 85ms/step - accuracy: 0.8958 - loss: 0.3097

 40/573 ━━━━━━━━━━━━━━━━━━━━ 45s 85ms/step - accuracy: 0.8961 - loss: 0.3082

 41/573 ━━━━━━━━━━━━━━━━━━━━ 45s 85ms/step - accuracy: 0.8963 - loss: 0.3093

 42/573 ━━━━━━━━━━━━━━━━━━━━ 45s 85ms/step - accuracy: 0.8973 - loss: 0.3054

 43/573 ━━━━━━━━━━━━━━━━━━━━ 44s 85ms/step - accuracy: 0.8974 - loss: 0.3050

 44/573 ━━━━━━━━━━━━━━━━━━━━ 44s 85ms/step - accuracy: 0.8976 - loss: 0.3085

 45/573 ━━━━━━━━━━━━━━━━━━━━ 44s 85ms/step - accuracy: 0.8985 - loss: 0.3090

 46/573 ━━━━━━━━━━━━━━━━━━━━ 44s 85ms/step - accuracy: 0.8987 - loss: 0.3103

 47/573 ━━━━━━━━━━━━━━━━━━━━ 44s 85ms/step - accuracy: 0.8982 - loss: 0.3090

 48/573 ━━━━━━━━━━━━━━━━━━━━ 44s 85ms/step - accuracy: 0.8984 - loss: 0.3071

 49/573 ━━━━━━━━━━━━━━━━━━━━ 44s 85ms/step - accuracy: 0.8966 - loss: 0.3122

 50/573 ━━━━━━━━━━━━━━━━━━━━ 44s 85ms/step - accuracy: 0.8980 - loss: 0.3094

 51/573 ━━━━━━━━━━━━━━━━━━━━ 44s 85ms/step - accuracy: 0.8982 - loss: 0.3084

 52/573 ━━━━━━━━━━━━━━━━━━━━ 44s 85ms/step - accuracy: 0.8990 - loss: 0.3056

 53/573 ━━━━━━━━━━━━━━━━━━━━ 44s 85ms/step - accuracy: 0.8997 - loss: 0.3052

 54/573 ━━━━━━━━━━━━━━━━━━━━ 43s 85ms/step - accuracy: 0.8981 - loss: 0.3092

 55/573 ━━━━━━━━━━━━━━━━━━━━ 43s 85ms/step - accuracy: 0.8965 - loss: 0.3145

 56/573 ━━━━━━━━━━━━━━━━━━━━ 43s 85ms/step - accuracy: 0.8972 - loss: 0.3133

 57/573 ━━━━━━━━━━━━━━━━━━━━ 43s 85ms/step - accuracy: 0.8963 - loss: 0.3151

 58/573 ━━━━━━━━━━━━━━━━━━━━ 43s 85ms/step - accuracy: 0.8965 - loss: 0.3221

 59/573 ━━━━━━━━━━━━━━━━━━━━ 43s 85ms/step - accuracy: 0.8945 - loss: 0.3315

 60/573 ━━━━━━━━━━━━━━━━━━━━ 43s 85ms/step - accuracy: 0.8952 - loss: 0.3314

 61/573 ━━━━━━━━━━━━━━━━━━━━ 43s 85ms/step - accuracy: 0.8959 - loss: 0.3287

 62/573 ━━━━━━━━━━━━━━━━━━━━ 43s 85ms/step - accuracy: 0.8951 - loss: 0.3303

 63/573 ━━━━━━━━━━━━━━━━━━━━ 43s 85ms/step - accuracy: 0.8948 - loss: 0.3308

 64/573 ━━━━━━━━━━━━━━━━━━━━ 43s 85ms/step - accuracy: 0.8945 - loss: 0.3334

 65/573 ━━━━━━━━━━━━━━━━━━━━ 43s 85ms/step - accuracy: 0.8942 - loss: 0.3355

 66/573 ━━━━━━━━━━━━━━━━━━━━ 43s 85ms/step - accuracy: 0.8943 - loss: 0.3330

 67/573 ━━━━━━━━━━━━━━━━━━━━ 43s 85ms/step - accuracy: 0.8959 - loss: 0.3285

 68/573 ━━━━━━━━━━━━━━━━━━━━ 43s 85ms/step - accuracy: 0.8947 - loss: 0.3310

 69/573 ━━━━━━━━━━━━━━━━━━━━ 43s 85ms/step - accuracy: 0.8944 - loss: 0.3309

 70/573 ━━━━━━━━━━━━━━━━━━━━ 42s 85ms/step - accuracy: 0.8959 - loss: 0.3270

 71/573 ━━━━━━━━━━━━━━━━━━━━ 42s 85ms/step - accuracy: 0.8969 - loss: 0.3239

 72/573 ━━━━━━━━━━━━━━━━━━━━ 42s 85ms/step - accuracy: 0.8958 - loss: 0.3280

 73/573 ━━━━━━━━━━━━━━━━━━━━ 42s 85ms/step - accuracy: 0.8963 - loss: 0.3265

 74/573 ━━━━━━━━━━━━━━━━━━━━ 42s 85ms/step - accuracy: 0.8965 - loss: 0.3257

 75/573 ━━━━━━━━━━━━━━━━━━━━ 42s 85ms/step - accuracy: 0.8966 - loss: 0.3248

 76/573 ━━━━━━━━━━━━━━━━━━━━ 42s 86ms/step - accuracy: 0.8955 - loss: 0.3261

 77/573 ━━━━━━━━━━━━━━━━━━━━ 42s 86ms/step - accuracy: 0.8952 - loss: 0.3267

 78/573 ━━━━━━━━━━━━━━━━━━━━ 42s 86ms/step - accuracy: 0.8958 - loss: 0.3265

 79/573 ━━━━━━━━━━━━━━━━━━━━ 42s 86ms/step - accuracy: 0.8955 - loss: 0.3270

 80/573 ━━━━━━━━━━━━━━━━━━━━ 42s 86ms/step - accuracy: 0.8956 - loss: 0.3268

 81/573 ━━━━━━━━━━━━━━━━━━━━ 42s 86ms/step - accuracy: 0.8966 - loss: 0.3240

 82/573 ━━━━━━━━━━━━━━━━━━━━ 42s 86ms/step - accuracy: 0.8971 - loss: 0.3217

 83/573 ━━━━━━━━━━━━━━━━━━━━ 42s 86ms/step - accuracy: 0.8972 - loss: 0.3223

 84/573 ━━━━━━━━━━━━━━━━━━━━ 42s 86ms/step - accuracy: 0.8976 - loss: 0.3193

 85/573 ━━━━━━━━━━━━━━━━━━━━ 42s 86ms/step - accuracy: 0.8974 - loss: 0.3193

 86/573 ━━━━━━━━━━━━━━━━━━━━ 41s 86ms/step - accuracy: 0.8978 - loss: 0.3188

 87/573 ━━━━━━━━━━━━━━━━━━━━ 41s 86ms/step - accuracy: 0.8979 - loss: 0.3170

 88/573 ━━━━━━━━━━━━━━━━━━━━ 41s 86ms/step - accuracy: 0.8984 - loss: 0.3178

 89/573 ━━━━━━━━━━━━━━━━━━━━ 41s 86ms/step - accuracy: 0.8974 - loss: 0.3246

 90/573 ━━━━━━━━━━━━━━━━━━━━ 41s 86ms/step - accuracy: 0.8979 - loss: 0.3233

 91/573 ━━━━━━━━━━━━━━━━━━━━ 41s 86ms/step - accuracy: 0.8983 - loss: 0.3216

 92/573 ━━━━━━━━━━━━━━━━━━━━ 41s 86ms/step - accuracy: 0.8991 - loss: 0.3193

 93/573 ━━━━━━━━━━━━━━━━━━━━ 41s 86ms/step - accuracy: 0.8981 - loss: 0.3227

 94/573 ━━━━━━━━━━━━━━━━━━━━ 41s 86ms/step - accuracy: 0.8979 - loss: 0.3230

 95/573 ━━━━━━━━━━━━━━━━━━━━ 41s 86ms/step - accuracy: 0.8980 - loss: 0.3222

 96/573 ━━━━━━━━━━━━━━━━━━━━ 41s 87ms/step - accuracy: 0.8984 - loss: 0.3222

 97/573 ━━━━━━━━━━━━━━━━━━━━ 41s 87ms/step - accuracy: 0.8982 - loss: 0.3245

 98/573 ━━━━━━━━━━━━━━━━━━━━ 41s 87ms/step - accuracy: 0.8976 - loss: 0.3274

 99/573 ━━━━━━━━━━━━━━━━━━━━ 41s 87ms/step - accuracy: 0.8977 - loss: 0.3279

100/573 ━━━━━━━━━━━━━━━━━━━━ 41s 87ms/step - accuracy: 0.8981 - loss: 0.3269

101/573 ━━━━━━━━━━━━━━━━━━━━ 40s 87ms/step - accuracy: 0.8979 - loss: 0.3279

102/573 ━━━━━━━━━━━━━━━━━━━━ 41s 87ms/step - accuracy: 0.8986 - loss: 0.3263

103/573 ━━━━━━━━━━━━━━━━━━━━ 40s 87ms/step - accuracy: 0.8977 - loss: 0.3269

104/573 ━━━━━━━━━━━━━━━━━━━━ 40s 87ms/step - accuracy: 0.8981 - loss: 0.3247

105/573 ━━━━━━━━━━━━━━━━━━━━ 40s 87ms/step - accuracy: 0.8988 - loss: 0.3237

106/573 ━━━━━━━━━━━━━━━━━━━━ 40s 87ms/step - accuracy: 0.8991 - loss: 0.3216

107/573 ━━━━━━━━━━━━━━━━━━━━ 40s 87ms/step - accuracy: 0.8998 - loss: 0.3206

108/573 ━━━━━━━━━━━━━━━━━━━━ 40s 87ms/step - accuracy: 0.8996 - loss: 0.3208

109/573 ━━━━━━━━━━━━━━━━━━━━ 40s 87ms/step - accuracy: 0.8993 - loss: 0.3235

110/573 ━━━━━━━━━━━━━━━━━━━━ 40s 87ms/step - accuracy: 0.8988 - loss: 0.3241

111/573 ━━━━━━━━━━━━━━━━━━━━ 40s 87ms/step - accuracy: 0.8992 - loss: 0.3234

112/573 ━━━━━━━━━━━━━━━━━━━━ 40s 87ms/step - accuracy: 0.8998 - loss: 0.3225

113/573 ━━━━━━━━━━━━━━━━━━━━ 40s 87ms/step - accuracy: 0.8993 - loss: 0.3236

114/573 ━━━━━━━━━━━━━━━━━━━━ 40s 87ms/step - accuracy: 0.8991 - loss: 0.3228

115/573 ━━━━━━━━━━━━━━━━━━━━ 39s 87ms/step - accuracy: 0.8997 - loss: 0.3219

116/573 ━━━━━━━━━━━━━━━━━━━━ 39s 87ms/step - accuracy: 0.8992 - loss: 0.3225

117/573 ━━━━━━━━━━━━━━━━━━━━ 39s 87ms/step - accuracy: 0.8998 - loss: 0.3211

118/573 ━━━━━━━━━━━━━━━━━━━━ 39s 87ms/step - accuracy: 0.8996 - loss: 0.3219

119/573 ━━━━━━━━━━━━━━━━━━━━ 39s 87ms/step - accuracy: 0.9002 - loss: 0.3205

120/573 ━━━━━━━━━━━━━━━━━━━━ 39s 87ms/step - accuracy: 0.8992 - loss: 0.3232

121/573 ━━━━━━━━━━━━━━━━━━━━ 39s 87ms/step - accuracy: 0.8995 - loss: 0.3221

122/573 ━━━━━━━━━━━━━━━━━━━━ 39s 87ms/step - accuracy: 0.9001 - loss: 0.3211

123/573 ━━━━━━━━━━━━━━━━━━━━ 39s 87ms/step - accuracy: 0.9001 - loss: 0.3198

124/573 ━━━━━━━━━━━━━━━━━━━━ 39s 87ms/step - accuracy: 0.8997 - loss: 0.3205

125/573 ━━━━━━━━━━━━━━━━━━━━ 38s 87ms/step - accuracy: 0.9005 - loss: 0.3184

126/573 ━━━━━━━━━━━━━━━━━━━━ 38s 87ms/step - accuracy: 0.9008 - loss: 0.3171

127/573 ━━━━━━━━━━━━━━━━━━━━ 38s 87ms/step - accuracy: 0.9011 - loss: 0.3161

128/573 ━━━━━━━━━━━━━━━━━━━━ 38s 87ms/step - accuracy: 0.9004 - loss: 0.3184

129/573 ━━━━━━━━━━━━━━━━━━━━ 38s 87ms/step - accuracy: 0.9009 - loss: 0.3176

130/573 ━━━━━━━━━━━━━━━━━━━━ 38s 87ms/step - accuracy: 0.9012 - loss: 0.3173

131/573 ━━━━━━━━━━━━━━━━━━━━ 38s 87ms/step - accuracy: 0.9005 - loss: 0.3216

132/573 ━━━━━━━━━━━━━━━━━━━━ 38s 87ms/step - accuracy: 0.9010 - loss: 0.3212

133/573 ━━━━━━━━━━━━━━━━━━━━ 38s 87ms/step - accuracy: 0.9008 - loss: 0.3225

134/573 ━━━━━━━━━━━━━━━━━━━━ 38s 87ms/step - accuracy: 0.9009 - loss: 0.3219

135/573 ━━━━━━━━━━━━━━━━━━━━ 38s 87ms/step - accuracy: 0.9009 - loss: 0.3222

136/573 ━━━━━━━━━━━━━━━━━━━━ 37s 87ms/step - accuracy: 0.9014 - loss: 0.3204

137/573 ━━━━━━━━━━━━━━━━━━━━ 37s 87ms/step - accuracy: 0.9008 - loss: 0.3220

138/573 ━━━━━━━━━━━━━━━━━━━━ 37s 87ms/step - accuracy: 0.9001 - loss: 0.3236

139/573 ━━━━━━━━━━━━━━━━━━━━ 37s 87ms/step - accuracy: 0.8999 - loss: 0.3247

140/573 ━━━━━━━━━━━━━━━━━━━━ 37s 87ms/step - accuracy: 0.9006 - loss: 0.3227

141/573 ━━━━━━━━━━━━━━━━━━━━ 37s 87ms/step - accuracy: 0.9009 - loss: 0.3219

142/573 ━━━━━━━━━━━━━━━━━━━━ 37s 87ms/step - accuracy: 0.9012 - loss: 0.3212

143/573 ━━━━━━━━━━━━━━━━━━━━ 37s 87ms/step - accuracy: 0.9010 - loss: 0.3215

144/573 ━━━━━━━━━━━━━━━━━━━━ 37s 87ms/step - accuracy: 0.9015 - loss: 0.3200

145/573 ━━━━━━━━━━━━━━━━━━━━ 37s 87ms/step - accuracy: 0.9015 - loss: 0.3204

146/573 ━━━━━━━━━━━━━━━━━━━━ 37s 87ms/step - accuracy: 0.9015 - loss: 0.3205

147/573 ━━━━━━━━━━━━━━━━━━━━ 36s 87ms/step - accuracy: 0.9011 - loss: 0.3213

148/573 ━━━━━━━━━━━━━━━━━━━━ 36s 87ms/step - accuracy: 0.9018 - loss: 0.3199

149/573 ━━━━━━━━━━━━━━━━━━━━ 36s 87ms/step - accuracy: 0.9018 - loss: 0.3198

150/573 ━━━━━━━━━━━━━━━━━━━━ 36s 87ms/step - accuracy: 0.9021 - loss: 0.3198

151/573 ━━━━━━━━━━━━━━━━━━━━ 36s 87ms/step - accuracy: 0.9021 - loss: 0.3189

152/573 ━━━━━━━━━━━━━━━━━━━━ 36s 87ms/step - accuracy: 0.9017 - loss: 0.3202

153/573 ━━━━━━━━━━━━━━━━━━━━ 36s 87ms/step - accuracy: 0.9017 - loss: 0.3200

154/573 ━━━━━━━━━━━━━━━━━━━━ 36s 87ms/step - accuracy: 0.9024 - loss: 0.3181

155/573 ━━━━━━━━━━━━━━━━━━━━ 36s 87ms/step - accuracy: 0.9026 - loss: 0.3176

156/573 ━━━━━━━━━━━━━━━━━━━━ 36s 87ms/step - accuracy: 0.9026 - loss: 0.3172

157/573 ━━━━━━━━━━━━━━━━━━━━ 36s 87ms/step - accuracy: 0.9031 - loss: 0.3157

158/573 ━━━━━━━━━━━━━━━━━━━━ 36s 87ms/step - accuracy: 0.9031 - loss: 0.3149

159/573 ━━━━━━━━━━━━━━━━━━━━ 36s 87ms/step - accuracy: 0.9031 - loss: 0.3148

160/573 ━━━━━━━━━━━━━━━━━━━━ 36s 87ms/step - accuracy: 0.9033 - loss: 0.3162

161/573 ━━━━━━━━━━━━━━━━━━━━ 35s 87ms/step - accuracy: 0.9031 - loss: 0.3182

162/573 ━━━━━━━━━━━━━━━━━━━━ 35s 87ms/step - accuracy: 0.9030 - loss: 0.3183

163/573 ━━━━━━━━━━━━━━━━━━━━ 35s 87ms/step - accuracy: 0.9036 - loss: 0.3168

164/573 ━━━━━━━━━━━━━━━━━━━━ 35s 87ms/step - accuracy: 0.9032 - loss: 0.3189

165/573 ━━━━━━━━━━━━━━━━━━━━ 35s 87ms/step - accuracy: 0.9034 - loss: 0.3181

166/573 ━━━━━━━━━━━━━━━━━━━━ 35s 87ms/step - accuracy: 0.9028 - loss: 0.3195

167/573 ━━━━━━━━━━━━━━━━━━━━ 35s 87ms/step - accuracy: 0.9031 - loss: 0.3183

168/573 ━━━━━━━━━━━━━━━━━━━━ 35s 87ms/step - accuracy: 0.9034 - loss: 0.3168

169/573 ━━━━━━━━━━━━━━━━━━━━ 35s 87ms/step - accuracy: 0.9035 - loss: 0.3176

170/573 ━━━━━━━━━━━━━━━━━━━━ 35s 87ms/step - accuracy: 0.9035 - loss: 0.3178

171/573 ━━━━━━━━━━━━━━━━━━━━ 35s 87ms/step - accuracy: 0.9039 - loss: 0.3167

172/573 ━━━━━━━━━━━━━━━━━━━━ 34s 87ms/step - accuracy: 0.9035 - loss: 0.3173

173/573 ━━━━━━━━━━━━━━━━━━━━ 34s 87ms/step - accuracy: 0.9035 - loss: 0.3179

174/573 ━━━━━━━━━━━━━━━━━━━━ 34s 87ms/step - accuracy: 0.9035 - loss: 0.3179

175/573 ━━━━━━━━━━━━━━━━━━━━ 34s 87ms/step - accuracy: 0.9034 - loss: 0.3179

176/573 ━━━━━━━━━━━━━━━━━━━━ 34s 87ms/step - accuracy: 0.9029 - loss: 0.3203

177/573 ━━━━━━━━━━━━━━━━━━━━ 34s 87ms/step - accuracy: 0.9027 - loss: 0.3202

178/573 ━━━━━━━━━━━━━━━━━━━━ 34s 87ms/step - accuracy: 0.9027 - loss: 0.3195

179/573 ━━━━━━━━━━━━━━━━━━━━ 34s 87ms/step - accuracy: 0.9027 - loss: 0.3191

180/573 ━━━━━━━━━━━━━━━━━━━━ 34s 87ms/step - accuracy: 0.9029 - loss: 0.3190

181/573 ━━━━━━━━━━━━━━━━━━━━ 34s 87ms/step - accuracy: 0.9031 - loss: 0.3187

182/573 ━━━━━━━━━━━━━━━━━━━━ 34s 87ms/step - accuracy: 0.9031 - loss: 0.3191

183/573 ━━━━━━━━━━━━━━━━━━━━ 33s 87ms/step - accuracy: 0.9033 - loss: 0.3185

184/573 ━━━━━━━━━━━━━━━━━━━━ 33s 87ms/step - accuracy: 0.9028 - loss: 0.3193

185/573 ━━━━━━━━━━━━━━━━━━━━ 33s 87ms/step - accuracy: 0.9030 - loss: 0.3187

186/573 ━━━━━━━━━━━━━━━━━━━━ 33s 87ms/step - accuracy: 0.9030 - loss: 0.3182

187/573 ━━━━━━━━━━━━━━━━━━━━ 33s 87ms/step - accuracy: 0.9032 - loss: 0.3169

188/573 ━━━━━━━━━━━━━━━━━━━━ 33s 87ms/step - accuracy: 0.9032 - loss: 0.3167

189/573 ━━━━━━━━━━━━━━━━━━━━ 33s 87ms/step - accuracy: 0.9034 - loss: 0.3169

190/573 ━━━━━━━━━━━━━━━━━━━━ 33s 87ms/step - accuracy: 0.9033 - loss: 0.3169

191/573 ━━━━━━━━━━━━━━━━━━━━ 33s 87ms/step - accuracy: 0.9033 - loss: 0.3164

192/573 ━━━━━━━━━━━━━━━━━━━━ 33s 87ms/step - accuracy: 0.9033 - loss: 0.3160

193/573 ━━━━━━━━━━━━━━━━━━━━ 33s 87ms/step - accuracy: 0.9036 - loss: 0.3153

194/573 ━━━━━━━━━━━━━━━━━━━━ 32s 87ms/step - accuracy: 0.9038 - loss: 0.3145

195/573 ━━━━━━━━━━━━━━━━━━━━ 32s 87ms/step - accuracy: 0.9038 - loss: 0.3146

196/573 ━━━━━━━━━━━━━━━━━━━━ 32s 87ms/step - accuracy: 0.9038 - loss: 0.3143

197/573 ━━━━━━━━━━━━━━━━━━━━ 32s 87ms/step - accuracy: 0.9034 - loss: 0.3157

198/573 ━━━━━━━━━━━━━━━━━━━━ 32s 87ms/step - accuracy: 0.9032 - loss: 0.3159

199/573 ━━━━━━━━━━━━━━━━━━━━ 32s 87ms/step - accuracy: 0.9031 - loss: 0.3160

200/573 ━━━━━━━━━━━━━━━━━━━━ 32s 87ms/step - accuracy: 0.9031 - loss: 0.3156

201/573 ━━━━━━━━━━━━━━━━━━━━ 32s 87ms/step - accuracy: 0.9031 - loss: 0.3160

202/573 ━━━━━━━━━━━━━━━━━━━━ 32s 87ms/step - accuracy: 0.9028 - loss: 0.3169

203/573 ━━━━━━━━━━━━━━━━━━━━ 32s 87ms/step - accuracy: 0.9030 - loss: 0.3163

204/573 ━━━━━━━━━━━━━━━━━━━━ 32s 87ms/step - accuracy: 0.9032 - loss: 0.3159

205/573 ━━━━━━━━━━━━━━━━━━━━ 31s 87ms/step - accuracy: 0.9035 - loss: 0.3161

206/573 ━━━━━━━━━━━━━━━━━━━━ 31s 87ms/step - accuracy: 0.9037 - loss: 0.3154

207/573 ━━━━━━━━━━━━━━━━━━━━ 31s 87ms/step - accuracy: 0.9034 - loss: 0.3163

208/573 ━━━━━━━━━━━━━━━━━━━━ 31s 87ms/step - accuracy: 0.9038 - loss: 0.3151

209/573 ━━━━━━━━━━━━━━━━━━━━ 31s 87ms/step - accuracy: 0.9037 - loss: 0.3153

210/573 ━━━━━━━━━━━━━━━━━━━━ 31s 87ms/step - accuracy: 0.9031 - loss: 0.3176

211/573 ━━━━━━━━━━━━━━━━━━━━ 31s 87ms/step - accuracy: 0.9027 - loss: 0.3181

212/573 ━━━━━━━━━━━━━━━━━━━━ 31s 87ms/step - accuracy: 0.9030 - loss: 0.3170

213/573 ━━━━━━━━━━━━━━━━━━━━ 31s 87ms/step - accuracy: 0.9030 - loss: 0.3167

214/573 ━━━━━━━━━━━━━━━━━━━━ 31s 87ms/step - accuracy: 0.9030 - loss: 0.3163

215/573 ━━━━━━━━━━━━━━━━━━━━ 31s 87ms/step - accuracy: 0.9029 - loss: 0.3166

216/573 ━━━━━━━━━━━━━━━━━━━━ 31s 87ms/step - accuracy: 0.9029 - loss: 0.3160

217/573 ━━━━━━━━━━━━━━━━━━━━ 31s 87ms/step - accuracy: 0.9028 - loss: 0.3156

218/573 ━━━━━━━━━━━━━━━━━━━━ 30s 87ms/step - accuracy: 0.9028 - loss: 0.3152

219/573 ━━━━━━━━━━━━━━━━━━━━ 30s 87ms/step - accuracy: 0.9027 - loss: 0.3151

220/573 ━━━━━━━━━━━━━━━━━━━━ 30s 87ms/step - accuracy: 0.9030 - loss: 0.3141

221/573 ━━━━━━━━━━━━━━━━━━━━ 30s 87ms/step - accuracy: 0.9028 - loss: 0.3147

222/573 ━━━━━━━━━━━━━━━━━━━━ 30s 87ms/step - accuracy: 0.9029 - loss: 0.3142

223/573 ━━━━━━━━━━━━━━━━━━━━ 30s 87ms/step - accuracy: 0.9026 - loss: 0.3149

224/573 ━━━━━━━━━━━━━━━━━━━━ 30s 87ms/step - accuracy: 0.9025 - loss: 0.3151

225/573 ━━━━━━━━━━━━━━━━━━━━ 30s 87ms/step - accuracy: 0.9025 - loss: 0.3148

226/573 ━━━━━━━━━━━━━━━━━━━━ 30s 87ms/step - accuracy: 0.9024 - loss: 0.3152

227/573 ━━━━━━━━━━━━━━━━━━━━ 30s 87ms/step - accuracy: 0.9025 - loss: 0.3145

228/573 ━━━━━━━━━━━━━━━━━━━━ 30s 87ms/step - accuracy: 0.9025 - loss: 0.3139

229/573 ━━━━━━━━━━━━━━━━━━━━ 29s 87ms/step - accuracy: 0.9027 - loss: 0.3134

230/573 ━━━━━━━━━━━━━━━━━━━━ 29s 87ms/step - accuracy: 0.9027 - loss: 0.3145

231/573 ━━━━━━━━━━━━━━━━━━━━ 29s 87ms/step - accuracy: 0.9029 - loss: 0.3140

232/573 ━━━━━━━━━━━━━━━━━━━━ 29s 87ms/step - accuracy: 0.9030 - loss: 0.3130

233/573 ━━━━━━━━━━━━━━━━━━━━ 29s 87ms/step - accuracy: 0.9032 - loss: 0.3125

234/573 ━━━━━━━━━━━━━━━━━━━━ 29s 87ms/step - accuracy: 0.9032 - loss: 0.3130

235/573 ━━━━━━━━━━━━━━━━━━━━ 29s 87ms/step - accuracy: 0.9034 - loss: 0.3120

236/573 ━━━━━━━━━━━━━━━━━━━━ 29s 87ms/step - accuracy: 0.9033 - loss: 0.3116

237/573 ━━━━━━━━━━━━━━━━━━━━ 29s 87ms/step - accuracy: 0.9032 - loss: 0.3117

238/573 ━━━━━━━━━━━━━━━━━━━━ 29s 87ms/step - accuracy: 0.9034 - loss: 0.3115

239/573 ━━━━━━━━━━━━━━━━━━━━ 29s 87ms/step - accuracy: 0.9034 - loss: 0.3108

240/573 ━━━━━━━━━━━━━━━━━━━━ 29s 87ms/step - accuracy: 0.9035 - loss: 0.3101

241/573 ━━━━━━━━━━━━━━━━━━━━ 29s 88ms/step - accuracy: 0.9035 - loss: 0.3099

242/573 ━━━━━━━━━━━━━━━━━━━━ 29s 88ms/step - accuracy: 0.9039 - loss: 0.3090

243/573 ━━━━━━━━━━━━━━━━━━━━ 28s 88ms/step - accuracy: 0.9039 - loss: 0.3093

244/573 ━━━━━━━━━━━━━━━━━━━━ 28s 88ms/step - accuracy: 0.9038 - loss: 0.3099

245/573 ━━━━━━━━━━━━━━━━━━━━ 28s 88ms/step - accuracy: 0.9039 - loss: 0.3100

246/573 ━━━━━━━━━━━━━━━━━━━━ 28s 88ms/step - accuracy: 0.9041 - loss: 0.3096

247/573 ━━━━━━━━━━━━━━━━━━━━ 28s 88ms/step - accuracy: 0.9036 - loss: 0.3105

248/573 ━━━━━━━━━━━━━━━━━━━━ 28s 88ms/step - accuracy: 0.9036 - loss: 0.3105

249/573 ━━━━━━━━━━━━━━━━━━━━ 28s 88ms/step - accuracy: 0.9032 - loss: 0.3116

250/573 ━━━━━━━━━━━━━━━━━━━━ 28s 88ms/step - accuracy: 0.9034 - loss: 0.3116

251/573 ━━━━━━━━━━━━━━━━━━━━ 28s 88ms/step - accuracy: 0.9035 - loss: 0.3115

252/573 ━━━━━━━━━━━━━━━━━━━━ 28s 87ms/step - accuracy: 0.9033 - loss: 0.3120

253/573 ━━━━━━━━━━━━━━━━━━━━ 27s 87ms/step - accuracy: 0.9036 - loss: 0.3111

254/573 ━━━━━━━━━━━━━━━━━━━━ 27s 87ms/step - accuracy: 0.9037 - loss: 0.3108

255/573 ━━━━━━━━━━━━━━━━━━━━ 27s 87ms/step - accuracy: 0.9037 - loss: 0.3117

256/573 ━━━━━━━━━━━━━━━━━━━━ 27s 87ms/step - accuracy: 0.9036 - loss: 0.3123

257/573 ━━━━━━━━━━━━━━━━━━━━ 27s 87ms/step - accuracy: 0.9037 - loss: 0.3122

258/573 ━━━━━━━━━━━━━━━━━━━━ 27s 87ms/step - accuracy: 0.9036 - loss: 0.3128

259/573 ━━━━━━━━━━━━━━━━━━━━ 27s 87ms/step - accuracy: 0.9038 - loss: 0.3119

260/573 ━━━━━━━━━━━━━━━━━━━━ 27s 87ms/step - accuracy: 0.9042 - loss: 0.3109

261/573 ━━━━━━━━━━━━━━━━━━━━ 27s 87ms/step - accuracy: 0.9042 - loss: 0.3105

262/573 ━━━━━━━━━━━━━━━━━━━━ 27s 87ms/step - accuracy: 0.9045 - loss: 0.3097

263/573 ━━━━━━━━━━━━━━━━━━━━ 27s 88ms/step - accuracy: 0.9045 - loss: 0.3096

264/573 ━━━━━━━━━━━━━━━━━━━━ 27s 88ms/step - accuracy: 0.9043 - loss: 0.3108

265/573 ━━━━━━━━━━━━━━━━━━━━ 26s 88ms/step - accuracy: 0.9045 - loss: 0.3102

266/573 ━━━━━━━━━━━━━━━━━━━━ 26s 88ms/step - accuracy: 0.9046 - loss: 0.3096

267/573 ━━━━━━━━━━━━━━━━━━━━ 26s 88ms/step - accuracy: 0.9046 - loss: 0.3095

268/573 ━━━━━━━━━━━━━━━━━━━━ 26s 88ms/step - accuracy: 0.9045 - loss: 0.3104

269/573 ━━━━━━━━━━━━━━━━━━━━ 26s 88ms/step - accuracy: 0.9045 - loss: 0.3110

270/573 ━━━━━━━━━━━━━━━━━━━━ 26s 88ms/step - accuracy: 0.9046 - loss: 0.3105

271/573 ━━━━━━━━━━━━━━━━━━━━ 26s 88ms/step - accuracy: 0.9043 - loss: 0.3111

272/573 ━━━━━━━━━━━━━━━━━━━━ 26s 88ms/step - accuracy: 0.9043 - loss: 0.3110

273/573 ━━━━━━━━━━━━━━━━━━━━ 26s 88ms/step - accuracy: 0.9044 - loss: 0.3110

274/573 ━━━━━━━━━━━━━━━━━━━━ 26s 88ms/step - accuracy: 0.9043 - loss: 0.3109

275/573 ━━━━━━━━━━━━━━━━━━━━ 26s 88ms/step - accuracy: 0.9044 - loss: 0.3110

276/573 ━━━━━━━━━━━━━━━━━━━━ 26s 88ms/step - accuracy: 0.9044 - loss: 0.3121

277/573 ━━━━━━━━━━━━━━━━━━━━ 25s 88ms/step - accuracy: 0.9043 - loss: 0.3121

278/573 ━━━━━━━━━━━━━━━━━━━━ 25s 88ms/step - accuracy: 0.9044 - loss: 0.3117

279/573 ━━━━━━━━━━━━━━━━━━━━ 25s 88ms/step - accuracy: 0.9046 - loss: 0.3122

280/573 ━━━━━━━━━━━━━━━━━━━━ 25s 88ms/step - accuracy: 0.9043 - loss: 0.3126

281/573 ━━━━━━━━━━━━━━━━━━━━ 25s 88ms/step - accuracy: 0.9045 - loss: 0.3118

282/573 ━━━━━━━━━━━━━━━━━━━━ 25s 88ms/step - accuracy: 0.9048 - loss: 0.3108

283/573 ━━━━━━━━━━━━━━━━━━━━ 25s 88ms/step - accuracy: 0.9048 - loss: 0.3107

284/573 ━━━━━━━━━━━━━━━━━━━━ 25s 88ms/step - accuracy: 0.9047 - loss: 0.3109

285/573 ━━━━━━━━━━━━━━━━━━━━ 25s 88ms/step - accuracy: 0.9049 - loss: 0.3109

286/573 ━━━━━━━━━━━━━━━━━━━━ 25s 88ms/step - accuracy: 0.9047 - loss: 0.3114

287/573 ━━━━━━━━━━━━━━━━━━━━ 25s 88ms/step - accuracy: 0.9044 - loss: 0.3119

288/573 ━━━━━━━━━━━━━━━━━━━━ 25s 88ms/step - accuracy: 0.9043 - loss: 0.3123

289/573 ━━━━━━━━━━━━━━━━━━━━ 24s 88ms/step - accuracy: 0.9040 - loss: 0.3140

290/573 ━━━━━━━━━━━━━━━━━━━━ 24s 88ms/step - accuracy: 0.9040 - loss: 0.3141

291/573 ━━━━━━━━━━━━━━━━━━━━ 24s 88ms/step - accuracy: 0.9041 - loss: 0.3135

292/573 ━━━━━━━━━━━━━━━━━━━━ 24s 88ms/step - accuracy: 0.9042 - loss: 0.3127

293/573 ━━━━━━━━━━━━━━━━━━━━ 24s 88ms/step - accuracy: 0.9040 - loss: 0.3139

294/573 ━━━━━━━━━━━━━━━━━━━━ 24s 88ms/step - accuracy: 0.9040 - loss: 0.3134

295/573 ━━━━━━━━━━━━━━━━━━━━ 24s 88ms/step - accuracy: 0.9042 - loss: 0.3132

296/573 ━━━━━━━━━━━━━━━━━━━━ 24s 88ms/step - accuracy: 0.9040 - loss: 0.3142

297/573 ━━━━━━━━━━━━━━━━━━━━ 24s 88ms/step - accuracy: 0.9038 - loss: 0.3145

298/573 ━━━━━━━━━━━━━━━━━━━━ 24s 88ms/step - accuracy: 0.9040 - loss: 0.3138

299/573 ━━━━━━━━━━━━━━━━━━━━ 24s 88ms/step - accuracy: 0.9043 - loss: 0.3134

300/573 ━━━━━━━━━━━━━━━━━━━━ 24s 88ms/step - accuracy: 0.9044 - loss: 0.3127

301/573 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - accuracy: 0.9043 - loss: 0.3129

302/573 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - accuracy: 0.9044 - loss: 0.3125

303/573 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - accuracy: 0.9047 - loss: 0.3116

304/573 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - accuracy: 0.9047 - loss: 0.3116

305/573 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - accuracy: 0.9046 - loss: 0.3113

306/573 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - accuracy: 0.9044 - loss: 0.3114

307/573 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - accuracy: 0.9045 - loss: 0.3115

308/573 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - accuracy: 0.9045 - loss: 0.3115

309/573 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - accuracy: 0.9046 - loss: 0.3111

310/573 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - accuracy: 0.9044 - loss: 0.3119

311/573 ━━━━━━━━━━━━━━━━━━━━ 23s 88ms/step - accuracy: 0.9045 - loss: 0.3120

312/573 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - accuracy: 0.9046 - loss: 0.3115

313/573 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - accuracy: 0.9044 - loss: 0.3117

314/573 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - accuracy: 0.9046 - loss: 0.3119

315/573 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - accuracy: 0.9046 - loss: 0.3114

316/573 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - accuracy: 0.9045 - loss: 0.3111

317/573 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - accuracy: 0.9048 - loss: 0.3103

318/573 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - accuracy: 0.9048 - loss: 0.3102

319/573 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - accuracy: 0.9050 - loss: 0.3097

320/573 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - accuracy: 0.9051 - loss: 0.3094

321/573 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - accuracy: 0.9052 - loss: 0.3092

322/573 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - accuracy: 0.9052 - loss: 0.3096

323/573 ━━━━━━━━━━━━━━━━━━━━ 22s 88ms/step - accuracy: 0.9049 - loss: 0.3107

324/573 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - accuracy: 0.9048 - loss: 0.3114

325/573 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - accuracy: 0.9050 - loss: 0.3111

326/573 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - accuracy: 0.9053 - loss: 0.3102

327/573 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - accuracy: 0.9051 - loss: 0.3111

328/573 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - accuracy: 0.9049 - loss: 0.3116

329/573 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - accuracy: 0.9045 - loss: 0.3134

330/573 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - accuracy: 0.9045 - loss: 0.3134

331/573 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - accuracy: 0.9046 - loss: 0.3129

332/573 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - accuracy: 0.9046 - loss: 0.3135

333/573 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - accuracy: 0.9048 - loss: 0.3128

334/573 ━━━━━━━━━━━━━━━━━━━━ 21s 88ms/step - accuracy: 0.9049 - loss: 0.3127

335/573 ━━━━━━━━━━━━━━━━━━━━ 20s 88ms/step - accuracy: 0.9049 - loss: 0.3124

336/573 ━━━━━━━━━━━━━━━━━━━━ 20s 88ms/step - accuracy: 0.9049 - loss: 0.3124

337/573 ━━━━━━━━━━━━━━━━━━━━ 20s 88ms/step - accuracy: 0.9049 - loss: 0.3124

338/573 ━━━━━━━━━━━━━━━━━━━━ 20s 88ms/step - accuracy: 0.9049 - loss: 0.3124

339/573 ━━━━━━━━━━━━━━━━━━━━ 20s 88ms/step - accuracy: 0.9049 - loss: 0.3127

340/573 ━━━━━━━━━━━━━━━━━━━━ 20s 88ms/step - accuracy: 0.9051 - loss: 0.3119

341/573 ━━━━━━━━━━━━━━━━━━━━ 20s 88ms/step - accuracy: 0.9051 - loss: 0.3119

342/573 ━━━━━━━━━━━━━━━━━━━━ 20s 88ms/step - accuracy: 0.9050 - loss: 0.3121

343/573 ━━━━━━━━━━━━━━━━━━━━ 20s 88ms/step - accuracy: 0.9051 - loss: 0.3124

344/573 ━━━━━━━━━━━━━━━━━━━━ 20s 88ms/step - accuracy: 0.9052 - loss: 0.3125

345/573 ━━━━━━━━━━━━━━━━━━━━ 20s 88ms/step - accuracy: 0.9052 - loss: 0.3122

346/573 ━━━━━━━━━━━━━━━━━━━━ 20s 88ms/step - accuracy: 0.9051 - loss: 0.3124

347/573 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - accuracy: 0.9052 - loss: 0.3120

348/573 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - accuracy: 0.9053 - loss: 0.3116

349/573 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - accuracy: 0.9053 - loss: 0.3116

350/573 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - accuracy: 0.9054 - loss: 0.3111

351/573 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - accuracy: 0.9051 - loss: 0.3122

352/573 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - accuracy: 0.9052 - loss: 0.3118

353/573 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - accuracy: 0.9052 - loss: 0.3117

354/573 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - accuracy: 0.9052 - loss: 0.3114

355/573 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - accuracy: 0.9049 - loss: 0.3122

356/573 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - accuracy: 0.9048 - loss: 0.3127

357/573 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - accuracy: 0.9047 - loss: 0.3129

358/573 ━━━━━━━━━━━━━━━━━━━━ 19s 88ms/step - accuracy: 0.9048 - loss: 0.3126

359/573 ━━━━━━━━━━━━━━━━━━━━ 18s 88ms/step - accuracy: 0.9048 - loss: 0.3123

360/573 ━━━━━━━━━━━━━━━━━━━━ 18s 88ms/step - accuracy: 0.9046 - loss: 0.3124

361/573 ━━━━━━━━━━━━━━━━━━━━ 18s 88ms/step - accuracy: 0.9046 - loss: 0.3119

362/573 ━━━━━━━━━━━━━━━━━━━━ 18s 88ms/step - accuracy: 0.9044 - loss: 0.3122

363/573 ━━━━━━━━━━━━━━━━━━━━ 18s 88ms/step - accuracy: 0.9045 - loss: 0.3125

364/573 ━━━━━━━━━━━━━━━━━━━━ 18s 88ms/step - accuracy: 0.9045 - loss: 0.3124

365/573 ━━━━━━━━━━━━━━━━━━━━ 18s 88ms/step - accuracy: 0.9048 - loss: 0.3118

366/573 ━━━━━━━━━━━━━━━━━━━━ 18s 88ms/step - accuracy: 0.9049 - loss: 0.3114

367/573 ━━━━━━━━━━━━━━━━━━━━ 18s 88ms/step - accuracy: 0.9051 - loss: 0.3113

368/573 ━━━━━━━━━━━━━━━━━━━━ 18s 88ms/step - accuracy: 0.9050 - loss: 0.3115

369/573 ━━━━━━━━━━━━━━━━━━━━ 18s 88ms/step - accuracy: 0.9050 - loss: 0.3111

370/573 ━━━━━━━━━━━━━━━━━━━━ 17s 88ms/step - accuracy: 0.9048 - loss: 0.3117

371/573 ━━━━━━━━━━━━━━━━━━━━ 17s 88ms/step - accuracy: 0.9048 - loss: 0.3120

372/573 ━━━━━━━━━━━━━━━━━━━━ 17s 88ms/step - accuracy: 0.9049 - loss: 0.3119

373/573 ━━━━━━━━━━━━━━━━━━━━ 17s 88ms/step - accuracy: 0.9050 - loss: 0.3116

374/573 ━━━━━━━━━━━━━━━━━━━━ 17s 88ms/step - accuracy: 0.9048 - loss: 0.3117

375/573 ━━━━━━━━━━━━━━━━━━━━ 17s 88ms/step - accuracy: 0.9044 - loss: 0.3134

376/573 ━━━━━━━━━━━━━━━━━━━━ 17s 88ms/step - accuracy: 0.9045 - loss: 0.3132

377/573 ━━━━━━━━━━━━━━━━━━━━ 17s 88ms/step - accuracy: 0.9039 - loss: 0.3138

378/573 ━━━━━━━━━━━━━━━━━━━━ 17s 88ms/step - accuracy: 0.9039 - loss: 0.3138

379/573 ━━━━━━━━━━━━━━━━━━━━ 17s 88ms/step - accuracy: 0.9037 - loss: 0.3140

380/573 ━━━━━━━━━━━━━━━━━━━━ 17s 88ms/step - accuracy: 0.9039 - loss: 0.3136

381/573 ━━━━━━━━━━━━━━━━━━━━ 16s 88ms/step - accuracy: 0.9040 - loss: 0.3130

382/573 ━━━━━━━━━━━━━━━━━━━━ 16s 88ms/step - accuracy: 0.9041 - loss: 0.3129

383/573 ━━━━━━━━━━━━━━━━━━━━ 16s 88ms/step - accuracy: 0.9043 - loss: 0.3124

384/573 ━━━━━━━━━━━━━━━━━━━━ 16s 88ms/step - accuracy: 0.9043 - loss: 0.3133

385/573 ━━━━━━━━━━━━━━━━━━━━ 16s 89ms/step - accuracy: 0.9041 - loss: 0.3137

386/573 ━━━━━━━━━━━━━━━━━━━━ 16s 89ms/step - accuracy: 0.9040 - loss: 0.3137

387/573 ━━━━━━━━━━━━━━━━━━━━ 16s 89ms/step - accuracy: 0.9036 - loss: 0.3155

388/573 ━━━━━━━━━━━━━━━━━━━━ 16s 89ms/step - accuracy: 0.9037 - loss: 0.3149

389/573 ━━━━━━━━━━━━━━━━━━━━ 16s 89ms/step - accuracy: 0.9035 - loss: 0.3156

390/573 ━━━━━━━━━━━━━━━━━━━━ 16s 89ms/step - accuracy: 0.9032 - loss: 0.3163

391/573 ━━━━━━━━━━━━━━━━━━━━ 16s 89ms/step - accuracy: 0.9032 - loss: 0.3169

392/573 ━━━━━━━━━━━━━━━━━━━━ 16s 89ms/step - accuracy: 0.9032 - loss: 0.3167

393/573 ━━━━━━━━━━━━━━━━━━━━ 15s 89ms/step - accuracy: 0.9032 - loss: 0.3164

394/573 ━━━━━━━━━━━━━━━━━━━━ 15s 89ms/step - accuracy: 0.9030 - loss: 0.3171

395/573 ━━━━━━━━━━━━━━━━━━━━ 15s 89ms/step - accuracy: 0.9032 - loss: 0.3166

396/573 ━━━━━━━━━━━━━━━━━━━━ 15s 89ms/step - accuracy: 0.9032 - loss: 0.3162

397/573 ━━━━━━━━━━━━━━━━━━━━ 15s 89ms/step - accuracy: 0.9033 - loss: 0.3163

398/573 ━━━━━━━━━━━━━━━━━━━━ 15s 89ms/step - accuracy: 0.9034 - loss: 0.3159

399/573 ━━━━━━━━━━━━━━━━━━━━ 15s 89ms/step - accuracy: 0.9033 - loss: 0.3162

400/573 ━━━━━━━━━━━━━━━━━━━━ 15s 89ms/step - accuracy: 0.9031 - loss: 0.3167

401/573 ━━━━━━━━━━━━━━━━━━━━ 15s 89ms/step - accuracy: 0.9031 - loss: 0.3164

402/573 ━━━━━━━━━━━━━━━━━━━━ 15s 89ms/step - accuracy: 0.9032 - loss: 0.3164

403/573 ━━━━━━━━━━━━━━━━━━━━ 15s 89ms/step - accuracy: 0.9032 - loss: 0.3162

404/573 ━━━━━━━━━━━━━━━━━━━━ 14s 89ms/step - accuracy: 0.9032 - loss: 0.3160

405/573 ━━━━━━━━━━━━━━━━━━━━ 14s 89ms/step - accuracy: 0.9034 - loss: 0.3161

406/573 ━━━━━━━━━━━━━━━━━━━━ 14s 89ms/step - accuracy: 0.9033 - loss: 0.3162

407/573 ━━━━━━━━━━━━━━━━━━━━ 14s 89ms/step - accuracy: 0.9033 - loss: 0.3170

408/573 ━━━━━━━━━━━━━━━━━━━━ 14s 89ms/step - accuracy: 0.9035 - loss: 0.3165

409/573 ━━━━━━━━━━━━━━━━━━━━ 14s 89ms/step - accuracy: 0.9035 - loss: 0.3164

410/573 ━━━━━━━━━━━━━━━━━━━━ 14s 89ms/step - accuracy: 0.9033 - loss: 0.3167

411/573 ━━━━━━━━━━━━━━━━━━━━ 14s 89ms/step - accuracy: 0.9033 - loss: 0.3164

412/573 ━━━━━━━━━━━━━━━━━━━━ 14s 89ms/step - accuracy: 0.9030 - loss: 0.3169

413/573 ━━━━━━━━━━━━━━━━━━━━ 14s 89ms/step - accuracy: 0.9031 - loss: 0.3166

414/573 ━━━━━━━━━━━━━━━━━━━━ 14s 89ms/step - accuracy: 0.9032 - loss: 0.3166

415/573 ━━━━━━━━━━━━━━━━━━━━ 13s 89ms/step - accuracy: 0.9031 - loss: 0.3169

416/573 ━━━━━━━━━━━━━━━━━━━━ 13s 89ms/step - accuracy: 0.9029 - loss: 0.3175

417/573 ━━━━━━━━━━━━━━━━━━━━ 13s 89ms/step - accuracy: 0.9030 - loss: 0.3177

418/573 ━━━━━━━━━━━━━━━━━━━━ 13s 88ms/step - accuracy: 0.9032 - loss: 0.3172

419/573 ━━━━━━━━━━━━━━━━━━━━ 13s 88ms/step - accuracy: 0.9031 - loss: 0.3174

420/573 ━━━━━━━━━━━━━━━━━━━━ 13s 88ms/step - accuracy: 0.9029 - loss: 0.3178

421/573 ━━━━━━━━━━━━━━━━━━━━ 13s 88ms/step - accuracy: 0.9028 - loss: 0.3180

422/573 ━━━━━━━━━━━━━━━━━━━━ 13s 88ms/step - accuracy: 0.9028 - loss: 0.3178

423/573 ━━━━━━━━━━━━━━━━━━━━ 13s 88ms/step - accuracy: 0.9028 - loss: 0.3180

424/573 ━━━━━━━━━━━━━━━━━━━━ 13s 88ms/step - accuracy: 0.9029 - loss: 0.3185

425/573 ━━━━━━━━━━━━━━━━━━━━ 13s 88ms/step - accuracy: 0.9031 - loss: 0.3179

426/573 ━━━━━━━━━━━━━━━━━━━━ 12s 88ms/step - accuracy: 0.9032 - loss: 0.3175

427/573 ━━━━━━━━━━━━━━━━━━━━ 12s 88ms/step - accuracy: 0.9032 - loss: 0.3174

428/573 ━━━━━━━━━━━━━━━━━━━━ 12s 88ms/step - accuracy: 0.9033 - loss: 0.3169

429/573 ━━━━━━━━━━━━━━━━━━━━ 12s 88ms/step - accuracy: 0.9033 - loss: 0.3165

430/573 ━━━━━━━━━━━━━━━━━━━━ 12s 88ms/step - accuracy: 0.9031 - loss: 0.3169

431/573 ━━━━━━━━━━━━━━━━━━━━ 12s 88ms/step - accuracy: 0.9032 - loss: 0.3166

432/573 ━━━━━━━━━━━━━━━━━━━━ 12s 88ms/step - accuracy: 0.9032 - loss: 0.3165

433/573 ━━━━━━━━━━━━━━━━━━━━ 12s 88ms/step - accuracy: 0.9029 - loss: 0.3172

434/573 ━━━━━━━━━━━━━━━━━━━━ 12s 88ms/step - accuracy: 0.9031 - loss: 0.3169

435/573 ━━━━━━━━━━━━━━━━━━━━ 12s 88ms/step - accuracy: 0.9031 - loss: 0.3170

436/573 ━━━━━━━━━━━━━━━━━━━━ 12s 88ms/step - accuracy: 0.9032 - loss: 0.3168

437/573 ━━━━━━━━━━━━━━━━━━━━ 12s 88ms/step - accuracy: 0.9034 - loss: 0.3163

438/573 ━━━━━━━━━━━━━━━━━━━━ 11s 89ms/step - accuracy: 0.9035 - loss: 0.3158

439/573 ━━━━━━━━━━━━━━━━━━━━ 11s 89ms/step - accuracy: 0.9036 - loss: 0.3156

440/573 ━━━━━━━━━━━━━━━━━━━━ 11s 89ms/step - accuracy: 0.9037 - loss: 0.3152

441/573 ━━━━━━━━━━━━━━━━━━━━ 11s 89ms/step - accuracy: 0.9036 - loss: 0.3156

442/573 ━━━━━━━━━━━━━━━━━━━━ 11s 89ms/step - accuracy: 0.9037 - loss: 0.3153

443/573 ━━━━━━━━━━━━━━━━━━━━ 11s 89ms/step - accuracy: 0.9038 - loss: 0.3149

444/573 ━━━━━━━━━━━━━━━━━━━━ 11s 89ms/step - accuracy: 0.9038 - loss: 0.3155

445/573 ━━━━━━━━━━━━━━━━━━━━ 11s 89ms/step - accuracy: 0.9039 - loss: 0.3157

446/573 ━━━━━━━━━━━━━━━━━━━━ 11s 88ms/step - accuracy: 0.9041 - loss: 0.3150

447/573 ━━━━━━━━━━━━━━━━━━━━ 11s 88ms/step - accuracy: 0.9041 - loss: 0.3148

448/573 ━━━━━━━━━━━━━━━━━━━━ 11s 88ms/step - accuracy: 0.9042 - loss: 0.3149

449/573 ━━━━━━━━━━━━━━━━━━━━ 10s 88ms/step - accuracy: 0.9042 - loss: 0.3149

450/573 ━━━━━━━━━━━━━━━━━━━━ 10s 88ms/step - accuracy: 0.9042 - loss: 0.3147

451/573 ━━━━━━━━━━━━━━━━━━━━ 10s 88ms/step - accuracy: 0.9041 - loss: 0.3148

452/573 ━━━━━━━━━━━━━━━━━━━━ 10s 88ms/step - accuracy: 0.9041 - loss: 0.3145

453/573 ━━━━━━━━━━━━━━━━━━━━ 10s 88ms/step - accuracy: 0.9042 - loss: 0.3144

454/573 ━━━━━━━━━━━━━━━━━━━━ 10s 88ms/step - accuracy: 0.9040 - loss: 0.3153

455/573 ━━━━━━━━━━━━━━━━━━━━ 10s 88ms/step - accuracy: 0.9041 - loss: 0.3152

456/573 ━━━━━━━━━━━━━━━━━━━━ 10s 88ms/step - accuracy: 0.9040 - loss: 0.3154

457/573 ━━━━━━━━━━━━━━━━━━━━ 10s 88ms/step - accuracy: 0.9040 - loss: 0.3153

458/573 ━━━━━━━━━━━━━━━━━━━━ 10s 88ms/step - accuracy: 0.9039 - loss: 0.3156

459/573 ━━━━━━━━━━━━━━━━━━━━ 10s 88ms/step - accuracy: 0.9040 - loss: 0.3152

460/573 ━━━━━━━━━━━━━━━━━━━━ 9s 88ms/step - accuracy: 0.9042 - loss: 0.3146

461/573 ━━━━━━━━━━━━━━━━━━━━ 9s 88ms/step - accuracy: 0.9042 - loss: 0.3147

462/573 ━━━━━━━━━━━━━━━━━━━━ 9s 88ms/step - accuracy: 0.9043 - loss: 0.3146

463/573 ━━━━━━━━━━━━━━━━━━━━ 9s 88ms/step - accuracy: 0.9045 - loss: 0.3140

464/573 ━━━━━━━━━━━━━━━━━━━━ 9s 88ms/step - accuracy: 0.9045 - loss: 0.3140

465/573 ━━━━━━━━━━━━━━━━━━━━ 9s 88ms/step - accuracy: 0.9047 - loss: 0.3135

466/573 ━━━━━━━━━━━━━━━━━━━━ 9s 88ms/step - accuracy: 0.9046 - loss: 0.3141

467/573 ━━━━━━━━━━━━━━━━━━━━ 9s 88ms/step - accuracy: 0.9047 - loss: 0.3138

468/573 ━━━━━━━━━━━━━━━━━━━━ 9s 88ms/step - accuracy: 0.9046 - loss: 0.3138

469/573 ━━━━━━━━━━━━━━━━━━━━ 9s 88ms/step - accuracy: 0.9046 - loss: 0.3141

470/573 ━━━━━━━━━━━━━━━━━━━━ 9s 88ms/step - accuracy: 0.9045 - loss: 0.3150

471/573 ━━━━━━━━━━━━━━━━━━━━ 9s 88ms/step - accuracy: 0.9047 - loss: 0.3144

472/573 ━━━━━━━━━━━━━━━━━━━━ 8s 88ms/step - accuracy: 0.9047 - loss: 0.3146

473/573 ━━━━━━━━━━━━━━━━━━━━ 8s 88ms/step - accuracy: 0.9047 - loss: 0.3147

474/573 ━━━━━━━━━━━━━━━━━━━━ 8s 88ms/step - accuracy: 0.9047 - loss: 0.3144

475/573 ━━━━━━━━━━━━━━━━━━━━ 8s 88ms/step - accuracy: 0.9047 - loss: 0.3140

476/573 ━━━━━━━━━━━━━━━━━━━━ 8s 88ms/step - accuracy: 0.9043 - loss: 0.3145

477/573 ━━━━━━━━━━━━━━━━━━━━ 8s 88ms/step - accuracy: 0.9043 - loss: 0.3143

478/573 ━━━━━━━━━━━━━━━━━━━━ 8s 88ms/step - accuracy: 0.9042 - loss: 0.3147

479/573 ━━━━━━━━━━━━━━━━━━━━ 8s 88ms/step - accuracy: 0.9040 - loss: 0.3149

480/573 ━━━━━━━━━━━━━━━━━━━━ 8s 88ms/step - accuracy: 0.9041 - loss: 0.3149

481/573 ━━━━━━━━━━━━━━━━━━━━ 8s 88ms/step - accuracy: 0.9042 - loss: 0.3148

482/573 ━━━━━━━━━━━━━━━━━━━━ 8s 88ms/step - accuracy: 0.9042 - loss: 0.3146

483/573 ━━━━━━━━━━━━━━━━━━━━ 7s 88ms/step - accuracy: 0.9044 - loss: 0.3145

484/573 ━━━━━━━━━━━━━━━━━━━━ 7s 88ms/step - accuracy: 0.9042 - loss: 0.3150

485/573 ━━━━━━━━━━━━━━━━━━━━ 7s 88ms/step - accuracy: 0.9043 - loss: 0.3147

486/573 ━━━━━━━━━━━━━━━━━━━━ 7s 88ms/step - accuracy: 0.9043 - loss: 0.3147

487/573 ━━━━━━━━━━━━━━━━━━━━ 7s 88ms/step - accuracy: 0.9044 - loss: 0.3144

488/573 ━━━━━━━━━━━━━━━━━━━━ 7s 88ms/step - accuracy: 0.9045 - loss: 0.3139

489/573 ━━━━━━━━━━━━━━━━━━━━ 7s 88ms/step - accuracy: 0.9044 - loss: 0.3142

490/573 ━━━━━━━━━━━━━━━━━━━━ 7s 88ms/step - accuracy: 0.9043 - loss: 0.3140

491/573 ━━━━━━━━━━━━━━━━━━━━ 7s 88ms/step - accuracy: 0.9045 - loss: 0.3136

492/573 ━━━━━━━━━━━━━━━━━━━━ 7s 88ms/step - accuracy: 0.9044 - loss: 0.3138

493/573 ━━━━━━━━━━━━━━━━━━━━ 7s 88ms/step - accuracy: 0.9045 - loss: 0.3136

494/573 ━━━━━━━━━━━━━━━━━━━━ 6s 88ms/step - accuracy: 0.9045 - loss: 0.3136

495/573 ━━━━━━━━━━━━━━━━━━━━ 6s 88ms/step - accuracy: 0.9044 - loss: 0.3139

496/573 ━━━━━━━━━━━━━━━━━━━━ 6s 88ms/step - accuracy: 0.9042 - loss: 0.3148

497/573 ━━━━━━━━━━━━━━━━━━━━ 6s 88ms/step - accuracy: 0.9042 - loss: 0.3151

498/573 ━━━━━━━━━━━━━━━━━━━━ 6s 88ms/step - accuracy: 0.9043 - loss: 0.3152

499/573 ━━━━━━━━━━━━━━━━━━━━ 6s 88ms/step - accuracy: 0.9042 - loss: 0.3160

500/573 ━━━━━━━━━━━━━━━━━━━━ 6s 88ms/step - accuracy: 0.9042 - loss: 0.3162

501/573 ━━━━━━━━━━━━━━━━━━━━ 6s 88ms/step - accuracy: 0.9041 - loss: 0.3164

502/573 ━━━━━━━━━━━━━━━━━━━━ 6s 88ms/step - accuracy: 0.9043 - loss: 0.3159

503/573 ━━━━━━━━━━━━━━━━━━━━ 6s 88ms/step - accuracy: 0.9043 - loss: 0.3165

504/573 ━━━━━━━━━━━━━━━━━━━━ 6s 88ms/step - accuracy: 0.9043 - loss: 0.3164

505/573 ━━━━━━━━━━━━━━━━━━━━ 6s 88ms/step - accuracy: 0.9045 - loss: 0.3160

506/573 ━━━━━━━━━━━━━━━━━━━━ 5s 88ms/step - accuracy: 0.9045 - loss: 0.3159

507/573 ━━━━━━━━━━━━━━━━━━━━ 5s 88ms/step - accuracy: 0.9046 - loss: 0.3159

508/573 ━━━━━━━━━━━━━━━━━━━━ 5s 88ms/step - accuracy: 0.9043 - loss: 0.3165

509/573 ━━━━━━━━━━━━━━━━━━━━ 5s 88ms/step - accuracy: 0.9045 - loss: 0.3161

510/573 ━━━━━━━━━━━━━━━━━━━━ 5s 88ms/step - accuracy: 0.9045 - loss: 0.3162

511/573 ━━━━━━━━━━━━━━━━━━━━ 5s 88ms/step - accuracy: 0.9045 - loss: 0.3163

512/573 ━━━━━━━━━━━━━━━━━━━━ 5s 88ms/step - accuracy: 0.9045 - loss: 0.3166

513/573 ━━━━━━━━━━━━━━━━━━━━ 5s 88ms/step - accuracy: 0.9044 - loss: 0.3167

514/573 ━━━━━━━━━━━━━━━━━━━━ 5s 88ms/step - accuracy: 0.9045 - loss: 0.3165

515/573 ━━━━━━━━━━━━━━━━━━━━ 5s 88ms/step - accuracy: 0.9046 - loss: 0.3163

516/573 ━━━━━━━━━━━━━━━━━━━━ 5s 88ms/step - accuracy: 0.9044 - loss: 0.3173

517/573 ━━━━━━━━━━━━━━━━━━━━ 4s 88ms/step - accuracy: 0.9043 - loss: 0.3178

518/573 ━━━━━━━━━━━━━━━━━━━━ 4s 88ms/step - accuracy: 0.9043 - loss: 0.3177

519/573 ━━━━━━━━━━━━━━━━━━━━ 4s 88ms/step - accuracy: 0.9042 - loss: 0.3176

520/573 ━━━━━━━━━━━━━━━━━━━━ 4s 88ms/step - accuracy: 0.9041 - loss: 0.3178

521/573 ━━━━━━━━━━━━━━━━━━━━ 4s 88ms/step - accuracy: 0.9038 - loss: 0.3181

522/573 ━━━━━━━━━━━━━━━━━━━━ 4s 88ms/step - accuracy: 0.9036 - loss: 0.3188

523/573 ━━━━━━━━━━━━━━━━━━━━ 4s 88ms/step - accuracy: 0.9034 - loss: 0.3193

524/573 ━━━━━━━━━━━━━━━━━━━━ 4s 88ms/step - accuracy: 0.9036 - loss: 0.3188

525/573 ━━━━━━━━━━━━━━━━━━━━ 4s 88ms/step - accuracy: 0.9036 - loss: 0.3187

526/573 ━━━━━━━━━━━━━━━━━━━━ 4s 88ms/step - accuracy: 0.9034 - loss: 0.3195

527/573 ━━━━━━━━━━━━━━━━━━━━ 4s 88ms/step - accuracy: 0.9035 - loss: 0.3193

528/573 ━━━━━━━━━━━━━━━━━━━━ 3s 88ms/step - accuracy: 0.9033 - loss: 0.3202

529/573 ━━━━━━━━━━━━━━━━━━━━ 3s 88ms/step - accuracy: 0.9034 - loss: 0.3199

530/573 ━━━━━━━━━━━━━━━━━━━━ 3s 88ms/step - accuracy: 0.9033 - loss: 0.3202

531/573 ━━━━━━━━━━━━━━━━━━━━ 3s 88ms/step - accuracy: 0.9034 - loss: 0.3203

532/573 ━━━━━━━━━━━━━━━━━━━━ 3s 88ms/step - accuracy: 0.9034 - loss: 0.3200

533/573 ━━━━━━━━━━━━━━━━━━━━ 3s 88ms/step - accuracy: 0.9035 - loss: 0.3196

534/573 ━━━━━━━━━━━━━━━━━━━━ 3s 88ms/step - accuracy: 0.9036 - loss: 0.3193

535/573 ━━━━━━━━━━━━━━━━━━━━ 3s 88ms/step - accuracy: 0.9035 - loss: 0.3193

536/573 ━━━━━━━━━━━━━━━━━━━━ 3s 88ms/step - accuracy: 0.9035 - loss: 0.3192

537/573 ━━━━━━━━━━━━━━━━━━━━ 3s 88ms/step - accuracy: 0.9036 - loss: 0.3189

538/573 ━━━━━━━━━━━━━━━━━━━━ 3s 88ms/step - accuracy: 0.9036 - loss: 0.3189

539/573 ━━━━━━━━━━━━━━━━━━━━ 2s 88ms/step - accuracy: 0.9036 - loss: 0.3188

540/573 ━━━━━━━━━━━━━━━━━━━━ 2s 88ms/step - accuracy: 0.9036 - loss: 0.3193

541/573 ━━━━━━━━━━━━━━━━━━━━ 2s 88ms/step - accuracy: 0.9036 - loss: 0.3190

542/573 ━━━━━━━━━━━━━━━━━━━━ 2s 88ms/step - accuracy: 0.9037 - loss: 0.3190

543/573 ━━━━━━━━━━━━━━━━━━━━ 2s 88ms/step - accuracy: 0.9037 - loss: 0.3196

544/573 ━━━━━━━━━━━━━━━━━━━━ 2s 88ms/step - accuracy: 0.9038 - loss: 0.3192

545/573 ━━━━━━━━━━━━━━━━━━━━ 2s 88ms/step - accuracy: 0.9040 - loss: 0.3186

546/573 ━━━━━━━━━━━━━━━━━━━━ 2s 88ms/step - accuracy: 0.9038 - loss: 0.3191

547/573 ━━━━━━━━━━━━━━━━━━━━ 2s 88ms/step - accuracy: 0.9038 - loss: 0.3190

548/573 ━━━━━━━━━━━━━━━━━━━━ 2s 88ms/step - accuracy: 0.9037 - loss: 0.3194

549/573 ━━━━━━━━━━━━━━━━━━━━ 2s 88ms/step - accuracy: 0.9035 - loss: 0.3204

550/573 ━━━━━━━━━━━━━━━━━━━━ 2s 88ms/step - accuracy: 0.9036 - loss: 0.3201

551/573 ━━━━━━━━━━━━━━━━━━━━ 1s 88ms/step - accuracy: 0.9036 - loss: 0.3199

552/573 ━━━━━━━━━━━━━━━━━━━━ 1s 88ms/step - accuracy: 0.9034 - loss: 0.3207

553/573 ━━━━━━━━━━━━━━━━━━━━ 1s 88ms/step - accuracy: 0.9033 - loss: 0.3213

554/573 ━━━━━━━━━━━━━━━━━━━━ 1s 88ms/step - accuracy: 0.9032 - loss: 0.3216

555/573 ━━━━━━━━━━━━━━━━━━━━ 1s 88ms/step - accuracy: 0.9030 - loss: 0.3218

556/573 ━━━━━━━━━━━━━━━━━━━━ 1s 88ms/step - accuracy: 0.9031 - loss: 0.3215

557/573 ━━━━━━━━━━━━━━━━━━━━ 1s 88ms/step - accuracy: 0.9030 - loss: 0.3218

558/573 ━━━━━━━━━━━━━━━━━━━━ 1s 88ms/step - accuracy: 0.9031 - loss: 0.3218

559/573 ━━━━━━━━━━━━━━━━━━━━ 1s 88ms/step - accuracy: 0.9030 - loss: 0.3218

560/573 ━━━━━━━━━━━━━━━━━━━━ 1s 88ms/step - accuracy: 0.9029 - loss: 0.3226

561/573 ━━━━━━━━━━━━━━━━━━━━ 1s 88ms/step - accuracy: 0.9030 - loss: 0.3223

562/573 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.9030 - loss: 0.3223

563/573 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.9029 - loss: 0.3226

564/573 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.9029 - loss: 0.3225

565/573 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.9029 - loss: 0.3229

566/573 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.9029 - loss: 0.3230

567/573 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.9030 - loss: 0.3229

568/573 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.9031 - loss: 0.3227

569/573 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.9032 - loss: 0.3222

570/573 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.9032 - loss: 0.3223

571/573 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.9032 - loss: 0.3220

572/573 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.9032 - loss: 0.3220

573/573 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.9032 - loss: 0.3218

573/573 ━━━━━━━━━━━━━━━━━━━━ 56s 98ms/step - accuracy: 0.9032 - loss: 0.3218 - val_accuracy: 0.9277 - val_loss: 0.2438

Trained in 4.5 min.

## 6. Training history

In [6]:
if history is not None:
    history_df = pd.DataFrame(history.history)
    history_df.index.name = "epoch"
    history_df["acc_gap"] = history_df["accuracy"] - history_df["val_accuracy"]
    display(history_df)
else:
    print("Model was loaded from disk - no training history this run.")

       accuracy      loss  val_accuracy  val_loss   acc_gap
epoch
0      0.810477  0.611557      0.920550  0.248467 -0.110073
1      0.890259  0.362924      0.925643  0.233796 -0.035384
2      0.893042  0.346577      0.928699  0.239014 -0.035657
3      0.899536  0.333685      0.928189  0.236186 -0.028653
4      0.903247  0.321822      0.927680  0.243814 -0.024433

## 7. Evaluate: per-class report + confusion matrix

In [7]:
debug_model(model, val_generator)

  1/123 ━━━━━━━━━━━━━━━━━━━━ 1:01 502ms/step

  3/123 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step

  5/123 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step

  7/123 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step

  9/123 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step

 10/123 ━━━━━━━━━━━━━━━━━━━━ 5s 52ms/step

 11/123 ━━━━━━━━━━━━━━━━━━━━ 6s 57ms/step

 12/123 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step

 14/123 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step

 15/123 ━━━━━━━━━━━━━━━━━━━━ 6s 59ms/step

 17/123 ━━━━━━━━━━━━━━━━━━━━ 6s 58ms/step

 19/123 ━━━━━━━━━━━━━━━━━━━━ 5s 56ms/step

 21/123 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step

 23/123 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step

 25/123 ━━━━━━━━━━━━━━━━━━━━ 5s 54ms/step

 27/123 ━━━━━━━━━━━━━━━━━━━━ 5s 54ms/step

 29/123 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step

 31/123 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step

 32/123 ━━━━━━━━━━━━━━━━━━━━ 4s 54ms/step

 33/123 ━━━━━━━━━━━━━━━━━━━━ 4s 55ms/step

 35/123 ━━━━━━━━━━━━━━━━━━━━ 4s 54ms/step

 37/123 ━━━━━━━━━━━━━━━━━━━━ 4s 54ms/step

 39/123 ━━━━━━━━━━━━━━━━━━━━ 4s 54ms/step

 41/123 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step

 43/123 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step

 45/123 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step

 47/123 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step

 49/123 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step

 51/123 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step

 53/123 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step

 55/123 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step

 57/123 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step

 59/123 ━━━━━━━━━━━━━━━━━━━━ 3s 51ms/step

 61/123 ━━━━━━━━━━━━━━━━━━━━ 3s 51ms/step

 63/123 ━━━━━━━━━━━━━━━━━━━━ 3s 51ms/step

 65/123 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step

 67/123 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step

 69/123 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step

 71/123 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step

 73/123 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step

 75/123 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step

 77/123 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step

 79/123 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step

 81/123 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step

 83/123 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step

 85/123 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step

 87/123 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step

 89/123 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step

 91/123 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step

 93/123 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step

 95/123 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step

 97/123 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step

 99/123 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step

101/123 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step

103/123 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step

105/123 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step

107/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

109/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

111/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

113/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

115/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

117/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

119/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

121/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

123/123 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

123/123 ━━━━━━━━━━━━━━━━━━━━ 7s 52ms/step

              precision    recall  f1-score   support

   butterfly       0.93      0.97      0.95       317
         cat       0.90      0.94      0.92       250
     chicken       0.96      0.96      0.96       464
         cow       0.80      0.87      0.83       280
         dog       0.95      0.90      0.92       730
    elephant       0.93      0.91      0.92       217
       horse       0.87      0.93      0.90       393
       sheep       0.87      0.84      0.85       273
      spider       0.98      0.98      0.98       723
    squirrel       0.98      0.91      0.94       280

    accuracy                           0.93      3927
   macro avg       0.92      0.92      0.92      3927
weighted avg       0.93      0.93      0.93      3927

C:\Users\GBT H610M-\Documents\ironHack\task\project-2\evaluation\model_metrics\model_metrics.py:92: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

,butterfly,cat,chicken,cow,dog,elephant,horse,sheep,spider,squirrel
butterfly,307,0,1,0,1,0,0,0,8,0
cat,1,234,3,0,7,1,2,0,0,2
chicken,5,2,445,1,5,1,2,1,2,0
cow,0,0,0,244,5,3,15,11,1,1
dog,2,17,8,12,654,2,26,7,1,1
elephant,0,0,0,5,5,198,2,5,2,0
horse,1,0,1,13,4,1,364,8,0,1
sheep,0,0,2,28,2,5,6,229,1,0
spider,12,1,2,0,1,0,0,0,706,1
squirrel,2,6,2,2,7,1,0,3,3,254

## 8. Misclassified images

In [8]:
plot_misclassified(model, val_generator)

  1/123 ━━━━━━━━━━━━━━━━━━━━ 9s 76ms/step

  2/123 ━━━━━━━━━━━━━━━━━━━━ 6s 53ms/step

  4/123 ━━━━━━━━━━━━━━━━━━━━ 5s 49ms/step

  6/123 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step

  8/123 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step

 10/123 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step

 11/123 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step

 12/123 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step

 14/123 ━━━━━━━━━━━━━━━━━━━━ 5s 54ms/step

 15/123 ━━━━━━━━━━━━━━━━━━━━ 6s 57ms/step

 16/123 ━━━━━━━━━━━━━━━━━━━━ 6s 57ms/step

 18/123 ━━━━━━━━━━━━━━━━━━━━ 5s 56ms/step

 20/123 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step

 22/123 ━━━━━━━━━━━━━━━━━━━━ 5s 54ms/step

 24/123 ━━━━━━━━━━━━━━━━━━━━ 5s 53ms/step

 26/123 ━━━━━━━━━━━━━━━━━━━━ 5s 53ms/step

 28/123 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step

 30/123 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step

 32/123 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step

 33/123 ━━━━━━━━━━━━━━━━━━━━ 4s 54ms/step

 35/123 ━━━━━━━━━━━━━━━━━━━━ 4s 54ms/step

 37/123 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step

 39/123 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step

 41/123 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step

 43/123 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step

 45/123 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step

 47/123 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step

 49/123 ━━━━━━━━━━━━━━━━━━━━ 3s 52ms/step

 51/123 ━━━━━━━━━━━━━━━━━━━━ 3s 51ms/step

 53/123 ━━━━━━━━━━━━━━━━━━━━ 3s 51ms/step

 55/123 ━━━━━━━━━━━━━━━━━━━━ 3s 51ms/step

 57/123 ━━━━━━━━━━━━━━━━━━━━ 3s 51ms/step

 59/123 ━━━━━━━━━━━━━━━━━━━━ 3s 51ms/step

 61/123 ━━━━━━━━━━━━━━━━━━━━ 3s 51ms/step

 63/123 ━━━━━━━━━━━━━━━━━━━━ 3s 51ms/step

 65/123 ━━━━━━━━━━━━━━━━━━━━ 2s 51ms/step

 67/123 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step

 69/123 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step

 71/123 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step

 73/123 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step

 75/123 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step

 77/123 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step

 79/123 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step

 81/123 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step

 83/123 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step

 85/123 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step

 87/123 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step

 89/123 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step

 91/123 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step

 93/123 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step

 95/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

 97/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

 99/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

101/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

103/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

105/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

107/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

109/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

111/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

113/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

115/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

117/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

119/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

121/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

123/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

123/123 ━━━━━━━━━━━━━━━━━━━━ 6s 49ms/step

C:\Users\GBT H610M-\Documents\ironHack\task\project-2\evaluation\plots\plots.py:74: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## 9. Record result to the tracking sheet

In [9]:
learning_rate = round(float(model.optimizer.learning_rate.numpy()), 6)

row = evaluate_model(model, val_generator, "transfer_mobilenet_aug")
row.update({
    "architecture": "MobileNetV2 (ImageNet, frozen) -> GlobalAveragePooling -> Dropout(0.5) + augmentation",
    "learning_rate": learning_rate,
    "train_time_min": train_time_min,
    "notes": "Transfer learning + train augmentation (val metrics). Does augmentation beat plain transfer (model 7)?",
})
record_result(row)

  1/123 ━━━━━━━━━━━━━━━━━━━━ 9s 79ms/step

  3/123 ━━━━━━━━━━━━━━━━━━━━ 5s 46ms/step

  5/123 ━━━━━━━━━━━━━━━━━━━━ 5s 46ms/step

  7/123 ━━━━━━━━━━━━━━━━━━━━ 5s 46ms/step

  9/123 ━━━━━━━━━━━━━━━━━━━━ 5s 46ms/step

 10/123 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step

 11/123 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step

 12/123 ━━━━━━━━━━━━━━━━━━━━ 6s 54ms/step

 14/123 ━━━━━━━━━━━━━━━━━━━━ 5s 53ms/step

 15/123 ━━━━━━━━━━━━━━━━━━━━ 6s 56ms/step

 17/123 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step

 19/123 ━━━━━━━━━━━━━━━━━━━━ 5s 54ms/step

 21/123 ━━━━━━━━━━━━━━━━━━━━ 5s 53ms/step

 23/123 ━━━━━━━━━━━━━━━━━━━━ 5s 52ms/step

 25/123 ━━━━━━━━━━━━━━━━━━━━ 5s 52ms/step

 27/123 ━━━━━━━━━━━━━━━━━━━━ 4s 51ms/step

 29/123 ━━━━━━━━━━━━━━━━━━━━ 4s 51ms/step

 31/123 ━━━━━━━━━━━━━━━━━━━━ 4s 51ms/step

 32/123 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step

 33/123 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step

 35/123 ━━━━━━━━━━━━━━━━━━━━ 4s 53ms/step

 37/123 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step

 39/123 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step

 41/123 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step

 43/123 ━━━━━━━━━━━━━━━━━━━━ 4s 51ms/step

 45/123 ━━━━━━━━━━━━━━━━━━━━ 3s 51ms/step

 47/123 ━━━━━━━━━━━━━━━━━━━━ 3s 51ms/step

 49/123 ━━━━━━━━━━━━━━━━━━━━ 3s 51ms/step

 51/123 ━━━━━━━━━━━━━━━━━━━━ 3s 51ms/step

 53/123 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step

 55/123 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step

 57/123 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step

 59/123 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step

 61/123 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step

 63/123 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step

 65/123 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step

 67/123 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step

 69/123 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step

 71/123 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step

 73/123 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step

 75/123 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step

 77/123 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step

 79/123 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step

 81/123 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step

 83/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

 85/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

 87/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

 89/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

 91/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

 93/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

 95/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

 97/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

 99/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

101/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

103/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

105/123 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

107/123 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

109/123 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

111/123 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

113/123 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

115/123 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

117/123 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

119/123 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

121/123 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

123/123 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

123/123 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step

,model,architecture,learning_rate,train_time_min,accuracy,precision,recall,f1,notes
0,baseline_cnn,3 conv blocks (6 Conv) -> Flatten -> Dropout(0.5),0.001,15.6,0.6988,0.6875,0.6569,0.6677,Baseline (val metrics). Overfits (~13% train-v...
1,gap_cnn,3 conv blocks (6 Conv) -> GlobalAveragePooling...,0.001,32.3,0.7403,0.7321,0.7111,0.7136,Flatten -> GAP (val metrics). Less overfit (~8...
2,gap_bn_cnn,3 conv blocks (Conv-BN-ReLU) -> GlobalAverageP...,0.001,62.6,0.6924,0.7526,0.6448,0.6593,GAP + BatchNorm (val metrics). Test if BN beat...
3,gap_aug,3 conv blocks (6 Conv) -> GlobalAveragePooling...,0.001,47.3,0.6677,0.6511,0.6433,0.6300,GAP + train augmentation (flip/rotate/shift/zo...
4,gap_aug2,3 conv blocks (6 Conv) -> GlobalAveragePooling...,0.001,54.7,0.7179,0.7065,0.7053,0.6895,Augmentation retry: dropout 0.3 + 60 epochs. T...
5,gap_deep,"4 conv blocks (8 Conv, +256) -> GlobalAverageP...",0.001,14.6,0.1859,0.0186,0.1000,0.0314,FAILED to train: plain deep CNN collapsed to ~...
6,transfer_mobilenet,"MobileNetV2 (ImageNet, frozen) -> GlobalAverag...",0.001,4.1,0.9404,0.9338,0.9309,0.9321,Transfer learning (val metrics). Frozen ImageN...
7,transfer_mobilenet_aug,"MobileNetV2 (ImageNet, frozen) -> GlobalAverag...",0.001,4.5,0.9256,0.9162,0.9192,0.9172,Transfer learning + train augmentation (val me...

## 10. Save the model

In [10]:
if history is not None:
    os.makedirs("models_saved", exist_ok=True)
    model.save(MODEL_PATH)
    print(f"Saved {MODEL_PATH}")
else:
    print(f"Using existing {MODEL_PATH}")

Saved models_saved/transfer_mobilenet_aug.keras

## 11. Compare all models

In [11]:
from model_metrics import plot_accuracy_comparison

plot_accuracy_comparison()

C:\Users\GBT H610M-\Documents\ironHack\task\project-2\evaluation\model_metrics\model_metrics.py:109: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

,model,architecture,learning_rate,train_time_min,accuracy,precision,recall,f1,notes
5,gap_deep,"4 conv blocks (8 Conv, +256) -> GlobalAverageP...",0.001,14.6,0.1859,0.0186,0.1000,0.0314,FAILED to train: plain deep CNN collapsed to ~...
3,gap_aug,3 conv blocks (6 Conv) -> GlobalAveragePooling...,0.001,47.3,0.6677,0.6511,0.6433,0.6300,GAP + train augmentation (flip/rotate/shift/zo...
2,gap_bn_cnn,3 conv blocks (Conv-BN-ReLU) -> GlobalAverageP...,0.001,62.6,0.6924,0.7526,0.6448,0.6593,GAP + BatchNorm (val metrics). Test if BN beat...
0,baseline_cnn,3 conv blocks (6 Conv) -> Flatten -> Dropout(0.5),0.001,15.6,0.6988,0.6875,0.6569,0.6677,Baseline (val metrics). Overfits (~13% train-v...
4,gap_aug2,3 conv blocks (6 Conv) -> GlobalAveragePooling...,0.001,54.7,0.7179,0.7065,0.7053,0.6895,Augmentation retry: dropout 0.3 + 60 epochs. T...
1,gap_cnn,3 conv blocks (6 Conv) -> GlobalAveragePooling...,0.001,32.3,0.7403,0.7321,0.7111,0.7136,Flatten -> GAP (val metrics). Less overfit (~8...
7,transfer_mobilenet_aug,"MobileNetV2 (ImageNet, frozen) -> GlobalAverag...",0.001,4.5,0.9256,0.9162,0.9192,0.9172,Transfer learning + train augmentation (val me...
6,transfer_mobilenet,"MobileNetV2 (ImageNet, frozen) -> GlobalAverag...",0.001,4.1,0.9404,0.9338,0.9309,0.9321,Transfer learning (val metrics). Frozen ImageN...