# Model 7 - Transfer Learning (MobileNetV2)

**Bonus / different approach.** Every other model learns features from scratch;
this one reuses **MobileNetV2 pre-trained on ImageNet** (base frozen) and trains
only a small `GAP -> Dropout -> Dense` head. The point: borrow a big model's
learned edges/textures/shapes instead of relearning them from ~18k images, and
see how far past the ~74% from-scratch ceiling it gets.

## 1. Setup & imports

Same shared pipeline as the other notebooks; only the model factory imported
differs.

In [1]:
import os
import sys

sys.path.append(os.path.join(os.getcwd(), "preprocessing", "label_mapping"))
sys.path.append(os.path.join(os.getcwd(), "preprocessing", "data_loader"))
sys.path.append(os.path.join(os.getcwd(), "model"))
sys.path.append(os.path.join(os.getcwd(), "evaluation", "model_metrics"))
sys.path.append(os.path.join(os.getcwd(), "evaluation", "plots"))

import pandas as pd
from tensorflow.keras.callbacks import EarlyStopping

from label_mapping import build_labeled_dataset
from data_loader import build_train_val_test_generators
from transfer_mobilenet import build_transfer_mobilenet
from model_metrics import debug_model, evaluate_model, record_result
from plots import plot_misclassified

## 2. Load & label the dataset

Build the image index (Italian folder -> English label, root-relative paths).

In [2]:
df = build_labeled_dataset()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26179 entries, 0 to 26178
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   image_path  26179 non-null  str
 1   label_it    26179 non-null  str
 2   label_en    26179 non-null  str
dtypes: str(3)
memory usage: 613.7 KB

## 3. Preprocess: split, resize, normalize

Identical preprocessing to every other model (128x128, rescale 1/255, stratified
70/15/15) so the comparison stays fair. The `[0,1] -> [-1,1]` shift MobileNetV2
needs is baked **inside** the model, so this pipeline is untouched.

In [3]:
train_generator, val_generator, test_generator = build_train_val_test_generators(
    df, project_root=os.getcwd(), image_size=(128, 128)
)
train_generator.class_indices

Found 18325 validated image filenames belonging to 10 classes.

Found 3927 validated image filenames belonging to 10 classes.

Found 3927 validated image filenames belonging to 10 classes.

{'butterfly': 0,
 'cat': 1,
 'chicken': 2,
 'cow': 3,
 'dog': 4,
 'elephant': 5,
 'horse': 6,
 'sheep': 7,
 'spider': 8,
 'squirrel': 9}

## 4. Build the model

Frozen **MobileNetV2 (ImageNet)** base + a fresh `GAP -> Dropout -> Dense` head.
Note the summary: ~2.3M total params but only ~13k **trainable** - we only train
the tiny head, which is why this is fast despite the big base.

In [4]:
model = build_transfer_mobilenet(
    input_shape=train_generator.image_shape,
    num_classes=len(train_generator.class_indices),
)
model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ rescaling (Rescaling)           │ (None, 128, 128, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ mobilenetv2_1.00_128            │ (None, 4, 4, 1280)     │     2,257,984 │
│ (Functional)                    │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 1280)           │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 1280)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 10)             │        12,810 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,270,794 (8.66 MB)

 Trainable params: 12,810 (50.04 KB)

 Non-trainable params: 2,257,984 (8.61 MB)

## 5. Train - or load a saved model

If `models_saved/transfer_mobilenet.keras` exists it's **loaded** (skips retrain);
otherwise it trains with `EarlyStopping` and is saved. Only the head trains
(base frozen), so epochs are cheap. Set `RETRAIN = True` to force a fresh run.

In [5]:
import time
from tensorflow import keras

MODEL_PATH = "models_saved/transfer_mobilenet.keras"
RETRAIN = False

if not RETRAIN and os.path.exists(MODEL_PATH):
    model = keras.models.load_model(MODEL_PATH)
    history, train_time_min = None, None
    print(f"Loaded {MODEL_PATH} (skipped training).")
else:
    early_stopping = EarlyStopping(
        monitor="val_loss", patience=3, restore_best_weights=True
    )
    start_time = time.time()
    history = model.fit(
        train_generator,
        validation_data=val_generator,
        epochs=20,
        callbacks=[early_stopping],
    )
    train_time_min = round((time.time() - start_time) / 60, 1)
    print(f"Trained in {train_time_min} min.")

Epoch 1/20

  1/573 ━━━━━━━━━━━━━━━━━━━━ 18:03 2s/step - accuracy: 0.0000e+00 - loss: 3.6819

  3/573 ━━━━━━━━━━━━━━━━━━━━ 27s 48ms/step - accuracy: 0.0521 - loss: 3.4703

  5/573 ━━━━━━━━━━━━━━━━━━━━ 27s 48ms/step - accuracy: 0.0625 - loss: 3.1816

  7/573 ━━━━━━━━━━━━━━━━━━━━ 27s 48ms/step - accuracy: 0.1027 - loss: 3.1475

  9/573 ━━━━━━━━━━━━━━━━━━━━ 27s 48ms/step - accuracy: 0.1285 - loss: 2.9570

 11/573 ━━━━━━━━━━━━━━━━━━━━ 27s 48ms/step - accuracy: 0.1420 - loss: 2.8318

 13/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.1659 - loss: 2.7262

 15/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.1875 - loss: 2.6687

 17/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.2132 - loss: 2.5988

 19/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.2401 - loss: 2.5038

 20/573 ━━━━━━━━━━━━━━━━━━━━ 28s 51ms/step - accuracy: 0.2547 - loss: 2.4494

 22/573 ━━━━━━━━━━━━━━━━━━━━ 28s 51ms/step - accuracy: 0.2770 - loss: 2.3660

 24/573 ━━━━━━━━━━━━━━━━━━━━ 27s 51ms/step - accuracy: 0.2982 - loss: 2.2993

 26/573 ━━━━━━━━━━━━━━━━━━━━ 27s 50ms/step - accuracy: 0.3137 - loss: 2.2499

 28/573 ━━━━━━━━━━━━━━━━━━━━ 27s 50ms/step - accuracy: 0.3348 - loss: 2.1846

 29/573 ━━━━━━━━━━━━━━━━━━━━ 27s 51ms/step - accuracy: 0.3448 - loss: 2.1521

 31/573 ━━━━━━━━━━━━━━━━━━━━ 27s 51ms/step - accuracy: 0.3659 - loss: 2.0840

 33/573 ━━━━━━━━━━━━━━━━━━━━ 27s 50ms/step - accuracy: 0.3722 - loss: 2.0359

 35/573 ━━━━━━━━━━━━━━━━━━━━ 27s 50ms/step - accuracy: 0.3893 - loss: 1.9869

 37/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.4079 - loss: 1.9281

 39/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.4151 - loss: 1.8923

 40/573 ━━━━━━━━━━━━━━━━━━━━ 27s 51ms/step - accuracy: 0.4203 - loss: 1.8756

 42/573 ━━━━━━━━━━━━━━━━━━━━ 26s 51ms/step - accuracy: 0.4315 - loss: 1.8288

 44/573 ━━━━━━━━━━━━━━━━━━━━ 26s 51ms/step - accuracy: 0.4446 - loss: 1.7975

 46/573 ━━━━━━━━━━━━━━━━━━━━ 26s 51ms/step - accuracy: 0.4511 - loss: 1.7666

 47/573 ━━━━━━━━━━━━━━━━━━━━ 26s 51ms/step - accuracy: 0.4594 - loss: 1.7435

 49/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.4681 - loss: 1.7172

 51/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.4773 - loss: 1.6861

 52/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.4844 - loss: 1.6644

 53/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.4912 - loss: 1.6439

 54/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.4959 - loss: 1.6273

 56/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.5061 - loss: 1.5951

 58/573 ━━━━━━━━━━━━━━━━━━━━ 25s 50ms/step - accuracy: 0.5189 - loss: 1.5573

 60/573 ━━━━━━━━━━━━━━━━━━━━ 25s 50ms/step - accuracy: 0.5286 - loss: 1.5274

 62/573 ━━━━━━━━━━━━━━━━━━━━ 25s 50ms/step - accuracy: 0.5378 - loss: 1.4967

 64/573 ━━━━━━━━━━━━━━━━━━━━ 25s 50ms/step - accuracy: 0.5464 - loss: 1.4706

 66/573 ━━━━━━━━━━━━━━━━━━━━ 25s 50ms/step - accuracy: 0.5511 - loss: 1.4509

 68/573 ━━━━━━━━━━━━━━━━━━━━ 25s 50ms/step - accuracy: 0.5588 - loss: 1.4288

 70/573 ━━━━━━━━━━━━━━━━━━━━ 25s 50ms/step - accuracy: 0.5656 - loss: 1.4055

 72/573 ━━━━━━━━━━━━━━━━━━━━ 24s 50ms/step - accuracy: 0.5734 - loss: 1.3824

 74/573 ━━━━━━━━━━━━━━━━━━━━ 24s 50ms/step - accuracy: 0.5807 - loss: 1.3614

 76/573 ━━━━━━━━━━━━━━━━━━━━ 24s 50ms/step - accuracy: 0.5855 - loss: 1.3433

 78/573 ━━━━━━━━━━━━━━━━━━━━ 24s 50ms/step - accuracy: 0.5917 - loss: 1.3219

 80/573 ━━━━━━━━━━━━━━━━━━━━ 24s 50ms/step - accuracy: 0.5980 - loss: 1.3012

 82/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.6040 - loss: 1.2831

 84/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.6079 - loss: 1.2709

 85/573 ━━━━━━━━━━━━━━━━━━━━ 24s 50ms/step - accuracy: 0.6103 - loss: 1.2629

 87/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.6153 - loss: 1.2471

 89/573 ━━━━━━━━━━━━━━━━━━━━ 23s 49ms/step - accuracy: 0.6204 - loss: 1.2321

 91/573 ━━━━━━━━━━━━━━━━━━━━ 23s 49ms/step - accuracy: 0.6267 - loss: 1.2123

 93/573 ━━━━━━━━━━━━━━━━━━━━ 23s 49ms/step - accuracy: 0.6331 - loss: 1.1923

 95/573 ━━━━━━━━━━━━━━━━━━━━ 23s 49ms/step - accuracy: 0.6368 - loss: 1.1796

 97/573 ━━━━━━━━━━━━━━━━━━━━ 23s 49ms/step - accuracy: 0.6405 - loss: 1.1711

 99/573 ━━━━━━━━━━━━━━━━━━━━ 23s 49ms/step - accuracy: 0.6436 - loss: 1.1611

101/573 ━━━━━━━━━━━━━━━━━━━━ 23s 49ms/step - accuracy: 0.6482 - loss: 1.1465

103/573 ━━━━━━━━━━━━━━━━━━━━ 23s 49ms/step - accuracy: 0.6517 - loss: 1.1354

105/573 ━━━━━━━━━━━━━━━━━━━━ 22s 49ms/step - accuracy: 0.6554 - loss: 1.1230

107/573 ━━━━━━━━━━━━━━━━━━━━ 22s 49ms/step - accuracy: 0.6586 - loss: 1.1132

109/573 ━━━━━━━━━━━━━━━━━━━━ 22s 49ms/step - accuracy: 0.6608 - loss: 1.1048

111/573 ━━━━━━━━━━━━━━━━━━━━ 22s 49ms/step - accuracy: 0.6639 - loss: 1.0941

113/573 ━━━━━━━━━━━━━━━━━━━━ 22s 49ms/step - accuracy: 0.6684 - loss: 1.0791

115/573 ━━━━━━━━━━━━━━━━━━━━ 22s 49ms/step - accuracy: 0.6728 - loss: 1.0662

117/573 ━━━━━━━━━━━━━━━━━━━━ 22s 49ms/step - accuracy: 0.6757 - loss: 1.0614

119/573 ━━━━━━━━━━━━━━━━━━━━ 22s 49ms/step - accuracy: 0.6794 - loss: 1.0497

120/573 ━━━━━━━━━━━━━━━━━━━━ 22s 49ms/step - accuracy: 0.6799 - loss: 1.0467

121/573 ━━━━━━━━━━━━━━━━━━━━ 22s 49ms/step - accuracy: 0.6818 - loss: 1.0415

122/573 ━━━━━━━━━━━━━━━━━━━━ 22s 49ms/step - accuracy: 0.6831 - loss: 1.0395

123/573 ━━━━━━━━━━━━━━━━━━━━ 22s 49ms/step - accuracy: 0.6852 - loss: 1.0328

124/573 ━━━━━━━━━━━━━━━━━━━━ 22s 49ms/step - accuracy: 0.6865 - loss: 1.0283

125/573 ━━━━━━━━━━━━━━━━━━━━ 22s 49ms/step - accuracy: 0.6875 - loss: 1.0254

126/573 ━━━━━━━━━━━━━━━━━━━━ 22s 50ms/step - accuracy: 0.6880 - loss: 1.0220

127/573 ━━━━━━━━━━━━━━━━━━━━ 22s 50ms/step - accuracy: 0.6900 - loss: 1.0157

128/573 ━━━━━━━━━━━━━━━━━━━━ 22s 50ms/step - accuracy: 0.6909 - loss: 1.0117

129/573 ━━━━━━━━━━━━━━━━━━━━ 21s 50ms/step - accuracy: 0.6919 - loss: 1.0073

130/573 ━━━━━━━━━━━━━━━━━━━━ 21s 50ms/step - accuracy: 0.6928 - loss: 1.0050

131/573 ━━━━━━━━━━━━━━━━━━━━ 21s 50ms/step - accuracy: 0.6947 - loss: 0.9985

133/573 ━━━━━━━━━━━━━━━━━━━━ 21s 50ms/step - accuracy: 0.6988 - loss: 0.9869

135/573 ━━━━━━━━━━━━━━━━━━━━ 21s 49ms/step - accuracy: 0.7019 - loss: 0.9775

137/573 ━━━━━━━━━━━━━━━━━━━━ 21s 49ms/step - accuracy: 0.7048 - loss: 0.9690

139/573 ━━━━━━━━━━━━━━━━━━━━ 21s 49ms/step - accuracy: 0.7080 - loss: 0.9591

141/573 ━━━━━━━━━━━━━━━━━━━━ 21s 49ms/step - accuracy: 0.7110 - loss: 0.9507

143/573 ━━━━━━━━━━━━━━━━━━━━ 21s 49ms/step - accuracy: 0.7142 - loss: 0.9413

145/573 ━━━━━━━━━━━━━━━━━━━━ 21s 49ms/step - accuracy: 0.7166 - loss: 0.9320

147/573 ━━━━━━━━━━━━━━━━━━━━ 21s 49ms/step - accuracy: 0.7190 - loss: 0.9234

149/573 ━━━━━━━━━━━━━━━━━━━━ 20s 49ms/step - accuracy: 0.7206 - loss: 0.9170

151/573 ━━━━━━━━━━━━━━━━━━━━ 20s 49ms/step - accuracy: 0.7225 - loss: 0.9113

153/573 ━━━━━━━━━━━━━━━━━━━━ 20s 49ms/step - accuracy: 0.7243 - loss: 0.9039

155/573 ━━━━━━━━━━━━━━━━━━━━ 20s 49ms/step - accuracy: 0.7258 - loss: 0.8977

157/573 ━━━━━━━━━━━━━━━━━━━━ 20s 49ms/step - accuracy: 0.7275 - loss: 0.8923

159/573 ━━━━━━━━━━━━━━━━━━━━ 20s 49ms/step - accuracy: 0.7284 - loss: 0.8892

161/573 ━━━━━━━━━━━━━━━━━━━━ 20s 49ms/step - accuracy: 0.7308 - loss: 0.8833

163/573 ━━━━━━━━━━━━━━━━━━━━ 20s 49ms/step - accuracy: 0.7324 - loss: 0.8771

165/573 ━━━━━━━━━━━━━━━━━━━━ 20s 49ms/step - accuracy: 0.7343 - loss: 0.8702

167/573 ━━━━━━━━━━━━━━━━━━━━ 19s 49ms/step - accuracy: 0.7358 - loss: 0.8649

169/573 ━━━━━━━━━━━━━━━━━━━━ 19s 49ms/step - accuracy: 0.7372 - loss: 0.8594

171/573 ━━━━━━━━━━━━━━━━━━━━ 19s 49ms/step - accuracy: 0.7394 - loss: 0.8530

173/573 ━━━━━━━━━━━━━━━━━━━━ 19s 49ms/step - accuracy: 0.7411 - loss: 0.8477

175/573 ━━━━━━━━━━━━━━━━━━━━ 19s 49ms/step - accuracy: 0.7423 - loss: 0.8412

177/573 ━━━━━━━━━━━━━━━━━━━━ 19s 49ms/step - accuracy: 0.7442 - loss: 0.8364

179/573 ━━━━━━━━━━━━━━━━━━━━ 19s 49ms/step - accuracy: 0.7455 - loss: 0.8321

181/573 ━━━━━━━━━━━━━━━━━━━━ 19s 49ms/step - accuracy: 0.7460 - loss: 0.8270

183/573 ━━━━━━━━━━━━━━━━━━━━ 19s 49ms/step - accuracy: 0.7480 - loss: 0.8215

185/573 ━━━━━━━━━━━━━━━━━━━━ 18s 49ms/step - accuracy: 0.7498 - loss: 0.8148

187/573 ━━━━━━━━━━━━━━━━━━━━ 18s 49ms/step - accuracy: 0.7517 - loss: 0.8101

189/573 ━━━━━━━━━━━━━━━━━━━━ 18s 49ms/step - accuracy: 0.7535 - loss: 0.8041

191/573 ━━━━━━━━━━━━━━━━━━━━ 18s 49ms/step - accuracy: 0.7549 - loss: 0.7993

193/573 ━━━━━━━━━━━━━━━━━━━━ 18s 49ms/step - accuracy: 0.7565 - loss: 0.7945

195/573 ━━━━━━━━━━━━━━━━━━━━ 18s 49ms/step - accuracy: 0.7582 - loss: 0.7889

197/573 ━━━━━━━━━━━━━━━━━━━━ 18s 49ms/step - accuracy: 0.7600 - loss: 0.7833

198/573 ━━━━━━━━━━━━━━━━━━━━ 18s 49ms/step - accuracy: 0.7612 - loss: 0.7799

199/573 ━━━━━━━━━━━━━━━━━━━━ 18s 49ms/step - accuracy: 0.7622 - loss: 0.7769

201/573 ━━━━━━━━━━━━━━━━━━━━ 18s 49ms/step - accuracy: 0.7637 - loss: 0.7723

203/573 ━━━━━━━━━━━━━━━━━━━━ 18s 49ms/step - accuracy: 0.7652 - loss: 0.7674

205/573 ━━━━━━━━━━━━━━━━━━━━ 17s 49ms/step - accuracy: 0.7667 - loss: 0.7636

207/573 ━━━━━━━━━━━━━━━━━━━━ 17s 49ms/step - accuracy: 0.7679 - loss: 0.7600

209/573 ━━━━━━━━━━━━━━━━━━━━ 17s 49ms/step - accuracy: 0.7691 - loss: 0.7555

211/573 ━━━━━━━━━━━━━━━━━━━━ 17s 49ms/step - accuracy: 0.7707 - loss: 0.7503

213/573 ━━━━━━━━━━━━━━━━━━━━ 17s 49ms/step - accuracy: 0.7716 - loss: 0.7467

215/573 ━━━━━━━━━━━━━━━━━━━━ 17s 49ms/step - accuracy: 0.7720 - loss: 0.7437

217/573 ━━━━━━━━━━━━━━━━━━━━ 17s 49ms/step - accuracy: 0.7727 - loss: 0.7418

219/573 ━━━━━━━━━━━━━━━━━━━━ 17s 49ms/step - accuracy: 0.7743 - loss: 0.7371

221/573 ━━━━━━━━━━━━━━━━━━━━ 17s 49ms/step - accuracy: 0.7743 - loss: 0.7363

223/573 ━━━━━━━━━━━━━━━━━━━━ 17s 49ms/step - accuracy: 0.7754 - loss: 0.7328

225/573 ━━━━━━━━━━━━━━━━━━━━ 16s 49ms/step - accuracy: 0.7766 - loss: 0.7285

227/573 ━━━━━━━━━━━━━━━━━━━━ 16s 49ms/step - accuracy: 0.7771 - loss: 0.7265

229/573 ━━━━━━━━━━━━━━━━━━━━ 16s 49ms/step - accuracy: 0.7783 - loss: 0.7226

231/573 ━━━━━━━━━━━━━━━━━━━━ 16s 49ms/step - accuracy: 0.7797 - loss: 0.7181

233/573 ━━━━━━━━━━━━━━━━━━━━ 16s 49ms/step - accuracy: 0.7808 - loss: 0.7159

235/573 ━━━━━━━━━━━━━━━━━━━━ 16s 49ms/step - accuracy: 0.7816 - loss: 0.7137

237/573 ━━━━━━━━━━━━━━━━━━━━ 16s 49ms/step - accuracy: 0.7823 - loss: 0.7121

239/573 ━━━━━━━━━━━━━━━━━━━━ 16s 49ms/step - accuracy: 0.7828 - loss: 0.7091

241/573 ━━━━━━━━━━━━━━━━━━━━ 16s 49ms/step - accuracy: 0.7839 - loss: 0.7068

243/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.7849 - loss: 0.7031

245/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.7858 - loss: 0.7000

247/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.7865 - loss: 0.6979

249/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.7877 - loss: 0.6946

251/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.7884 - loss: 0.6913

253/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.7891 - loss: 0.6887

254/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.7897 - loss: 0.6866

256/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.7901 - loss: 0.6857

258/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.7905 - loss: 0.6844

260/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.7912 - loss: 0.6819

262/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.7917 - loss: 0.6794

264/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.7925 - loss: 0.6774

266/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.7927 - loss: 0.6771

268/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.7932 - loss: 0.6764

270/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.7936 - loss: 0.6754

272/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.7942 - loss: 0.6749

274/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.7950 - loss: 0.6728

276/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.7962 - loss: 0.6692

278/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.7962 - loss: 0.6677

280/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.7966 - loss: 0.6663

282/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.7974 - loss: 0.6640

284/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.7984 - loss: 0.6606

286/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.7987 - loss: 0.6596

288/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.7989 - loss: 0.6603

290/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.7997 - loss: 0.6575

292/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.8003 - loss: 0.6555

294/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.8006 - loss: 0.6541

296/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.8010 - loss: 0.6530

298/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.8020 - loss: 0.6499

300/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.8030 - loss: 0.6471

302/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.8037 - loss: 0.6444

304/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.8047 - loss: 0.6414

306/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.8052 - loss: 0.6394

308/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.8060 - loss: 0.6370

310/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.8067 - loss: 0.6354

312/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.8074 - loss: 0.6336

313/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.8076 - loss: 0.6324

315/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.8083 - loss: 0.6308

317/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.8086 - loss: 0.6292

319/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.8092 - loss: 0.6271

321/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.8096 - loss: 0.6258

323/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.8105 - loss: 0.6229

325/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.8111 - loss: 0.6206

327/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.8113 - loss: 0.6189

329/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.8115 - loss: 0.6176

331/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.8121 - loss: 0.6151

333/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.8123 - loss: 0.6144

335/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.8125 - loss: 0.6132

337/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.8128 - loss: 0.6119

339/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.8130 - loss: 0.6107

341/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.8136 - loss: 0.6086

343/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.8141 - loss: 0.6070

345/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.8148 - loss: 0.6055

347/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.8153 - loss: 0.6035

349/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.8161 - loss: 0.6021

351/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.8169 - loss: 0.5994

353/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.8171 - loss: 0.5977

355/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.8173 - loss: 0.5969

357/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.8178 - loss: 0.5958

359/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.8183 - loss: 0.5937

361/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.8186 - loss: 0.5924

363/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.8189 - loss: 0.5909

365/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.8192 - loss: 0.5897

366/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.8193 - loss: 0.5889

367/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.8197 - loss: 0.5879

368/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.8201 - loss: 0.5866

369/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.8200 - loss: 0.5866

370/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.8201 - loss: 0.5868

371/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.8203 - loss: 0.5860

372/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.8206 - loss: 0.5852

374/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.8209 - loss: 0.5842

376/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.8213 - loss: 0.5828

378/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.8217 - loss: 0.5815

380/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.8223 - loss: 0.5796

382/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.8227 - loss: 0.5783

384/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.8233 - loss: 0.5767

385/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.8236 - loss: 0.5759

386/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.8239 - loss: 0.5748

387/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.8241 - loss: 0.5741

389/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.8246 - loss: 0.5726

391/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.8251 - loss: 0.5707

393/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.8254 - loss: 0.5707

395/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.8260 - loss: 0.5688

397/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.8266 - loss: 0.5671

398/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.8268 - loss: 0.5669

399/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.8269 - loss: 0.5664

400/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.8273 - loss: 0.5653

401/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.8275 - loss: 0.5648

402/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.8277 - loss: 0.5639

404/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.8281 - loss: 0.5626

405/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.8283 - loss: 0.5617

406/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.8282 - loss: 0.5619

408/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.8284 - loss: 0.5612

410/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.8288 - loss: 0.5597

412/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.8293 - loss: 0.5581

414/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.8300 - loss: 0.5559

416/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.8302 - loss: 0.5558

418/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.8305 - loss: 0.5551

420/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.8311 - loss: 0.5534

422/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.8314 - loss: 0.5520

424/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.8318 - loss: 0.5508

426/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.8320 - loss: 0.5504

428/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.8324 - loss: 0.5492

430/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.8331 - loss: 0.5475

432/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.8336 - loss: 0.5456

434/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.8338 - loss: 0.5448

436/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.8340 - loss: 0.5437

438/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.8344 - loss: 0.5423

440/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.8350 - loss: 0.5405

442/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.8351 - loss: 0.5395

444/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.8354 - loss: 0.5386

446/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.8358 - loss: 0.5373

448/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.8360 - loss: 0.5362

450/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.8361 - loss: 0.5362

452/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.8365 - loss: 0.5350

454/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.8371 - loss: 0.5332

456/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.8375 - loss: 0.5327

458/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.8378 - loss: 0.5316

460/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.8379 - loss: 0.5309

462/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.8383 - loss: 0.5295

464/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.8384 - loss: 0.5300

466/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.8385 - loss: 0.5297

468/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.8388 - loss: 0.5289

470/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.8391 - loss: 0.5279

472/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.8396 - loss: 0.5263

474/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.8400 - loss: 0.5249

476/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.8402 - loss: 0.5238

478/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.8405 - loss: 0.5227

480/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.8408 - loss: 0.5216

482/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.8412 - loss: 0.5205

484/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.8416 - loss: 0.5191

486/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.8420 - loss: 0.5176

488/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.8424 - loss: 0.5174

490/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.8427 - loss: 0.5164

492/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.8428 - loss: 0.5157

493/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.8429 - loss: 0.5151

495/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.8433 - loss: 0.5137

496/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.8433 - loss: 0.5136

497/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.8436 - loss: 0.5130

499/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.8436 - loss: 0.5126

501/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.8438 - loss: 0.5124

503/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.8441 - loss: 0.5119

505/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.8447 - loss: 0.5103

507/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.8449 - loss: 0.5092

509/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.8451 - loss: 0.5083

510/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.8452 - loss: 0.5080

512/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.8454 - loss: 0.5076

513/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.8457 - loss: 0.5067

515/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.8460 - loss: 0.5058

517/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.8462 - loss: 0.5056

519/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.8464 - loss: 0.5051

521/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.8466 - loss: 0.5041

523/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.8469 - loss: 0.5035

525/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.8472 - loss: 0.5024

526/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.8473 - loss: 0.5021

527/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.8473 - loss: 0.5017

528/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.8474 - loss: 0.5012

530/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.8475 - loss: 0.5010

532/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.8476 - loss: 0.5014

534/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.8479 - loss: 0.5004

536/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.8481 - loss: 0.4994

538/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.8484 - loss: 0.4991

540/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.8485 - loss: 0.4993

542/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.8487 - loss: 0.4983

544/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.8489 - loss: 0.4976

546/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.8491 - loss: 0.4968

548/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.8492 - loss: 0.4968

550/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.8492 - loss: 0.4963

552/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.8494 - loss: 0.4956

554/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8497 - loss: 0.4944

556/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8498 - loss: 0.4945

558/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8500 - loss: 0.4938

560/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8500 - loss: 0.4939

562/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8502 - loss: 0.4933

564/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8503 - loss: 0.4928

566/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8506 - loss: 0.4922

568/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8505 - loss: 0.4923

570/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8510 - loss: 0.4910

572/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8513 - loss: 0.4901

573/573 ━━━━━━━━━━━━━━━━━━━━ 36s 60ms/step - accuracy: 0.8515 - loss: 0.4894 - val_accuracy: 0.9325 - val_loss: 0.2287

Epoch 2/20

  1/573 ━━━━━━━━━━━━━━━━━━━━ 47s 83ms/step - accuracy: 0.8438 - loss: 0.3795

  3/573 ━━━━━━━━━━━━━━━━━━━━ 26s 46ms/step - accuracy: 0.8958 - loss: 0.2546

  5/573 ━━━━━━━━━━━━━━━━━━━━ 26s 47ms/step - accuracy: 0.9062 - loss: 0.2402

  6/573 ━━━━━━━━━━━━━━━━━━━━ 30s 54ms/step - accuracy: 0.9115 - loss: 0.2749

  8/573 ━━━━━━━━━━━━━━━━━━━━ 29s 52ms/step - accuracy: 0.9023 - loss: 0.2856

 10/573 ━━━━━━━━━━━━━━━━━━━━ 28s 51ms/step - accuracy: 0.9187 - loss: 0.2530

 12/573 ━━━━━━━━━━━━━━━━━━━━ 28s 50ms/step - accuracy: 0.9297 - loss: 0.2231

 14/573 ━━━━━━━━━━━━━━━━━━━━ 27s 49ms/step - accuracy: 0.9286 - loss: 0.2395

 16/573 ━━━━━━━━━━━━━━━━━━━━ 27s 49ms/step - accuracy: 0.9336 - loss: 0.2315

 18/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9292 - loss: 0.2325

 19/573 ━━━━━━━━━━━━━━━━━━━━ 27s 50ms/step - accuracy: 0.9263 - loss: 0.2540

 21/573 ━━━━━━━━━━━━━━━━━━━━ 27s 49ms/step - accuracy: 0.9274 - loss: 0.2472

 23/573 ━━━━━━━━━━━━━━━━━━━━ 26s 49ms/step - accuracy: 0.9269 - loss: 0.2388

 25/573 ━━━━━━━━━━━━━━━━━━━━ 26s 49ms/step - accuracy: 0.9278 - loss: 0.2330

 27/573 ━━━━━━━━━━━━━━━━━━━━ 26s 49ms/step - accuracy: 0.9320 - loss: 0.2202

 29/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9335 - loss: 0.2170

 31/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9327 - loss: 0.2235

 33/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9311 - loss: 0.2327

 35/573 ━━━━━━━━━━━━━━━━━━━━ 25s 48ms/step - accuracy: 0.9324 - loss: 0.2262

 36/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.9325 - loss: 0.2235

 37/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.9292 - loss: 0.2336

 38/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.9303 - loss: 0.2306

 39/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.9297 - loss: 0.2351

 40/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.9283 - loss: 0.2437

 41/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.9285 - loss: 0.2439

 42/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.9280 - loss: 0.2472

 43/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.9297 - loss: 0.2427

 44/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.9298 - loss: 0.2415

 45/573 ━━━━━━━━━━━━━━━━━━━━ 26s 51ms/step - accuracy: 0.9293 - loss: 0.2420

 46/573 ━━━━━━━━━━━━━━━━━━━━ 26s 51ms/step - accuracy: 0.9302 - loss: 0.2392

 47/573 ━━━━━━━━━━━━━━━━━━━━ 26s 51ms/step - accuracy: 0.9317 - loss: 0.2353

 48/573 ━━━━━━━━━━━━━━━━━━━━ 26s 51ms/step - accuracy: 0.9318 - loss: 0.2349

 49/573 ━━━━━━━━━━━━━━━━━━━━ 26s 51ms/step - accuracy: 0.9319 - loss: 0.2372

 50/573 ━━━━━━━━━━━━━━━━━━━━ 26s 51ms/step - accuracy: 0.9327 - loss: 0.2353

 51/573 ━━━━━━━━━━━━━━━━━━━━ 26s 51ms/step - accuracy: 0.9321 - loss: 0.2345

 53/573 ━━━━━━━━━━━━━━━━━━━━ 26s 51ms/step - accuracy: 0.9318 - loss: 0.2345

 55/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.9325 - loss: 0.2320

 57/573 ━━━━━━━━━━━━━━━━━━━━ 26s 51ms/step - accuracy: 0.9316 - loss: 0.2357

 59/573 ━━━━━━━━━━━━━━━━━━━━ 25s 50ms/step - accuracy: 0.9291 - loss: 0.2400

 61/573 ━━━━━━━━━━━━━━━━━━━━ 25s 51ms/step - accuracy: 0.9268 - loss: 0.2433

 63/573 ━━━━━━━━━━━━━━━━━━━━ 25s 51ms/step - accuracy: 0.9247 - loss: 0.2501

 65/573 ━━━━━━━━━━━━━━━━━━━━ 25s 50ms/step - accuracy: 0.9256 - loss: 0.2469

 67/573 ━━━━━━━━━━━━━━━━━━━━ 25s 50ms/step - accuracy: 0.9269 - loss: 0.2432

 68/573 ━━━━━━━━━━━━━━━━━━━━ 25s 50ms/step - accuracy: 0.9270 - loss: 0.2443

 69/573 ━━━━━━━━━━━━━━━━━━━━ 25s 50ms/step - accuracy: 0.9235 - loss: 0.2501

 70/573 ━━━━━━━━━━━━━━━━━━━━ 25s 50ms/step - accuracy: 0.9242 - loss: 0.2477

 71/573 ━━━━━━━━━━━━━━━━━━━━ 25s 50ms/step - accuracy: 0.9248 - loss: 0.2467

 72/573 ━━━━━━━━━━━━━━━━━━━━ 25s 51ms/step - accuracy: 0.9241 - loss: 0.2490

 73/573 ━━━━━━━━━━━━━━━━━━━━ 25s 51ms/step - accuracy: 0.9243 - loss: 0.2502

 74/573 ━━━━━━━━━━━━━━━━━━━━ 25s 51ms/step - accuracy: 0.9232 - loss: 0.2519

 75/573 ━━━━━━━━━━━━━━━━━━━━ 25s 51ms/step - accuracy: 0.9230 - loss: 0.2532

 76/573 ━━━━━━━━━━━━━━━━━━━━ 25s 51ms/step - accuracy: 0.9228 - loss: 0.2521

 77/573 ━━━━━━━━━━━━━━━━━━━━ 25s 51ms/step - accuracy: 0.9230 - loss: 0.2536

 78/573 ━━━━━━━━━━━━━━━━━━━━ 25s 51ms/step - accuracy: 0.9223 - loss: 0.2534

 79/573 ━━━━━━━━━━━━━━━━━━━━ 25s 51ms/step - accuracy: 0.9225 - loss: 0.2517

 80/573 ━━━━━━━━━━━━━━━━━━━━ 25s 52ms/step - accuracy: 0.9235 - loss: 0.2491

 81/573 ━━━━━━━━━━━━━━━━━━━━ 25s 52ms/step - accuracy: 0.9244 - loss: 0.2471

 82/573 ━━━━━━━━━━━━━━━━━━━━ 25s 52ms/step - accuracy: 0.9235 - loss: 0.2528

 83/573 ━━━━━━━━━━━━━━━━━━━━ 25s 53ms/step - accuracy: 0.9233 - loss: 0.2520

 84/573 ━━━━━━━━━━━━━━━━━━━━ 25s 53ms/step - accuracy: 0.9234 - loss: 0.2513

 85/573 ━━━━━━━━━━━━━━━━━━━━ 25s 53ms/step - accuracy: 0.9236 - loss: 0.2505

 87/573 ━━━━━━━━━━━━━━━━━━━━ 25s 53ms/step - accuracy: 0.9232 - loss: 0.2537

 89/573 ━━━━━━━━━━━━━━━━━━━━ 25s 53ms/step - accuracy: 0.9228 - loss: 0.2548

 90/573 ━━━━━━━━━━━━━━━━━━━━ 25s 53ms/step - accuracy: 0.9219 - loss: 0.2569

 92/573 ━━━━━━━━━━━━━━━━━━━━ 25s 53ms/step - accuracy: 0.9219 - loss: 0.2589

 93/573 ━━━━━━━━━━━━━━━━━━━━ 25s 53ms/step - accuracy: 0.9221 - loss: 0.2587

 94/573 ━━━━━━━━━━━━━━━━━━━━ 25s 53ms/step - accuracy: 0.9219 - loss: 0.2603

 95/573 ━━━━━━━━━━━━━━━━━━━━ 25s 53ms/step - accuracy: 0.9204 - loss: 0.2612

 96/573 ━━━━━━━━━━━━━━━━━━━━ 25s 53ms/step - accuracy: 0.9206 - loss: 0.2600

 97/573 ━━━━━━━━━━━━━━━━━━━━ 25s 53ms/step - accuracy: 0.9208 - loss: 0.2588

 98/573 ━━━━━━━━━━━━━━━━━━━━ 25s 53ms/step - accuracy: 0.9203 - loss: 0.2600

 99/573 ━━━━━━━━━━━━━━━━━━━━ 25s 53ms/step - accuracy: 0.9205 - loss: 0.2605

100/573 ━━━━━━━━━━━━━━━━━━━━ 25s 53ms/step - accuracy: 0.9207 - loss: 0.2599

101/573 ━━━━━━━━━━━━━━━━━━━━ 25s 53ms/step - accuracy: 0.9202 - loss: 0.2615

102/573 ━━━━━━━━━━━━━━━━━━━━ 25s 54ms/step - accuracy: 0.9201 - loss: 0.2605

103/573 ━━━━━━━━━━━━━━━━━━━━ 25s 54ms/step - accuracy: 0.9202 - loss: 0.2606

104/573 ━━━━━━━━━━━━━━━━━━━━ 25s 54ms/step - accuracy: 0.9195 - loss: 0.2622

105/573 ━━━━━━━━━━━━━━━━━━━━ 25s 54ms/step - accuracy: 0.9197 - loss: 0.2618

106/573 ━━━━━━━━━━━━━━━━━━━━ 25s 54ms/step - accuracy: 0.9201 - loss: 0.2604

108/573 ━━━━━━━━━━━━━━━━━━━━ 24s 54ms/step - accuracy: 0.9202 - loss: 0.2610

109/573 ━━━━━━━━━━━━━━━━━━━━ 24s 54ms/step - accuracy: 0.9200 - loss: 0.2628

111/573 ━━━━━━━━━━━━━━━━━━━━ 24s 54ms/step - accuracy: 0.9192 - loss: 0.2645

113/573 ━━━━━━━━━━━━━━━━━━━━ 24s 53ms/step - accuracy: 0.9198 - loss: 0.2640

115/573 ━━━━━━━━━━━━━━━━━━━━ 24s 53ms/step - accuracy: 0.9204 - loss: 0.2618

117/573 ━━━━━━━━━━━━━━━━━━━━ 24s 53ms/step - accuracy: 0.9204 - loss: 0.2621

118/573 ━━━━━━━━━━━━━━━━━━━━ 24s 53ms/step - accuracy: 0.9206 - loss: 0.2615

120/573 ━━━━━━━━━━━━━━━━━━━━ 24s 53ms/step - accuracy: 0.9201 - loss: 0.2610

121/573 ━━━━━━━━━━━━━━━━━━━━ 24s 53ms/step - accuracy: 0.9200 - loss: 0.2606

122/573 ━━━━━━━━━━━━━━━━━━━━ 23s 53ms/step - accuracy: 0.9196 - loss: 0.2609

123/573 ━━━━━━━━━━━━━━━━━━━━ 23s 53ms/step - accuracy: 0.9190 - loss: 0.2620

124/573 ━━━━━━━━━━━━━━━━━━━━ 23s 53ms/step - accuracy: 0.9191 - loss: 0.2608

125/573 ━━━━━━━━━━━━━━━━━━━━ 23s 53ms/step - accuracy: 0.9193 - loss: 0.2597

126/573 ━━━━━━━━━━━━━━━━━━━━ 23s 53ms/step - accuracy: 0.9199 - loss: 0.2580

127/573 ━━━━━━━━━━━━━━━━━━━━ 23s 53ms/step - accuracy: 0.9201 - loss: 0.2573

128/573 ━━━━━━━━━━━━━━━━━━━━ 23s 53ms/step - accuracy: 0.9202 - loss: 0.2570

129/573 ━━━━━━━━━━━━━━━━━━━━ 23s 53ms/step - accuracy: 0.9206 - loss: 0.2560

130/573 ━━━━━━━━━━━━━━━━━━━━ 23s 53ms/step - accuracy: 0.9207 - loss: 0.2551

131/573 ━━━━━━━━━━━━━━━━━━━━ 23s 53ms/step - accuracy: 0.9208 - loss: 0.2544

132/573 ━━━━━━━━━━━━━━━━━━━━ 23s 53ms/step - accuracy: 0.9212 - loss: 0.2534

133/573 ━━━━━━━━━━━━━━━━━━━━ 23s 53ms/step - accuracy: 0.9213 - loss: 0.2533

134/573 ━━━━━━━━━━━━━━━━━━━━ 23s 53ms/step - accuracy: 0.9219 - loss: 0.2522

135/573 ━━━━━━━━━━━━━━━━━━━━ 23s 53ms/step - accuracy: 0.9218 - loss: 0.2525

136/573 ━━━━━━━━━━━━━━━━━━━━ 23s 53ms/step - accuracy: 0.9217 - loss: 0.2528

137/573 ━━━━━━━━━━━━━━━━━━━━ 23s 53ms/step - accuracy: 0.9223 - loss: 0.2511

138/573 ━━━━━━━━━━━━━━━━━━━━ 23s 53ms/step - accuracy: 0.9219 - loss: 0.2527

139/573 ━━━━━━━━━━━━━━━━━━━━ 23s 53ms/step - accuracy: 0.9222 - loss: 0.2517

140/573 ━━━━━━━━━━━━━━━━━━━━ 22s 53ms/step - accuracy: 0.9224 - loss: 0.2512

141/573 ━━━━━━━━━━━━━━━━━━━━ 22s 53ms/step - accuracy: 0.9222 - loss: 0.2505

142/573 ━━━━━━━━━━━━━━━━━━━━ 22s 53ms/step - accuracy: 0.9221 - loss: 0.2513

143/573 ━━━━━━━━━━━━━━━━━━━━ 22s 53ms/step - accuracy: 0.9222 - loss: 0.2514

144/573 ━━━━━━━━━━━━━━━━━━━━ 22s 53ms/step - accuracy: 0.9223 - loss: 0.2517

145/573 ━━━━━━━━━━━━━━━━━━━━ 22s 53ms/step - accuracy: 0.9222 - loss: 0.2521

146/573 ━━━━━━━━━━━━━━━━━━━━ 22s 53ms/step - accuracy: 0.9221 - loss: 0.2527

147/573 ━━━━━━━━━━━━━━━━━━━━ 22s 53ms/step - accuracy: 0.9224 - loss: 0.2517

148/573 ━━━━━━━━━━━━━━━━━━━━ 22s 53ms/step - accuracy: 0.9228 - loss: 0.2506

149/573 ━━━━━━━━━━━━━━━━━━━━ 22s 53ms/step - accuracy: 0.9231 - loss: 0.2503

150/573 ━━━━━━━━━━━━━━━━━━━━ 22s 53ms/step - accuracy: 0.9229 - loss: 0.2507

151/573 ━━━━━━━━━━━━━━━━━━━━ 22s 54ms/step - accuracy: 0.9233 - loss: 0.2497

152/573 ━━━━━━━━━━━━━━━━━━━━ 22s 54ms/step - accuracy: 0.9236 - loss: 0.2488

154/573 ━━━━━━━━━━━━━━━━━━━━ 22s 54ms/step - accuracy: 0.9235 - loss: 0.2493

156/573 ━━━━━━━━━━━━━━━━━━━━ 22s 54ms/step - accuracy: 0.9235 - loss: 0.2492

158/573 ━━━━━━━━━━━━━━━━━━━━ 22s 53ms/step - accuracy: 0.9235 - loss: 0.2490

160/573 ━━━━━━━━━━━━━━━━━━━━ 22s 53ms/step - accuracy: 0.9231 - loss: 0.2515

162/573 ━━━━━━━━━━━━━━━━━━━━ 21s 53ms/step - accuracy: 0.9234 - loss: 0.2510

164/573 ━━━━━━━━━━━━━━━━━━━━ 21s 53ms/step - accuracy: 0.9236 - loss: 0.2511

166/573 ━━━━━━━━━━━━━━━━━━━━ 21s 53ms/step - accuracy: 0.9242 - loss: 0.2514

168/573 ━━━━━━━━━━━━━━━━━━━━ 21s 53ms/step - accuracy: 0.9238 - loss: 0.2519

169/573 ━━━━━━━━━━━━━━━━━━━━ 21s 53ms/step - accuracy: 0.9240 - loss: 0.2509

170/573 ━━━━━━━━━━━━━━━━━━━━ 21s 53ms/step - accuracy: 0.9245 - loss: 0.2498

171/573 ━━━━━━━━━━━━━━━━━━━━ 21s 53ms/step - accuracy: 0.9247 - loss: 0.2491

172/573 ━━━━━━━━━━━━━━━━━━━━ 21s 53ms/step - accuracy: 0.9243 - loss: 0.2511

173/573 ━━━━━━━━━━━━━━━━━━━━ 21s 53ms/step - accuracy: 0.9243 - loss: 0.2511

174/573 ━━━━━━━━━━━━━━━━━━━━ 21s 53ms/step - accuracy: 0.9246 - loss: 0.2509

175/573 ━━━━━━━━━━━━━━━━━━━━ 21s 53ms/step - accuracy: 0.9249 - loss: 0.2505

176/573 ━━━━━━━━━━━━━━━━━━━━ 21s 53ms/step - accuracy: 0.9246 - loss: 0.2512

177/573 ━━━━━━━━━━━━━━━━━━━━ 20s 53ms/step - accuracy: 0.9246 - loss: 0.2509

178/573 ━━━━━━━━━━━━━━━━━━━━ 20s 53ms/step - accuracy: 0.9245 - loss: 0.2506

179/573 ━━━━━━━━━━━━━━━━━━━━ 20s 53ms/step - accuracy: 0.9248 - loss: 0.2498

180/573 ━━━━━━━━━━━━━━━━━━━━ 20s 53ms/step - accuracy: 0.9249 - loss: 0.2496

181/573 ━━━━━━━━━━━━━━━━━━━━ 20s 53ms/step - accuracy: 0.9253 - loss: 0.2485

182/573 ━━━━━━━━━━━━━━━━━━━━ 20s 53ms/step - accuracy: 0.9255 - loss: 0.2477

183/573 ━━━━━━━━━━━━━━━━━━━━ 20s 53ms/step - accuracy: 0.9257 - loss: 0.2478

184/573 ━━━━━━━━━━━━━━━━━━━━ 20s 53ms/step - accuracy: 0.9258 - loss: 0.2485

185/573 ━━━━━━━━━━━━━━━━━━━━ 20s 53ms/step - accuracy: 0.9259 - loss: 0.2479

186/573 ━━━━━━━━━━━━━━━━━━━━ 20s 53ms/step - accuracy: 0.9256 - loss: 0.2498

187/573 ━━━━━━━━━━━━━━━━━━━━ 20s 53ms/step - accuracy: 0.9255 - loss: 0.2501

188/573 ━━━━━━━━━━━━━━━━━━━━ 20s 53ms/step - accuracy: 0.9256 - loss: 0.2501

190/573 ━━━━━━━━━━━━━━━━━━━━ 20s 53ms/step - accuracy: 0.9259 - loss: 0.2491

192/573 ━━━━━━━━━━━━━━━━━━━━ 20s 53ms/step - accuracy: 0.9256 - loss: 0.2490

193/573 ━━━━━━━━━━━━━━━━━━━━ 20s 53ms/step - accuracy: 0.9257 - loss: 0.2492

195/573 ━━━━━━━━━━━━━━━━━━━━ 19s 53ms/step - accuracy: 0.9262 - loss: 0.2477

197/573 ━━━━━━━━━━━━━━━━━━━━ 19s 53ms/step - accuracy: 0.9258 - loss: 0.2480

199/573 ━━━━━━━━━━━━━━━━━━━━ 19s 53ms/step - accuracy: 0.9258 - loss: 0.2476

201/573 ━━━━━━━━━━━━━━━━━━━━ 19s 53ms/step - accuracy: 0.9260 - loss: 0.2465

203/573 ━━━━━━━━━━━━━━━━━━━━ 19s 53ms/step - accuracy: 0.9264 - loss: 0.2473

204/573 ━━━━━━━━━━━━━━━━━━━━ 19s 53ms/step - accuracy: 0.9263 - loss: 0.2478

205/573 ━━━━━━━━━━━━━━━━━━━━ 19s 53ms/step - accuracy: 0.9262 - loss: 0.2477

206/573 ━━━━━━━━━━━━━━━━━━━━ 19s 53ms/step - accuracy: 0.9263 - loss: 0.2471

207/573 ━━━━━━━━━━━━━━━━━━━━ 19s 53ms/step - accuracy: 0.9262 - loss: 0.2472

208/573 ━━━━━━━━━━━━━━━━━━━━ 19s 53ms/step - accuracy: 0.9264 - loss: 0.2468

209/573 ━━━━━━━━━━━━━━━━━━━━ 19s 53ms/step - accuracy: 0.9262 - loss: 0.2478

210/573 ━━━━━━━━━━━━━━━━━━━━ 19s 53ms/step - accuracy: 0.9258 - loss: 0.2486

211/573 ━━━━━━━━━━━━━━━━━━━━ 19s 53ms/step - accuracy: 0.9258 - loss: 0.2481

213/573 ━━━━━━━━━━━━━━━━━━━━ 18s 52ms/step - accuracy: 0.9255 - loss: 0.2490

215/573 ━━━━━━━━━━━━━━━━━━━━ 18s 52ms/step - accuracy: 0.9250 - loss: 0.2495

217/573 ━━━━━━━━━━━━━━━━━━━━ 18s 52ms/step - accuracy: 0.9253 - loss: 0.2486

219/573 ━━━━━━━━━━━━━━━━━━━━ 18s 52ms/step - accuracy: 0.9254 - loss: 0.2483

221/573 ━━━━━━━━━━━━━━━━━━━━ 18s 52ms/step - accuracy: 0.9256 - loss: 0.2479

223/573 ━━━━━━━━━━━━━━━━━━━━ 18s 52ms/step - accuracy: 0.9255 - loss: 0.2486

225/573 ━━━━━━━━━━━━━━━━━━━━ 18s 52ms/step - accuracy: 0.9260 - loss: 0.2471

227/573 ━━━━━━━━━━━━━━━━━━━━ 18s 52ms/step - accuracy: 0.9262 - loss: 0.2463

229/573 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - accuracy: 0.9263 - loss: 0.2478

231/573 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - accuracy: 0.9266 - loss: 0.2472

233/573 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - accuracy: 0.9264 - loss: 0.2477

234/573 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - accuracy: 0.9264 - loss: 0.2473

235/573 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - accuracy: 0.9262 - loss: 0.2478

236/573 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - accuracy: 0.9263 - loss: 0.2474

237/573 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - accuracy: 0.9264 - loss: 0.2469

238/573 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - accuracy: 0.9262 - loss: 0.2471

239/573 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - accuracy: 0.9264 - loss: 0.2466

240/573 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - accuracy: 0.9265 - loss: 0.2465

241/573 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - accuracy: 0.9265 - loss: 0.2461

242/573 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - accuracy: 0.9267 - loss: 0.2456

244/573 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - accuracy: 0.9269 - loss: 0.2451

245/573 ━━━━━━━━━━━━━━━━━━━━ 17s 52ms/step - accuracy: 0.9267 - loss: 0.2460

246/573 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - accuracy: 0.9270 - loss: 0.2453

247/573 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - accuracy: 0.9269 - loss: 0.2461

249/573 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - accuracy: 0.9272 - loss: 0.2456

251/573 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - accuracy: 0.9276 - loss: 0.2446

252/573 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - accuracy: 0.9276 - loss: 0.2440

253/573 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - accuracy: 0.9273 - loss: 0.2452

254/573 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - accuracy: 0.9273 - loss: 0.2451

255/573 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - accuracy: 0.9274 - loss: 0.2455

257/573 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - accuracy: 0.9278 - loss: 0.2447

259/573 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - accuracy: 0.9274 - loss: 0.2444

261/573 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - accuracy: 0.9272 - loss: 0.2444

263/573 ━━━━━━━━━━━━━━━━━━━━ 16s 52ms/step - accuracy: 0.9277 - loss: 0.2432

264/573 ━━━━━━━━━━━━━━━━━━━━ 15s 52ms/step - accuracy: 0.9279 - loss: 0.2425

265/573 ━━━━━━━━━━━━━━━━━━━━ 15s 52ms/step - accuracy: 0.9275 - loss: 0.2439

266/573 ━━━━━━━━━━━━━━━━━━━━ 15s 52ms/step - accuracy: 0.9272 - loss: 0.2442

268/573 ━━━━━━━━━━━━━━━━━━━━ 15s 52ms/step - accuracy: 0.9269 - loss: 0.2448

270/573 ━━━━━━━━━━━━━━━━━━━━ 15s 52ms/step - accuracy: 0.9269 - loss: 0.2440

272/573 ━━━━━━━━━━━━━━━━━━━━ 15s 52ms/step - accuracy: 0.9266 - loss: 0.2446

274/573 ━━━━━━━━━━━━━━━━━━━━ 15s 52ms/step - accuracy: 0.9270 - loss: 0.2432

276/573 ━━━━━━━━━━━━━━━━━━━━ 15s 52ms/step - accuracy: 0.9270 - loss: 0.2425

278/573 ━━━━━━━━━━━━━━━━━━━━ 15s 52ms/step - accuracy: 0.9270 - loss: 0.2435

280/573 ━━━━━━━━━━━━━━━━━━━━ 15s 51ms/step - accuracy: 0.9270 - loss: 0.2435

282/573 ━━━━━━━━━━━━━━━━━━━━ 14s 51ms/step - accuracy: 0.9274 - loss: 0.2427

284/573 ━━━━━━━━━━━━━━━━━━━━ 14s 51ms/step - accuracy: 0.9272 - loss: 0.2426

285/573 ━━━━━━━━━━━━━━━━━━━━ 14s 51ms/step - accuracy: 0.9270 - loss: 0.2432

286/573 ━━━━━━━━━━━━━━━━━━━━ 14s 51ms/step - accuracy: 0.9269 - loss: 0.2436

287/573 ━━━━━━━━━━━━━━━━━━━━ 14s 51ms/step - accuracy: 0.9269 - loss: 0.2436

288/573 ━━━━━━━━━━━━━━━━━━━━ 14s 51ms/step - accuracy: 0.9268 - loss: 0.2437

289/573 ━━━━━━━━━━━━━━━━━━━━ 14s 51ms/step - accuracy: 0.9269 - loss: 0.2430

290/573 ━━━━━━━━━━━━━━━━━━━━ 14s 51ms/step - accuracy: 0.9271 - loss: 0.2427

291/573 ━━━━━━━━━━━━━━━━━━━━ 14s 51ms/step - accuracy: 0.9270 - loss: 0.2425

292/573 ━━━━━━━━━━━━━━━━━━━━ 14s 51ms/step - accuracy: 0.9269 - loss: 0.2425

293/573 ━━━━━━━━━━━━━━━━━━━━ 14s 51ms/step - accuracy: 0.9270 - loss: 0.2423

294/573 ━━━━━━━━━━━━━━━━━━━━ 14s 51ms/step - accuracy: 0.9269 - loss: 0.2424

295/573 ━━━━━━━━━━━━━━━━━━━━ 14s 51ms/step - accuracy: 0.9270 - loss: 0.2420

296/573 ━━━━━━━━━━━━━━━━━━━━ 14s 51ms/step - accuracy: 0.9268 - loss: 0.2422

297/573 ━━━━━━━━━━━━━━━━━━━━ 14s 51ms/step - accuracy: 0.9269 - loss: 0.2417

298/573 ━━━━━━━━━━━━━━━━━━━━ 14s 51ms/step - accuracy: 0.9266 - loss: 0.2425

299/573 ━━━━━━━━━━━━━━━━━━━━ 14s 51ms/step - accuracy: 0.9267 - loss: 0.2422

300/573 ━━━━━━━━━━━━━━━━━━━━ 14s 51ms/step - accuracy: 0.9265 - loss: 0.2423

302/573 ━━━━━━━━━━━━━━━━━━━━ 13s 51ms/step - accuracy: 0.9268 - loss: 0.2420

304/573 ━━━━━━━━━━━━━━━━━━━━ 13s 51ms/step - accuracy: 0.9266 - loss: 0.2431

306/573 ━━━━━━━━━━━━━━━━━━━━ 13s 51ms/step - accuracy: 0.9267 - loss: 0.2430

307/573 ━━━━━━━━━━━━━━━━━━━━ 13s 51ms/step - accuracy: 0.9267 - loss: 0.2427

308/573 ━━━━━━━━━━━━━━━━━━━━ 13s 51ms/step - accuracy: 0.9267 - loss: 0.2433

309/573 ━━━━━━━━━━━━━━━━━━━━ 13s 51ms/step - accuracy: 0.9268 - loss: 0.2431

310/573 ━━━━━━━━━━━━━━━━━━━━ 13s 51ms/step - accuracy: 0.9267 - loss: 0.2435

311/573 ━━━━━━━━━━━━━━━━━━━━ 13s 51ms/step - accuracy: 0.9267 - loss: 0.2443

312/573 ━━━━━━━━━━━━━━━━━━━━ 13s 51ms/step - accuracy: 0.9266 - loss: 0.2443

313/573 ━━━━━━━━━━━━━━━━━━━━ 13s 51ms/step - accuracy: 0.9268 - loss: 0.2438

315/573 ━━━━━━━━━━━━━━━━━━━━ 13s 51ms/step - accuracy: 0.9271 - loss: 0.2433

317/573 ━━━━━━━━━━━━━━━━━━━━ 13s 51ms/step - accuracy: 0.9274 - loss: 0.2424

318/573 ━━━━━━━━━━━━━━━━━━━━ 13s 51ms/step - accuracy: 0.9271 - loss: 0.2434

319/573 ━━━━━━━━━━━━━━━━━━━━ 13s 51ms/step - accuracy: 0.9271 - loss: 0.2437

320/573 ━━━━━━━━━━━━━━━━━━━━ 13s 51ms/step - accuracy: 0.9269 - loss: 0.2443

321/573 ━━━━━━━━━━━━━━━━━━━━ 12s 51ms/step - accuracy: 0.9270 - loss: 0.2438

322/573 ━━━━━━━━━━━━━━━━━━━━ 12s 51ms/step - accuracy: 0.9270 - loss: 0.2434

324/573 ━━━━━━━━━━━━━━━━━━━━ 12s 51ms/step - accuracy: 0.9271 - loss: 0.2431

326/573 ━━━━━━━━━━━━━━━━━━━━ 12s 51ms/step - accuracy: 0.9275 - loss: 0.2425

328/573 ━━━━━━━━━━━━━━━━━━━━ 12s 51ms/step - accuracy: 0.9274 - loss: 0.2432

330/573 ━━━━━━━━━━━━━━━━━━━━ 12s 51ms/step - accuracy: 0.9275 - loss: 0.2438

332/573 ━━━━━━━━━━━━━━━━━━━━ 12s 51ms/step - accuracy: 0.9276 - loss: 0.2440

334/573 ━━━━━━━━━━━━━━━━━━━━ 12s 51ms/step - accuracy: 0.9272 - loss: 0.2445

336/573 ━━━━━━━━━━━━━━━━━━━━ 12s 51ms/step - accuracy: 0.9271 - loss: 0.2453

338/573 ━━━━━━━━━━━━━━━━━━━━ 12s 51ms/step - accuracy: 0.9269 - loss: 0.2450

340/573 ━━━━━━━━━━━━━━━━━━━━ 11s 51ms/step - accuracy: 0.9267 - loss: 0.2456

342/573 ━━━━━━━━━━━━━━━━━━━━ 11s 51ms/step - accuracy: 0.9268 - loss: 0.2452

344/573 ━━━━━━━━━━━━━━━━━━━━ 11s 51ms/step - accuracy: 0.9267 - loss: 0.2456

346/573 ━━━━━━━━━━━━━━━━━━━━ 11s 51ms/step - accuracy: 0.9264 - loss: 0.2459

348/573 ━━━━━━━━━━━━━━━━━━━━ 11s 51ms/step - accuracy: 0.9267 - loss: 0.2453

350/573 ━━━━━━━━━━━━━━━━━━━━ 11s 51ms/step - accuracy: 0.9266 - loss: 0.2447

352/573 ━━━━━━━━━━━━━━━━━━━━ 11s 51ms/step - accuracy: 0.9264 - loss: 0.2455

354/573 ━━━━━━━━━━━━━━━━━━━━ 11s 51ms/step - accuracy: 0.9264 - loss: 0.2455

356/573 ━━━━━━━━━━━━━━━━━━━━ 11s 51ms/step - accuracy: 0.9268 - loss: 0.2446

358/573 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - accuracy: 0.9269 - loss: 0.2442

360/573 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - accuracy: 0.9268 - loss: 0.2447

362/573 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - accuracy: 0.9272 - loss: 0.2437

364/573 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - accuracy: 0.9271 - loss: 0.2435

366/573 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - accuracy: 0.9273 - loss: 0.2431

368/573 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - accuracy: 0.9267 - loss: 0.2442

370/573 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - accuracy: 0.9268 - loss: 0.2446

372/573 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - accuracy: 0.9269 - loss: 0.2440

374/573 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - accuracy: 0.9270 - loss: 0.2441

376/573 ━━━━━━━━━━━━━━━━━━━━ 10s 51ms/step - accuracy: 0.9268 - loss: 0.2446

378/573 ━━━━━━━━━━━━━━━━━━━━ 9s 51ms/step - accuracy: 0.9268 - loss: 0.2445

380/573 ━━━━━━━━━━━━━━━━━━━━ 9s 51ms/step - accuracy: 0.9268 - loss: 0.2443

382/573 ━━━━━━━━━━━━━━━━━━━━ 9s 51ms/step - accuracy: 0.9266 - loss: 0.2447

384/573 ━━━━━━━━━━━━━━━━━━━━ 9s 51ms/step - accuracy: 0.9267 - loss: 0.2444

386/573 ━━━━━━━━━━━━━━━━━━━━ 9s 51ms/step - accuracy: 0.9267 - loss: 0.2441

388/573 ━━━━━━━━━━━━━━━━━━━━ 9s 51ms/step - accuracy: 0.9267 - loss: 0.2438

390/573 ━━━━━━━━━━━━━━━━━━━━ 9s 51ms/step - accuracy: 0.9269 - loss: 0.2434

392/573 ━━━━━━━━━━━━━━━━━━━━ 9s 51ms/step - accuracy: 0.9269 - loss: 0.2430

394/573 ━━━━━━━━━━━━━━━━━━━━ 9s 51ms/step - accuracy: 0.9270 - loss: 0.2428

396/573 ━━━━━━━━━━━━━━━━━━━━ 8s 51ms/step - accuracy: 0.9273 - loss: 0.2421

398/573 ━━━━━━━━━━━━━━━━━━━━ 8s 51ms/step - accuracy: 0.9270 - loss: 0.2433

400/573 ━━━━━━━━━━━━━━━━━━━━ 8s 51ms/step - accuracy: 0.9267 - loss: 0.2438

402/573 ━━━━━━━━━━━━━━━━━━━━ 8s 51ms/step - accuracy: 0.9266 - loss: 0.2446

404/573 ━━━━━━━━━━━━━━━━━━━━ 8s 51ms/step - accuracy: 0.9266 - loss: 0.2446

406/573 ━━━━━━━━━━━━━━━━━━━━ 8s 50ms/step - accuracy: 0.9264 - loss: 0.2445

408/573 ━━━━━━━━━━━━━━━━━━━━ 8s 50ms/step - accuracy: 0.9264 - loss: 0.2442

410/573 ━━━━━━━━━━━━━━━━━━━━ 8s 50ms/step - accuracy: 0.9264 - loss: 0.2443

412/573 ━━━━━━━━━━━━━━━━━━━━ 8s 50ms/step - accuracy: 0.9262 - loss: 0.2443

414/573 ━━━━━━━━━━━━━━━━━━━━ 8s 50ms/step - accuracy: 0.9260 - loss: 0.2446

416/573 ━━━━━━━━━━━━━━━━━━━━ 7s 50ms/step - accuracy: 0.9261 - loss: 0.2454

418/573 ━━━━━━━━━━━━━━━━━━━━ 7s 50ms/step - accuracy: 0.9260 - loss: 0.2458

420/573 ━━━━━━━━━━━━━━━━━━━━ 7s 50ms/step - accuracy: 0.9261 - loss: 0.2452

422/573 ━━━━━━━━━━━━━━━━━━━━ 7s 50ms/step - accuracy: 0.9263 - loss: 0.2452

424/573 ━━━━━━━━━━━━━━━━━━━━ 7s 50ms/step - accuracy: 0.9264 - loss: 0.2453

426/573 ━━━━━━━━━━━━━━━━━━━━ 7s 50ms/step - accuracy: 0.9264 - loss: 0.2448

428/573 ━━━━━━━━━━━━━━━━━━━━ 7s 50ms/step - accuracy: 0.9263 - loss: 0.2454

430/573 ━━━━━━━━━━━━━━━━━━━━ 7s 50ms/step - accuracy: 0.9264 - loss: 0.2452

432/573 ━━━━━━━━━━━━━━━━━━━━ 7s 50ms/step - accuracy: 0.9263 - loss: 0.2455

434/573 ━━━━━━━━━━━━━━━━━━━━ 6s 50ms/step - accuracy: 0.9263 - loss: 0.2455

436/573 ━━━━━━━━━━━━━━━━━━━━ 6s 50ms/step - accuracy: 0.9260 - loss: 0.2459

438/573 ━━━━━━━━━━━━━━━━━━━━ 6s 50ms/step - accuracy: 0.9262 - loss: 0.2451

440/573 ━━━━━━━━━━━━━━━━━━━━ 6s 50ms/step - accuracy: 0.9263 - loss: 0.2447

442/573 ━━━━━━━━━━━━━━━━━━━━ 6s 50ms/step - accuracy: 0.9264 - loss: 0.2443

444/573 ━━━━━━━━━━━━━━━━━━━━ 6s 50ms/step - accuracy: 0.9264 - loss: 0.2444

446/573 ━━━━━━━━━━━━━━━━━━━━ 6s 50ms/step - accuracy: 0.9263 - loss: 0.2448

448/573 ━━━━━━━━━━━━━━━━━━━━ 6s 50ms/step - accuracy: 0.9264 - loss: 0.2448

450/573 ━━━━━━━━━━━━━━━━━━━━ 6s 50ms/step - accuracy: 0.9264 - loss: 0.2455

452/573 ━━━━━━━━━━━━━━━━━━━━ 6s 50ms/step - accuracy: 0.9264 - loss: 0.2451

454/573 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step - accuracy: 0.9266 - loss: 0.2446

456/573 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step - accuracy: 0.9268 - loss: 0.2441

457/573 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step - accuracy: 0.9266 - loss: 0.2441

459/573 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step - accuracy: 0.9265 - loss: 0.2443

461/573 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step - accuracy: 0.9265 - loss: 0.2439

463/573 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step - accuracy: 0.9263 - loss: 0.2445

465/573 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step - accuracy: 0.9264 - loss: 0.2441

467/573 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step - accuracy: 0.9265 - loss: 0.2439

469/573 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step - accuracy: 0.9265 - loss: 0.2435

470/573 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step - accuracy: 0.9265 - loss: 0.2433

471/573 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step - accuracy: 0.9264 - loss: 0.2435

472/573 ━━━━━━━━━━━━━━━━━━━━ 5s 50ms/step - accuracy: 0.9265 - loss: 0.2433

473/573 ━━━━━━━━━━━━━━━━━━━━ 4s 50ms/step - accuracy: 0.9263 - loss: 0.2435

474/573 ━━━━━━━━━━━━━━━━━━━━ 4s 50ms/step - accuracy: 0.9263 - loss: 0.2437

475/573 ━━━━━━━━━━━━━━━━━━━━ 4s 50ms/step - accuracy: 0.9263 - loss: 0.2439

476/573 ━━━━━━━━━━━━━━━━━━━━ 4s 50ms/step - accuracy: 0.9262 - loss: 0.2439

477/573 ━━━━━━━━━━━━━━━━━━━━ 4s 50ms/step - accuracy: 0.9261 - loss: 0.2443

479/573 ━━━━━━━━━━━━━━━━━━━━ 4s 50ms/step - accuracy: 0.9260 - loss: 0.2448

480/573 ━━━━━━━━━━━━━━━━━━━━ 4s 50ms/step - accuracy: 0.9258 - loss: 0.2451

481/573 ━━━━━━━━━━━━━━━━━━━━ 4s 50ms/step - accuracy: 0.9259 - loss: 0.2448

482/573 ━━━━━━━━━━━━━━━━━━━━ 4s 50ms/step - accuracy: 0.9258 - loss: 0.2447

483/573 ━━━━━━━━━━━━━━━━━━━━ 4s 50ms/step - accuracy: 0.9257 - loss: 0.2448

484/573 ━━━━━━━━━━━━━━━━━━━━ 4s 50ms/step - accuracy: 0.9256 - loss: 0.2451

485/573 ━━━━━━━━━━━━━━━━━━━━ 4s 50ms/step - accuracy: 0.9255 - loss: 0.2456

487/573 ━━━━━━━━━━━━━━━━━━━━ 4s 50ms/step - accuracy: 0.9255 - loss: 0.2457

489/573 ━━━━━━━━━━━━━━━━━━━━ 4s 50ms/step - accuracy: 0.9254 - loss: 0.2458

490/573 ━━━━━━━━━━━━━━━━━━━━ 4s 50ms/step - accuracy: 0.9253 - loss: 0.2464

492/573 ━━━━━━━━━━━━━━━━━━━━ 4s 50ms/step - accuracy: 0.9253 - loss: 0.2467

494/573 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - accuracy: 0.9254 - loss: 0.2463

496/573 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - accuracy: 0.9254 - loss: 0.2460

498/573 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - accuracy: 0.9252 - loss: 0.2463

500/573 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - accuracy: 0.9253 - loss: 0.2460

501/573 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - accuracy: 0.9253 - loss: 0.2461

502/573 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - accuracy: 0.9254 - loss: 0.2458

503/573 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - accuracy: 0.9253 - loss: 0.2458

505/573 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - accuracy: 0.9249 - loss: 0.2463

507/573 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - accuracy: 0.9251 - loss: 0.2460

508/573 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - accuracy: 0.9251 - loss: 0.2459

510/573 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - accuracy: 0.9249 - loss: 0.2462

511/573 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - accuracy: 0.9250 - loss: 0.2460

512/573 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - accuracy: 0.9248 - loss: 0.2465

513/573 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step - accuracy: 0.9247 - loss: 0.2469

515/573 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.9243 - loss: 0.2473

517/573 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.9242 - loss: 0.2473

519/573 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.9242 - loss: 0.2474

521/573 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.9244 - loss: 0.2467

523/573 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.9245 - loss: 0.2468

524/573 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.9246 - loss: 0.2464

525/573 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.9246 - loss: 0.2468

526/573 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.9246 - loss: 0.2466

527/573 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.9247 - loss: 0.2464

528/573 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.9246 - loss: 0.2467

529/573 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.9246 - loss: 0.2466

530/573 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.9247 - loss: 0.2465

531/573 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.9245 - loss: 0.2467

532/573 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.9246 - loss: 0.2464

533/573 ━━━━━━━━━━━━━━━━━━━━ 2s 50ms/step - accuracy: 0.9247 - loss: 0.2461

534/573 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.9248 - loss: 0.2459

535/573 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.9248 - loss: 0.2458

536/573 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.9246 - loss: 0.2463

537/573 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.9246 - loss: 0.2462

538/573 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.9248 - loss: 0.2458

539/573 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.9249 - loss: 0.2455

540/573 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.9250 - loss: 0.2456

541/573 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.9250 - loss: 0.2455

542/573 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.9251 - loss: 0.2452

543/573 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.9251 - loss: 0.2449

544/573 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.9252 - loss: 0.2448

545/573 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.9252 - loss: 0.2445

546/573 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.9252 - loss: 0.2444

548/573 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.9253 - loss: 0.2442

550/573 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.9253 - loss: 0.2446

552/573 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - accuracy: 0.9255 - loss: 0.2441

554/573 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9252 - loss: 0.2447

556/573 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9250 - loss: 0.2449

558/573 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9249 - loss: 0.2450

559/573 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9250 - loss: 0.2446

560/573 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9250 - loss: 0.2448

561/573 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9250 - loss: 0.2446

562/573 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9251 - loss: 0.2443

563/573 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9251 - loss: 0.2445

564/573 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9252 - loss: 0.2444

566/573 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9253 - loss: 0.2441

568/573 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9255 - loss: 0.2439

570/573 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9251 - loss: 0.2451

572/573 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.9251 - loss: 0.2454

573/573 ━━━━━━━━━━━━━━━━━━━━ 35s 60ms/step - accuracy: 0.9250 - loss: 0.2460 - val_accuracy: 0.9366 - val_loss: 0.2206

Epoch 3/20

  1/573 ━━━━━━━━━━━━━━━━━━━━ 1:41 177ms/step - accuracy: 0.9688 - loss: 0.1165

  2/573 ━━━━━━━━━━━━━━━━━━━━ 59s 104ms/step - accuracy: 0.9531 - loss: 0.2437

  3/573 ━━━━━━━━━━━━━━━━━━━━ 44s 79ms/step - accuracy: 0.9375 - loss: 0.2878

  4/573 ━━━━━━━━━━━━━━━━━━━━ 39s 69ms/step - accuracy: 0.9297 - loss: 0.2672

  5/573 ━━━━━━━━━━━━━━━━━━━━ 36s 65ms/step - accuracy: 0.9250 - loss: 0.2568

  6/573 ━━━━━━━━━━━━━━━━━━━━ 35s 62ms/step - accuracy: 0.9219 - loss: 0.2522

  7/573 ━━━━━━━━━━━━━━━━━━━━ 34s 60ms/step - accuracy: 0.9196 - loss: 0.2470

  8/573 ━━━━━━━━━━━━━━━━━━━━ 33s 59ms/step - accuracy: 0.9141 - loss: 0.2728

  9/573 ━━━━━━━━━━━━━━━━━━━━ 32s 58ms/step - accuracy: 0.9201 - loss: 0.2505

 10/573 ━━━━━━━━━━━━━━━━━━━━ 32s 57ms/step - accuracy: 0.9250 - loss: 0.2471

 11/573 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.9290 - loss: 0.2501

 12/573 ━━━━━━━━━━━━━━━━━━━━ 31s 56ms/step - accuracy: 0.9323 - loss: 0.2423

 13/573 ━━━━━━━━━━━━━━━━━━━━ 31s 56ms/step - accuracy: 0.9351 - loss: 0.2316

 14/573 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.9330 - loss: 0.2281

 15/573 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.9250 - loss: 0.2389

 16/573 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.9277 - loss: 0.2281

 17/573 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.9265 - loss: 0.2310

 18/573 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.9288 - loss: 0.2265

 19/573 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.9293 - loss: 0.2290

 21/573 ━━━━━━━━━━━━━━━━━━━━ 29s 54ms/step - accuracy: 0.9271 - loss: 0.2411

 22/573 ━━━━━━━━━━━━━━━━━━━━ 29s 54ms/step - accuracy: 0.9261 - loss: 0.2403

 23/573 ━━━━━━━━━━━━━━━━━━━━ 29s 54ms/step - accuracy: 0.9253 - loss: 0.2346

 24/573 ━━━━━━━━━━━━━━━━━━━━ 29s 54ms/step - accuracy: 0.9206 - loss: 0.2443

 25/573 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.9187 - loss: 0.2505

 26/573 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.9219 - loss: 0.2421

 27/573 ━━━━━━━━━━━━━━━━━━━━ 29s 54ms/step - accuracy: 0.9225 - loss: 0.2408

 29/573 ━━━━━━━━━━━━━━━━━━━━ 29s 54ms/step - accuracy: 0.9235 - loss: 0.2373

 31/573 ━━━━━━━━━━━━━━━━━━━━ 29s 54ms/step - accuracy: 0.9224 - loss: 0.2412

 33/573 ━━━━━━━━━━━━━━━━━━━━ 28s 54ms/step - accuracy: 0.9195 - loss: 0.2396

 34/573 ━━━━━━━━━━━━━━━━━━━━ 28s 54ms/step - accuracy: 0.9210 - loss: 0.2364

 35/573 ━━━━━━━━━━━━━━━━━━━━ 28s 53ms/step - accuracy: 0.9223 - loss: 0.2310

 36/573 ━━━━━━━━━━━━━━━━━━━━ 28s 53ms/step - accuracy: 0.9236 - loss: 0.2280

 38/573 ━━━━━━━━━━━━━━━━━━━━ 28s 53ms/step - accuracy: 0.9268 - loss: 0.2231

 39/573 ━━━━━━━━━━━━━━━━━━━━ 28s 53ms/step - accuracy: 0.9279 - loss: 0.2197

 41/573 ━━━━━━━━━━━━━━━━━━━━ 28s 53ms/step - accuracy: 0.9276 - loss: 0.2192

 42/573 ━━━━━━━━━━━━━━━━━━━━ 27s 53ms/step - accuracy: 0.9271 - loss: 0.2194

 44/573 ━━━━━━━━━━━━━━━━━━━━ 27s 53ms/step - accuracy: 0.9268 - loss: 0.2165

 46/573 ━━━━━━━━━━━━━━━━━━━━ 27s 52ms/step - accuracy: 0.9260 - loss: 0.2295

 48/573 ━━━━━━━━━━━━━━━━━━━━ 27s 52ms/step - accuracy: 0.9258 - loss: 0.2317

 50/573 ━━━━━━━━━━━━━━━━━━━━ 27s 52ms/step - accuracy: 0.9250 - loss: 0.2343

 51/573 ━━━━━━━━━━━━━━━━━━━━ 27s 52ms/step - accuracy: 0.9246 - loss: 0.2335

 52/573 ━━━━━━━━━━━━━━━━━━━━ 27s 52ms/step - accuracy: 0.9255 - loss: 0.2305

 53/573 ━━━━━━━━━━━━━━━━━━━━ 27s 52ms/step - accuracy: 0.9239 - loss: 0.2343

 55/573 ━━━━━━━━━━━━━━━━━━━━ 27s 52ms/step - accuracy: 0.9250 - loss: 0.2323

 57/573 ━━━━━━━━━━━━━━━━━━━━ 26s 52ms/step - accuracy: 0.9260 - loss: 0.2312

 59/573 ━━━━━━━━━━━━━━━━━━━━ 26s 52ms/step - accuracy: 0.9280 - loss: 0.2250

 61/573 ━━━━━━━━━━━━━━━━━━━━ 26s 52ms/step - accuracy: 0.9283 - loss: 0.2218

 62/573 ━━━━━━━━━━━━━━━━━━━━ 26s 52ms/step - accuracy: 0.9294 - loss: 0.2188

 64/573 ━━━━━━━━━━━━━━━━━━━━ 26s 52ms/step - accuracy: 0.9297 - loss: 0.2196

 66/573 ━━━━━━━━━━━━━━━━━━━━ 26s 53ms/step - accuracy: 0.9309 - loss: 0.2156

 68/573 ━━━━━━━━━━━━━━━━━━━━ 26s 53ms/step - accuracy: 0.9301 - loss: 0.2183

 70/573 ━━━━━━━━━━━━━━━━━━━━ 26s 52ms/step - accuracy: 0.9308 - loss: 0.2156

 72/573 ━━━━━━━━━━━━━━━━━━━━ 26s 52ms/step - accuracy: 0.9319 - loss: 0.2143

 74/573 ━━━━━━━━━━━━━━━━━━━━ 26s 52ms/step - accuracy: 0.9324 - loss: 0.2118

 75/573 ━━━━━━━━━━━━━━━━━━━━ 25s 52ms/step - accuracy: 0.9317 - loss: 0.2134

 77/573 ━━━━━━━━━━━━━━━━━━━━ 25s 52ms/step - accuracy: 0.9330 - loss: 0.2116

 79/573 ━━━━━━━━━━━━━━━━━━━━ 25s 52ms/step - accuracy: 0.9335 - loss: 0.2106

 81/573 ━━━━━━━━━━━━━━━━━━━━ 25s 52ms/step - accuracy: 0.9348 - loss: 0.2072

 83/573 ━━━━━━━━━━━━━━━━━━━━ 25s 52ms/step - accuracy: 0.9352 - loss: 0.2052

 85/573 ━━━━━━━━━━━━━━━━━━━━ 25s 52ms/step - accuracy: 0.9357 - loss: 0.2034

 87/573 ━━━━━━━━━━━━━━━━━━━━ 25s 51ms/step - accuracy: 0.9346 - loss: 0.2068

 89/573 ━━━━━━━━━━━━━━━━━━━━ 24s 51ms/step - accuracy: 0.9347 - loss: 0.2053

 91/573 ━━━━━━━━━━━━━━━━━━━━ 24s 51ms/step - accuracy: 0.9344 - loss: 0.2078

 92/573 ━━━━━━━━━━━━━━━━━━━━ 24s 51ms/step - accuracy: 0.9344 - loss: 0.2076

 94/573 ━━━━━━━━━━━━━━━━━━━━ 24s 51ms/step - accuracy: 0.9338 - loss: 0.2079

 96/573 ━━━━━━━━━━━━━━━━━━━━ 24s 51ms/step - accuracy: 0.9339 - loss: 0.2071

 97/573 ━━━━━━━━━━━━━━━━━━━━ 24s 51ms/step - accuracy: 0.9343 - loss: 0.2058

 98/573 ━━━━━━━━━━━━━━━━━━━━ 24s 51ms/step - accuracy: 0.9334 - loss: 0.2078

 99/573 ━━━━━━━━━━━━━━━━━━━━ 24s 51ms/step - accuracy: 0.9331 - loss: 0.2103

100/573 ━━━━━━━━━━━━━━━━━━━━ 24s 51ms/step - accuracy: 0.9334 - loss: 0.2099

101/573 ━━━━━━━━━━━━━━━━━━━━ 24s 51ms/step - accuracy: 0.9335 - loss: 0.2096

102/573 ━━━━━━━━━━━━━━━━━━━━ 24s 51ms/step - accuracy: 0.9329 - loss: 0.2120

104/573 ━━━━━━━━━━━━━━━━━━━━ 23s 51ms/step - accuracy: 0.9339 - loss: 0.2106

106/573 ━━━━━━━━━━━━━━━━━━━━ 23s 51ms/step - accuracy: 0.9334 - loss: 0.2147

107/573 ━━━━━━━━━━━━━━━━━━━━ 23s 51ms/step - accuracy: 0.9331 - loss: 0.2157

109/573 ━━━━━━━━━━━━━━━━━━━━ 23s 51ms/step - accuracy: 0.9335 - loss: 0.2147

111/573 ━━━━━━━━━━━━━━━━━━━━ 23s 51ms/step - accuracy: 0.9330 - loss: 0.2143

113/573 ━━━━━━━━━━━━━━━━━━━━ 23s 51ms/step - accuracy: 0.9339 - loss: 0.2116

115/573 ━━━━━━━━━━━━━━━━━━━━ 23s 51ms/step - accuracy: 0.9340 - loss: 0.2108

117/573 ━━━━━━━━━━━━━━━━━━━━ 23s 51ms/step - accuracy: 0.9346 - loss: 0.2097

119/573 ━━━━━━━━━━━━━━━━━━━━ 23s 51ms/step - accuracy: 0.9341 - loss: 0.2117

121/573 ━━━━━━━━━━━━━━━━━━━━ 22s 51ms/step - accuracy: 0.9352 - loss: 0.2091

123/573 ━━━━━━━━━━━━━━━━━━━━ 22s 51ms/step - accuracy: 0.9360 - loss: 0.2073

125/573 ━━━━━━━━━━━━━━━━━━━━ 22s 51ms/step - accuracy: 0.9365 - loss: 0.2056

127/573 ━━━━━━━━━━━━━━━━━━━━ 22s 51ms/step - accuracy: 0.9363 - loss: 0.2058

129/573 ━━━━━━━━━━━━━━━━━━━━ 22s 50ms/step - accuracy: 0.9360 - loss: 0.2087

131/573 ━━━━━━━━━━━━━━━━━━━━ 22s 50ms/step - accuracy: 0.9356 - loss: 0.2104

133/573 ━━━━━━━━━━━━━━━━━━━━ 22s 50ms/step - accuracy: 0.9354 - loss: 0.2106

135/573 ━━━━━━━━━━━━━━━━━━━━ 22s 50ms/step - accuracy: 0.9352 - loss: 0.2107

137/573 ━━━━━━━━━━━━━━━━━━━━ 21s 50ms/step - accuracy: 0.9348 - loss: 0.2119

139/573 ━━━━━━━━━━━━━━━━━━━━ 21s 50ms/step - accuracy: 0.9346 - loss: 0.2120

141/573 ━━━━━━━━━━━━━━━━━━━━ 21s 50ms/step - accuracy: 0.9346 - loss: 0.2139

142/573 ━━━━━━━━━━━━━━━━━━━━ 21s 50ms/step - accuracy: 0.9346 - loss: 0.2142

143/573 ━━━━━━━━━━━━━━━━━━━━ 21s 50ms/step - accuracy: 0.9347 - loss: 0.2159

144/573 ━━━━━━━━━━━━━━━━━━━━ 21s 50ms/step - accuracy: 0.9347 - loss: 0.2154

146/573 ━━━━━━━━━━━━━━━━━━━━ 21s 50ms/step - accuracy: 0.9351 - loss: 0.2136

148/573 ━━━━━━━━━━━━━━━━━━━━ 21s 50ms/step - accuracy: 0.9352 - loss: 0.2131

150/573 ━━━━━━━━━━━━━━━━━━━━ 21s 50ms/step - accuracy: 0.9348 - loss: 0.2132

152/573 ━━━━━━━━━━━━━━━━━━━━ 21s 50ms/step - accuracy: 0.9354 - loss: 0.2124

154/573 ━━━━━━━━━━━━━━━━━━━━ 21s 50ms/step - accuracy: 0.9353 - loss: 0.2138

156/573 ━━━━━━━━━━━━━━━━━━━━ 20s 50ms/step - accuracy: 0.9347 - loss: 0.2143

158/573 ━━━━━━━━━━━━━━━━━━━━ 20s 50ms/step - accuracy: 0.9341 - loss: 0.2150

160/573 ━━━━━━━━━━━━━━━━━━━━ 20s 50ms/step - accuracy: 0.9344 - loss: 0.2139

162/573 ━━━━━━━━━━━━━━━━━━━━ 20s 50ms/step - accuracy: 0.9342 - loss: 0.2136

164/573 ━━━━━━━━━━━━━━━━━━━━ 20s 50ms/step - accuracy: 0.9341 - loss: 0.2154

166/573 ━━━━━━━━━━━━━━━━━━━━ 20s 50ms/step - accuracy: 0.9341 - loss: 0.2158

168/573 ━━━━━━━━━━━━━━━━━━━━ 20s 50ms/step - accuracy: 0.9338 - loss: 0.2165

170/573 ━━━━━━━━━━━━━━━━━━━━ 20s 50ms/step - accuracy: 0.9333 - loss: 0.2175

172/573 ━━━━━━━━━━━━━━━━━━━━ 20s 50ms/step - accuracy: 0.9330 - loss: 0.2177

173/573 ━━━━━━━━━━━━━━━━━━━━ 19s 50ms/step - accuracy: 0.9333 - loss: 0.2167

174/573 ━━━━━━━━━━━━━━━━━━━━ 19s 50ms/step - accuracy: 0.9334 - loss: 0.2163

176/573 ━━━━━━━━━━━━━━━━━━━━ 19s 50ms/step - accuracy: 0.9332 - loss: 0.2170

178/573 ━━━━━━━━━━━━━━━━━━━━ 19s 50ms/step - accuracy: 0.9335 - loss: 0.2163

180/573 ━━━━━━━━━━━━━━━━━━━━ 19s 50ms/step - accuracy: 0.9330 - loss: 0.2182

181/573 ━━━━━━━━━━━━━━━━━━━━ 19s 50ms/step - accuracy: 0.9330 - loss: 0.2178

183/573 ━━━━━━━━━━━━━━━━━━━━ 19s 50ms/step - accuracy: 0.9329 - loss: 0.2184

185/573 ━━━━━━━━━━━━━━━━━━━━ 19s 50ms/step - accuracy: 0.9331 - loss: 0.2186

187/573 ━━━━━━━━━━━━━━━━━━━━ 19s 50ms/step - accuracy: 0.9328 - loss: 0.2193

189/573 ━━━━━━━━━━━━━━━━━━━━ 19s 50ms/step - accuracy: 0.9332 - loss: 0.2183

191/573 ━━━━━━━━━━━━━━━━━━━━ 19s 50ms/step - accuracy: 0.9334 - loss: 0.2173

193/573 ━━━━━━━━━━━━━━━━━━━━ 18s 50ms/step - accuracy: 0.9330 - loss: 0.2182

195/573 ━━━━━━━━━━━━━━━━━━━━ 18s 50ms/step - accuracy: 0.9330 - loss: 0.2180

197/573 ━━━━━━━━━━━━━━━━━━━━ 18s 50ms/step - accuracy: 0.9326 - loss: 0.2193

199/573 ━━━━━━━━━━━━━━━━━━━━ 18s 50ms/step - accuracy: 0.9326 - loss: 0.2199

201/573 ━━━━━━━━━━━━━━━━━━━━ 18s 50ms/step - accuracy: 0.9330 - loss: 0.2191

203/573 ━━━━━━━━━━━━━━━━━━━━ 18s 50ms/step - accuracy: 0.9329 - loss: 0.2195

205/573 ━━━━━━━━━━━━━━━━━━━━ 18s 50ms/step - accuracy: 0.9329 - loss: 0.2194

206/573 ━━━━━━━━━━━━━━━━━━━━ 18s 50ms/step - accuracy: 0.9328 - loss: 0.2204

208/573 ━━━━━━━━━━━━━━━━━━━━ 18s 50ms/step - accuracy: 0.9327 - loss: 0.2210

210/573 ━━━━━━━━━━━━━━━━━━━━ 18s 50ms/step - accuracy: 0.9329 - loss: 0.2201

212/573 ━━━━━━━━━━━━━━━━━━━━ 17s 50ms/step - accuracy: 0.9329 - loss: 0.2196

214/573 ━━━━━━━━━━━━━━━━━━━━ 17s 50ms/step - accuracy: 0.9331 - loss: 0.2195

216/573 ━━━━━━━━━━━━━━━━━━━━ 17s 50ms/step - accuracy: 0.9329 - loss: 0.2198

218/573 ━━━━━━━━━━━━━━━━━━━━ 17s 50ms/step - accuracy: 0.9329 - loss: 0.2205

220/573 ━━━━━━━━━━━━━━━━━━━━ 17s 50ms/step - accuracy: 0.9330 - loss: 0.2212

222/573 ━━━━━━━━━━━━━━━━━━━━ 17s 50ms/step - accuracy: 0.9330 - loss: 0.2212

224/573 ━━━━━━━━━━━━━━━━━━━━ 17s 49ms/step - accuracy: 0.9328 - loss: 0.2220

226/573 ━━━━━━━━━━━━━━━━━━━━ 17s 49ms/step - accuracy: 0.9322 - loss: 0.2233

228/573 ━━━━━━━━━━━━━━━━━━━━ 17s 49ms/step - accuracy: 0.9322 - loss: 0.2232

230/573 ━━━━━━━━━━━━━━━━━━━━ 16s 49ms/step - accuracy: 0.9322 - loss: 0.2227

232/573 ━━━━━━━━━━━━━━━━━━━━ 16s 49ms/step - accuracy: 0.9322 - loss: 0.2231

234/573 ━━━━━━━━━━━━━━━━━━━━ 16s 49ms/step - accuracy: 0.9327 - loss: 0.2217

236/573 ━━━━━━━━━━━━━━━━━━━━ 16s 49ms/step - accuracy: 0.9330 - loss: 0.2211

238/573 ━━━━━━━━━━━━━━━━━━━━ 16s 49ms/step - accuracy: 0.9330 - loss: 0.2208

240/573 ━━━━━━━━━━━━━━━━━━━━ 16s 49ms/step - accuracy: 0.9333 - loss: 0.2200

242/573 ━━━━━━━━━━━━━━━━━━━━ 16s 49ms/step - accuracy: 0.9331 - loss: 0.2202

244/573 ━━━━━━━━━━━━━━━━━━━━ 16s 49ms/step - accuracy: 0.9333 - loss: 0.2205

246/573 ━━━━━━━━━━━━━━━━━━━━ 16s 49ms/step - accuracy: 0.9336 - loss: 0.2205

248/573 ━━━━━━━━━━━━━━━━━━━━ 16s 49ms/step - accuracy: 0.9333 - loss: 0.2204

250/573 ━━━━━━━━━━━━━━━━━━━━ 15s 49ms/step - accuracy: 0.9336 - loss: 0.2197

252/573 ━━━━━━━━━━━━━━━━━━━━ 15s 49ms/step - accuracy: 0.9337 - loss: 0.2193

254/573 ━━━━━━━━━━━━━━━━━━━━ 15s 49ms/step - accuracy: 0.9337 - loss: 0.2187

256/573 ━━━━━━━━━━━━━━━━━━━━ 15s 49ms/step - accuracy: 0.9337 - loss: 0.2187

258/573 ━━━━━━━━━━━━━━━━━━━━ 15s 49ms/step - accuracy: 0.9339 - loss: 0.2187

260/573 ━━━━━━━━━━━━━━━━━━━━ 15s 49ms/step - accuracy: 0.9334 - loss: 0.2206

262/573 ━━━━━━━━━━━━━━━━━━━━ 15s 49ms/step - accuracy: 0.9339 - loss: 0.2192

264/573 ━━━━━━━━━━━━━━━━━━━━ 15s 49ms/step - accuracy: 0.9339 - loss: 0.2191

266/573 ━━━━━━━━━━━━━━━━━━━━ 15s 49ms/step - accuracy: 0.9334 - loss: 0.2211

268/573 ━━━━━━━━━━━━━━━━━━━━ 15s 49ms/step - accuracy: 0.9335 - loss: 0.2206

269/573 ━━━━━━━━━━━━━━━━━━━━ 14s 49ms/step - accuracy: 0.9334 - loss: 0.2204

270/573 ━━━━━━━━━━━━━━━━━━━━ 14s 49ms/step - accuracy: 0.9334 - loss: 0.2218

271/573 ━━━━━━━━━━━━━━━━━━━━ 14s 49ms/step - accuracy: 0.9335 - loss: 0.2217

272/573 ━━━━━━━━━━━━━━━━━━━━ 14s 49ms/step - accuracy: 0.9334 - loss: 0.2222

273/573 ━━━━━━━━━━━━━━━━━━━━ 14s 49ms/step - accuracy: 0.9334 - loss: 0.2221

274/573 ━━━━━━━━━━━━━━━━━━━━ 14s 49ms/step - accuracy: 0.9334 - loss: 0.2226

275/573 ━━━━━━━━━━━━━━━━━━━━ 14s 49ms/step - accuracy: 0.9334 - loss: 0.2237

276/573 ━━━━━━━━━━━━━━━━━━━━ 14s 49ms/step - accuracy: 0.9334 - loss: 0.2236

277/573 ━━━━━━━━━━━━━━━━━━━━ 14s 49ms/step - accuracy: 0.9334 - loss: 0.2235

279/573 ━━━━━━━━━━━━━━━━━━━━ 14s 49ms/step - accuracy: 0.9338 - loss: 0.2230

280/573 ━━━━━━━━━━━━━━━━━━━━ 14s 49ms/step - accuracy: 0.9340 - loss: 0.2223

281/573 ━━━━━━━━━━━━━━━━━━━━ 14s 49ms/step - accuracy: 0.9338 - loss: 0.2222

283/573 ━━━━━━━━━━━━━━━━━━━━ 14s 49ms/step - accuracy: 0.9337 - loss: 0.2225

285/573 ━━━━━━━━━━━━━━━━━━━━ 14s 49ms/step - accuracy: 0.9337 - loss: 0.2219

287/573 ━━━━━━━━━━━━━━━━━━━━ 14s 49ms/step - accuracy: 0.9335 - loss: 0.2222

289/573 ━━━━━━━━━━━━━━━━━━━━ 13s 49ms/step - accuracy: 0.9337 - loss: 0.2215

291/573 ━━━━━━━━━━━━━━━━━━━━ 13s 49ms/step - accuracy: 0.9334 - loss: 0.2229

293/573 ━━━━━━━━━━━━━━━━━━━━ 13s 49ms/step - accuracy: 0.9334 - loss: 0.2234

295/573 ━━━━━━━━━━━━━━━━━━━━ 13s 49ms/step - accuracy: 0.9332 - loss: 0.2245

297/573 ━━━━━━━━━━━━━━━━━━━━ 13s 49ms/step - accuracy: 0.9333 - loss: 0.2238

299/573 ━━━━━━━━━━━━━━━━━━━━ 13s 49ms/step - accuracy: 0.9334 - loss: 0.2235

301/573 ━━━━━━━━━━━━━━━━━━━━ 13s 49ms/step - accuracy: 0.9331 - loss: 0.2243

303/573 ━━━━━━━━━━━━━━━━━━━━ 13s 49ms/step - accuracy: 0.9329 - loss: 0.2255

305/573 ━━━━━━━━━━━━━━━━━━━━ 13s 49ms/step - accuracy: 0.9330 - loss: 0.2255

307/573 ━━━━━━━━━━━━━━━━━━━━ 13s 49ms/step - accuracy: 0.9330 - loss: 0.2258

309/573 ━━━━━━━━━━━━━━━━━━━━ 12s 49ms/step - accuracy: 0.9333 - loss: 0.2252

311/573 ━━━━━━━━━━━━━━━━━━━━ 12s 49ms/step - accuracy: 0.9334 - loss: 0.2251

313/573 ━━━━━━━━━━━━━━━━━━━━ 12s 49ms/step - accuracy: 0.9332 - loss: 0.2268

315/573 ━━━━━━━━━━━━━━━━━━━━ 12s 49ms/step - accuracy: 0.9334 - loss: 0.2261

317/573 ━━━━━━━━━━━━━━━━━━━━ 12s 49ms/step - accuracy: 0.9337 - loss: 0.2255

319/573 ━━━━━━━━━━━━━━━━━━━━ 12s 49ms/step - accuracy: 0.9339 - loss: 0.2247

321/573 ━━━━━━━━━━━━━━━━━━━━ 12s 49ms/step - accuracy: 0.9341 - loss: 0.2239

323/573 ━━━━━━━━━━━━━━━━━━━━ 12s 49ms/step - accuracy: 0.9339 - loss: 0.2251

325/573 ━━━━━━━━━━━━━━━━━━━━ 12s 49ms/step - accuracy: 0.9338 - loss: 0.2254

327/573 ━━━━━━━━━━━━━━━━━━━━ 12s 49ms/step - accuracy: 0.9339 - loss: 0.2260

329/573 ━━━━━━━━━━━━━━━━━━━━ 11s 49ms/step - accuracy: 0.9338 - loss: 0.2263

331/573 ━━━━━━━━━━━━━━━━━━━━ 11s 49ms/step - accuracy: 0.9340 - loss: 0.2257

333/573 ━━━━━━━━━━━━━━━━━━━━ 11s 49ms/step - accuracy: 0.9339 - loss: 0.2271

335/573 ━━━━━━━━━━━━━━━━━━━━ 11s 49ms/step - accuracy: 0.9343 - loss: 0.2262

337/573 ━━━━━━━━━━━━━━━━━━━━ 11s 49ms/step - accuracy: 0.9343 - loss: 0.2261

339/573 ━━━━━━━━━━━━━━━━━━━━ 11s 49ms/step - accuracy: 0.9342 - loss: 0.2259

341/573 ━━━━━━━━━━━━━━━━━━━━ 11s 49ms/step - accuracy: 0.9340 - loss: 0.2261

343/573 ━━━━━━━━━━━━━━━━━━━━ 11s 49ms/step - accuracy: 0.9341 - loss: 0.2254

345/573 ━━━━━━━━━━━━━━━━━━━━ 11s 49ms/step - accuracy: 0.9341 - loss: 0.2252

346/573 ━━━━━━━━━━━━━━━━━━━━ 11s 49ms/step - accuracy: 0.9342 - loss: 0.2252

347/573 ━━━━━━━━━━━━━━━━━━━━ 11s 49ms/step - accuracy: 0.9341 - loss: 0.2252

349/573 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - accuracy: 0.9341 - loss: 0.2252

351/573 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - accuracy: 0.9340 - loss: 0.2253

353/573 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - accuracy: 0.9343 - loss: 0.2246

355/573 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - accuracy: 0.9342 - loss: 0.2249

356/573 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - accuracy: 0.9342 - loss: 0.2250

358/573 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - accuracy: 0.9340 - loss: 0.2253

359/573 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - accuracy: 0.9339 - loss: 0.2253

360/573 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - accuracy: 0.9338 - loss: 0.2258

361/573 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - accuracy: 0.9340 - loss: 0.2253

363/573 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - accuracy: 0.9338 - loss: 0.2261

365/573 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - accuracy: 0.9340 - loss: 0.2254

367/573 ━━━━━━━━━━━━━━━━━━━━ 10s 49ms/step - accuracy: 0.9342 - loss: 0.2247

369/573 ━━━━━━━━━━━━━━━━━━━━ 9s 49ms/step - accuracy: 0.9344 - loss: 0.2247

371/573 ━━━━━━━━━━━━━━━━━━━━ 9s 49ms/step - accuracy: 0.9344 - loss: 0.2246

373/573 ━━━━━━━━━━━━━━━━━━━━ 9s 49ms/step - accuracy: 0.9343 - loss: 0.2243

375/573 ━━━━━━━━━━━━━━━━━━━━ 9s 49ms/step - accuracy: 0.9342 - loss: 0.2244

377/573 ━━━━━━━━━━━━━━━━━━━━ 9s 49ms/step - accuracy: 0.9341 - loss: 0.2261

379/573 ━━━━━━━━━━━━━━━━━━━━ 9s 49ms/step - accuracy: 0.9340 - loss: 0.2275

381/573 ━━━━━━━━━━━━━━━━━━━━ 9s 49ms/step - accuracy: 0.9341 - loss: 0.2272

383/573 ━━━━━━━━━━━━━━━━━━━━ 9s 49ms/step - accuracy: 0.9339 - loss: 0.2279

385/573 ━━━━━━━━━━━━━━━━━━━━ 9s 49ms/step - accuracy: 0.9337 - loss: 0.2288

387/573 ━━━━━━━━━━━━━━━━━━━━ 9s 49ms/step - accuracy: 0.9337 - loss: 0.2284

389/573 ━━━━━━━━━━━━━━━━━━━━ 8s 49ms/step - accuracy: 0.9339 - loss: 0.2277

391/573 ━━━━━━━━━━━━━━━━━━━━ 8s 49ms/step - accuracy: 0.9339 - loss: 0.2280

393/573 ━━━━━━━━━━━━━━━━━━━━ 8s 49ms/step - accuracy: 0.9338 - loss: 0.2283

395/573 ━━━━━━━━━━━━━━━━━━━━ 8s 49ms/step - accuracy: 0.9338 - loss: 0.2282

397/573 ━━━━━━━━━━━━━━━━━━━━ 8s 49ms/step - accuracy: 0.9338 - loss: 0.2280

399/573 ━━━━━━━━━━━━━━━━━━━━ 8s 49ms/step - accuracy: 0.9341 - loss: 0.2272

401/573 ━━━━━━━━━━━━━━━━━━━━ 8s 49ms/step - accuracy: 0.9340 - loss: 0.2273

403/573 ━━━━━━━━━━━━━━━━━━━━ 8s 49ms/step - accuracy: 0.9339 - loss: 0.2270

405/573 ━━━━━━━━━━━━━━━━━━━━ 8s 49ms/step - accuracy: 0.9341 - loss: 0.2264

407/573 ━━━━━━━━━━━━━━━━━━━━ 8s 49ms/step - accuracy: 0.9338 - loss: 0.2277

409/573 ━━━━━━━━━━━━━━━━━━━━ 7s 49ms/step - accuracy: 0.9335 - loss: 0.2287

411/573 ━━━━━━━━━━━━━━━━━━━━ 7s 49ms/step - accuracy: 0.9334 - loss: 0.2287

413/573 ━━━━━━━━━━━━━━━━━━━━ 7s 49ms/step - accuracy: 0.9335 - loss: 0.2283

415/573 ━━━━━━━━━━━━━━━━━━━━ 7s 49ms/step - accuracy: 0.9334 - loss: 0.2282

416/573 ━━━━━━━━━━━━━━━━━━━━ 7s 49ms/step - accuracy: 0.9335 - loss: 0.2277

417/573 ━━━━━━━━━━━━━━━━━━━━ 7s 49ms/step - accuracy: 0.9335 - loss: 0.2276

418/573 ━━━━━━━━━━━━━━━━━━━━ 7s 49ms/step - accuracy: 0.9335 - loss: 0.2274

420/573 ━━━━━━━━━━━━━━━━━━━━ 7s 49ms/step - accuracy: 0.9334 - loss: 0.2275

421/573 ━━━━━━━━━━━━━━━━━━━━ 7s 49ms/step - accuracy: 0.9334 - loss: 0.2273

423/573 ━━━━━━━━━━━━━━━━━━━━ 7s 49ms/step - accuracy: 0.9335 - loss: 0.2273

425/573 ━━━━━━━━━━━━━━━━━━━━ 7s 49ms/step - accuracy: 0.9337 - loss: 0.2269

427/573 ━━━━━━━━━━━━━━━━━━━━ 7s 49ms/step - accuracy: 0.9336 - loss: 0.2270

429/573 ━━━━━━━━━━━━━━━━━━━━ 7s 49ms/step - accuracy: 0.9338 - loss: 0.2263

431/573 ━━━━━━━━━━━━━━━━━━━━ 6s 49ms/step - accuracy: 0.9337 - loss: 0.2270

433/573 ━━━━━━━━━━━━━━━━━━━━ 6s 49ms/step - accuracy: 0.9340 - loss: 0.2264

435/573 ━━━━━━━━━━━━━━━━━━━━ 6s 49ms/step - accuracy: 0.9340 - loss: 0.2263

437/573 ━━━━━━━━━━━━━━━━━━━━ 6s 49ms/step - accuracy: 0.9342 - loss: 0.2257

438/573 ━━━━━━━━━━━━━━━━━━━━ 6s 49ms/step - accuracy: 0.9343 - loss: 0.2253

440/573 ━━━━━━━━━━━━━━━━━━━━ 6s 49ms/step - accuracy: 0.9342 - loss: 0.2253

442/573 ━━━━━━━━━━━━━━━━━━━━ 6s 49ms/step - accuracy: 0.9343 - loss: 0.2247

444/573 ━━━━━━━━━━━━━━━━━━━━ 6s 49ms/step - accuracy: 0.9344 - loss: 0.2242

446/573 ━━━━━━━━━━━━━━━━━━━━ 6s 49ms/step - accuracy: 0.9341 - loss: 0.2250

448/573 ━━━━━━━━━━━━━━━━━━━━ 6s 49ms/step - accuracy: 0.9342 - loss: 0.2245

450/573 ━━━━━━━━━━━━━━━━━━━━ 5s 49ms/step - accuracy: 0.9340 - loss: 0.2246

452/573 ━━━━━━━━━━━━━━━━━━━━ 5s 49ms/step - accuracy: 0.9341 - loss: 0.2243

454/573 ━━━━━━━━━━━━━━━━━━━━ 5s 49ms/step - accuracy: 0.9340 - loss: 0.2242

456/573 ━━━━━━━━━━━━━━━━━━━━ 5s 49ms/step - accuracy: 0.9341 - loss: 0.2236

458/573 ━━━━━━━━━━━━━━━━━━━━ 5s 49ms/step - accuracy: 0.9342 - loss: 0.2237

460/573 ━━━━━━━━━━━━━━━━━━━━ 5s 49ms/step - accuracy: 0.9341 - loss: 0.2236

462/573 ━━━━━━━━━━━━━━━━━━━━ 5s 49ms/step - accuracy: 0.9341 - loss: 0.2237

464/573 ━━━━━━━━━━━━━━━━━━━━ 5s 49ms/step - accuracy: 0.9339 - loss: 0.2239

466/573 ━━━━━━━━━━━━━━━━━━━━ 5s 49ms/step - accuracy: 0.9341 - loss: 0.2234

468/573 ━━━━━━━━━━━━━━━━━━━━ 5s 49ms/step - accuracy: 0.9338 - loss: 0.2238

470/573 ━━━━━━━━━━━━━━━━━━━━ 5s 49ms/step - accuracy: 0.9338 - loss: 0.2241

472/573 ━━━━━━━━━━━━━━━━━━━━ 4s 49ms/step - accuracy: 0.9340 - loss: 0.2238

474/573 ━━━━━━━━━━━━━━━━━━━━ 4s 49ms/step - accuracy: 0.9340 - loss: 0.2235

476/573 ━━━━━━━━━━━━━━━━━━━━ 4s 49ms/step - accuracy: 0.9338 - loss: 0.2233

478/573 ━━━━━━━━━━━━━━━━━━━━ 4s 49ms/step - accuracy: 0.9338 - loss: 0.2234

480/573 ━━━━━━━━━━━━━━━━━━━━ 4s 49ms/step - accuracy: 0.9338 - loss: 0.2232

482/573 ━━━━━━━━━━━━━━━━━━━━ 4s 49ms/step - accuracy: 0.9336 - loss: 0.2237

484/573 ━━━━━━━━━━━━━━━━━━━━ 4s 49ms/step - accuracy: 0.9336 - loss: 0.2234

486/573 ━━━━━━━━━━━━━━━━━━━━ 4s 49ms/step - accuracy: 0.9335 - loss: 0.2235

488/573 ━━━━━━━━━━━━━━━━━━━━ 4s 49ms/step - accuracy: 0.9334 - loss: 0.2237

490/573 ━━━━━━━━━━━━━━━━━━━━ 4s 49ms/step - accuracy: 0.9333 - loss: 0.2237

492/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9334 - loss: 0.2235

494/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9333 - loss: 0.2233

496/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9334 - loss: 0.2229

498/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9336 - loss: 0.2224

500/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9336 - loss: 0.2222

502/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9337 - loss: 0.2222

504/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9336 - loss: 0.2224

506/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9335 - loss: 0.2230

508/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9336 - loss: 0.2229

510/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9335 - loss: 0.2230

512/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9332 - loss: 0.2237

514/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9331 - loss: 0.2236

516/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9332 - loss: 0.2232

518/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9330 - loss: 0.2237

520/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9329 - loss: 0.2233

522/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9330 - loss: 0.2235

524/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9328 - loss: 0.2242

525/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9328 - loss: 0.2242

527/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9329 - loss: 0.2238

529/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9326 - loss: 0.2242

531/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9325 - loss: 0.2244

533/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9325 - loss: 0.2243

535/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9326 - loss: 0.2240

537/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9326 - loss: 0.2237

539/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9325 - loss: 0.2234

541/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9326 - loss: 0.2232

543/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9322 - loss: 0.2240

545/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9321 - loss: 0.2244

547/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9321 - loss: 0.2243

549/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9322 - loss: 0.2238

551/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9324 - loss: 0.2233

553/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9325 - loss: 0.2228

555/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9325 - loss: 0.2225

557/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9326 - loss: 0.2225

559/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9325 - loss: 0.2227

561/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9325 - loss: 0.2227

563/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9326 - loss: 0.2223

565/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9325 - loss: 0.2225

567/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9326 - loss: 0.2223

569/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9327 - loss: 0.2223

571/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9328 - loss: 0.2217

573/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9328 - loss: 0.2222

573/573 ━━━━━━━━━━━━━━━━━━━━ 34s 58ms/step - accuracy: 0.9328 - loss: 0.2222 - val_accuracy: 0.9389 - val_loss: 0.2119

Epoch 4/20

  1/573 ━━━━━━━━━━━━━━━━━━━━ 45s 79ms/step - accuracy: 0.9688 - loss: 0.2061

  3/573 ━━━━━━━━━━━━━━━━━━━━ 27s 48ms/step - accuracy: 0.9375 - loss: 0.1593

  5/573 ━━━━━━━━━━━━━━━━━━━━ 27s 48ms/step - accuracy: 0.9438 - loss: 0.1940

  7/573 ━━━━━━━━━━━━━━━━━━━━ 27s 48ms/step - accuracy: 0.9464 - loss: 0.2049

  9/573 ━━━━━━━━━━━━━━━━━━━━ 27s 48ms/step - accuracy: 0.9479 - loss: 0.1835

 11/573 ━━━━━━━━━━━━━━━━━━━━ 27s 48ms/step - accuracy: 0.9489 - loss: 0.1877

 13/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9471 - loss: 0.2005

 15/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9479 - loss: 0.2063

 17/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9449 - loss: 0.2115

 19/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9490 - loss: 0.1949

 20/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9484 - loss: 0.1965

 22/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9474 - loss: 0.1959

 24/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9466 - loss: 0.2031

 26/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9459 - loss: 0.2031

 28/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9431 - loss: 0.2139

 30/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9448 - loss: 0.2085

 32/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9463 - loss: 0.1995

 34/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9458 - loss: 0.2047

 36/573 ━━━━━━━━━━━━━━━━━━━━ 25s 48ms/step - accuracy: 0.9427 - loss: 0.2101

 38/573 ━━━━━━━━━━━━━━━━━━━━ 25s 48ms/step - accuracy: 0.9416 - loss: 0.2094

 40/573 ━━━━━━━━━━━━━━━━━━━━ 25s 48ms/step - accuracy: 0.9414 - loss: 0.2049

 42/573 ━━━━━━━━━━━━━━━━━━━━ 25s 48ms/step - accuracy: 0.9420 - loss: 0.2014

 44/573 ━━━━━━━━━━━━━━━━━━━━ 25s 48ms/step - accuracy: 0.9432 - loss: 0.1981

 46/573 ━━━━━━━━━━━━━━━━━━━━ 25s 48ms/step - accuracy: 0.9395 - loss: 0.2074

 48/573 ━━━━━━━━━━━━━━━━━━━━ 25s 48ms/step - accuracy: 0.9401 - loss: 0.2070

 50/573 ━━━━━━━━━━━━━━━━━━━━ 25s 48ms/step - accuracy: 0.9388 - loss: 0.2121

 52/573 ━━━━━━━━━━━━━━━━━━━━ 25s 48ms/step - accuracy: 0.9387 - loss: 0.2113

 54/573 ━━━━━━━━━━━━━━━━━━━━ 25s 48ms/step - accuracy: 0.9387 - loss: 0.2148

 56/573 ━━━━━━━━━━━━━━━━━━━━ 24s 48ms/step - accuracy: 0.9381 - loss: 0.2160

 58/573 ━━━━━━━━━━━━━━━━━━━━ 24s 48ms/step - accuracy: 0.9380 - loss: 0.2158

 60/573 ━━━━━━━━━━━━━━━━━━━━ 24s 48ms/step - accuracy: 0.9380 - loss: 0.2141

 62/573 ━━━━━━━━━━━━━━━━━━━━ 24s 48ms/step - accuracy: 0.9395 - loss: 0.2087

 64/573 ━━━━━━━━━━━━━━━━━━━━ 24s 48ms/step - accuracy: 0.9409 - loss: 0.2040

 66/573 ━━━━━━━━━━━━━━━━━━━━ 24s 48ms/step - accuracy: 0.9394 - loss: 0.2100

 68/573 ━━━━━━━━━━━━━━━━━━━━ 24s 48ms/step - accuracy: 0.9393 - loss: 0.2109

 70/573 ━━━━━━━━━━━━━━━━━━━━ 24s 48ms/step - accuracy: 0.9379 - loss: 0.2118

 72/573 ━━━━━━━━━━━━━━━━━━━━ 24s 48ms/step - accuracy: 0.9384 - loss: 0.2085

 74/573 ━━━━━━━━━━━━━━━━━━━━ 24s 48ms/step - accuracy: 0.9388 - loss: 0.2065

 76/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9396 - loss: 0.2036

 78/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9395 - loss: 0.2021

 80/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9387 - loss: 0.2020

 82/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9379 - loss: 0.2021

 84/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9382 - loss: 0.2037

 86/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9382 - loss: 0.2025

 88/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9379 - loss: 0.2079

 90/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9361 - loss: 0.2102

 92/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9372 - loss: 0.2075

 94/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9365 - loss: 0.2085

 96/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9362 - loss: 0.2101

 98/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9365 - loss: 0.2094

100/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9362 - loss: 0.2106

102/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9360 - loss: 0.2120

104/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9357 - loss: 0.2117

106/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9357 - loss: 0.2107

108/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9352 - loss: 0.2118

110/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9352 - loss: 0.2109

112/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9350 - loss: 0.2111

113/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9353 - loss: 0.2101

115/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9359 - loss: 0.2083

117/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9354 - loss: 0.2101

119/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9354 - loss: 0.2088

121/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9360 - loss: 0.2074

123/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9362 - loss: 0.2063

125/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9358 - loss: 0.2067

127/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9363 - loss: 0.2049

129/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9358 - loss: 0.2063

131/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9361 - loss: 0.2058

133/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9368 - loss: 0.2036

135/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9368 - loss: 0.2033

137/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9368 - loss: 0.2052

139/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9371 - loss: 0.2041

141/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9371 - loss: 0.2037

143/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9360 - loss: 0.2079

145/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9356 - loss: 0.2079

147/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9354 - loss: 0.2078

149/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9354 - loss: 0.2076

151/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9356 - loss: 0.2070

153/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9353 - loss: 0.2068

155/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9355 - loss: 0.2059

157/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9357 - loss: 0.2056

159/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9359 - loss: 0.2047

161/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9367 - loss: 0.2024

162/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9367 - loss: 0.2022

164/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9365 - loss: 0.2023

166/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9369 - loss: 0.2011

168/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9368 - loss: 0.2023

170/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9368 - loss: 0.2027

172/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9362 - loss: 0.2031

174/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9359 - loss: 0.2047

175/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9361 - loss: 0.2041

177/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9366 - loss: 0.2026

179/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9370 - loss: 0.2024

180/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9368 - loss: 0.2024

182/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9368 - loss: 0.2022

184/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9370 - loss: 0.2012

186/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9372 - loss: 0.2005

188/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9370 - loss: 0.2005

190/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9368 - loss: 0.2008

192/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9365 - loss: 0.2019

194/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9362 - loss: 0.2027

196/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9365 - loss: 0.2016

198/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9367 - loss: 0.2012

200/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9364 - loss: 0.2031

202/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9356 - loss: 0.2043

204/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9355 - loss: 0.2045

206/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9358 - loss: 0.2045

208/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9352 - loss: 0.2058

210/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9351 - loss: 0.2059

212/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9353 - loss: 0.2051

214/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9356 - loss: 0.2039

216/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9350 - loss: 0.2049

218/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9356 - loss: 0.2034

220/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9359 - loss: 0.2025

222/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9354 - loss: 0.2032

224/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9351 - loss: 0.2035

226/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9349 - loss: 0.2037

228/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9350 - loss: 0.2029

230/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9351 - loss: 0.2024

232/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9348 - loss: 0.2025

234/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9350 - loss: 0.2025

236/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9348 - loss: 0.2028

238/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9346 - loss: 0.2031

240/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9349 - loss: 0.2027

242/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9351 - loss: 0.2042

244/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9350 - loss: 0.2036

246/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9351 - loss: 0.2036

248/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9349 - loss: 0.2035

250/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9352 - loss: 0.2029

252/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9352 - loss: 0.2031

254/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9351 - loss: 0.2036

256/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9350 - loss: 0.2034

258/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9347 - loss: 0.2043

260/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9346 - loss: 0.2042

262/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9347 - loss: 0.2035

264/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9349 - loss: 0.2023

266/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9348 - loss: 0.2024

268/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9351 - loss: 0.2016

270/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9349 - loss: 0.2033

272/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9352 - loss: 0.2021

274/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9351 - loss: 0.2021

276/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9350 - loss: 0.2023

278/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9349 - loss: 0.2033

279/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9350 - loss: 0.2037

281/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9349 - loss: 0.2049

283/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9350 - loss: 0.2046

285/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9349 - loss: 0.2057

286/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9348 - loss: 0.2067

287/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9349 - loss: 0.2064

289/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9349 - loss: 0.2072

291/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9353 - loss: 0.2062

293/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9350 - loss: 0.2071

295/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9351 - loss: 0.2071

297/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9348 - loss: 0.2071

299/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9346 - loss: 0.2077

301/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9341 - loss: 0.2108

303/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9339 - loss: 0.2117

305/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9337 - loss: 0.2121

307/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9338 - loss: 0.2122

309/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9340 - loss: 0.2115

311/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9341 - loss: 0.2112

313/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9337 - loss: 0.2116

315/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9336 - loss: 0.2126

316/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9337 - loss: 0.2122

317/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9338 - loss: 0.2118

319/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9338 - loss: 0.2114

321/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9335 - loss: 0.2124

323/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9335 - loss: 0.2128

325/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9337 - loss: 0.2123

327/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9335 - loss: 0.2126

329/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9334 - loss: 0.2127

331/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9335 - loss: 0.2128

333/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9334 - loss: 0.2124

335/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9332 - loss: 0.2132

337/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9330 - loss: 0.2134

339/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9333 - loss: 0.2126

341/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9332 - loss: 0.2125

343/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9333 - loss: 0.2120

345/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9335 - loss: 0.2114

347/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9335 - loss: 0.2121

349/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9333 - loss: 0.2123

351/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9331 - loss: 0.2129

353/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9330 - loss: 0.2133

355/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9333 - loss: 0.2123

357/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9334 - loss: 0.2122

359/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9334 - loss: 0.2130

361/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9335 - loss: 0.2128

362/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9335 - loss: 0.2128

364/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9334 - loss: 0.2131

366/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9336 - loss: 0.2124

368/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9340 - loss: 0.2115

370/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9339 - loss: 0.2114

372/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9339 - loss: 0.2118

374/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9340 - loss: 0.2119

376/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9341 - loss: 0.2122

378/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9338 - loss: 0.2127

380/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9339 - loss: 0.2125

382/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9338 - loss: 0.2130

384/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9337 - loss: 0.2134

386/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9335 - loss: 0.2140

388/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9334 - loss: 0.2144

390/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9334 - loss: 0.2144

392/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9335 - loss: 0.2142

394/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9336 - loss: 0.2143

396/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9332 - loss: 0.2147

398/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9330 - loss: 0.2153

400/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9331 - loss: 0.2148

402/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9332 - loss: 0.2143

404/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9332 - loss: 0.2140

406/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9332 - loss: 0.2137

408/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9333 - loss: 0.2130

410/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9333 - loss: 0.2127

412/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9334 - loss: 0.2126

414/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9334 - loss: 0.2126

416/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9336 - loss: 0.2121

418/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9339 - loss: 0.2115

420/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9339 - loss: 0.2111

422/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9340 - loss: 0.2109

424/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9340 - loss: 0.2108

426/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9343 - loss: 0.2099

428/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9345 - loss: 0.2095

430/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9345 - loss: 0.2096

432/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9343 - loss: 0.2095

434/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9338 - loss: 0.2115

436/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9338 - loss: 0.2118

438/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9338 - loss: 0.2122

440/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9338 - loss: 0.2119

442/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9339 - loss: 0.2117

444/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9339 - loss: 0.2121

446/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9340 - loss: 0.2118

448/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9339 - loss: 0.2120

450/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9339 - loss: 0.2117

452/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9338 - loss: 0.2116

454/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9339 - loss: 0.2111

456/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9339 - loss: 0.2109

458/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9340 - loss: 0.2108

460/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9336 - loss: 0.2111

462/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9338 - loss: 0.2112

464/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9339 - loss: 0.2110

466/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9340 - loss: 0.2107

468/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9342 - loss: 0.2101

470/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9343 - loss: 0.2099

472/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9343 - loss: 0.2097

474/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9346 - loss: 0.2091

476/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9346 - loss: 0.2088

478/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9346 - loss: 0.2083

480/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9348 - loss: 0.2078

482/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9347 - loss: 0.2079

484/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9349 - loss: 0.2076

486/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9351 - loss: 0.2069

488/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9352 - loss: 0.2064

490/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9353 - loss: 0.2062

492/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9351 - loss: 0.2065

494/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9352 - loss: 0.2064

495/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9352 - loss: 0.2062

497/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9353 - loss: 0.2059

499/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9353 - loss: 0.2056

501/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9352 - loss: 0.2056

503/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9352 - loss: 0.2062

505/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9351 - loss: 0.2064

507/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9353 - loss: 0.2058

509/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9355 - loss: 0.2053

511/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9354 - loss: 0.2052

513/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9355 - loss: 0.2050

515/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9355 - loss: 0.2050

516/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9356 - loss: 0.2047

518/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9357 - loss: 0.2044

520/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9357 - loss: 0.2041

522/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9357 - loss: 0.2043

524/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9357 - loss: 0.2040

526/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9356 - loss: 0.2043

528/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9356 - loss: 0.2046

530/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9356 - loss: 0.2044

532/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9356 - loss: 0.2043

534/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9356 - loss: 0.2048

536/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9357 - loss: 0.2044

538/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9356 - loss: 0.2048

540/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9354 - loss: 0.2052

542/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9353 - loss: 0.2056

544/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9354 - loss: 0.2052

546/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9354 - loss: 0.2055

548/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9355 - loss: 0.2054

550/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9357 - loss: 0.2048

552/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9358 - loss: 0.2046

554/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9357 - loss: 0.2046

556/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9358 - loss: 0.2042

558/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9358 - loss: 0.2044

560/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9358 - loss: 0.2044

562/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9360 - loss: 0.2040

564/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9361 - loss: 0.2037

566/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9361 - loss: 0.2036

568/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9360 - loss: 0.2034

570/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9360 - loss: 0.2036

572/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9360 - loss: 0.2034

573/573 ━━━━━━━━━━━━━━━━━━━━ 33s 58ms/step - accuracy: 0.9359 - loss: 0.2036 - val_accuracy: 0.9404 - val_loss: 0.2062

Epoch 5/20

  1/573 ━━━━━━━━━━━━━━━━━━━━ 43s 77ms/step - accuracy: 0.8750 - loss: 0.3493

  3/573 ━━━━━━━━━━━━━━━━━━━━ 26s 47ms/step - accuracy: 0.9167 - loss: 0.2564

  5/573 ━━━━━━━━━━━━━━━━━━━━ 26s 47ms/step - accuracy: 0.9375 - loss: 0.1859

  7/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9420 - loss: 0.1659

  9/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9410 - loss: 0.1852

 11/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9432 - loss: 0.1693

 13/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9399 - loss: 0.1756

 15/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9417 - loss: 0.1697

 17/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9320 - loss: 0.1995

 19/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9359 - loss: 0.1909

 21/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9360 - loss: 0.1986

 23/573 ━━━━━━━━━━━━━━━━━━━━ 27s 50ms/step - accuracy: 0.9334 - loss: 0.2067

 25/573 ━━━━━━━━━━━━━━━━━━━━ 27s 50ms/step - accuracy: 0.9337 - loss: 0.2024

 27/573 ━━━━━━━━━━━━━━━━━━━━ 27s 50ms/step - accuracy: 0.9352 - loss: 0.1985

 29/573 ━━━━━━━━━━━━━━━━━━━━ 26s 49ms/step - accuracy: 0.9332 - loss: 0.1975

 31/573 ━━━━━━━━━━━━━━━━━━━━ 26s 49ms/step - accuracy: 0.9375 - loss: 0.1860

 33/573 ━━━━━━━━━━━━━━━━━━━━ 26s 49ms/step - accuracy: 0.9384 - loss: 0.1830

 35/573 ━━━━━━━━━━━━━━━━━━━━ 26s 49ms/step - accuracy: 0.9366 - loss: 0.1905

 37/573 ━━━━━━━━━━━━━━━━━━━━ 26s 49ms/step - accuracy: 0.9358 - loss: 0.1966

 39/573 ━━━━━━━━━━━━━━━━━━━━ 26s 49ms/step - accuracy: 0.9351 - loss: 0.2055

 41/573 ━━━━━━━━━━━━━━━━━━━━ 26s 49ms/step - accuracy: 0.9360 - loss: 0.2000

 43/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9353 - loss: 0.2007

 45/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9375 - loss: 0.1939

 47/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9368 - loss: 0.1986

 49/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9369 - loss: 0.1974

 51/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9363 - loss: 0.2001

 53/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9363 - loss: 0.1994

 55/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9381 - loss: 0.1933

 57/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9391 - loss: 0.1924

 59/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9375 - loss: 0.1949

 61/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.9380 - loss: 0.1946

 63/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.9380 - loss: 0.1920

 65/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.9370 - loss: 0.1959

 67/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.9375 - loss: 0.1936

 69/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.9375 - loss: 0.1958

 71/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.9379 - loss: 0.1937

 73/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.9371 - loss: 0.1966

 75/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.9367 - loss: 0.1987

 77/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.9355 - loss: 0.1988

 79/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.9351 - loss: 0.1986

 81/573 ━━━━━━━━━━━━━━━━━━━━ 23s 49ms/step - accuracy: 0.9356 - loss: 0.1964

 83/573 ━━━━━━━━━━━━━━━━━━━━ 23s 49ms/step - accuracy: 0.9356 - loss: 0.1972

 85/573 ━━━━━━━━━━━━━━━━━━━━ 23s 49ms/step - accuracy: 0.9349 - loss: 0.1979

 87/573 ━━━━━━━━━━━━━━━━━━━━ 23s 49ms/step - accuracy: 0.9357 - loss: 0.1960

 89/573 ━━━━━━━━━━━━━━━━━━━━ 23s 49ms/step - accuracy: 0.9350 - loss: 0.1995

 91/573 ━━━━━━━━━━━━━━━━━━━━ 23s 49ms/step - accuracy: 0.9351 - loss: 0.2006

 93/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9358 - loss: 0.1986

 95/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9345 - loss: 0.2003

 97/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9343 - loss: 0.2022

 99/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9343 - loss: 0.2006

101/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9338 - loss: 0.2024

103/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9345 - loss: 0.2016

104/573 ━━━━━━━━━━━━━━━━━━━━ 22s 49ms/step - accuracy: 0.9348 - loss: 0.2006

106/573 ━━━━━━━━━━━━━━━━━━━━ 22s 49ms/step - accuracy: 0.9357 - loss: 0.1982

108/573 ━━━━━━━━━━━━━━━━━━━━ 22s 49ms/step - accuracy: 0.9361 - loss: 0.1971

110/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9361 - loss: 0.1961

112/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9361 - loss: 0.1956

114/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9364 - loss: 0.1941

116/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9356 - loss: 0.1979

118/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9359 - loss: 0.1973

119/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9359 - loss: 0.1972

121/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9357 - loss: 0.1994

123/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9360 - loss: 0.1984

125/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9352 - loss: 0.2033

127/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9355 - loss: 0.2031

129/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9356 - loss: 0.2036

131/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9356 - loss: 0.2046

133/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9359 - loss: 0.2049

135/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9354 - loss: 0.2058

137/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9348 - loss: 0.2060

139/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9346 - loss: 0.2056

141/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9337 - loss: 0.2095

143/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9336 - loss: 0.2096

145/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9334 - loss: 0.2111

147/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9332 - loss: 0.2120

149/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9325 - loss: 0.2133

151/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9321 - loss: 0.2137

153/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9328 - loss: 0.2117

155/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9333 - loss: 0.2107

157/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9327 - loss: 0.2116

159/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9326 - loss: 0.2138

161/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9330 - loss: 0.2120

163/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9333 - loss: 0.2113

165/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9335 - loss: 0.2105

167/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9326 - loss: 0.2117

168/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9327 - loss: 0.2114

169/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9323 - loss: 0.2125

170/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9325 - loss: 0.2116

171/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9324 - loss: 0.2121

172/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9324 - loss: 0.2120

173/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9323 - loss: 0.2138

174/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9325 - loss: 0.2131

175/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9323 - loss: 0.2135

177/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9327 - loss: 0.2121

179/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9326 - loss: 0.2121

181/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9328 - loss: 0.2112

183/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9325 - loss: 0.2112

185/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9326 - loss: 0.2117

187/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9330 - loss: 0.2112

189/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9332 - loss: 0.2109

191/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9334 - loss: 0.2108

193/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9335 - loss: 0.2114

195/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9335 - loss: 0.2114

197/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9327 - loss: 0.2138

199/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9325 - loss: 0.2140

201/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9325 - loss: 0.2131

203/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9327 - loss: 0.2126

205/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9326 - loss: 0.2128

207/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9328 - loss: 0.2119

209/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9329 - loss: 0.2120

211/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9326 - loss: 0.2124

213/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9328 - loss: 0.2115

215/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9321 - loss: 0.2126

217/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9323 - loss: 0.2122

219/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9322 - loss: 0.2130

221/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9323 - loss: 0.2125

223/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9322 - loss: 0.2121

225/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9326 - loss: 0.2106

227/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9327 - loss: 0.2105

229/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9326 - loss: 0.2104

231/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9328 - loss: 0.2101

233/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9323 - loss: 0.2110

235/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9323 - loss: 0.2105

237/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9325 - loss: 0.2108

239/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9328 - loss: 0.2098

241/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9327 - loss: 0.2097

243/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9331 - loss: 0.2083

245/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9327 - loss: 0.2096

247/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9328 - loss: 0.2089

249/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9330 - loss: 0.2079

251/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9331 - loss: 0.2073

253/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9333 - loss: 0.2072

255/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9331 - loss: 0.2072

257/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9329 - loss: 0.2081

259/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9327 - loss: 0.2085

261/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9326 - loss: 0.2092

263/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9326 - loss: 0.2084

265/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9324 - loss: 0.2090

267/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9328 - loss: 0.2082

269/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9332 - loss: 0.2073

271/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9335 - loss: 0.2063

273/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9335 - loss: 0.2056

275/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9335 - loss: 0.2052

277/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9337 - loss: 0.2050

279/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9334 - loss: 0.2067

281/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9335 - loss: 0.2065

282/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9333 - loss: 0.2064

284/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9332 - loss: 0.2068

286/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9335 - loss: 0.2061

288/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9333 - loss: 0.2067

290/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9334 - loss: 0.2061

292/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9335 - loss: 0.2051

294/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9336 - loss: 0.2058

296/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9338 - loss: 0.2050

298/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9336 - loss: 0.2057

300/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9334 - loss: 0.2055

302/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9336 - loss: 0.2053

304/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9335 - loss: 0.2054

306/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9334 - loss: 0.2050

308/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9337 - loss: 0.2045

310/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9338 - loss: 0.2043

312/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9339 - loss: 0.2036

314/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9339 - loss: 0.2035

316/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9340 - loss: 0.2029

318/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9340 - loss: 0.2031

320/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9342 - loss: 0.2028

321/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9344 - loss: 0.2022

323/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9344 - loss: 0.2019

325/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9342 - loss: 0.2026

327/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9343 - loss: 0.2030

329/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9340 - loss: 0.2037

331/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9343 - loss: 0.2029

333/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9343 - loss: 0.2028

335/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9343 - loss: 0.2027

337/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9340 - loss: 0.2032

339/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9339 - loss: 0.2033

341/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9340 - loss: 0.2030

343/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9341 - loss: 0.2029

345/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9343 - loss: 0.2022

347/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9343 - loss: 0.2028

349/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9342 - loss: 0.2029

351/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9343 - loss: 0.2025

353/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9343 - loss: 0.2031

355/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9345 - loss: 0.2029

357/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9347 - loss: 0.2024

359/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9349 - loss: 0.2017

361/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9346 - loss: 0.2025

363/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9345 - loss: 0.2030

365/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9346 - loss: 0.2029

367/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9348 - loss: 0.2023

369/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9341 - loss: 0.2031

371/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9341 - loss: 0.2040

373/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9341 - loss: 0.2040

375/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9341 - loss: 0.2038

377/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9340 - loss: 0.2039

379/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9338 - loss: 0.2048

381/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9337 - loss: 0.2046

383/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9339 - loss: 0.2051

385/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9337 - loss: 0.2062

387/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9337 - loss: 0.2057

389/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9337 - loss: 0.2054

391/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9337 - loss: 0.2052

393/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9338 - loss: 0.2046

395/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9339 - loss: 0.2046

397/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9338 - loss: 0.2052

399/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9339 - loss: 0.2048

401/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9340 - loss: 0.2043

403/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9340 - loss: 0.2041

405/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9340 - loss: 0.2037

407/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9340 - loss: 0.2037

409/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9339 - loss: 0.2034

411/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9338 - loss: 0.2036

413/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9337 - loss: 0.2037

415/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9338 - loss: 0.2035

417/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9338 - loss: 0.2040

419/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9341 - loss: 0.2032

421/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9343 - loss: 0.2027

423/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9343 - loss: 0.2024

425/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9344 - loss: 0.2023

427/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9344 - loss: 0.2025

429/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9341 - loss: 0.2037

431/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9344 - loss: 0.2028

433/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9344 - loss: 0.2030

435/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9345 - loss: 0.2027

437/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9345 - loss: 0.2027

439/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9345 - loss: 0.2033

441/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9345 - loss: 0.2030

443/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9348 - loss: 0.2023

444/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9348 - loss: 0.2021

446/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9347 - loss: 0.2024

448/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9349 - loss: 0.2021

450/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9347 - loss: 0.2026

452/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9346 - loss: 0.2031

454/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9348 - loss: 0.2028

456/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9349 - loss: 0.2023

458/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9350 - loss: 0.2017

460/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9350 - loss: 0.2022

462/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9350 - loss: 0.2019

464/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9352 - loss: 0.2015

466/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9350 - loss: 0.2025

468/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9349 - loss: 0.2026

470/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9349 - loss: 0.2031

472/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9349 - loss: 0.2029

474/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9350 - loss: 0.2028

476/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9349 - loss: 0.2031

478/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9350 - loss: 0.2029

480/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9350 - loss: 0.2031

482/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9351 - loss: 0.2033

484/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9351 - loss: 0.2032

486/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9352 - loss: 0.2027

488/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9353 - loss: 0.2028

490/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9354 - loss: 0.2026

492/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9352 - loss: 0.2029

494/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9354 - loss: 0.2023

496/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9352 - loss: 0.2026

498/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9354 - loss: 0.2022

500/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9355 - loss: 0.2020

502/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9354 - loss: 0.2020

504/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9350 - loss: 0.2029

506/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9350 - loss: 0.2033

508/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9350 - loss: 0.2031

510/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9348 - loss: 0.2033

512/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9348 - loss: 0.2039

514/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9347 - loss: 0.2041

516/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9347 - loss: 0.2040

518/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9349 - loss: 0.2035

520/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9348 - loss: 0.2034

522/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9347 - loss: 0.2033

524/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9347 - loss: 0.2035

526/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9347 - loss: 0.2031

528/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9347 - loss: 0.2033

530/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9347 - loss: 0.2030

532/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9345 - loss: 0.2031

534/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9347 - loss: 0.2025

536/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9349 - loss: 0.2020

538/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9348 - loss: 0.2021

540/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9349 - loss: 0.2022

542/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9349 - loss: 0.2022

544/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9349 - loss: 0.2025

546/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9350 - loss: 0.2025

548/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9347 - loss: 0.2032

550/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9348 - loss: 0.2029

552/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9347 - loss: 0.2027

554/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9347 - loss: 0.2032

556/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9346 - loss: 0.2033

558/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9347 - loss: 0.2034

560/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9346 - loss: 0.2037

562/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9347 - loss: 0.2032

564/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9349 - loss: 0.2026

566/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9350 - loss: 0.2023

568/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9350 - loss: 0.2022

570/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9350 - loss: 0.2023

572/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9352 - loss: 0.2019

573/573 ━━━━━━━━━━━━━━━━━━━━ 33s 58ms/step - accuracy: 0.9352 - loss: 0.2016 - val_accuracy: 0.9394 - val_loss: 0.2144

Epoch 6/20

  1/573 ━━━━━━━━━━━━━━━━━━━━ 1:15:25 8s/step - accuracy: 0.9062 - loss: 0.2794

  3/573 ━━━━━━━━━━━━━━━━━━━━ 26s 47ms/step - accuracy: 0.9375 - loss: 0.1982

  5/573 ━━━━━━━━━━━━━━━━━━━━ 26s 48ms/step - accuracy: 0.9375 - loss: 0.1692

  6/573 ━━━━━━━━━━━━━━━━━━━━ 32s 57ms/step - accuracy: 0.9427 - loss: 0.1532

  8/573 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.9492 - loss: 0.1445

 10/573 ━━━━━━━━━━━━━━━━━━━━ 29s 53ms/step - accuracy: 0.9500 - loss: 0.1379

 12/573 ━━━━━━━━━━━━━━━━━━━━ 29s 52ms/step - accuracy: 0.9505 - loss: 0.1328

 14/573 ━━━━━━━━━━━━━━━━━━━━ 28s 51ms/step - accuracy: 0.9509 - loss: 0.1257

 15/573 ━━━━━━━━━━━━━━━━━━━━ 29s 53ms/step - accuracy: 0.9542 - loss: 0.1208

 17/573 ━━━━━━━━━━━━━━━━━━━━ 28s 52ms/step - accuracy: 0.9522 - loss: 0.1186

 19/573 ━━━━━━━━━━━━━━━━━━━━ 28s 51ms/step - accuracy: 0.9490 - loss: 0.1276

 21/573 ━━━━━━━━━━━━━━━━━━━━ 28s 51ms/step - accuracy: 0.9539 - loss: 0.1186

 23/573 ━━━━━━━━━━━━━━━━━━━━ 27s 51ms/step - accuracy: 0.9457 - loss: 0.1362

 25/573 ━━━━━━━━━━━━━━━━━━━━ 27s 51ms/step - accuracy: 0.9475 - loss: 0.1316

 27/573 ━━━━━━━━━━━━━━━━━━━━ 27s 50ms/step - accuracy: 0.9468 - loss: 0.1312

 28/573 ━━━━━━━━━━━━━━━━━━━━ 27s 50ms/step - accuracy: 0.9487 - loss: 0.1283

 30/573 ━━━━━━━━━━━━━━━━━━━━ 27s 50ms/step - accuracy: 0.9469 - loss: 0.1346

 32/573 ━━━━━━━━━━━━━━━━━━━━ 27s 50ms/step - accuracy: 0.9434 - loss: 0.1450

 34/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.9439 - loss: 0.1422

 36/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.9444 - loss: 0.1450

 38/573 ━━━━━━━━━━━━━━━━━━━━ 26s 50ms/step - accuracy: 0.9416 - loss: 0.1513

 40/573 ━━━━━━━━━━━━━━━━━━━━ 26s 49ms/step - accuracy: 0.9414 - loss: 0.1538

 42/573 ━━━━━━━━━━━━━━━━━━━━ 26s 49ms/step - accuracy: 0.9435 - loss: 0.1486

 44/573 ━━━━━━━━━━━━━━━━━━━━ 26s 49ms/step - accuracy: 0.9439 - loss: 0.1523

 46/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9443 - loss: 0.1507

 48/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9421 - loss: 0.1536

 50/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9425 - loss: 0.1528

 51/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9436 - loss: 0.1503

 52/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9429 - loss: 0.1525

 54/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9410 - loss: 0.1536

 56/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9414 - loss: 0.1525

 58/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9402 - loss: 0.1567

 60/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9411 - loss: 0.1551

 62/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.9410 - loss: 0.1546

 64/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.9404 - loss: 0.1569

 66/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.9408 - loss: 0.1572

 68/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.9426 - loss: 0.1536

 70/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.9415 - loss: 0.1537

 72/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.9418 - loss: 0.1524

 74/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.9426 - loss: 0.1500

 76/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.9420 - loss: 0.1519

 78/573 ━━━━━━━━━━━━━━━━━━━━ 24s 49ms/step - accuracy: 0.9427 - loss: 0.1501

 80/573 ━━━━━━━━━━━━━━━━━━━━ 23s 49ms/step - accuracy: 0.9434 - loss: 0.1478

 82/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9440 - loss: 0.1462

 84/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9435 - loss: 0.1486

 86/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9448 - loss: 0.1458

 87/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9450 - loss: 0.1447

 89/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9442 - loss: 0.1461

 91/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9440 - loss: 0.1482

 93/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9439 - loss: 0.1481

 95/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9444 - loss: 0.1493

 97/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9449 - loss: 0.1486

 99/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9441 - loss: 0.1491

101/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9446 - loss: 0.1482

103/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9442 - loss: 0.1521

105/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9443 - loss: 0.1523

107/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9439 - loss: 0.1536

109/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9435 - loss: 0.1550

111/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9437 - loss: 0.1555

113/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9433 - loss: 0.1570

115/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9424 - loss: 0.1599

117/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9420 - loss: 0.1632

118/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9423 - loss: 0.1628

120/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9419 - loss: 0.1638

122/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9424 - loss: 0.1647

124/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9428 - loss: 0.1630

126/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9432 - loss: 0.1615

128/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9434 - loss: 0.1617

129/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9436 - loss: 0.1614

131/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9442 - loss: 0.1604

133/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9436 - loss: 0.1612

135/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9433 - loss: 0.1623

137/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9437 - loss: 0.1617

139/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9440 - loss: 0.1610

141/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9444 - loss: 0.1599

143/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9443 - loss: 0.1596

145/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9444 - loss: 0.1595

147/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9441 - loss: 0.1598

149/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9440 - loss: 0.1596

151/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9443 - loss: 0.1601

153/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9440 - loss: 0.1606

155/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9442 - loss: 0.1599

157/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9443 - loss: 0.1604

159/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9444 - loss: 0.1602

161/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9449 - loss: 0.1592

163/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9452 - loss: 0.1589

165/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9455 - loss: 0.1605

167/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9454 - loss: 0.1607

169/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9456 - loss: 0.1607

171/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9454 - loss: 0.1612

173/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9454 - loss: 0.1610

175/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9459 - loss: 0.1597

177/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9446 - loss: 0.1648

179/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9448 - loss: 0.1659

181/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9444 - loss: 0.1684

183/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9447 - loss: 0.1677

184/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9443 - loss: 0.1691

186/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9446 - loss: 0.1680

188/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9441 - loss: 0.1691

190/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9436 - loss: 0.1712

192/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9442 - loss: 0.1700

194/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9443 - loss: 0.1696

196/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9444 - loss: 0.1690

198/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9440 - loss: 0.1691

200/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9442 - loss: 0.1681

202/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9442 - loss: 0.1680

204/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9432 - loss: 0.1703

206/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9431 - loss: 0.1713

208/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9419 - loss: 0.1741

210/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9423 - loss: 0.1730

212/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9422 - loss: 0.1727

214/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9423 - loss: 0.1725

216/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9421 - loss: 0.1729

218/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9417 - loss: 0.1745

220/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9416 - loss: 0.1749

222/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9417 - loss: 0.1749

224/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9415 - loss: 0.1758

226/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9415 - loss: 0.1764

228/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9417 - loss: 0.1760

230/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9420 - loss: 0.1754

232/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9421 - loss: 0.1760

234/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9424 - loss: 0.1751

236/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9423 - loss: 0.1749

238/573 ━━━━━━━━━━━━━━━━━━━━ 16s 48ms/step - accuracy: 0.9422 - loss: 0.1749

240/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9424 - loss: 0.1743

242/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9424 - loss: 0.1742

244/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9426 - loss: 0.1740

246/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9423 - loss: 0.1743

248/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9428 - loss: 0.1733

250/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9425 - loss: 0.1739

252/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9426 - loss: 0.1737

254/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9424 - loss: 0.1735

256/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9418 - loss: 0.1759

258/573 ━━━━━━━━━━━━━━━━━━━━ 15s 48ms/step - accuracy: 0.9417 - loss: 0.1755

260/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9412 - loss: 0.1773

262/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9416 - loss: 0.1767

264/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9413 - loss: 0.1766

266/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9410 - loss: 0.1774

268/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9410 - loss: 0.1785

270/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9407 - loss: 0.1795

272/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9408 - loss: 0.1792

274/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9406 - loss: 0.1797

276/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9406 - loss: 0.1790

278/573 ━━━━━━━━━━━━━━━━━━━━ 14s 48ms/step - accuracy: 0.9406 - loss: 0.1789

280/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9404 - loss: 0.1805

282/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9405 - loss: 0.1803

284/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9408 - loss: 0.1795

286/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9409 - loss: 0.1807

288/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9411 - loss: 0.1800

290/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9406 - loss: 0.1813

292/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9407 - loss: 0.1810

294/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9405 - loss: 0.1823

296/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9402 - loss: 0.1823

298/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9402 - loss: 0.1823

300/573 ━━━━━━━━━━━━━━━━━━━━ 13s 48ms/step - accuracy: 0.9402 - loss: 0.1819

302/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9401 - loss: 0.1819

304/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9399 - loss: 0.1827

306/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9402 - loss: 0.1828

308/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9402 - loss: 0.1824

310/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9401 - loss: 0.1824

312/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9403 - loss: 0.1818

314/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9401 - loss: 0.1822

316/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9400 - loss: 0.1820

318/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9399 - loss: 0.1820

320/573 ━━━━━━━━━━━━━━━━━━━━ 12s 48ms/step - accuracy: 0.9401 - loss: 0.1812

322/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9403 - loss: 0.1805

324/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9403 - loss: 0.1809

326/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9402 - loss: 0.1813

328/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9401 - loss: 0.1814

330/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9403 - loss: 0.1805

332/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9406 - loss: 0.1800

334/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9407 - loss: 0.1798

336/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9406 - loss: 0.1801

338/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9406 - loss: 0.1797

340/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9404 - loss: 0.1802

342/573 ━━━━━━━━━━━━━━━━━━━━ 11s 48ms/step - accuracy: 0.9404 - loss: 0.1800

344/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9404 - loss: 0.1802

346/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9407 - loss: 0.1795

348/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9403 - loss: 0.1803

350/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9404 - loss: 0.1802

352/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9405 - loss: 0.1809

354/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9403 - loss: 0.1818

356/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9403 - loss: 0.1819

358/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9403 - loss: 0.1830

360/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9404 - loss: 0.1826

362/573 ━━━━━━━━━━━━━━━━━━━━ 10s 48ms/step - accuracy: 0.9404 - loss: 0.1823

364/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9405 - loss: 0.1826

366/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9407 - loss: 0.1822

368/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9406 - loss: 0.1826

370/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9406 - loss: 0.1822

372/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9408 - loss: 0.1820

374/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9407 - loss: 0.1817

376/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9405 - loss: 0.1824

378/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9405 - loss: 0.1829

380/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9406 - loss: 0.1828

382/573 ━━━━━━━━━━━━━━━━━━━━ 9s 48ms/step - accuracy: 0.9404 - loss: 0.1833

384/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9402 - loss: 0.1840

385/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9403 - loss: 0.1835

387/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9406 - loss: 0.1827

388/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9406 - loss: 0.1827

389/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9407 - loss: 0.1824

391/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9408 - loss: 0.1828

393/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9409 - loss: 0.1823

395/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9409 - loss: 0.1822

397/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9409 - loss: 0.1823

399/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9409 - loss: 0.1825

401/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9407 - loss: 0.1830

403/573 ━━━━━━━━━━━━━━━━━━━━ 8s 48ms/step - accuracy: 0.9407 - loss: 0.1829

405/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9407 - loss: 0.1827

407/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9406 - loss: 0.1835

409/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9406 - loss: 0.1835

411/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9404 - loss: 0.1849

413/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9403 - loss: 0.1848

415/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9404 - loss: 0.1846

417/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9404 - loss: 0.1843

419/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9404 - loss: 0.1845

420/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9404 - loss: 0.1852

422/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9405 - loss: 0.1853

424/573 ━━━━━━━━━━━━━━━━━━━━ 7s 48ms/step - accuracy: 0.9405 - loss: 0.1852

426/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9405 - loss: 0.1850

428/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9405 - loss: 0.1848

430/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9402 - loss: 0.1857

432/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9401 - loss: 0.1859

434/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9402 - loss: 0.1855

436/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9402 - loss: 0.1854

438/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9401 - loss: 0.1856

440/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9400 - loss: 0.1858

441/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9401 - loss: 0.1860

443/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9400 - loss: 0.1859

445/573 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step - accuracy: 0.9401 - loss: 0.1854

447/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9398 - loss: 0.1859

449/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9398 - loss: 0.1860

451/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9399 - loss: 0.1855

453/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9399 - loss: 0.1850

455/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9396 - loss: 0.1857

457/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9396 - loss: 0.1858

458/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9396 - loss: 0.1860

460/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9396 - loss: 0.1862

462/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9393 - loss: 0.1862

464/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9391 - loss: 0.1867

466/573 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step - accuracy: 0.9391 - loss: 0.1865

468/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9388 - loss: 0.1875

470/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9388 - loss: 0.1876

472/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9388 - loss: 0.1879

474/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9386 - loss: 0.1883

476/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9386 - loss: 0.1879

478/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9387 - loss: 0.1874

480/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9389 - loss: 0.1868

482/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9389 - loss: 0.1867

484/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9389 - loss: 0.1867

486/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9389 - loss: 0.1862

488/573 ━━━━━━━━━━━━━━━━━━━━ 4s 48ms/step - accuracy: 0.9390 - loss: 0.1867

490/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9389 - loss: 0.1868

492/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9387 - loss: 0.1873

494/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9387 - loss: 0.1875

496/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9387 - loss: 0.1878

498/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9387 - loss: 0.1875

500/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9385 - loss: 0.1880

502/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9385 - loss: 0.1878

504/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9384 - loss: 0.1878

506/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9383 - loss: 0.1879

508/573 ━━━━━━━━━━━━━━━━━━━━ 3s 48ms/step - accuracy: 0.9382 - loss: 0.1883

510/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9383 - loss: 0.1882

512/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9383 - loss: 0.1886

514/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9382 - loss: 0.1886

516/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9382 - loss: 0.1888

518/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9381 - loss: 0.1891

520/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9382 - loss: 0.1886

522/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9382 - loss: 0.1887

524/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9382 - loss: 0.1885

525/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9381 - loss: 0.1888

527/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9382 - loss: 0.1886

528/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9382 - loss: 0.1886

530/573 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.9383 - loss: 0.1883

532/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9382 - loss: 0.1887

534/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9380 - loss: 0.1892

536/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9380 - loss: 0.1892

538/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9380 - loss: 0.1890

540/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9381 - loss: 0.1887

542/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9382 - loss: 0.1883

544/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9383 - loss: 0.1880

546/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9383 - loss: 0.1878

548/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9384 - loss: 0.1881

550/573 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - accuracy: 0.9384 - loss: 0.1886

552/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9383 - loss: 0.1886

554/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9384 - loss: 0.1891

556/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9384 - loss: 0.1889

558/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9385 - loss: 0.1889

560/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9387 - loss: 0.1884

562/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9387 - loss: 0.1885

564/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9387 - loss: 0.1889

566/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9386 - loss: 0.1889

568/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9385 - loss: 0.1900

570/573 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9383 - loss: 0.1900

572/573 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9382 - loss: 0.1904

573/573 ━━━━━━━━━━━━━━━━━━━━ 41s 58ms/step - accuracy: 0.9382 - loss: 0.1904 - val_accuracy: 0.9374 - val_loss: 0.2262

Epoch 7/20

  1/573 ━━━━━━━━━━━━━━━━━━━━ 45s 80ms/step - accuracy: 1.0000 - loss: 0.0378

  3/573 ━━━━━━━━━━━━━━━━━━━━ 27s 48ms/step - accuracy: 0.9583 - loss: 0.1442

  4/573 ━━━━━━━━━━━━━━━━━━━━ 27s 49ms/step - accuracy: 0.9375 - loss: 0.2017

  5/573 ━━━━━━━━━━━━━━━━━━━━ 28s 50ms/step - accuracy: 0.9438 - loss: 0.2152

  6/573 ━━━━━━━━━━━━━━━━━━━━ 28s 51ms/step - accuracy: 0.9427 - loss: 0.2100

  7/573 ━━━━━━━━━━━━━━━━━━━━ 28s 51ms/step - accuracy: 0.9375 - loss: 0.2298

  9/573 ━━━━━━━━━━━━━━━━━━━━ 28s 50ms/step - accuracy: 0.9410 - loss: 0.2231

 11/573 ━━━━━━━━━━━━━━━━━━━━ 29s 52ms/step - accuracy: 0.9432 - loss: 0.2079

 13/573 ━━━━━━━━━━━━━━━━━━━━ 28s 52ms/step - accuracy: 0.9399 - loss: 0.2091

 15/573 ━━━━━━━━━━━━━━━━━━━━ 28s 51ms/step - accuracy: 0.9479 - loss: 0.1868

 17/573 ━━━━━━━━━━━━━━━━━━━━ 28s 51ms/step - accuracy: 0.9430 - loss: 0.1968

 19/573 ━━━━━━━━━━━━━━━━━━━━ 28s 51ms/step - accuracy: 0.9359 - loss: 0.2030

 21/573 ━━━━━━━━━━━━━━━━━━━━ 27s 50ms/step - accuracy: 0.9390 - loss: 0.2002

 23/573 ━━━━━━━━━━━━━━━━━━━━ 27s 50ms/step - accuracy: 0.9402 - loss: 0.1945

 25/573 ━━━━━━━━━━━━━━━━━━━━ 27s 50ms/step - accuracy: 0.9400 - loss: 0.1959

 27/573 ━━━━━━━━━━━━━━━━━━━━ 27s 50ms/step - accuracy: 0.9375 - loss: 0.2018

 29/573 ━━━━━━━━━━━━━━━━━━━━ 26s 49ms/step - accuracy: 0.9343 - loss: 0.2124

 31/573 ━━━━━━━━━━━━━━━━━━━━ 26s 49ms/step - accuracy: 0.9355 - loss: 0.2057

 33/573 ━━━━━━━━━━━━━━━━━━━━ 26s 49ms/step - accuracy: 0.9375 - loss: 0.1994

 35/573 ━━━━━━━━━━━━━━━━━━━━ 26s 49ms/step - accuracy: 0.9384 - loss: 0.2001

 37/573 ━━━━━━━━━━━━━━━━━━━━ 26s 49ms/step - accuracy: 0.9400 - loss: 0.1937

 39/573 ━━━━━━━━━━━━━━━━━━━━ 26s 49ms/step - accuracy: 0.9391 - loss: 0.1920

 41/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9413 - loss: 0.1856

 43/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9404 - loss: 0.1844

 45/573 ━━━━━━━━━━━━━━━━━━━━ 25s 49ms/step - accuracy: 0.9417 - loss: 0.1823

 47/573 ━━━━━━━━━━━━━━━━━━━━ 25s 48ms/step - accuracy: 0.9415 - loss: 0.1809

 49/573 ━━━━━━━━━━━━━━━━━━━━ 25s 48ms/step - accuracy: 0.9432 - loss: 0.1763

 51/573 ━━━━━━━━━━━━━━━━━━━━ 25s 48ms/step - accuracy: 0.9436 - loss: 0.1770

 53/573 ━━━━━━━━━━━━━━━━━━━━ 25s 48ms/step - accuracy: 0.9416 - loss: 0.1797

 55/573 ━━━━━━━━━━━━━━━━━━━━ 25s 48ms/step - accuracy: 0.9432 - loss: 0.1761

 57/573 ━━━━━━━━━━━━━━━━━━━━ 24s 48ms/step - accuracy: 0.9430 - loss: 0.1742

 59/573 ━━━━━━━━━━━━━━━━━━━━ 24s 48ms/step - accuracy: 0.9423 - loss: 0.1755

 61/573 ━━━━━━━━━━━━━━━━━━━━ 24s 48ms/step - accuracy: 0.9421 - loss: 0.1792

 63/573 ━━━━━━━━━━━━━━━━━━━━ 24s 48ms/step - accuracy: 0.9420 - loss: 0.1796

 65/573 ━━━━━━━━━━━━━━━━━━━━ 24s 48ms/step - accuracy: 0.9413 - loss: 0.1777

 67/573 ━━━━━━━━━━━━━━━━━━━━ 24s 48ms/step - accuracy: 0.9426 - loss: 0.1748

 69/573 ━━━━━━━━━━━━━━━━━━━━ 24s 48ms/step - accuracy: 0.9438 - loss: 0.1754

 71/573 ━━━━━━━━━━━━━━━━━━━━ 24s 48ms/step - accuracy: 0.9445 - loss: 0.1733

 73/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9439 - loss: 0.1745

 75/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9442 - loss: 0.1733

 77/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9448 - loss: 0.1726

 79/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9446 - loss: 0.1721

 80/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9445 - loss: 0.1731

 82/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9444 - loss: 0.1725

 84/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9438 - loss: 0.1725

 86/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9422 - loss: 0.1745

 88/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9418 - loss: 0.1766

 90/573 ━━━━━━━━━━━━━━━━━━━━ 23s 48ms/step - accuracy: 0.9420 - loss: 0.1763

 92/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9426 - loss: 0.1746

 94/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9418 - loss: 0.1747

 95/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9421 - loss: 0.1742

 97/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9407 - loss: 0.1757

 99/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9407 - loss: 0.1763

101/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9406 - loss: 0.1769

103/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9411 - loss: 0.1751

105/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9414 - loss: 0.1747

107/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9410 - loss: 0.1746

109/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9407 - loss: 0.1742

111/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9403 - loss: 0.1753

113/573 ━━━━━━━━━━━━━━━━━━━━ 22s 48ms/step - accuracy: 0.9408 - loss: 0.1732

115/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9405 - loss: 0.1742

117/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9402 - loss: 0.1753

119/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9391 - loss: 0.1777

121/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9393 - loss: 0.1770

123/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9395 - loss: 0.1778

125/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9388 - loss: 0.1792

127/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9395 - loss: 0.1775

129/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9394 - loss: 0.1775

131/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9396 - loss: 0.1762

133/573 ━━━━━━━━━━━━━━━━━━━━ 21s 48ms/step - accuracy: 0.9398 - loss: 0.1754

135/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9403 - loss: 0.1744

137/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9400 - loss: 0.1760

139/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9404 - loss: 0.1752

141/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9402 - loss: 0.1750

143/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9399 - loss: 0.1749

145/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9401 - loss: 0.1746

147/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9401 - loss: 0.1756

149/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9398 - loss: 0.1759

151/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9394 - loss: 0.1778

153/573 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.9389 - loss: 0.1781

155/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9393 - loss: 0.1775

157/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9393 - loss: 0.1776

159/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9393 - loss: 0.1785

161/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9398 - loss: 0.1770

163/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9402 - loss: 0.1766

165/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9396 - loss: 0.1782

167/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9399 - loss: 0.1773

169/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9399 - loss: 0.1773

171/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9397 - loss: 0.1770

173/573 ━━━━━━━━━━━━━━━━━━━━ 19s 48ms/step - accuracy: 0.9398 - loss: 0.1762

175/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9402 - loss: 0.1755

177/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9403 - loss: 0.1745

179/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9403 - loss: 0.1747

181/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9404 - loss: 0.1743

183/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9406 - loss: 0.1739

185/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9407 - loss: 0.1737

187/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9405 - loss: 0.1736

189/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9405 - loss: 0.1737

191/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9398 - loss: 0.1774

193/573 ━━━━━━━━━━━━━━━━━━━━ 18s 48ms/step - accuracy: 0.9399 - loss: 0.1768

195/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9402 - loss: 0.1764

197/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9396 - loss: 0.1786

199/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9394 - loss: 0.1798

201/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9391 - loss: 0.1808

203/573 ━━━━━━━━━━━━━━━━━━━━ 17s 47ms/step - accuracy: 0.9392 - loss: 0.1805

204/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9390 - loss: 0.1805

206/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9390 - loss: 0.1803

208/573 ━━━━━━━━━━━━━━━━━━━━ 17s 48ms/step - accuracy: 0.9392 - loss: 0.1814

210/573 ━━━━━━━━━━━━━━━━━━━━ 17s 47ms/step - accuracy: 0.9396 - loss: 0.1809

212/573 ━━━━━━━━━━━━━━━━━━━━ 17s 47ms/step - accuracy: 0.9396 - loss: 0.1803

214/573 ━━━━━━━━━━━━━━━━━━━━ 17s 47ms/step - accuracy: 0.9397 - loss: 0.1799

216/573 ━━━━━━━━━━━━━━━━━━━━ 16s 47ms/step - accuracy: 0.9398 - loss: 0.1795

218/573 ━━━━━━━━━━━━━━━━━━━━ 16s 47ms/step - accuracy: 0.9399 - loss: 0.1788

220/573 ━━━━━━━━━━━━━━━━━━━━ 16s 47ms/step - accuracy: 0.9398 - loss: 0.1785

222/573 ━━━━━━━━━━━━━━━━━━━━ 16s 47ms/step - accuracy: 0.9400 - loss: 0.1777

224/573 ━━━━━━━━━━━━━━━━━━━━ 16s 47ms/step - accuracy: 0.9404 - loss: 0.1765

226/573 ━━━━━━━━━━━━━━━━━━━━ 16s 47ms/step - accuracy: 0.9405 - loss: 0.1761

228/573 ━━━━━━━━━━━━━━━━━━━━ 16s 47ms/step - accuracy: 0.9407 - loss: 0.1757

230/573 ━━━━━━━━━━━━━━━━━━━━ 16s 47ms/step - accuracy: 0.9405 - loss: 0.1762

232/573 ━━━━━━━━━━━━━━━━━━━━ 16s 47ms/step - accuracy: 0.9406 - loss: 0.1762

234/573 ━━━━━━━━━━━━━━━━━━━━ 16s 47ms/step - accuracy: 0.9406 - loss: 0.1765

236/573 ━━━━━━━━━━━━━━━━━━━━ 15s 47ms/step - accuracy: 0.9400 - loss: 0.1767

238/573 ━━━━━━━━━━━━━━━━━━━━ 15s 47ms/step - accuracy: 0.9401 - loss: 0.1762

240/573 ━━━━━━━━━━━━━━━━━━━━ 15s 47ms/step - accuracy: 0.9400 - loss: 0.1757

242/573 ━━━━━━━━━━━━━━━━━━━━ 15s 47ms/step - accuracy: 0.9402 - loss: 0.1748

244/573 ━━━━━━━━━━━━━━━━━━━━ 15s 47ms/step - accuracy: 0.9404 - loss: 0.1742

246/573 ━━━━━━━━━━━━━━━━━━━━ 15s 47ms/step - accuracy: 0.9402 - loss: 0.1742

248/573 ━━━━━━━━━━━━━━━━━━━━ 15s 47ms/step - accuracy: 0.9403 - loss: 0.1748

250/573 ━━━━━━━━━━━━━━━━━━━━ 15s 47ms/step - accuracy: 0.9404 - loss: 0.1759

252/573 ━━━━━━━━━━━━━━━━━━━━ 15s 47ms/step - accuracy: 0.9404 - loss: 0.1754

254/573 ━━━━━━━━━━━━━━━━━━━━ 15s 47ms/step - accuracy: 0.9405 - loss: 0.1760

256/573 ━━━━━━━━━━━━━━━━━━━━ 15s 47ms/step - accuracy: 0.9403 - loss: 0.1759

258/573 ━━━━━━━━━━━━━━━━━━━━ 14s 47ms/step - accuracy: 0.9402 - loss: 0.1769

260/573 ━━━━━━━━━━━━━━━━━━━━ 14s 47ms/step - accuracy: 0.9398 - loss: 0.1778

262/573 ━━━━━━━━━━━━━━━━━━━━ 14s 47ms/step - accuracy: 0.9399 - loss: 0.1778

264/573 ━━━━━━━━━━━━━━━━━━━━ 14s 47ms/step - accuracy: 0.9397 - loss: 0.1786

266/573 ━━━━━━━━━━━━━━━━━━━━ 14s 47ms/step - accuracy: 0.9400 - loss: 0.1780

268/573 ━━━━━━━━━━━━━━━━━━━━ 14s 47ms/step - accuracy: 0.9398 - loss: 0.1785

270/573 ━━━━━━━━━━━━━━━━━━━━ 14s 47ms/step - accuracy: 0.9400 - loss: 0.1783

272/573 ━━━━━━━━━━━━━━━━━━━━ 14s 47ms/step - accuracy: 0.9400 - loss: 0.1784

274/573 ━━━━━━━━━━━━━━━━━━━━ 14s 47ms/step - accuracy: 0.9401 - loss: 0.1782

276/573 ━━━━━━━━━━━━━━━━━━━━ 14s 47ms/step - accuracy: 0.9398 - loss: 0.1793

278/573 ━━━━━━━━━━━━━━━━━━━━ 13s 47ms/step - accuracy: 0.9400 - loss: 0.1787

280/573 ━━━━━━━━━━━━━━━━━━━━ 13s 47ms/step - accuracy: 0.9403 - loss: 0.1782

281/573 ━━━━━━━━━━━━━━━━━━━━ 13s 47ms/step - accuracy: 0.9404 - loss: 0.1778

283/573 ━━━━━━━━━━━━━━━━━━━━ 13s 47ms/step - accuracy: 0.9405 - loss: 0.1782

285/573 ━━━━━━━━━━━━━━━━━━━━ 13s 47ms/step - accuracy: 0.9405 - loss: 0.1782

287/573 ━━━━━━━━━━━━━━━━━━━━ 13s 47ms/step - accuracy: 0.9400 - loss: 0.1793

289/573 ━━━━━━━━━━━━━━━━━━━━ 13s 47ms/step - accuracy: 0.9400 - loss: 0.1793

291/573 ━━━━━━━━━━━━━━━━━━━━ 13s 47ms/step - accuracy: 0.9402 - loss: 0.1792

293/573 ━━━━━━━━━━━━━━━━━━━━ 13s 47ms/step - accuracy: 0.9405 - loss: 0.1784

295/573 ━━━━━━━━━━━━━━━━━━━━ 13s 47ms/step - accuracy: 0.9405 - loss: 0.1795

297/573 ━━━━━━━━━━━━━━━━━━━━ 13s 47ms/step - accuracy: 0.9407 - loss: 0.1789

299/573 ━━━━━━━━━━━━━━━━━━━━ 12s 47ms/step - accuracy: 0.9405 - loss: 0.1799

301/573 ━━━━━━━━━━━━━━━━━━━━ 12s 47ms/step - accuracy: 0.9407 - loss: 0.1793

303/573 ━━━━━━━━━━━━━━━━━━━━ 12s 47ms/step - accuracy: 0.9407 - loss: 0.1792

305/573 ━━━━━━━━━━━━━━━━━━━━ 12s 47ms/step - accuracy: 0.9407 - loss: 0.1794

307/573 ━━━━━━━━━━━━━━━━━━━━ 12s 47ms/step - accuracy: 0.9404 - loss: 0.1797

309/573 ━━━━━━━━━━━━━━━━━━━━ 12s 47ms/step - accuracy: 0.9403 - loss: 0.1798

311/573 ━━━━━━━━━━━━━━━━━━━━ 12s 47ms/step - accuracy: 0.9398 - loss: 0.1810

313/573 ━━━━━━━━━━━━━━━━━━━━ 12s 47ms/step - accuracy: 0.9399 - loss: 0.1808

315/573 ━━━━━━━━━━━━━━━━━━━━ 12s 47ms/step - accuracy: 0.9396 - loss: 0.1815

317/573 ━━━━━━━━━━━━━━━━━━━━ 12s 47ms/step - accuracy: 0.9397 - loss: 0.1810

319/573 ━━━━━━━━━━━━━━━━━━━━ 12s 47ms/step - accuracy: 0.9398 - loss: 0.1808

321/573 ━━━━━━━━━━━━━━━━━━━━ 11s 47ms/step - accuracy: 0.9399 - loss: 0.1804

323/573 ━━━━━━━━━━━━━━━━━━━━ 11s 47ms/step - accuracy: 0.9400 - loss: 0.1800

325/573 ━━━━━━━━━━━━━━━━━━━━ 11s 47ms/step - accuracy: 0.9402 - loss: 0.1794

327/573 ━━━━━━━━━━━━━━━━━━━━ 11s 47ms/step - accuracy: 0.9396 - loss: 0.1802

329/573 ━━━━━━━━━━━━━━━━━━━━ 11s 47ms/step - accuracy: 0.9395 - loss: 0.1806

331/573 ━━━━━━━━━━━━━━━━━━━━ 11s 47ms/step - accuracy: 0.9396 - loss: 0.1807

333/573 ━━━━━━━━━━━━━━━━━━━━ 11s 47ms/step - accuracy: 0.9396 - loss: 0.1812

335/573 ━━━━━━━━━━━━━━━━━━━━ 11s 47ms/step - accuracy: 0.9394 - loss: 0.1821

337/573 ━━━━━━━━━━━━━━━━━━━━ 11s 47ms/step - accuracy: 0.9396 - loss: 0.1818

339/573 ━━━━━━━━━━━━━━━━━━━━ 11s 47ms/step - accuracy: 0.9393 - loss: 0.1827

341/573 ━━━━━━━━━━━━━━━━━━━━ 10s 47ms/step - accuracy: 0.9393 - loss: 0.1827

343/573 ━━━━━━━━━━━━━━━━━━━━ 10s 47ms/step - accuracy: 0.9395 - loss: 0.1820

345/573 ━━━━━━━━━━━━━━━━━━━━ 10s 47ms/step - accuracy: 0.9397 - loss: 0.1818

347/573 ━━━━━━━━━━━━━━━━━━━━ 10s 47ms/step - accuracy: 0.9400 - loss: 0.1812

349/573 ━━━━━━━━━━━━━━━━━━━━ 10s 47ms/step - accuracy: 0.9402 - loss: 0.1805

351/573 ━━━━━━━━━━━━━━━━━━━━ 10s 47ms/step - accuracy: 0.9399 - loss: 0.1814

353/573 ━━━━━━━━━━━━━━━━━━━━ 10s 47ms/step - accuracy: 0.9399 - loss: 0.1815

355/573 ━━━━━━━━━━━━━━━━━━━━ 10s 47ms/step - accuracy: 0.9398 - loss: 0.1816

357/573 ━━━━━━━━━━━━━━━━━━━━ 10s 47ms/step - accuracy: 0.9401 - loss: 0.1810

359/573 ━━━━━━━━━━━━━━━━━━━━ 10s 47ms/step - accuracy: 0.9401 - loss: 0.1814

361/573 ━━━━━━━━━━━━━━━━━━━━ 10s 47ms/step - accuracy: 0.9404 - loss: 0.1806

363/573 ━━━━━━━━━━━━━━━━━━━━ 9s 47ms/step - accuracy: 0.9405 - loss: 0.1804

365/573 ━━━━━━━━━━━━━━━━━━━━ 9s 47ms/step - accuracy: 0.9403 - loss: 0.1812

367/573 ━━━━━━━━━━━━━━━━━━━━ 9s 47ms/step - accuracy: 0.9403 - loss: 0.1812

369/573 ━━━━━━━━━━━━━━━━━━━━ 9s 47ms/step - accuracy: 0.9402 - loss: 0.1817

371/573 ━━━━━━━━━━━━━━━━━━━━ 9s 47ms/step - accuracy: 0.9401 - loss: 0.1817

373/573 ━━━━━━━━━━━━━━━━━━━━ 9s 47ms/step - accuracy: 0.9403 - loss: 0.1814

375/573 ━━━━━━━━━━━━━━━━━━━━ 9s 47ms/step - accuracy: 0.9404 - loss: 0.1814

377/573 ━━━━━━━━━━━━━━━━━━━━ 9s 47ms/step - accuracy: 0.9403 - loss: 0.1812

379/573 ━━━━━━━━━━━━━━━━━━━━ 9s 47ms/step - accuracy: 0.9405 - loss: 0.1810

381/573 ━━━━━━━━━━━━━━━━━━━━ 9s 47ms/step - accuracy: 0.9406 - loss: 0.1805

383/573 ━━━━━━━━━━━━━━━━━━━━ 8s 47ms/step - accuracy: 0.9406 - loss: 0.1800

385/573 ━━━━━━━━━━━━━━━━━━━━ 8s 47ms/step - accuracy: 0.9405 - loss: 0.1803

387/573 ━━━━━━━━━━━━━━━━━━━━ 8s 47ms/step - accuracy: 0.9405 - loss: 0.1800

389/573 ━━━━━━━━━━━━━━━━━━━━ 8s 47ms/step - accuracy: 0.9406 - loss: 0.1798

391/573 ━━━━━━━━━━━━━━━━━━━━ 8s 47ms/step - accuracy: 0.9406 - loss: 0.1800

393/573 ━━━━━━━━━━━━━━━━━━━━ 8s 47ms/step - accuracy: 0.9409 - loss: 0.1793

395/573 ━━━━━━━━━━━━━━━━━━━━ 8s 47ms/step - accuracy: 0.9409 - loss: 0.1794

397/573 ━━━━━━━━━━━━━━━━━━━━ 8s 47ms/step - accuracy: 0.9408 - loss: 0.1791

399/573 ━━━━━━━━━━━━━━━━━━━━ 8s 47ms/step - accuracy: 0.9407 - loss: 0.1794

401/573 ━━━━━━━━━━━━━━━━━━━━ 8s 47ms/step - accuracy: 0.9406 - loss: 0.1796

403/573 ━━━━━━━━━━━━━━━━━━━━ 8s 47ms/step - accuracy: 0.9406 - loss: 0.1804

405/573 ━━━━━━━━━━━━━━━━━━━━ 7s 47ms/step - accuracy: 0.9406 - loss: 0.1804

407/573 ━━━━━━━━━━━━━━━━━━━━ 7s 47ms/step - accuracy: 0.9408 - loss: 0.1799

409/573 ━━━━━━━━━━━━━━━━━━━━ 7s 47ms/step - accuracy: 0.9407 - loss: 0.1805

411/573 ━━━━━━━━━━━━━━━━━━━━ 7s 47ms/step - accuracy: 0.9406 - loss: 0.1806

413/573 ━━━━━━━━━━━━━━━━━━━━ 7s 47ms/step - accuracy: 0.9405 - loss: 0.1806

415/573 ━━━━━━━━━━━━━━━━━━━━ 7s 47ms/step - accuracy: 0.9405 - loss: 0.1808

417/573 ━━━━━━━━━━━━━━━━━━━━ 7s 47ms/step - accuracy: 0.9405 - loss: 0.1809

419/573 ━━━━━━━━━━━━━━━━━━━━ 7s 47ms/step - accuracy: 0.9406 - loss: 0.1808

421/573 ━━━━━━━━━━━━━━━━━━━━ 7s 47ms/step - accuracy: 0.9406 - loss: 0.1806

423/573 ━━━━━━━━━━━━━━━━━━━━ 7s 47ms/step - accuracy: 0.9405 - loss: 0.1809

425/573 ━━━━━━━━━━━━━━━━━━━━ 6s 47ms/step - accuracy: 0.9405 - loss: 0.1812

427/573 ━━━━━━━━━━━━━━━━━━━━ 6s 47ms/step - accuracy: 0.9403 - loss: 0.1815

429/573 ━━━━━━━━━━━━━━━━━━━━ 6s 47ms/step - accuracy: 0.9402 - loss: 0.1815

431/573 ━━━━━━━━━━━━━━━━━━━━ 6s 47ms/step - accuracy: 0.9404 - loss: 0.1812

433/573 ━━━━━━━━━━━━━━━━━━━━ 6s 47ms/step - accuracy: 0.9404 - loss: 0.1812

435/573 ━━━━━━━━━━━━━━━━━━━━ 6s 47ms/step - accuracy: 0.9405 - loss: 0.1812

437/573 ━━━━━━━━━━━━━━━━━━━━ 6s 47ms/step - accuracy: 0.9406 - loss: 0.1808

439/573 ━━━━━━━━━━━━━━━━━━━━ 6s 47ms/step - accuracy: 0.9404 - loss: 0.1817

441/573 ━━━━━━━━━━━━━━━━━━━━ 6s 47ms/step - accuracy: 0.9403 - loss: 0.1820

443/573 ━━━━━━━━━━━━━━━━━━━━ 6s 47ms/step - accuracy: 0.9400 - loss: 0.1833

445/573 ━━━━━━━━━━━━━━━━━━━━ 6s 47ms/step - accuracy: 0.9400 - loss: 0.1833

447/573 ━━━━━━━━━━━━━━━━━━━━ 5s 47ms/step - accuracy: 0.9396 - loss: 0.1838

449/573 ━━━━━━━━━━━━━━━━━━━━ 5s 47ms/step - accuracy: 0.9395 - loss: 0.1840

451/573 ━━━━━━━━━━━━━━━━━━━━ 5s 47ms/step - accuracy: 0.9396 - loss: 0.1840

453/573 ━━━━━━━━━━━━━━━━━━━━ 5s 47ms/step - accuracy: 0.9397 - loss: 0.1838

455/573 ━━━━━━━━━━━━━━━━━━━━ 5s 47ms/step - accuracy: 0.9397 - loss: 0.1839

457/573 ━━━━━━━━━━━━━━━━━━━━ 5s 47ms/step - accuracy: 0.9399 - loss: 0.1833

459/573 ━━━━━━━━━━━━━━━━━━━━ 5s 47ms/step - accuracy: 0.9400 - loss: 0.1832

461/573 ━━━━━━━━━━━━━━━━━━━━ 5s 47ms/step - accuracy: 0.9401 - loss: 0.1827

463/573 ━━━━━━━━━━━━━━━━━━━━ 5s 47ms/step - accuracy: 0.9401 - loss: 0.1828

464/573 ━━━━━━━━━━━━━━━━━━━━ 5s 47ms/step - accuracy: 0.9401 - loss: 0.1825

466/573 ━━━━━━━━━━━━━━━━━━━━ 5s 47ms/step - accuracy: 0.9403 - loss: 0.1826

468/573 ━━━━━━━━━━━━━━━━━━━━ 4s 47ms/step - accuracy: 0.9402 - loss: 0.1832

470/573 ━━━━━━━━━━━━━━━━━━━━ 4s 47ms/step - accuracy: 0.9404 - loss: 0.1828

472/573 ━━━━━━━━━━━━━━━━━━━━ 4s 47ms/step - accuracy: 0.9404 - loss: 0.1825

474/573 ━━━━━━━━━━━━━━━━━━━━ 4s 47ms/step - accuracy: 0.9406 - loss: 0.1826

476/573 ━━━━━━━━━━━━━━━━━━━━ 4s 47ms/step - accuracy: 0.9405 - loss: 0.1828

478/573 ━━━━━━━━━━━━━━━━━━━━ 4s 47ms/step - accuracy: 0.9405 - loss: 0.1831

480/573 ━━━━━━━━━━━━━━━━━━━━ 4s 47ms/step - accuracy: 0.9404 - loss: 0.1836

482/573 ━━━━━━━━━━━━━━━━━━━━ 4s 47ms/step - accuracy: 0.9403 - loss: 0.1840

484/573 ━━━━━━━━━━━━━━━━━━━━ 4s 47ms/step - accuracy: 0.9401 - loss: 0.1850

486/573 ━━━━━━━━━━━━━━━━━━━━ 4s 47ms/step - accuracy: 0.9398 - loss: 0.1870

488/573 ━━━━━━━━━━━━━━━━━━━━ 4s 47ms/step - accuracy: 0.9396 - loss: 0.1874

490/573 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9393 - loss: 0.1878

492/573 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9394 - loss: 0.1874

494/573 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9394 - loss: 0.1875

496/573 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9395 - loss: 0.1872

498/573 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9395 - loss: 0.1875

500/573 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9396 - loss: 0.1873

502/573 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9397 - loss: 0.1871

504/573 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9397 - loss: 0.1869

506/573 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9394 - loss: 0.1874

508/573 ━━━━━━━━━━━━━━━━━━━━ 3s 47ms/step - accuracy: 0.9394 - loss: 0.1871

510/573 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.9395 - loss: 0.1877

512/573 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.9393 - loss: 0.1884

514/573 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.9393 - loss: 0.1886

516/573 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.9393 - loss: 0.1883

518/573 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.9392 - loss: 0.1883

520/573 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.9391 - loss: 0.1883

522/573 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.9390 - loss: 0.1886

524/573 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.9390 - loss: 0.1888

526/573 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.9392 - loss: 0.1884

528/573 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.9392 - loss: 0.1883

530/573 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.9393 - loss: 0.1883

532/573 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.9395 - loss: 0.1878

534/573 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.9395 - loss: 0.1877

536/573 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.9396 - loss: 0.1877

538/573 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.9396 - loss: 0.1876

540/573 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.9395 - loss: 0.1878

542/573 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.9396 - loss: 0.1875

544/573 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.9396 - loss: 0.1876

546/573 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.9395 - loss: 0.1881

548/573 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.9396 - loss: 0.1878

550/573 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - accuracy: 0.9395 - loss: 0.1888

552/573 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9394 - loss: 0.1888

554/573 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9393 - loss: 0.1898

556/573 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9393 - loss: 0.1898

557/573 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9392 - loss: 0.1900

559/573 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9393 - loss: 0.1900

561/573 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9394 - loss: 0.1898

563/573 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9393 - loss: 0.1897

565/573 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9392 - loss: 0.1896

567/573 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9391 - loss: 0.1896

568/573 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9391 - loss: 0.1897

569/573 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9392 - loss: 0.1894

570/573 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9393 - loss: 0.1891

572/573 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9394 - loss: 0.1890

573/573 ━━━━━━━━━━━━━━━━━━━━ 33s 58ms/step - accuracy: 0.9393 - loss: 0.1892 - val_accuracy: 0.9447 - val_loss: 0.2156

Trained in 4.1 min.

## 6. Training history

Per-epoch accuracy/loss. Transfer learning usually converges in just a few
epochs since the features are already learned.

In [6]:
if history is not None:
    history_df = pd.DataFrame(history.history)
    history_df.index.name = "epoch"
    history_df["acc_gap"] = history_df["accuracy"] - history_df["val_accuracy"]
    display(history_df)
else:
    print("Model was loaded from disk - no training history this run.")

       accuracy      loss  val_accuracy  val_loss   acc_gap
epoch
0      0.851460  0.489423      0.932518  0.228689 -0.081059
1      0.924966  0.245954      0.936593  0.220593 -0.011627
2      0.932769  0.222205      0.938885  0.211868 -0.006115
3      0.935880  0.203580      0.940413  0.206152 -0.004533
4      0.935225  0.201626      0.939394  0.214439 -0.004169
5      0.938226  0.190364      0.937357  0.226181  0.000870
6      0.939263  0.189176      0.944742  0.215647 -0.005478

## 7. Evaluate: per-class report + confusion matrix

Score on the validation set; per-class precision/recall/F1 + confusion-matrix
heatmap. Watch whether the weak from-scratch classes (cow, cat) improve.

In [7]:
debug_model(model, val_generator)

  1/123 ━━━━━━━━━━━━━━━━━━━━ 1:04 528ms/step

  2/123 ━━━━━━━━━━━━━━━━━━━━ 6s 53ms/step

  3/123 ━━━━━━━━━━━━━━━━━━━━ 6s 54ms/step

  4/123 ━━━━━━━━━━━━━━━━━━━━ 6s 54ms/step

  5/123 ━━━━━━━━━━━━━━━━━━━━ 6s 54ms/step

  6/123 ━━━━━━━━━━━━━━━━━━━━ 6s 54ms/step

  7/123 ━━━━━━━━━━━━━━━━━━━━ 6s 54ms/step

  8/123 ━━━━━━━━━━━━━━━━━━━━ 6s 54ms/step

  9/123 ━━━━━━━━━━━━━━━━━━━━ 6s 54ms/step

 10/123 ━━━━━━━━━━━━━━━━━━━━ 6s 58ms/step

 11/123 ━━━━━━━━━━━━━━━━━━━━ 6s 61ms/step

 12/123 ━━━━━━━━━━━━━━━━━━━━ 6s 61ms/step

 13/123 ━━━━━━━━━━━━━━━━━━━━ 6s 60ms/step

 14/123 ━━━━━━━━━━━━━━━━━━━━ 6s 59ms/step

 15/123 ━━━━━━━━━━━━━━━━━━━━ 6s 60ms/step

 16/123 ━━━━━━━━━━━━━━━━━━━━ 6s 60ms/step

 17/123 ━━━━━━━━━━━━━━━━━━━━ 6s 59ms/step

 18/123 ━━━━━━━━━━━━━━━━━━━━ 6s 59ms/step

 19/123 ━━━━━━━━━━━━━━━━━━━━ 6s 59ms/step

 20/123 ━━━━━━━━━━━━━━━━━━━━ 6s 59ms/step

 21/123 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step

 22/123 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step

 23/123 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step

 24/123 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step

 25/123 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step

 26/123 ━━━━━━━━━━━━━━━━━━━━ 5s 57ms/step

 27/123 ━━━━━━━━━━━━━━━━━━━━ 5s 57ms/step

 28/123 ━━━━━━━━━━━━━━━━━━━━ 5s 57ms/step

 29/123 ━━━━━━━━━━━━━━━━━━━━ 5s 57ms/step

 30/123 ━━━━━━━━━━━━━━━━━━━━ 5s 57ms/step

 31/123 ━━━━━━━━━━━━━━━━━━━━ 5s 57ms/step

 32/123 ━━━━━━━━━━━━━━━━━━━━ 5s 57ms/step

 33/123 ━━━━━━━━━━━━━━━━━━━━ 5s 57ms/step

 34/123 ━━━━━━━━━━━━━━━━━━━━ 5s 57ms/step

 35/123 ━━━━━━━━━━━━━━━━━━━━ 4s 57ms/step

 36/123 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step

 37/123 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step

 38/123 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step

 39/123 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step

 40/123 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step

 41/123 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step

 42/123 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step

 43/123 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step

 44/123 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step

 45/123 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step

 46/123 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step

 47/123 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step

 48/123 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step

 49/123 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step

 50/123 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step

 51/123 ━━━━━━━━━━━━━━━━━━━━ 4s 56ms/step

 52/123 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step

 53/123 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step

 54/123 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step

 55/123 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step

 56/123 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step

 57/123 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step

 58/123 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step

 59/123 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step

 60/123 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step

 61/123 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step

 62/123 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step

 63/123 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step

 64/123 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step

 65/123 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step

 66/123 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step

 67/123 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step

 68/123 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step

 69/123 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step

 70/123 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step

 71/123 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step

 72/123 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step

 73/123 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step

 74/123 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step

 75/123 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step

 76/123 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step

 77/123 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step

 78/123 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step

 79/123 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step

 80/123 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step

 81/123 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step

 82/123 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step

 83/123 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step

 84/123 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step

 85/123 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step

 86/123 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step

 87/123 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step

 88/123 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step

 89/123 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step

 90/123 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step

 91/123 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step

 92/123 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step

 93/123 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step

 94/123 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step

 95/123 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step

 96/123 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step

 97/123 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step

 98/123 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step

 99/123 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step

100/123 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step

101/123 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step

102/123 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step

103/123 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step

104/123 ━━━━━━━━━━━━━━━━━━━━ 1s 55ms/step

105/123 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

106/123 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

107/123 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

108/123 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

109/123 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

110/123 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

111/123 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

112/123 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

113/123 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

114/123 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

115/123 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

116/123 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

117/123 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

118/123 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

119/123 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

120/123 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

121/123 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

122/123 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

123/123 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step

123/123 ━━━━━━━━━━━━━━━━━━━━ 8s 58ms/step

              precision    recall  f1-score   support

   butterfly       0.95      0.97      0.96       317
         cat       0.97      0.91      0.94       250
     chicken       0.96      0.97      0.96       464
         cow       0.88      0.84      0.86       280
         dog       0.95      0.94      0.94       730
    elephant       0.95      0.93      0.94       217
       horse       0.90      0.93      0.91       393
       sheep       0.85      0.89      0.87       273
      spider       0.98      0.98      0.98       723
    squirrel       0.95      0.95      0.95       280

    accuracy                           0.94      3927
   macro avg       0.93      0.93      0.93      3927
weighted avg       0.94      0.94      0.94      3927

C:\Users\GBT H610M-\Documents\ironHack\task\project-2\evaluation\model_metrics\model_metrics.py:92: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

,butterfly,cat,chicken,cow,dog,elephant,horse,sheep,spider,squirrel
butterfly,307,0,1,0,1,0,0,0,8,0
cat,1,227,3,0,12,0,1,0,0,6
chicken,2,0,449,2,4,0,2,2,1,2
cow,0,0,2,235,5,2,18,16,1,1
dog,2,4,7,4,689,3,11,7,1,2
elephant,0,0,0,1,6,202,2,5,1,0
horse,2,0,2,9,7,0,365,7,0,1
sheep,0,1,2,15,1,5,6,242,0,1
spider,8,1,1,0,1,0,0,1,710,1
squirrel,1,2,1,0,3,1,0,4,1,267

## 8. Misclassified images

Grid of validation images the model got wrong (true -> pred).

In [8]:
plot_misclassified(model, val_generator)

  1/123 ━━━━━━━━━━━━━━━━━━━━ 10s 87ms/step

  2/123 ━━━━━━━━━━━━━━━━━━━━ 6s 53ms/step

  3/123 ━━━━━━━━━━━━━━━━━━━━ 6s 54ms/step

  4/123 ━━━━━━━━━━━━━━━━━━━━ 6s 53ms/step

  5/123 ━━━━━━━━━━━━━━━━━━━━ 6s 54ms/step

  6/123 ━━━━━━━━━━━━━━━━━━━━ 6s 53ms/step

  7/123 ━━━━━━━━━━━━━━━━━━━━ 6s 54ms/step

  8/123 ━━━━━━━━━━━━━━━━━━━━ 6s 54ms/step

  9/123 ━━━━━━━━━━━━━━━━━━━━ 6s 54ms/step

 10/123 ━━━━━━━━━━━━━━━━━━━━ 6s 58ms/step

 11/123 ━━━━━━━━━━━━━━━━━━━━ 6s 62ms/step

 12/123 ━━━━━━━━━━━━━━━━━━━━ 6s 61ms/step

 13/123 ━━━━━━━━━━━━━━━━━━━━ 6s 60ms/step

 14/123 ━━━━━━━━━━━━━━━━━━━━ 6s 60ms/step

 15/123 ━━━━━━━━━━━━━━━━━━━━ 6s 62ms/step

 16/123 ━━━━━━━━━━━━━━━━━━━━ 6s 61ms/step

 17/123 ━━━━━━━━━━━━━━━━━━━━ 6s 61ms/step

 18/123 ━━━━━━━━━━━━━━━━━━━━ 6s 60ms/step

 19/123 ━━━━━━━━━━━━━━━━━━━━ 6s 60ms/step

 20/123 ━━━━━━━━━━━━━━━━━━━━ 6s 60ms/step

 21/123 ━━━━━━━━━━━━━━━━━━━━ 6s 59ms/step

 22/123 ━━━━━━━━━━━━━━━━━━━━ 5s 59ms/step

 23/123 ━━━━━━━━━━━━━━━━━━━━ 5s 59ms/step

 24/123 ━━━━━━━━━━━━━━━━━━━━ 5s 59ms/step

 25/123 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step

 26/123 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step

 27/123 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step

 28/123 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step

 29/123 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step

 30/123 ━━━━━━━━━━━━━━━━━━━━ 5s 57ms/step

 31/123 ━━━━━━━━━━━━━━━━━━━━ 5s 57ms/step

 32/123 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step

 33/123 ━━━━━━━━━━━━━━━━━━━━ 5s 59ms/step

 34/123 ━━━━━━━━━━━━━━━━━━━━ 5s 59ms/step

 35/123 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step

 36/123 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step

 37/123 ━━━━━━━━━━━━━━━━━━━━ 5s 58ms/step

 38/123 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step

 39/123 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step

 40/123 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step

 41/123 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step

 42/123 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step

 43/123 ━━━━━━━━━━━━━━━━━━━━ 4s 58ms/step

 44/123 ━━━━━━━━━━━━━━━━━━━━ 4s 57ms/step

 45/123 ━━━━━━━━━━━━━━━━━━━━ 4s 57ms/step

 46/123 ━━━━━━━━━━━━━━━━━━━━ 4s 57ms/step

 47/123 ━━━━━━━━━━━━━━━━━━━━ 4s 57ms/step

 48/123 ━━━━━━━━━━━━━━━━━━━━ 4s 57ms/step

 49/123 ━━━━━━━━━━━━━━━━━━━━ 4s 57ms/step

 50/123 ━━━━━━━━━━━━━━━━━━━━ 4s 57ms/step

 51/123 ━━━━━━━━━━━━━━━━━━━━ 4s 57ms/step

 53/123 ━━━━━━━━━━━━━━━━━━━━ 3s 57ms/step

 55/123 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step

 57/123 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step

 59/123 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step

 61/123 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step

 63/123 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step

 65/123 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step

 67/123 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step

 69/123 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step

 71/123 ━━━━━━━━━━━━━━━━━━━━ 2s 54ms/step

 73/123 ━━━━━━━━━━━━━━━━━━━━ 2s 54ms/step

 75/123 ━━━━━━━━━━━━━━━━━━━━ 2s 54ms/step

 77/123 ━━━━━━━━━━━━━━━━━━━━ 2s 54ms/step

 79/123 ━━━━━━━━━━━━━━━━━━━━ 2s 54ms/step

 81/123 ━━━━━━━━━━━━━━━━━━━━ 2s 54ms/step

 83/123 ━━━━━━━━━━━━━━━━━━━━ 2s 53ms/step

 85/123 ━━━━━━━━━━━━━━━━━━━━ 2s 53ms/step

 87/123 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step

 89/123 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step

 91/123 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step

 93/123 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step

 95/123 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step

 97/123 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step

 99/123 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step

101/123 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/step

103/123 ━━━━━━━━━━━━━━━━━━━━ 1s 52ms/step

105/123 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

107/123 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

109/123 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

111/123 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

113/123 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

115/123 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

117/123 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

119/123 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

121/123 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step

123/123 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step

123/123 ━━━━━━━━━━━━━━━━━━━━ 6s 51ms/step

C:\Users\GBT H610M-\Documents\ironHack\task\project-2\evaluation\plots\plots.py:74: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## 9. Record result to the tracking sheet

Upsert this model's validation row into `model_tracking.csv`.

In [9]:
learning_rate = round(float(model.optimizer.learning_rate.numpy()), 6)

row = evaluate_model(model, val_generator, "transfer_mobilenet")
row.update({
    "architecture": "MobileNetV2 (ImageNet, frozen) -> GlobalAveragePooling -> Dropout(0.5)",
    "learning_rate": learning_rate,
    "train_time_min": train_time_min,
    "notes": "Transfer learning (val metrics). Frozen ImageNet base, only head trained. Bonus / different approach.",
})
record_result(row)

  1/123 ━━━━━━━━━━━━━━━━━━━━ 9s 81ms/step

  3/123 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step

  5/123 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step

  7/123 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step

  9/123 ━━━━━━━━━━━━━━━━━━━━ 5s 48ms/step

 10/123 ━━━━━━━━━━━━━━━━━━━━ 5s 52ms/step

 11/123 ━━━━━━━━━━━━━━━━━━━━ 6s 55ms/step

 13/123 ━━━━━━━━━━━━━━━━━━━━ 5s 53ms/step

 15/123 ━━━━━━━━━━━━━━━━━━━━ 5s 55ms/step

 17/123 ━━━━━━━━━━━━━━━━━━━━ 5s 54ms/step

 19/123 ━━━━━━━━━━━━━━━━━━━━ 5s 53ms/step

 21/123 ━━━━━━━━━━━━━━━━━━━━ 5s 53ms/step

 23/123 ━━━━━━━━━━━━━━━━━━━━ 5s 52ms/step

 25/123 ━━━━━━━━━━━━━━━━━━━━ 5s 52ms/step

 27/123 ━━━━━━━━━━━━━━━━━━━━ 4s 52ms/step

 29/123 ━━━━━━━━━━━━━━━━━━━━ 4s 51ms/step

 30/123 ━━━━━━━━━━━━━━━━━━━━ 4s 51ms/step

 32/123 ━━━━━━━━━━━━━━━━━━━━ 4s 51ms/step

 33/123 ━━━━━━━━━━━━━━━━━━━━ 4s 51ms/step

 35/123 ━━━━━━━━━━━━━━━━━━━━ 4s 51ms/step

 37/123 ━━━━━━━━━━━━━━━━━━━━ 4s 51ms/step

 39/123 ━━━━━━━━━━━━━━━━━━━━ 4s 51ms/step

 41/123 ━━━━━━━━━━━━━━━━━━━━ 4s 50ms/step

 43/123 ━━━━━━━━━━━━━━━━━━━━ 4s 50ms/step

 45/123 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step

 47/123 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step

 49/123 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step

 51/123 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step

 52/123 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step

 54/123 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step

 56/123 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step

 58/123 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step

 60/123 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step

 62/123 ━━━━━━━━━━━━━━━━━━━━ 3s 50ms/step

 64/123 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step

 66/123 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step

 68/123 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step

 70/123 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step

 72/123 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step

 74/123 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step

 76/123 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step

 78/123 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step

 80/123 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step

 82/123 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step

 84/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

 86/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

 88/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

 90/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

 92/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

 94/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

 96/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

 98/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

100/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

102/123 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step

104/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

106/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

108/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

109/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

111/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

113/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

115/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

117/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

119/123 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

121/123 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

123/123 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

123/123 ━━━━━━━━━━━━━━━━━━━━ 6s 48ms/step

,model,architecture,learning_rate,train_time_min,accuracy,precision,recall,f1,notes
0,baseline_cnn,3 conv blocks (6 Conv) -> Flatten -> Dropout(0.5),0.001,15.6,0.6988,0.6875,0.6569,0.6677,Baseline (val metrics). Overfits (~13% train-v...
1,gap_cnn,3 conv blocks (6 Conv) -> GlobalAveragePooling...,0.001,32.3,0.7403,0.7321,0.7111,0.7136,Flatten -> GAP (val metrics). Less overfit (~8...
2,gap_bn_cnn,3 conv blocks (Conv-BN-ReLU) -> GlobalAverageP...,0.001,62.6,0.6924,0.7526,0.6448,0.6593,GAP + BatchNorm (val metrics). Test if BN beat...
3,gap_aug,3 conv blocks (6 Conv) -> GlobalAveragePooling...,0.001,47.3,0.6677,0.6511,0.6433,0.6300,GAP + train augmentation (flip/rotate/shift/zo...
4,gap_aug2,3 conv blocks (6 Conv) -> GlobalAveragePooling...,0.001,54.7,0.7179,0.7065,0.7053,0.6895,Augmentation retry: dropout 0.3 + 60 epochs. T...
5,gap_deep,"4 conv blocks (8 Conv, +256) -> GlobalAverageP...",0.001,14.6,0.1859,0.0186,0.1000,0.0314,FAILED to train: plain deep CNN collapsed to ~...
6,transfer_mobilenet,"MobileNetV2 (ImageNet, frozen) -> GlobalAverag...",0.001,4.1,0.9404,0.9338,0.9309,0.9321,Transfer learning (val metrics). Frozen ImageN...

## 10. Save the model

Save only when freshly trained (a loaded model is already on disk).

In [10]:
if history is not None:
    os.makedirs("models_saved", exist_ok=True)
    model.save(MODEL_PATH)
    print(f"Saved {MODEL_PATH}")
else:
    print(f"Using existing {MODEL_PATH}")

Saved models_saved/transfer_mobilenet.keras

## 11. Compare all models

Bar chart of validation accuracy across every recorded model.

In [11]:
from model_metrics import plot_accuracy_comparison

plot_accuracy_comparison()

C:\Users\GBT H610M-\Documents\ironHack\task\project-2\evaluation\model_metrics\model_metrics.py:109: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

,model,architecture,learning_rate,train_time_min,accuracy,precision,recall,f1,notes
5,gap_deep,"4 conv blocks (8 Conv, +256) -> GlobalAverageP...",0.001,14.6,0.1859,0.0186,0.1000,0.0314,FAILED to train: plain deep CNN collapsed to ~...
3,gap_aug,3 conv blocks (6 Conv) -> GlobalAveragePooling...,0.001,47.3,0.6677,0.6511,0.6433,0.6300,GAP + train augmentation (flip/rotate/shift/zo...
2,gap_bn_cnn,3 conv blocks (Conv-BN-ReLU) -> GlobalAverageP...,0.001,62.6,0.6924,0.7526,0.6448,0.6593,GAP + BatchNorm (val metrics). Test if BN beat...
0,baseline_cnn,3 conv blocks (6 Conv) -> Flatten -> Dropout(0.5),0.001,15.6,0.6988,0.6875,0.6569,0.6677,Baseline (val metrics). Overfits (~13% train-v...
4,gap_aug2,3 conv blocks (6 Conv) -> GlobalAveragePooling...,0.001,54.7,0.7179,0.7065,0.7053,0.6895,Augmentation retry: dropout 0.3 + 60 epochs. T...
1,gap_cnn,3 conv blocks (6 Conv) -> GlobalAveragePooling...,0.001,32.3,0.7403,0.7321,0.7111,0.7136,Flatten -> GAP (val metrics). Less overfit (~8...
6,transfer_mobilenet,"MobileNetV2 (ImageNet, frozen) -> GlobalAverag...",0.001,4.1,0.9404,0.9338,0.9309,0.9321,Transfer learning (val metrics). Frozen ImageN...